### PR TITLE
chore(settings): Fix disabled state for scraping

### LINKED ISSUE #70604: [Ui] Enable JavaScript source fetching option not greyed out for Member role
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

In Project Settings - General Settings

Member role can't make changes to the settings on this page.  Most of them are greyed out as expected but the Enable Javascript Source Fetching option is still clickable.  If a member clicks it, it toggles off but the settings do not persist if you refresh.  Here is a screen recording -

https://github.com/getsentry/sentry/assets/96670625/a7035644-2c09-4856-9fc8-02c14c18d18d

### Expected Result

Option should not be clickable at all.

### Actual Result

Option can be clicked.

### Product Area

Settings - Projects

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by roggenkemper**
right now in project settings, the JS source fetching setting isn't disabled for members, even though if they try to update the setting it won't work. this pr fixes it so it is disabled correctly 

fixes https://github.com/getsentry/sentry/issues/70604

### CODE REVIEW

File: static/app/data/forms/projectGeneralSettings.tsx [hunk 1]
```diff
@@ -149,7 +150,8 @@ export const fields: Record<string, Field> = {
     name: 'scrapeJavaScript',
     type: 'boolean',
     // if this is off for the organization, it cannot be enabled for the project
-    disabled: ({organization, name}) => !organization[name],
+    disabled: ({organization, project, name}) =>
+      !organization[name] || !hasEveryAccess(['project:write'], {organization, project}),
```
Comment (MichaelSun48) [inline static/app/data/forms/projectGeneralSettings.tsx:154]: Is this ‘hasEveryAccess’ condition implicit for all of the other settings on this page? I noticed that none of the other settings explicitly have this disabled condition despite being disabled by default.

**Review by MichaelSun48 — APPROVED** [review]
