### PR TITLE
fix(replays): Catch errors that happen inside ReplayReader.factory and show a message

### LINKED ISSUE #46128: Refactor views/replays/details.tsx & useReplayData to add an ErrorBoundary so crumb parsing doesn't destroy the whole page
Right now we've got our call to `useReplayData()` at the top of the ReplayDetails component.

This is not ideal because `useReplayData` does a lot of parsing and stuff, so if anything throws we error out the whole page, just a big error message.

Instead we could move the `ReplayReader.factory()` call into the component (or a new child component), and then wrap that with the ErrorBoundary, so that if crumb/rrweb/error data parsing fails we can still show the replay header.

Related to https://sentry.sentry.io/issues/3913702422/?query=url%3A%2A%2Freplays%2F%2A&referrer=issue-stream

### PR DESCRIPTION
**Pull request by ryan953**
Now whenever an exception happens inside our ReplayReader.factory call (so things like attachments/breadcrumbs/rrweb events are malformed) we're going to see an error inside the page, instead of everything being useless.

| Before | After |
| --- | --- |
| SCR-20230324-nrkl | SCR-20230413-myes | 

Fixes https://github.com/getsentry/sentry/issues/46128

### CODE REVIEW

**Comment by billyvg** [comment]
We should think about updating this error message (the title specifically). It's quite specific about why it's erroring: "Expected two or more replay events". Maybe something more generic like, "Error loading replaying", with the explanations below.

**Comment by billyvg** [comment]
One of the failing tests look questionable

File: static/app/utils/replays/replayReader.tsx [hunk 1]
```diff
@@ -45,7 +46,21 @@ export default class ReplayReader {
...
+      // If something happens then we don't really know if it's the attachments
+      // array or errors array to blame (it's probably attachments though).
+      // Either way we can use the replayRecord to show some metadata, and then
+      // put an error message below it.
+      return new ReplayReader({
+        attachments: [],
+        errors: [],
+        replayRecord,
+      });
+    }
```
Comment (ryan953) [inline static/app/utils/replays/replayReader.tsx:63]: This is the important try/catch

in the failure case we still return a valid ReplayReader instance, albeit with less data than we expected.

**Review by billyvg — APPROVED** [review]

**Review by eliashussary — APPROVED** [review]

File: static/app/utils/replays/replayReader.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/utils/replays/replayReader.tsx:63]: we've got that ui, checkout the screen shot in the desc.

what happens is we mark `loading=finished` and then there are not enough rrweb events, so we show that message. We are not showing a message with the contents of the caught error. The reason though would be malformed data that wasn't parsed correctly, which could be an SDK payload thing, like if the customer is messing with the sdk output and gives us weird stuff, the server doesn't care about the schema and would store it anyway (at least in the pre pii stripping days).

File: static/app/utils/replays/replayDataUtils.tsx [hunk 2]
```diff
@@ -147,7 +148,7 @@ export function breadcrumbFactory(
 ): Crumb[] {
   const UNWANTED_CRUMB_CATEGORIES = ['ui.focus', 'ui.blur'];
 
-  const initialUrl = replayRecord.tags.url?.join(', ');
+  const initialUrl = replayRecord.urls?.[0] ?? replayRecord.tags.url?.join(', ');
```
[the remark this answers is not in the document]
Comment (ryan953) [reply static/app/utils/replays/replayDataUtils.tsx:151]: i'm not sure anymore why we look at `tags.url`. that might be an old sdk version or something.
