### PR TITLE
fix(replay): Fix canvas recordings crashing the browser

### LINKED ISSUE #65792: Large replays w/ canvas crashes the browser due to memory usage
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Description:**
A customer reported that a replay is crashing the page when they try to view the replay. 

Customer details with example in ZD: https://sentry.zendesk.com/agent/tickets/114411

Edited by @billyvg: This is because we eagerly load the entire replay (including canvas snapshots). Due to the size and quantity of the canvas snapshots, it is causing the browser to go OOM.

~Relevant Sentry issue: https://sentry.sentry.io/issues/4895039441/events/bc73d7ed17934fd2909e011b3a57fbc7/?project=11276~

### Expected Result

Replay page to load 

### Actual Result

Replay page crashes

### Product Area

Replays

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by billyvg**
Fixes an issue with canvas replayer where it would crash the browser for replays with a large amount of canvas frames. This happened because we were attempting to preload every canvas event on load.

This PR changes the canvas player to only preload up to 50 events in the future and will clear preloaded events not within 20 seconds of the current player time.

image

Closes https://github.com/getsentry/sentry/issues/65792

### CODE REVIEW

File: static/app/components/replays/canvasReplayerPlugin.tsx [hunk 1]
```diff
@@ -67,16 +160,34 @@ export function CanvasReplayerPlugin(events: eventWithTime[]) {
     return cloneNode;
   }
 
-  const promises: Promise<any>[] = [];
-  for (const event of events) {
-    if (
-      event.type === EventType.IncrementalSnapshot &&
-      event.data.source === IncrementalSource.CanvasMutation
-    ) {
-      promises.push(deserializeAndPreloadCanvasEvents(event.data, event));
```
Comment (billyvg) [inline static/app/components/replays/canvasReplayerPlugin.tsx:76]: This was one of the crash causes, where we would need at least 2 promises per event. If you changed this to be serial so that you wait for `deserializeAndPreloadCanvasEvents` to finish before moving to the next event, then it would eventually crash due to too many images being stored in `canvasEventMap`.

File: static/app/components/replays/canvasReplayerPlugin.tsx [hunk 2]
```diff
@@ -102,45 +213,59 @@ export function CanvasReplayerPlugin(events: eventWithTime[]) {
...
-          (source && cloneCanvas(e.data.id, source as HTMLCanvasElement));
-
-        // No canvas found for id... this isn't reliably reproducible and not
-        // exactly sure why it flakes. Saving as metric to keep an eye on it.
-        if (!target) {
-          Sentry.metrics.increment('replay.canvas_player.no_canvas_id');
-          return;
+      // isSync = =true means it is fast forwarding vs playing
+      // nothing to do when fast forwarding since canvas mutations for us are
+      // image snapshots and do not depend on past events
```
Comment (billyvg) [inline static/app/components/replays/canvasReplayerPlugin.tsx:221]:
```suggestion
      // isSync = true means it is fast forwarding vs playing
      // nothing to do when fast forwarding since canvas mutations for us are
      // image snapshots and do not depend on past events
```

Comment (billyvg) [reply static/app/components/replays/canvasReplayerPlugin.tsx:221]: This is a big fix too, previously we were always running the canvas mutations regardless of `isSync` - now we skip them when user fast forwards.

File: static/app/components/replays/canvasReplayerPlugin.tsx [hunk 3]
```diff
@@ -13,18 +13,118 @@ import type {CanvasArg} from '@sentry-internal/rrweb-types';
...
+ *   - preloads a small amount of canvas events to improve playback
+ *   - applies the canvas draw comands to a canvas outside of rrweb iframe
+ *    - copies outside canvas to iframe canvas
+ *    - this avoids having to remove iframe sandbox
+ */
+export function CanvasReplayerPlugin(events: eventWithTime[]): ReplayPlugin {
+  const PRELOAD_SIZE = 50;
+  const BUFFER_TIME = 20_000;
   const canvases = new Map<number, HTMLCanvasElement>([]);
   const containers = new Map<number, HTMLImageElement>([]);
```
Comment (ryan953) [inline static/app/components/replays/canvasReplayerPlugin.tsx:70]:
```suggestion
  const canvases = new Map<number, HTMLCanvasElement>();
  const containers = new Map<number, HTMLImageElement>();
```

File: static/app/components/replays/canvasReplayerPlugin.tsx [hunk 4]
```diff
@@ -102,45 +220,59 @@ export function CanvasReplayerPlugin(events: eventWithTime[]) {
...
+      preload(e);
+
+      const source = replayer.getMirror().getNode(e.data.id);
+      const target =
+        canvases.get(e.data.id) ||
+        (source && cloneCanvas(e.data.id, source as HTMLCanvasElement));
+
+      // No canvas found for id... this isn't reliably reproducible and not
+      // exactly sure why it flakes. Saving as metric to keep an eye on it.
+      if (!target) {
```
Comment (ryan953) [inline static/app/components/replays/canvasReplayerPlugin.tsx:250]: I suspect this could happen if the id isn't found in the mirror. That happens sometimes when seeking really fast and the play doesn't keep up... that message shows up in the console, something like "id not found" over and over and the playback is broken.

**Review by ryan953 — APPROVED** [review]
Seems ok.

I spent most of my focus reading how the preload queue works and how it handles things that have been pruned out.

It looks like it we create a list to preload a couple events, and if something isn't yet preloaded when we need it then it'll render on-demand. No problem there. A non-blocking issue is that it looks like if some stuff is queued up to preload, but then we seek around and call prune() we could endup requesting a prune of the same range which is being preloaded. So it looks like in that case we'd endup preloading the range anyway, and then prune it out when the next prune call is made.  Not a deal breaker for me.

**Comment by billyvg** [comment]
Will follow-up with some tests + the case that you pointed out, thanks!
