### PR TITLE
fix(replays): don't show 'jump to current timestamp' button if network tab empty

### LINKED ISSUE #56859: Bug: "Jump to current timestamp" shows up in empty Network table
See this replay: https://sentry.sentry.io/replays/6bec932905634a489ae2bd5c6bdcdd82/?project=1267915&query=&referrer=%2Freplays%2F&statsPeriod=7d&t_main=network&t_side=tags&yAxis=count%28%29

Image

The Network tab is open and empty, the "Jump to current timestamp" should not appear in this case. Player is paused and is at the start.

### PR DESCRIPTION
**Pull request by michellewzhang**
before:
SCR-20231002-jwjh

after:
SCR-20231002-jwib

closes https://github.com/getsentry/sentry/issues/56859

### CODE REVIEW

File: static/app/views/replays/detail/network/index.tsx [hunk 1]
```diff
@@ -192,7 +192,7 @@ function NetworkList() {
 
   const currentIndex = indexAtCurrentTime();
   const showJumpDownButton = currentIndex > visibleRange[1];
-  const showJumpUpButton = currentIndex < visibleRange[0];
+  const showJumpUpButton = currentIndex < visibleRange[0] && networkFrames?.length;
```
Comment (ryan953) [inline static/app/views/replays/detail/network/index.tsx:195]: should we add the condition to the down button too? just in case

Comment (ryan953) [reply static/app/views/replays/detail/network/index.tsx:195]: it could also be combined with `sortConfig.by === 'startTimestamp'` and given a new var name

**Review by ryan953 — APPROVED** [review]
