### PR TITLE
fix(issues): Repeat issues request if project id changes

### LINKED ISSUE #61823: Navigating to issues from another page makes incorrect request
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

If you go from a metric alert -> to the issues stream. The first issues request does not provide a project id from global selection.

[example metric alert](https://sentry.sentry.io/alerts/rules/details/5590/?alert=95475&environment=production&notification_uuid=32890451-80a7-4ce4-9148-af645838a3b2&referrer=metric_alert_slack)
the issues request should have the project id or wait until the project id is available?

### PR DESCRIPTION
**Pull request by scttcper**
When navigating to issues from another page via the sidebar:
- The project id is not present on component mount, but we start the first request without it
- The project id gets set but we're exiting early in component did mount https://github.com/getsentry/sentry/blob/0970ab84f7275506d828c1b1c40b10275af93f40/static/app/views/issueList/overview.tsx#L223-L229
- The page then errors as the project id does not match groups that were presented

fixes #61823

### CODE REVIEW

File: static/app/views/issueList/overview.tsx [hunk 1]
```diff
@@ -263,8 +260,10 @@ class IssueListOverview extends Component<Props, State> {
       prevUrlQuery.cursor !== newUrlQuery.cursor ||
       prevUrlQuery.statsPeriod !== newUrlQuery.statsPeriod ||
       prevUrlQuery.groupStatsPeriod !== newUrlQuery.groupStatsPeriod ||
-      prevQuery !== newQuery ||
-      prevSort !== newSort
+      prevSort !== newSort ||
+      // Ignore query changes when issue-stream-performance is live
+      (!this.props.organization.features.includes('issue-stream-performance') &&
+        prevQuery !== newQuery)
```
Comment (scttcper) [inline static/app/views/issueList/overview.tsx:266]: will have to change this, breaks the query updating when navigating using forward/back

**Review by roggenkemper — APPROVED** [review]
