### PR TITLE
bug(replay): Do not render the list page until project data has loaded

### LINKED ISSUE #44622: Refreshing the Replay list page shows (quickly) the onboarding screen before loading the replay list

### PR DESCRIPTION
**Pull request by ryan953**
We need to wait for project data so we can know whether to render the empty-state "setup" onboariding page, or if we should load the table and wait for table rows to appear

Fixes #44622

### CODE REVIEW

File: static/app/views/replays/list/replays.tsx [hunk 1]
```diff
@@ -50,13 +50,13 @@ function ReplaysList() {
...
 
-  const {hasSentOneReplay} = useReplayOnboardingSidebarPanel();
+  const {hasSentOneReplay, fetching} = useHaveSelectedProjectsSentAnyReplayEvents();
 
   return (
     <Layout.Body>
       <Layout.Main fullWidth>
         <ReplaysFilters />
-        {hasSentOneReplay ? (
+        {fetching ? null : hasSentOneReplay ? (
```
Comment (billyvg) [inline static/app/views/replays/list/replays.tsx:59]: No loader?

**Review by billyvg — APPROVED** [review]

File: static/app/views/replays/list/replays.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/views/replays/list/replays.tsx:59]: I looked at a `<Placeholder>` but the table is variable height, it felt like more flashing in and out to my eyes
