### PR TITLE
fix(discover-event-details): Re-routing links pointing to legacy discover event details

### LINKED ISSUE #98635: Short URLs to Discover Error Events Not Working
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We keep short URL links to specific error events from Discover for further detail/analysis in our internal systems. As of last week, these URLs no longer work.

The previous short URL format : 
https://<org_slug>.sentry.io/discover/<project_name>:<event_id>/

Seems like this format has changed and the new one is:
https://<org_slug>.sentry.io/<org_slug>/<project_name>/events/<event_id>/

### Expected Result

The previous short URL format should continue working (to support the URLs we've already persisted) 

### Actual Result

The previous short URL format does not work and we cant access the linked error event

### Product Area

Discover

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by Abdkhan14**
Fixes: https://github.com/getsentry/sentry/issues/98635
- Routing errors to issue details
- Routing transactions to trace view

### CODE REVIEW

File: static/app/views/discover/eventDetails.tsx [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+    {staleTime: 2 * 60 * 1000} // 2 minutes in milliseonds
+  );
+
+  useEffect(() => {
+    if (!event) return;
+
+    const traceId = event.contexts.trace?.trace_id ?? '';
+    const timestamp = getEventTimestampInSeconds(event);
+
+    if (event?.groupID && event?.eventID) {
```
Comment (yuvmen) [inline static/app/views/discover/eventDetails.tsx]: two things - 
1. you check for !event on top, so arent these`?` redudant?
2. how will groupID or eventID be empty? just a race condition on new events? not sure I understand the trace case, I think I just dont know it enough, perhaps you can give me some context?

Comment (yuvmen) [reply static/app/views/discover/eventDetails.tsx]: oh perhaps if the event is a trace and not an error thats what this is checking actually?

File: static/app/views/discover/eventDetails.tsx [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+        getTraceDetailsUrl({
+          organization,
+          traceSlug: traceId,
+          dateSelection: datetimeSelection,
+          timestamp,
+          eventId: event.eventID,
+          location,
+        })
+      );
+    }
```
[the remark this answers is not in the document]
Comment (yuvmen) [reply static/app/views/discover/eventDetails.tsx:61]: also this looks correct? unless events basically always have either a GroupID and EventID or a TraceID, perhaps we should enforce that in code and erroring out if the trace_id is somehow empty

File: static/app/views/discover/eventDetails.tsx (hunk 1 above)
Comment (Abdkhan14) [reply static/app/views/discover/eventDetails.tsx]: `you check for !event on top, so arent these? redudant?`

I cleaned this up in my latest commit

`oh perhaps if the event is a trace and not an error thats what this is checking actually?`

correct! transaction events won't have issue and group ids so we route them to the trace view

**Review by yuvmen — APPROVED** [review]
Looks good! thanks for taking this on 👍
