### PR TITLE
ref(replay): Pass in a path to query when loading a list of replays

### LINKED ISSUE #65888: Replays tab in Transaction Summary: `You cannot view events from multiple projects.`
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When accessing the Replays tab from the Transaction Summary page I get the following error: `You cannot view events from multiple projects.`. I'm not expecting this error since I'm not viewing multiple projects. The Transaction Summary page shows events for a specific project and a specific transaction.

The request URL:
```
https://us.sentry.io/api/0/organizations/lazars-experiments/replays/?field=activity&field=browser&field=count_dead_clicks&field=count_errors&field=count_rage_clicks&field=duration&field=finished_at&field=id&field=is_archived&field=os&field=project_id&field=started_at&field=user&per_page=50&query=id%3A%5B%5D&sort=-started_at&statsPeriod=14d
```

The dashboard URL:
```
https://lazars-experiments.sentry.io/performance/summary/replays/?project=6521984&query=&statsPeriod=14d&transaction=%2F
```

My org is on the free plan. It makes sense that I can't see multiple projects because of my plan, but I wasn't trying to in this view.

The tab also shows that I have 1 replay associated with this transaction.

### Expected Result

See the replays list with the 1 replay I have associated with this transaction.

### Actual Result

image

### Product Area

Replays

### Link

https://lazars-experiments.sentry.io/performance/summary/replays/?project=6521984&query=&statsPeriod=14d&transaction=%2F

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by ryan953**
Depends on https://github.com/getsentry/sentry/pull/66086
Fixes https://github.com/getsentry/sentry/issues/65888

### CODE REVIEW

File: static/app/views/performance/transactionSummary/transactionReplays/transactionReplays.tsx [hunk 1]
```diff
@@ -143,7 +143,7 @@ function ReplaysContent({
   const {replays, isFetching, fetchError} = useReplayList({
     eventView,
     location,
-    organization,
+    path: `/organizations/${organization.slug}/replays/`,
```
Comment (ryan953) [inline static/app/views/performance/transactionSummary/transactionReplays/transactionReplays.tsx:146]: @cmanallen lmk the new url and we'll update this line

Comment (cmanallen) [reply static/app/views/performance/transactionSummary/transactionReplays/transactionReplays.tsx:146]: Set the `queryReferrer` parameter to `issueReplays`.

Comment (ryan953) [reply static/app/views/performance/transactionSummary/transactionReplays/transactionReplays.tsx:146]: but the file is `transactionReplays`...

**Review by michellewzhang — APPROVED** [review]

**Review by c298lee — APPROVED** [review]
