### PR TITLE
fix(trace-view): Improve issue loading error message

### LINKED ISSUE #78321: Trace view: Improve issue loading error message
When the trace view tries to load issue details of a deleted issue it shows a generic error banner when it receives a 404.
We should improve the error message e.g. `This issue was deleted.`

### PR DESCRIPTION
**Pull request by priscilawebdev**
closes https://github.com/getsentry/sentry/issues/78321

**Preview**

https://github.com/user-attachments/assets/362ac09a-fbd7-448e-b88c-b02f8335227b

### CODE REVIEW

**Review by vgrozdanic — APPROVED** [review]

File: static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx [hunk 1]
```diff
@@ -135,7 +136,11 @@ function Issue(props: IssueProps) {
       </AssineeWrapper>
     </StyledPanelItem>
   ) : isError ? (
-    <LoadingError message={t('Failed to fetch issue')} />
+    <LoadingError
+      message={
+        error.status === 404 ? t('This issue was deleted') : t('Failed to fetch issue')
```
Comment (shellmayr) [inline static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx:141]: Couldn't this also be a 404 because the issue never existed?

Comment (priscilawebdev) [reply static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx:141]: [at this point](https://github.com/getsentry/sentry/blob/aa355a40d8b6b7b257296fad11530f50c242ff3b/static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx#L199-L201), the issue had to have existed before.

Comment (shellmayr) [reply static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx:141]: Ah ok gotcha - thank you for clarifying 
:)

Comment (priscilawebdev) [reply static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx:141]: no problem... to give you more information... the issue is returned by the endpoint https://pri-sentry.dev.getsentry.net:7999/region/de/api/0/organizations/pri-sentry/events-trace/558ae4f960134ccb9256f884266816ad/?limit=10000&timestamp=1727700756&useSpans=1

Comment (priscilawebdev) [reply static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx:141]: to give you more context. the issue is coming from here https://pri-sentry.dev.getsentry.net:7999/region/de/api/0/organizations/pri-sentry/events-trace/558ae4f960134ccb9256f884266816ad/?limit=10000&timestamp=1727700756&useSpans=1 . In the `orphan_errors` property. Now it seems to be gone... interesting 🧐

Comment (priscilawebdev) [reply static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx:141]: it is probably deleted from there after a few minutes
