### PR TITLE
bug(replays): Fix loading Replay Details at a specific timestamp

### LINKED ISSUE #49980: DOM Click search link to replay details is a bit buggy w/ highlighting
Repro:

* Do a DOM click search query (https://sentry.sentry.io/replays/?project=11276&query=click.selector%3A%22button.app-m4xrf2.e16hd6vm2%5Baria-label%3D%5C%22Expand%5C%22%5D%5Btype%3D%5C%22button%5C%22%5D%22)
* Open a replay (https://sentry.sentry.io/replays/javascript:b67b3345b03140a5acd201b55a436f5f/?project=11276&query=click.selector%3A%22button.app-m4xrf2.e16hd6vm2%5Baria-label%3D%5C%22Expand%5C%22%5D%5Btype%3D%5C%22button%5C%22%5D%22&referrer=%2Freplays%2F&statsPeriod=14d&yAxis=count%28%29)

It's hard to find the query, and when you hit the query, the button gets highlighted with the blue overlay, but it never goes away. It makes it hard to tell what is being clicked

### LINKED ISSUE #50312: Loading a replay at a specific timestamp isn't working
Tried to load up https://sentry.sentry.io/replays/javascript:74c092d6ac3d4f14af7a778ac6104bc2/?t=31 with `?t=31` and it's starting at 0:00 instead

### LINKED ISSUE #50843: Replay: Changing timestamp not working with loading at specific time
repro: https://sentry.sentry.io/replays/6a30d8847f0e499bbb0ab29d9ac64c44/?referrer=%2Fissues%2F%3AgroupId%2F&t=8&t_main=console

Notice: `t=8` ^

Rewind to a few seconds before:
image

Once you press Play, it moves straight to 8 seconds:

image

Relates to: https://github.com/getsentry/sentry/issues/50312

### PR DESCRIPTION
**Pull request by ryan953**
The issue was a race-condition between setting up the `replayerRef` and getting the timestamp/highlight config out of the query params. 

When the query params are set to `?t=` or `?event_t=` then getting that value is fast, and will be done before the ref is ready. In this case, previously, we tried to set the current time, didn't have a ref, and that was all. 
Now we set the current timestamp whenever we're updating the replayRef.

Tested by setting `?t=30`: was able to see that we jumped to the correct timestamp
Also by doing a click search for `click.tag:button` and then clicking through to some results: saw that the video did not start at 0 anymore.

Fixes https://github.com/getsentry/sentry/issues/50312
Fixes https://github.com/getsentry/sentry/issues/49980
Fixes https://github.com/getsentry/sentry/issues/50843

### CODE REVIEW

File: static/app/components/replays/replayContext.tsx [hunk 1]
```diff
@@ -289,23 +289,97 @@ export function Provider({
...
+    if (
+      !didApplyInitialOffset.current &&
+      initialTimeOffsetMs &&
+      events &&
+      replayerRef.current
+    ) {
+      const {highlight: highlightArgs, offsetMs} = initialTimeOffsetMs;
+      if (offsetMs) {
+        privateSetCurrentTime(offsetMs);
+      }
```
Comment (billyvg) [inline static/app/components/replays/replayContext.tsx:355]: Would `offsetMs = 0` be valid (or do anything at all)

**Review by billyvg — APPROVED** [review]

File: static/app/components/replays/replayContext.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/components/replays/replayContext.tsx:355]: Shouldn't do anything. but i can write it to be clearer. TS has `strictNullChecks` which isn't enabled in this repo.
