### PR TITLE
fix: Don't submit data from disabled fields on admin settings form

### LINKED ISSUE #21159: Sentry ratelimit cannot be changed when using self-hosted
## Important Details

How are you running Sentry?

On-Premise wo/ Docker, version 20.8.0

## Description
Sentry ratelimit cannot be changed when running on premises

## Steps to Reproduce

1. Go to web-interface, Admin/Settings
2. Set a non-zero ratelimit.
3. Get an error.

````
Oct  6 07:18:49 jsentry sentry[4128]: 10.100.33.5 - - [06/Oct/2020:04:18:49 +0000] "GET /api/0/internal/options/ HTTP/1.1" 200 20407 "https://sentry.findmykids.org/manage/settings/" "Mozilla/5.0 (X11; FreeBSD amd64; rv:76.0) Gecko/20100101 Firefox/76.0"
Oct  6 07:19:09 jsentry sentry[4128]: Traceback (most recent call last):
Oct  6 07:19:09 jsentry sentry[4128]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/api/base.py", line 134, in handle_exception
Oct  6 07:19:09 jsentry sentry[4128]:     response = super(Endpoint, self).handle_exception(exc)
Oct  6 07:19:09 jsentry sentry[4128]:   File "/usr/local/lib/python2.7/site-packages/djangorestframework-3.6.4-py2.7.egg/rest_framework/views.py", line 449, in handle_exception
Oct  6 07:19:09 jsentry sentry[4128]:     self.raise_uncaught_exception(exc)
Oct  6 07:19:09 jsentry sentry[4128]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/api/base.py", line 247, in dispatch
Oct  6 07:19:09 jsentry sentry[4128]:     response = handler(request, *args, **kwargs)
Oct  6 07:19:09 jsentry sentry[4128]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/api/endpoints/system_options.py", line 74, in put
Oct  6 07:19:09 jsentry sentry[4128]:     options.set(k, v)
Oct  6 07:19:09 jsentry sentry[4128]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/options/manager.py", line 83, in set
Oct  6 07:19:09 jsentry sentry[4128]:     "%r cannot be changed at runtime because it is configured on disk" % key
Oct  6 07:19:09 jsentry sentry[4128]: AssertionError: u'system.url-prefix' cannot be changed at runtime because it is configured on disk
Oct  6 07:19:09 jsentry sentry[4128]: 10.100.33.5 - - [06/Oct/2020:04:19:09 +0000] "PUT /api/0/internal/options/ HTTP/1.1" 500 746 "https://sentry.findmykids.org/manage/settings/" "Mozilla/5.0 (X11; FreeBSD amd64; rv:76.0) Gecko/20100101 Firefox/76.0"
````

### What you expected to happen
Ratelimit should be changeable from web-interface.

### Possible Solution
Stop sending system.url-prefix in PUT request ?

### PR DESCRIPTION
**Pull request by chadwhitacre**
Fixes #21159. Works for me in local manual testing.

### CODE REVIEW

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx [hunk 1]
```diff
@@ -40,19 +41,36 @@ export default class ApiForm extends Form<Props> {
     this.api.clear();
   }
 
+  groupDataByDisabled() {
+    // Return two hashes, one with data for live elements and another for disabled.
+    const [{data}, disabledData] = [{...this.state}, {}];
+    this.props.children &&
```
Comment (BYK) [inline src/sentry/static/sentry/app/components/forms/apiForm.tsx:47]: Would prefer an explicit `if (Array.isArray(this.props.children))` call here instead of the implicit `&&` check. The `Array.isArray` check should also fix the type error below.

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx [hunk 2]
```diff
@@ -40,19 +41,36 @@ export default class ApiForm extends Form<Props> {
...
+      this.props.children.forEach(child => {
+        // Bit of a hack: loop over components named *Field to find disabled ones.
+        if (child.type && child.type.name && RegExp('Field$').test(child.type.name)) {
```
Comment (BYK) [inline src/sentry/static/sentry/app/components/forms/apiForm.tsx:50]: Why not the traditional regex notation?
```suggestion
        if (child.type && child.type.name && /Field$/.test(child.type.name)) {
```

**Review by BYK — COMMENTED** [review]
I _think_ this is fine but cannot really wrap my head around the full logic.

Also maybe we can approach the problem from a slightly different angle: instead of separating enabled and disabled data and then keep merging them in various places, what if we just separated the "enabled" data and keep the full list so we don't need to do this merging everywhere.

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx (hunk 1 above)
Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx]: I like it. Done in fd7f5e346d4cc9589f58853e48815272ae378d01.

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx (hunk 2 above)
Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx]: Yes! Done in fd7f5e346d4cc9589f58853e48815272ae378d01.

**Comment by chadwhitacre** [comment]
> what if we just separated the "enabled" data

Good call! Done in fd7f5e346d4cc9589f58853e48815272ae378d01 (also rebased on latest `master`).

Now for testing ...

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx [hunk 3]
```diff
@@ -40,14 +41,32 @@ export default class ApiForm extends Form<Props> {
...
 
+  getEnabledData() {
+    // Return a hash of data from non-disabled fields.
+    const data = {...this.state.data}; // copy to avoid mutating original
+    if (Array.isArray(this.props.children)) {
+      this.props.children.forEach(child => {
+        // Bit of a hack: loop over components named *Field to filter out disabled ones.
+        if (child.type && child.type.name && child.props && child.key) {
+          if (/Field$/.test(child.type.name)) {
+            if (child.props.disabled) {
```
Comment (BYK) [inline src/sentry/static/sentry/app/components/forms/apiForm.tsx:52]:
```suggestion
        const childTypeName = child.type && child.type.name || '';
        if (/Field$/.test(childTypeName) && child.props?.disabled && child.key) {
```

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx [hunk 4]
```diff
@@ -40,14 +41,32 @@ export default class ApiForm extends Form<Props> {
     this.api.clear();
   }
 
+  getEnabledData() {
+    // Return a hash of data from non-disabled fields.
+    const data = {...this.state.data}; // copy to avoid mutating original
+    if (Array.isArray(this.props.children)) {
+      this.props.children.forEach(child => {
```
Comment (BYK) [inline src/sentry/static/sentry/app/components/forms/apiForm.tsx:48]: FYI `for .. of` loops are more performant than `.forEach` loops.

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx [hunk 5]
```diff
@@ -40,14 +41,32 @@ export default class ApiForm extends Form<Props> {
     this.api.clear();
   }
 
+  getEnabledData() {
+    // Return a hash of data from non-disabled fields.
+    const data = {...this.state.data}; // copy to avoid mutating original
```
Comment (BYK) [inline src/sentry/static/sentry/app/components/forms/apiForm.tsx:46]: Alternative approach: start with an empty object and only add valid ones instead of deletion.

Stating this as for some reason my brain assumes `delete` operation is costly or _bad_. Old habits maybe?

Btw. when `this.props.children` is not an array, now we return the full `this.state.data` object. Is that expected?

File: src/sentry/static/sentry/app/components/forms/form.tsx [hunk 6]
```diff
@@ -112,24 +112,10 @@ class Form<
...
-      });
-    } else {
-      newData = curData;
-    }
-
     this.setState({
       state: FormState.READY,
       errors: {},
-      initialData: newData,
+      initialData: {...this.state.data, ...(data || {})},
```
Comment (BYK) [inline src/sentry/static/sentry/app/components/forms/form.tsx:118]: `data` should never be `null` or `undefined`, right?

**Review by BYK — COMMENTED** [review]
This still has a type error: `error TS2533` and fails the GCB build. Once that passes, you can get a local on-premise installation with this commit via:

```shell
SENTRY_IMAGE=us.gcr.io/sentryio/sentry:<sha> ./install.sh
```

and test it there.

File: src/sentry/static/sentry/app/components/forms/form.tsx (hunk 6 above)
Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/form.tsx:118]: `null` and `undefined` would be fine, since those are both falsey. Right?

```js
> null || {}
{}
> undefined || {}
{}
>
```

Something like a non-empty string is what would break this:

```
> {...{}, ...{}}
{}
> {...{}, ..."cheese"}
{ '0': 'c', '1': 'h', '2': 'e', '3': 'e', '4': 's', '5': 'e' }
>
```

P.S. Interestingly, empty string would pass unnoticed. :)

```
> {...{}, ...""}
{}
```

Comment (BYK) [reply src/sentry/static/sentry/app/components/forms/form.tsx:118]: Ah, sorry for not being clearer. I was questioning the need for the empty object fallback. If this can never be `null` or `undefined`, why do we even need the `|| {}` part?

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx (hunk 5 above)
Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx:46]: Some digging turns up:

> In the below example, `delete o.x` does a lot more harm than good behind the scenes, as it changes `o`’s hidden class and makes it a generic slow object.

https://www.smashingmagazine.com/2012/11/writing-fast-memory-efficient-javascript/

2012, so ¯\_(ツ)_/¯

Fine to rework to avoid though ...

Comment (BYK) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx:46]: There shouldn't be enough fields to make the perf difference matter. Whichever logic is easier to follow would be my preference and I'll leave that to you 🙂

Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx:46]: > Btw. when `this.props.children` is not an array, now we return the full `this.state.data` object. Is that expected?

Returning the full `this.state.data` object makes this function a no-op (we're back to the original behavior prior to this exercise). I'm not super-familiar with all of the types of things React might put in `props.children`. Seems like if children is not an Array then falling back to the original behavior is as good an option as any. Eh?

Comment (BYK) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx:46]: >Seems like if children is not an Array then falling back to the original behavior is as good an option as any. Eh?

Yup, sounds good to me. Thanks for explaining! 🎉

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx (hunk 3 above)
Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx:52]: Do we not care about `child.props` and `child.key`? This is my first time working against a typechecker in JavaScript, I need to tune my internal dial here. :)

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx (hunk 4 above)
Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx]: Done with ead6d23f6995a0511bf109d090c5eb19c0a72790.

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx (hunk 3 above)
Comment (BYK) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx]: I think they are expected to be there but I followed your lead, just merged the nested `if` blocks into a single condition joined by `&&`, which is equivalent?

File: src/sentry/static/sentry/app/components/forms/form.tsx (hunk 6 above)
Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/form.tsx:118]: Ah, gotcha. I was preserving the `if (data)` guard from the original. I'm kinda nervous about tacking on this refactor since it's not necessary to fix #21159, and introduces a regression risk. Therefore I tried hard to preserve the original logic. 😬

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx [hunk 7]
```diff
@@ -40,14 +41,32 @@ export default class ApiForm extends Form<Props> {
     this.api.clear();
   }
 
+  getEnabledData() {
+    // Return a hash of data from non-disabled fields.
+    const data = {};
+    if (Array.isArray(this.props.children)) {
+      for (const child of this.props.children) => {
```
Comment (BYK) [inline src/sentry/static/sentry/app/components/forms/apiForm.tsx:48]:
```suggestion
      for (const child of this.props.children) {
```

**Review by BYK — CHANGES_REQUESTED** [review]

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx [hunk 8]
```diff
@@ -40,14 +41,32 @@ export default class ApiForm extends Form<Props> {
...
+      for (const child of this.props.children) {
+        // Bit of a hack: loop over components named *Field to filter out disabled ones.
+        const childTypeName = child.type && child.type.name || '';
+        if (/Field$/.test(childTypeName)) {
+          if (!child.props.disabled) {
+            data[child.key] = this.state.data[child.key];
+            delete data[child.key];
+          }
+        }
+      });
```
Comment (BYK) [inline src/sentry/static/sentry/app/components/forms/apiForm.tsx:57]:
```suggestion
      }
```

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx (hunk 3 above)
Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx]: My bad, I misread.

Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx]: TIL [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) 👍

**Comment by BYK** [comment]
So looking at this closer, I realized this is a `PUT` call which means we probably should not be omitting fields as `PUT` semantics would mean that data should be unset. I'd say either modify the relevant API endpoint to only error when somebody is trying to _change_ an unchangeable value (so don't error if it is unchangeable but the value is already the same) or switch to a `PATCH` request and only send the updated fields. The latter approach has the risk of having an inconsistent state with what the user sees on the UI if someone else changes the same settings from a different session.

**Comment by chadwhitacre** [comment]
> `PUT` semantics would mean that data should be unset

What does it mean to "unset" a value? If an equivalent [thought experiment](https://softwareengineering.stackexchange.com/q/348380) is "delete the old version, then create a new version," then the "new version" of the options resource (in the presenting case) would have the value for `system.url-prefix` set to the default configured via `config.yml`, no? In other words, I think the API is okay as implemented.

From the HTML side, disabled form fields should not be submitted ([SO](https://stackoverflow.com/questions/7357256/disabled-form-inputs-do-not-appear-in-the-request), [spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-the-form-data-set)). As written, this PR implements this behavior across all `ApiForm`s ... though maybe it should in fact touch all `Form`s? 🤔

**Comment by chadwhitacre** [comment]
For reference, here's the root of the 500:

https://github.com/getsentry/sentry/blob/2a30ac698d80403fdb6d9b7b4a11dd2e45e9f902/src/sentry/options/manager.py#L81-L84

(So one fix would be to run with `-O`. ;-)

```
$ python -c 'assert 0'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError
$ python -Oc 'assert 0'
$
```

And here's the `PUT` definition:

https://github.com/getsentry/sentry/blob/2a30ac698d80403fdb6d9b7b4a11dd2e45e9f902/src/sentry/api/endpoints/system_options.py#L57-L86

File: src/sentry/api/endpoints/system_options.py [hunk 9]
```diff
@@ -72,10 +72,10 @@ def put(self, request):
                     options.delete(k)
                 else:
                     options.set(k, v)
-            except TypeError as e:
+            except (TypeError, AssertionError) as e:
                 return Response(
                     {
-                        "error": "invalid_type",
+                        "error": "invalid_type" if type(e) is TypeError else "invalid_option",
```
Comment (BYK) [inline src/sentry/api/endpoints/system_options.py:78]: Mind explaining why this was needed?

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx [hunk 10]
```diff
@@ -40,14 +41,41 @@ export default class ApiForm extends Form<Props> {
...
+    // and adding, because a) this.state.data is our source of truth, and b)
+    // we'd have to do more work to loop over the state.data Object and lookup
+    // against the props.children Array (looping over the Array and looking up
+    // in the Object is more natural). Maybe the consequent use of delete
+    // carries a slight performance hit. Why is yer form so big? 🤔
+
+    const data = {...this.state.data}; // Copy to avoid mutating state.data itself.
+    if (Array.isArray(this.props.children)) {
+      let child: any;
+      for (child of this.props.children) {
```
Comment (BYK) [inline src/sentry/static/sentry/app/components/forms/apiForm.tsx:57]: So, just discovered that what we have been looking for was probably [`React.Children.forEach`](https://reactjs.org/docs/react-api.html#reactchildrenforeach). This should resolve some type issues we had here. (Sorry my React is rusty)

That said, since you've already resolved the type issues I'm not sure if we need to change it anymore.

**Review by BYK — APPROVED** [review]
>What does it mean to "unset" a value? If an equivalent thought experiment is "delete the old version, then create a new version," then the "new version" of the options resource (in the presenting case) would have the value for system.url-prefix set to the default configured via config.yml, no? In other words, I think the API is okay as implemented.

I think this is debatable as I was coming from a pure HTML resource perspective. In that world, when I `PUT` something, I should `GET` the exact same thing back. This API seems to violate that but I think this is on the edge and is fine to leave as it is based on your interpretation/approach.

>From the HTML side, disabled form fields should not be submitted (SO, spec). As written, this PR implements this behavior across all ApiForms ... though maybe it should in fact touch all Forms? 🤔

This is an excellent point that I've forgotten about! Yes and we should finish what you started about omitting disabled fields then.

>(So one fix would be to run with -O. ;-)

Lol, we probably should use `-O` for other reasons but after seeing this, please no :D


All the checks passed and the code LGTM. I'm assuming you've tested this manually? :)

File: src/sentry/api/endpoints/system_options.py (hunk 9 above)
Comment (chadwhitacre) [reply src/sentry/api/endpoints/system_options.py:78]: Sure! I wanted to preserve the error string in the `TypeError` case, but figured it made sense to have a different error string in the `AssertionError` case. I went with `invalid_option` to keep the parallelism with `invalid_type` on the one hand and `unknown_option` (just above) on the other.

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx (hunk 10 above)
Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx]: I like it! Implemented in b1739a1942. 👍

File: src/sentry/api/endpoints/system_options.py (hunk 9 above)
Comment (BYK) [reply src/sentry/api/endpoints/system_options.py:78]: Okay, I see that we also have an `unknown_option` error at the top which sounds similar. Should this be something like `immutable_option` or `unmodifiable_option` instead to clarify?

**Review by BYK — COMMENTED** [review]
I think we can promote this PR from draft at this point?

File: src/sentry/api/endpoints/system_options.py (hunk 9 above)
Comment (chadwhitacre) [reply src/sentry/api/endpoints/system_options.py:78]: Yeah, that can work. It looks like all five assertions beneath the relevant `OptionsManager` calls can be brought under the heading of immutability. Might be even better to have a custom exception for those vs. bare asserts, but there's a whole lot of asserting going on and I don't want to cut too deep.

https://github.com/getsentry/sentry/blob/848be85afc66acff6d430a6507cb5b8c59df96fc/src/sentry/options/manager.py#L77-L84

https://github.com/getsentry/sentry/blob/848be85afc66acff6d430a6507cb5b8c59df96fc/src/sentry/options/manager.py#L181-L184

Comment (chadwhitacre) [reply src/sentry/api/endpoints/system_options.py:78]: Done in e1d29ee0f4!

Comment (chadwhitacre) [reply src/sentry/api/endpoints/system_options.py]: Done in e1d29ee0f4!

**Comment by chadwhitacre** [comment]
Here are the places I find an `apiForm`:

```
app/components/forms/index.tsx
1:export {default as ApiForm} from './apiForm';

app/components/forms/form.tsx
53:    onSubmit: PropTypes.func, //actually required but we cannot make it required because it's optional in apiForm

app/views/settings/project/serviceHookSettingsForm.tsx
5:import ApiForm from 'app/views/settings/components/forms/apiForm';

app/views/settings/components/forms/index.tsx
1:export {default as ApiForm} from './apiForm';

app/views/settings/organizationApiKeys/organizationApiKeyDetails.jsx
9:import ApiForm from 'app/components/forms/apiForm';

app/views/settings/account/apiNewToken.tsx
7:import ApiForm from 'app/views/settings/components/forms/apiForm';

app/views/organizationGroupDetails/reprocessingForm.tsx
14:import ApiForm from 'app/components/forms/apiForm';
```

**Comment by chadwhitacre** [comment]
I'm going to go looking for regressions. Here are the places I find `ApiForm`:

```
app/components/forms/index.tsx:1:export {default as ApiForm} from './apiForm';
app/components/forms/apiForm.tsx:23:export default class ApiForm extends Form<Props> {
app/components/forms/form.tsx:207:// We need to keep `Form` as a React Component because ApiForm extends it :/
app/views/settings/project/serviceHookSettingsForm.tsx:5:import ApiForm from 'app/views/settings/components/forms/apiForm';
app/views/settings/project/serviceHookSettingsForm.tsx:37:        <ApiForm
app/views/settings/project/serviceHookSettingsForm.tsx:72:        </ApiForm>
app/views/settings/components/forms/index.tsx:1:export {default as ApiForm} from './apiForm';
app/views/settings/components/forms/apiForm.tsx:14:export default class ApiForm extends React.Component<Props> {
app/views/settings/organizationApiKeys/organizationApiKeyDetails.jsx:9:import ApiForm from 'app/components/forms/apiForm';
app/views/settings/organizationApiKeys/organizationApiKeyDetails.jsx:79:        <ApiForm
app/views/settings/organizationApiKeys/organizationApiKeyDetails.jsx:113:        </ApiForm>
app/views/settings/account/apiNewToken.tsx:7:import ApiForm from 'app/views/settings/components/forms/apiForm';
app/views/settings/account/apiNewToken.tsx:47:            <ApiForm
app/views/settings/account/apiNewToken.tsx:70:            </ApiForm>
app/views/admin/adminSettings.tsx:6:import {ApiForm} from 'app/components/forms';
app/views/admin/adminSettings.tsx:65:        <ApiForm
app/views/admin/adminSettings.tsx:86:        </ApiForm>
app/views/admin/installWizard/index.tsx:9:import {ApiForm} from 'app/components/forms';
app/views/admin/installWizard/index.tsx:123:      <ApiForm
app/views/admin/installWizard/index.tsx:133:      </ApiForm>
app/views/newsletterConsent.tsx:3:import {ApiForm, RadioBooleanField} from 'app/components/forms';
app/views/newsletterConsent.tsx:29:        <ApiForm
app/views/newsletterConsent.tsx:55:        </ApiForm>
app/views/organizationCreate.tsx:6:import {ApiForm, BooleanField, TextField} from 'app/components/forms';
app/views/organizationCreate.tsx:38:        <ApiForm
app/views/organizationCreate.tsx:66:        </ApiForm>
app/views/organizationGroupDetails/reprocessingForm.tsx:14:import ApiForm from 'app/components/forms/apiForm';
app/views/organizationGroupDetails/reprocessingForm.tsx:96:          <ApiForm
app/views/organizationGroupDetails/reprocessingForm.tsx:116:          </ApiForm>
```

**Comment by chadwhitacre** [comment]
The risk is that one of these forms was sending data for disabled form fields, and that behavior was depended upon. The sort of failure mode we'd expect would be that a value on a form regresses to some default now that we're not sending the disabled field, or perhaps an API endpoint errors out without the disabled field being set.

**Comment by chadwhitacre** [comment]
Hmmmmm ... what's the relation between these two `ApiForms`? 🤔

https://github.com/getsentry/sentry/blob/2b4b42e99d368aad80285e51870d5319055bdc7d/src/sentry/static/sentry/app/views/settings/components/forms/apiForm.tsx#L14

https://github.com/getsentry/sentry/blob/2b4b42e99d368aad80285e51870d5319055bdc7d/src/sentry/static/sentry/app/components/forms/apiForm.tsx

Looks like these are two separate implementations. :mouse:

**Comment by chadwhitacre** [comment]
```
components/forms/apiForm

views/admin/adminSettings
views/admin/installWizard/index
views/newsletterConsent
views/organizationCreate
views/organizationGroupDetails/reprocessingForm
views/settings/organizationApiKeys/organizationApiKeyDetails

--------------

views/settings/components/forms/apiForm

views/settings/project/serviceHookSettingsForm
views/settings/account/apiNewToken
```

**Comment by BYK** [comment]
LGTM but the two separate form implementations is not great. A fix for future PRs, I think this PRs scope already got extended a bit. As long as we can verify nothing else is broken, I'm game.

**Comment by chadwhitacre** [comment]
Ftr, from `#discuss-frontend`:

> the `app/components/` is legacy. we should mv `app/components/forms` -> `formsLegacy` and mv `app/views/settings/components/forms` -> `app/components/forms`

Agreed, out of scope here.

**Comment by chadwhitacre** [comment]
> As long as we can verify nothing else is broken, I'm game.

My plan:

1. Audit the code for the six instances of `components/forms/apiForm`, looking for possibly-disabled fields.
2. For each form with possibly-disabled fields, find the form in the test suite. Audit the coverage.
3. For each form with possibly-disabled fields and inadequate automated test coverage, find the form in the UI and manually test it.

**Comment by chadwhitacre** [comment]
- [] `views/admin/adminSettings`
- [] `views/admin/installWizard/index`
- [] `views/newsletterConsent`
- [] `views/organizationCreate`
- [] `views/organizationGroupDetails/reprocessingForm`
- [] `views/settings/organizationApiKeys/organizationApiKeyDetails`

**Comment by chadwhitacre** [comment]
Scratch that. Based on my research as well as conversations in discuss-frontend, it's way too risky to change the default behavior for `ApiForm` across the application. What's more, the form infra that `adminSettings` is using is the legacy one, not worth investing too much effort into. Therefore, I'm dropping back and adding an option called `sendDisabled` and using that to scope the behavior change to the single form mentioned in #21159.

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx [hunk 11]
```diff
@@ -32,6 +36,7 @@ export default class ApiForm extends Form<Props> {
 
   static defaultProps = {
     ...Form.defaultProps,
+    sendDisabled: true, // TODO(chadwhitacre) Upstream, flip to false, deprecate.
```
Comment (BYK) [inline src/sentry/static/sentry/app/components/forms/apiForm.tsx:39]: Idea: rename to `ignoreDisabled` and default to `true` to prevent `undefined` vs `false` confusion in the future?

**Review by BYK — APPROVED** [review]

File: src/sentry/static/sentry/app/components/forms/apiForm.tsx (hunk 11 above)
Comment (chadwhitacre) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx:39]: I think you mean "default to `false`," yes?

Comment (BYK) [reply src/sentry/static/sentry/app/components/forms/apiForm.tsx]: Yes 😀

**Review by BYK — APPROVED** [review]
