### PR TITLE
fix(ui): Support translated suffix in relative dates

### LINKED ISSUE #31542: Event detail doesn't load in French Language
### Environment

SaaS (https://sentry.io/)

### Version

_No response_

### Steps to Reproduce

1. go to User settings
2. switch language to French
3. Refresh the page
3. go to Découvrir (Discover)
4. click on a event ID

### Expected Result

Event detail is displayed

### Actual Result

An error is displayed : "Une erreur est survenue lors du chargement d'un composant." (There was an error loading a component.)

In console : 
Error: Unsupported time format suffix
    b timeSince.tsx:181
    getDerivedStateFromProps timeSince.tsx:70

### PR DESCRIPTION
**Pull request by scttcper**
fixes #31542
fixes JAVASCRIPT-26DC

checking for 'ago' when the strings are translated errors. This uses any suffix provided and falls back to just the date instead of an error.

### CODE REVIEW

File: static/app/components/timeSince.tsx [hunk 1]
```diff
@@ -169,14 +169,12 @@ export function getRelativeDate(
...
   }
-  if (!suffix) {
-    return moment(date).fromNow(true);
-  }
   if (suffix === 'ago') {
     return moment(date).fromNow();
   }
-  if (suffix === 'old') {
-    return t('%(time)s old', {time: moment(date).fromNow(true)});
+  if (suffix?.length) {
```
Comment (JonasBa) [inline static/app/components/timeSince.tsx:175]: nit, but you could keep the early return from L172 and you wouldnt need to check for length, just return with a suffix instead of throwing in the end. Not a big deal anyways

**Review by JonasBa — APPROVED** [review]
Thanks you for adding the tests 🥇
