### PR TITLE
fix(replays): network table styles

### LINKED ISSUE #37072: Bug: Network tab table headers are huge when there are no rows
Image

https://dev.getsentry.net:7999/organizations/sentry-emerging-tech/replays/sourcemapsio-replays:634545ef14434a47b9b28e6d52c559b6/

### PR DESCRIPTION
**Pull request by jesus4497**
Fixed the styles of the network table fixing the header cells and height of the table. Closes #37072 

image

image

image

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by jesus4497** [comment]
> Is it just me or are these headings not centered?
> 
> image

Fixed! 
image

**Comment by billyvg** [comment]
The sort icon still seems a tad large and is not aligned, but that seems consistent across our app so let's leave that.

However, other places in the app hide the sort icon unless it's active (see discover for an example).

**Comment by jesus4497** [comment]
> The sort icon still seems a tad large and is not aligned, but that seems consistent across our app so let's leave that.
> 
> However, other places in the app hide the sort icon unless it's active (see discover for an example).

Here's a loom video of the result: 

https://user-images.githubusercontent.com/39612839/181340802-115cf1c9-ffa6-4673-97d4-14943df4cecf.mp4

File: static/app/views/replays/detail/network/index.tsx [hunk 1]
```diff
@@ -122,23 +125,17 @@ const Item = styled('div')<{color?: string; numeric?: boolean}>`
...
   ${p => p.numeric && 'font-variant-numeric: tabular-nums;'}
 `;
 
 const StyledPanelTable = styled(PanelTable)<{columns: number}>`
   grid-template-columns: max-content minmax(200px, 1fr) repeat(3, max-content);
   font-size: ${p => p.theme.fontSizeSmall};
-  line-height: 16px;
   margin-bottom: 0;
-  height: 100%;
+  max-height: 100%;
```
Comment (ryan953) [inline static/app/views/replays/detail/network/index.tsx:137]: I'm not feeling this change.

We've got these big panel areas for the content to inflate and fill up.

cc @Jesse-Box 

the screen shot (copied from the description) shows the behavior in the bottom-right corner:

181275810-3ae25409-d8bb-4f58-af2a-0e37157cd279

**Review by billyvg — COMMENTED** [review]
LGTM pending what you decide about the height.

File: static/app/views/replays/detail/network/index.tsx (hunk 1 above)
Comment (jesus4497) [reply static/app/views/replays/detail/network/index.tsx:137]: The result would be something like this:

image

Comment (Jesse-Box) [reply static/app/views/replays/detail/network/index.tsx:137]: Considering this is a scrollable window, I think the 100% height is the way to go because it explains the bounds of the container. @jesus4497 @ryan953

Comment (ryan953) [reply static/app/views/replays/detail/network/index.tsx:137]:
```suggestion
  height: 100%;
```

**Comment by Jesse-Box** [comment]
> The sort icon still seems a tad large and is not aligned, but that seems consistent across our app so let's leave that.
> 
> However, other places in the app hide the sort icon unless it's active (see discover for an example).

Regarding the alignment, there are two ways of solving this
1. Wrap the label and icon in a flex container and align-items center
2. Give the line-height of the label the same height as the icon.

Is the icon 12px in size @jesus4497 ?

File: static/app/views/replays/detail/network/index.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/views/replays/detail/network/index.tsx:137]: I like the borders, I'll make low-pri follow up tickets to make sure all the other sections work this way (and their empty states too)

Comment (jesus4497) [reply static/app/views/replays/detail/network/index.tsx]: Done! 

image

image

**Comment by jesus4497** [comment]
> > The sort icon still seems a tad large and is not aligned, but that seems consistent across our app so let's leave that.
> > However, other places in the app hide the sort icon unless it's active (see discover for an example).
> 
> Regarding the alignment, there are two ways of solving this
> 
> 1. Wrap the label and icon in a flex container and align-items center
> 2. Give the line-height of the label the same height as the icon.
> 
> Is the icon 12px in size @jesus4497 ?

Yes! the icon is 12px in size.

With the first method the result is: 
image


Second method: 



> > The sort icon still seems a tad large and is not aligned, but that seems consistent across our app so let's leave that.
> > However, other places in the app hide the sort icon unless it's active (see discover for an example).
> 
> Regarding the alignment, there are two ways of solving this
> 
> 1. Wrap the label and icon in a flex container and align-items center
> 2. Give the line-height of the label the same height as the icon.
> 
> Is the icon 12px in size @jesus4497 ?

I think as this are capitalized letters its giving me troubles to fully center it with the icon, I manage it with another method and this is the result: 
image

**Review by ryan953 — APPROVED** [review]

File: static/app/views/replays/detail/network/index.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/views/replays/detail/network/index.tsx]: awesome. Thanks @jesus4497 for trying out the `max-height` option and taking a screen shot. I hadn't actually done that so it's really good to try it, make the proposal, and know for sure what the options looks like. 🥇
