### PR TITLE
fix(stats): Load all teams for owner on stats page

### LINKED ISSUE #58774: Owners are not able to view stats for teams that they are not a part of
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to the `stats/issues` page as an owner.

By looking at the [code](https://github.com/getsentry/sentry/blob/7bb213df90a03a982865916fcad1e0dbc18e2d35/static/app/views/organizationStats/teamInsights/controls.tsx#L133), it seems to me that we are just checking whether the user is either a super user or returning the teams that they are only a part of

### Expected Result

As an organization owner, I would expect to be able to select and see the stats for ALL the teams within my org, even if I am not part of that team

### Actual Result

As an owner, I am only able to select teams I am a part of in the dropdown

### Product Area

Issues

### Link

https://demo.sentry.io/stats/issues/

### DSN

_No response_

### Version

_No response_

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1968) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by schew2381**
Load all teams on the stats page for an owner, so they can switch between teams they are not part of in the dropdown
Continues fix from https://github.com/getsentry/sentry/pull/63486

https://github.com/getsentry/sentry/assets/67301797/00a662e2-6e19-4ca7-aa62-3b565bfc0cbd

Closes https://github.com/getsentry/sentry/issues/58774
for real this time :)

### CODE REVIEW

File: static/app/utils/useUserTeams.tsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ function buildUserTeamsQueryKey(orgSlug: string): ApiQueryKey {
  * const {teams, isLoading, isError} = useUserTeams();
  * ```
  */
-export function useUserTeams(): UseTeamsResult {
+export function useUserTeams(loadAllTeams?: boolean): UseTeamsResult {
```
Comment (JonasBa) [inline static/app/utils/useUserTeams.tsx:29]: question, but what teams does this return by default if you don't use loadAllTeams? When we expose interfaces like this, it is confusing as to how to properly use them, because eod, why wouldn't you want it to return all teams?

What would be the downside of making this a default behavior inside the hook like we do with the `superuser` check, instead of relying on the caller to pass the correct argument? My reasoning for that would be that an `org:admin` role is roughly equivalent to a `superuser` role from a user perspective, so the logic should be the same in both instances instead of relying on the user to pass the correct argument.

File: static/app/utils/useUserTeams.tsx [hunk 2]
```diff
@@ -54,8 +54,10 @@ export function useUserTeams(): UseTeamsResult {
 
   const isSuperuser = isActiveSuperuser();
   const teams = useMemo<Team[]>(() => {
-    return isSuperuser ? storeState.teams : storeState.teams.filter(t => t.isMember);
-  }, [storeState.teams, isSuperuser]);
+    return isSuperuser || loadAllTeams
```
Comment (JonasBa) [inline static/app/utils/useUserTeams.tsx:57]: Related to my comment above, but we would do something like
```suggestion
    return isSuperuser || organization.access.includes('org:admin')
```

File: static/app/utils/useUserTeams.spec.tsx [hunk 3]
```diff
@@ -66,4 +73,39 @@ describe('useUserTeams', () => {
...
+    const userTeams = [TeamFixture({id: '1', isMember: true})];
+    const nonUserTeams = [TeamFixture({id: '2', isMember: false})];
+    // User teams marked loaded because hasMore is false
+    TeamStore.loadInitialData([...userTeams, ...nonUserTeams], false, null);
+    expect(TeamStore.getState().loadedUserTeams).toBe(true);
+
+    const organization = OrganizationFixture({
+      access: ['org:admin'],
+    });
+    OrganizationStore.onUpdate(organization, {replace: true});
```
Comment (schew2381) [inline static/app/utils/useUserTeams.spec.tsx:103]: Not sure if there's an easier way to update what's in `OrganizationStore` already

File: static/app/utils/useUserTeams.tsx (hunk 1 above)
Comment (schew2381) [reply static/app/utils/useUserTeams.tsx]: That makes sense. I didn't move the logic inside originally b/c I wasn't sure where else `useUserTeams` was used, but it was only used in 1 other place in the alert rules tab. The logic doesn't affect that, so should be good to default to the behavior

**Review by JonasBa — APPROVED** [review]
Nice, lgtm + the API is simpler. Nice work 👏🏼 @schew2381
