### PR TITLE
fix(dashboards): metric widget default name

### LINKED ISSUE #64144: Broken autogenerated widget name
It's not broken, it just doesn't work.

### PR DESCRIPTION
**Pull request by obostjancic**
- closes #64144

### CODE REVIEW

File: static/app/views/dashboards/widgetCard/metricWidgetCard/index.tsx [hunk 1]
```diff
@@ -83,9 +83,13 @@ export function MetricWidgetCard({
       toMetricDisplayType(metricWidgetQueryParams.displayType)
     );
 
+    const isCustomTitle = parseField(title) === null && title !== '';
```
Comment (ArthurKnaus) [inline static/app/views/dashboards/widgetCard/metricWidgetCard/index.tsx:86]: k, there is this tiny corner case where it breaks if I enter a valid field, right?

Comment (ArthurKnaus) [reply static/app/views/dashboards/widgetCard/metricWidgetCard/index.tsx:86]: Could we do something like this?
```suggestion
    const isCustomTitle = title !== '' &&
      parseField(title)?.mri !== metricWidgetQueryParams.mri;
```

**Review by ArthurKnaus — APPROVED** [review]
