### PR TITLE
fix(transaction-summary): dont refetch totals, so tx list doesnt rerender

### LINKED ISSUE #47936: Performance Summary slow transactions reload gets triggered randomly
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

https://sentry.sentry.io/replays/javascript:714df4ff146440ef81ef8db5ed1e4a94/?project=11276&query=&referrer=%2Freplays%2F&statsPeriod=14d&yAxis=count%28%29

on this replay, watch the first 40 seconds. for some reason, at around second 35, the slow transactions table reloads. i find it annoying as often times i am looking at that table and it randomly reloads.

### Expected Result

The slow transactions table loads and only refreshes when data/filters are updated on the page

### Actual Result

the table randomly reloads

### Product Area

Performance

### Link

https://sentry.sentry.io/performance/summary/?project=1&query=&referrer=performance-transaction-summary&statsPeriod=90d&transaction=%2Fapi%2F0%2Forganizations%2F%7Borganization_slug%7D%2Fusers%2F&unselectedSeries=p100%28%29

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by JoshFerge**
- On the Transaction Summary page, currently window focus event (tab in, alt tab) trigger a re-rendering of the transaction list on the summary page. I found this extremely annoying. See the replay in the linked below issue to se what i'm talking about.
- This re-render seems to be triggered by the `getTotalsEventView` `queryData`. I'm not quite sure why, as I believe this table is rendered by https://github.com/getsentry/sentry/blob/66e7314e29f42fe5fe63f6da348fc8cad64411dc/static/app/components/discover/transactionsList.tsx#L365
- Regardless, I've made it so you can pass in `useQuery` options to `BaseDiscoverQueryProps`, and am now passing this parameter in the `queryData` call to `useDiscoverQuery`.
- I don't think this data really goes stale that quickly to where it needs a refresh every page focus, so I think this should be fine. We should consider using this property in other places where we deem its not necessary to refresh this data on window focus.

Resolves https://github.com/getsentry/sentry/issues/47936

### CODE REVIEW

**Review by ryan953 — APPROVED** [review]

**Comment by malwilley** [comment]
Looks good - we actually disable this option by default normally: https://github.com/getsentry/sentry/blob/bf1bf09fd77cd2a2a8a42afef95390fad9b27fb5/static/app/utils/queryClient.tsx#L13

However, it looks like performance is using its own provider that overrides it: https://github.com/getsentry/sentry/blob/bf1bf09fd77cd2a2a8a42afef95390fad9b27fb5/static/app/views/performance/index.tsx#L39

This is probably a holdover from before we were using react query across the whole app, so we should probably remove that extra provider.

File: static/app/utils/discover/genericDiscoverQuery.tsx [hunk 1]
```diff
@@ -77,6 +77,7 @@ type BaseDiscoverQueryProps = {
    * passed, but cursor will be ignored.
    */
   noPagination?: boolean;
+  options?: Omit<Parameters<typeof useQuery>[2], 'initialData'>;
```
Comment (scttcper) [inline static/app/utils/discover/genericDiscoverQuery.tsx:80]: i think this should be `UseApiQueryOptions` exported from `sentry/utils/queryClient`

Comment (scttcper) [reply static/app/utils/discover/genericDiscoverQuery.tsx:80]: nvm its not using useApiQuery

Comment (malwilley) [reply static/app/utils/discover/genericDiscoverQuery.tsx:80]: The discover query uses `useQuery` instead of our own `useApiQuery` so that might actually not work. Could use `UseQueryOptions` exported from the lib though.

Comment (JoshFerge) [reply static/app/utils/discover/genericDiscoverQuery.tsx:80]: just copying the usage of this type here: https://github.com/getsentry/sentry/blob/7d84829c2111305cd220b9ef1d482964b7bb45ad/static/app/utils/discover/genericDiscoverQuery.tsx#L133
