### PR TITLE
ref(replays): Refactor replay pagination to use Link response header

### LINKED ISSUE #37931: Bug: Pagination seems broken, the links don't light up
Ideally this will solve it: https://github.com/getsentry/replay-backend/issues/84

EDIT:
`jferg/fix-pagination-replays-index` is a branch that should have the `Links` response header.

With that branch we can instead remove `getPageLinks()` from `useReplayList.tsx` and pass along the `Links` header into `pageLinks`.

We've got more than 10 replays captured, these button should be active at the bottom of the list page:
Screen Shot 2022-08-17 at 11 30 52 AM

---

Previous Content: 

~~But we can't wait for that, need to fixup the shim that's in there now. See `getPageLinks()` inside `useReplayList.tsx`.~~

### PR DESCRIPTION
**Pull request by ryan953**
Depends on: https://github.com/getsentry/sentry/pull/37945
- #37945 should be deployed first, but if it doesn't we won't see any errors. What will happen is that we won't see any pagination because `pageLinks` will be `null`. Since the page is behind a feature-flag we're ok to bend deploy rules right now.

Fixes #37931

### CODE REVIEW

**Review by JoshFerge — APPROVED** [review]

File: static/app/views/replays/replays.tsx [hunk 1]
```diff
@@ -44,11 +45,35 @@ function Replays({location}: Props) {
...
+              {reasons.map((reason, i) => (
+                <li key={i}>{reason}</li>
+              ))}
+            </ol>
+          </div>
+        }
+      />
+    );
+  }
+
```
Comment (ryan953) [inline static/app/views/replays/replays.tsx:76]: I noticed we didn't have any error state before, and of course triggered some errors.

Now we show something instead of the empty list component:
Screen Shot 2022-08-17 at 3 15 34 PM

Comment (billyvg) [reply static/app/views/replays/replays.tsx:76]: This looks a bit awkward without any Replays chrome, but it's fine for now

**Review by billyvg — APPROVED** [review]
