### PR TITLE
fix(issues): Filter out null/undefined headers when formatting request as curl

### LINKED ISSUE #59034: [Issue details] Viewing request in curl format leads to error
### Environment

SaaS (https://sentry.io/)

**Description**
A customer is trying to copy and paste the "request" information with ease using the curl format. However, when selecting curl, they receive the following error:
Screenshot 2023-10-30 at 11 44 53 AM

Using the "Formatted" option does not expose all key value pairs unless you select every + icon manually

Customer details in support ticket - https://sentry.zendesk.com/agent/tickets/106143
Relevant Sentry issue - https://sentry.sentry.io/issues/4578014668/events/9952d8f81e8a454c91ca3eba72282a86/?project=11276

**Steps:**
1. Use example issue from Support ticket
2. Navigate to "request" section on the issue detail
3. Select curl

### Expected Result

Request to be in curl format

### Actual Result

Error when selecting curl

### Product Area

Issues

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by lobsterkatie**
On the issue details page, there is a button to display data about the request in `curl` format, at which point we convert it and do the formatting on the fly. As part of this formatting, we sort the headers. But if any of the headers is `null` or `undefined`, that sorting crashes, because it expects every header to be of the form `[headerName, value]` and therefore assumes it's safe to index into it, which of course you can't do with `null` or `undefined`. As a result of this sorting crash, the entire formatting process fails and we don't produce any output.

This fixes that by filtering `null` and `undefined` out of the `request.headers` array before any other processing is done.

Fixes https://github.com/getsentry/sentry/issues/59034
Fixes JAVASCRIPT-2PBG

### CODE REVIEW

File: static/app/components/events/interfaces/utils.tsx [hunk 1]
```diff
@@ -125,6 +125,10 @@ export function getCurlCommand(data: EntryRequest['data']) {
     result += ' \\\n -X ' + data.method;
   }
 
+  // Compare to null using != rather than !== to also catch undefined.
+  // eslint-disable-next-line no-eq-null, eqeqeq
+  data.headers = data.headers?.filter(h => h != null);
```
Comment (scttcper) [inline static/app/components/events/interfaces/utils.tsx:130]: we have a defined which also does typescript type narrowing (doesn't really matter in this case) https://github.com/getsentry/sentry/blob/master/static/app/utils.tsx#L123
```suggestion
  data.headers = data.headers?.filter(defined);
```

Comment (lobsterkatie) [reply static/app/components/events/interfaces/utils.tsx]: Oh, good call. Fixed.

**Review by scttcper — APPROVED** [review]
