### PR TITLE
fix(replay): Disable pointer events when resizing replay panels

### LINKED ISSUE #78977: Panel resizer is buggy in Replay Details
Inside of replay details, we have a bar in between the player and breadcrumbs pane that you can hover to resize the column widths. If you resize near the middle where the left side is the replayer iframe, it will break the resizing. If you resize near the top/bottom where the left side of the resizer is not replayer iframe, it will work fine.

The issue is likely due to pointer events over the iframe causing the resizer to think that the mouse click and hold has ended.

### PR DESCRIPTION
**Pull request by ryan953**
There was always some CSS to disable pointer-events when the replay view was resizing, but it broke a little while ago because of CSS selector specificity

The fixes selectors look like this:
 
fixed

Fixes #78977

### CODE REVIEW

File: static/app/components/splitPanel.tsx [hunk 1]
```diff
@@ -204,7 +204,11 @@ const SplitPanelContainer = styled('div')<{
   overflow: auto;
   grid-template-${p => p.orientation}: ${p => p.size} auto 1fr;
 
-  &.disable-iframe-pointer iframe {
+  /*
+   * This is more specific, with <code>&&</code> than the foundational rule:
+   * <code>&[data-inspectable='true'] .replayer-wrapper > iframe</code>
```
Comment (billyvg) [inline static/app/components/splitPanel.tsx:209]: What are these `<code>` tags doing in here?

**Review by billyvg — APPROVED** [review]
