### PR TITLE
fix(stacktrace): Update state when switching between events

### LINKED ISSUE #53556: Event navigation buttons don't update stacktrace
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The buttons to navigate between various events of the same issue (error) don't update the stacktrace, even though it is different.	 For example, see the following two subsequent events of the same issue:

* https://sentry-sdks.sentry.io/issues/4312921244/events/e56d428ef9f14b05b0adfe129b549635/
* https://sentry-sdks.sentry.io/issues/4312921244/events/0be97f077c994bdaa2f09475f83400ab/

and compare them to clicking the prev/next button on these pages.

### Expected Result

The stack trace is refreshed

### Actual Result

The stack trace looks like whichever stack traces was first loaded. Only some icons get updated, showing an issue with the stack trace symbolication (even though there's none)

### Product Area

Issues

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by roggenkemper**
this pr fixes a bug with some stack traces where the stack trace wouldn't update when switching between events, staying with the stacktrace of the initial event that was loaded. now, when the event changes, the state will also be updated. 

Closes https://github.com/getsentry/sentry/issues/53556

### CODE REVIEW

File: static/app/components/events/interfaces/threads.tsx [hunk 1]
```diff
@@ -85,6 +81,22 @@ export function getThreadStateIcon(state: ThreadStates | undefined) {
       return <IconInfo />;
   }
 }
+// We want to track the active thread but that can change if the eventId changes, so if the eventID we set the state to be the new best thread
```
Comment (malwilley) [inline static/app/components/events/interfaces/threads.tsx:84]: > so if the eventID we set

Missed a word! Also might want to change the wording to be more precise. We want to reset the active thread every time the event changes because we can't assume they are the same between events.

**Review by malwilley — APPROVED** [review]
