### PR TITLE
fix(view-hierarchy): Fix virtualized tree scrolling out of bounds

### LINKED ISSUE #44588: Clicking on the same element in the wireframe sometimes displaces the row highlight
https://user-images.githubusercontent.com/22846452/218786272-157b42ef-5ccd-4f20-af3e-e21a6ec03589.mov

The highlight should not move because it's on the correct row and it is visible.

### PR DESCRIPTION
**Pull request by edwardgou-sentry**
Adds a min and max boundary to computeVirtualizedTreeNodeScrollTop to ensure that the returned scrollTop value is always within the scrollable bounds. This fixes an issue where the ghost row would render focus incorrectly outside the actual selected row because the tree tries to scroll outside of bounds.

Closes [#44588](https://github.com/getsentry/sentry/issues/44588)

### CODE REVIEW

File: static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx [hunk 1]
```diff
@@ -67,6 +67,7 @@ export function useVirtualizedTree<T extends TreeLike>(
     scrollTop: 0,
     overscroll: props.overscroll ?? DEFAULT_OVERSCROLL_ITEMS,
     scrollHeight: props.scrollContainer?.getBoundingClientRect()?.height ?? 0,
+    maxScrollableHeight: (props.scrollContainer?.scrollHeight ?? 24) - 24, // Need subtract padding to get true height
```
Comment (edwardgou-sentry) [inline static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx:70]: As far as I know, there doesn't seem to be a way to directly get the scrollHeight excluding padding (which is what we need here). I had to subtract the padding height here, not the cleanest solution.

File: static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTreeReducer.tsx [hunk 2]
```diff
@@ -48,6 +55,9 @@ export function VirtualizedTreeReducer<T>(
     case 'set scroll height': {
       return {...state, scrollHeight: action.payload};
     }
+    case 'set max scrollable height': {
+      return {...state, maxScrollableHeight: action.payload};
+    }
```
Comment (edwardgou-sentry) [inline static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTreeReducer.tsx:60]: I think I could have update the `set scroll height` to also handle for `maxScrollableHeight`. Not totally sure if this would be cleaner/better. Let me know if anyone prefers that instead.

File: static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx (hunk 1 above)
Comment (edwardgou-sentry) [reply static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx]: removed vertical padding from view hierarchy so this is no longer needed

File: static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTreeReducer.tsx (hunk 2 above)
Comment (edwardgou-sentry) [reply static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTreeReducer.tsx]: removed maxScrollableHeight from reducer. This can be calculate when needed by multiplying the flattened tree length by rowHeight

File: static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx [hunk 3]
```diff
@@ -285,7 +287,13 @@ export function computeVirtualizedTreeNodeScrollTop(
   }
 
   if (block === 'center') {
-    return newPosition - scrollHeight / 2 + rowHeight;
+    return Math.max(
```
Comment (narsaynorath) [inline static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx:290]: small nit, but maybe we should leave a small comment about how we're bounding the scrolltop so we don't get a negative or something beyond the renderable elements

Comment (narsaynorath) [reply static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx:290]: Also, wouldn't all of these theoretically need this boundary calculation?

**Review by narsaynorath — APPROVED** [review]

File: static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx (hunk 3 above)
Comment (edwardgou-sentry) [reply static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx:295]: Yeah I _think_ the other block types are probably unbounded right now, so it might make sense to also put safeguards around them. Although, none of the other block types seem to be in use right now, so I haven't been testing those behaviours. lmk if you prefer I update those as well, or we can tackle it in the future

Comment (narsaynorath) [reply static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx:295]: Since it's only used once with this prop, I think we could just leave it for now and keep the change simple.

Comment (JonasBa) [reply static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx:295]: @edwardgou-sentry @narsaynorath In what case does an overscroll happen? Is it due to user action or do we improperly initialize something? I cant tell exactly from the description

Comment (narsaynorath) [reply static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx:295]: https://user-images.githubusercontent.com/22846452/220958109-25f7a847-cf34-404e-abc2-96da18d40d9d.mov


https://user-images.githubusercontent.com/22846452/220958121-2c1473fa-ab1f-4c71-81fe-0b46597d94ff.mov

Here are some examples where this happens. Basically it tries to scroll the row to the center, but if there aren't enough items to satisfy that scroll, the ghost row goes to the center but the selected row does not (and the hover row is displaced by the distance between the real row and the center). It seems to work if the row isn't in view but if it is it has this behaviour. It fixes itself if you trigger a scroll though

Comment (edwardgou-sentry) [reply static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx:295]: Hey @JonasBa ! Here's a couple scenarios where overscroll happens. It's usually when you click to an element on the flamegraph/viewhierarchy that is near the bottom of the tree. The tree tries `center` the selected node, but since the node is near the very bottom of the tree, it's not possible to fully center which causes the overscrolling effect. This can also happen when the node is at the very top of the tree too, which is why we bounded the minimum return value to 0.

https://user-images.githubusercontent.com/83961295/220958341-bce4b7d5-1296-44e7-99e0-37ecc377fcb1.mov
https://user-images.githubusercontent.com/83961295/220958353-9d6a3c2c-55a2-42e0-893e-db578e371011.mov

Comment (edwardgou-sentry) [reply static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx:295]: haha oops, nar responded before me, but he's entirely correct too.

Comment (JonasBa) [reply static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx:295]: Ahh, got it. Thanks for the explanation!

**Review by JonasBa — APPROVED** [review]
