### PR TITLE
ref: Update `file_formats` filters when querying Debug Files.

### LINKED ISSUE #44485: Debug file showing as deleted even though it isn't
### Environment

SaaS (https://sentry.io/)

### Version

_No response_

### Link

https://sentry-sdks.sentry.io/issues/3930501990/events/4ebd9752f0074af4b3c406765d08a710/?project=5428537

### DSN

_No response_

### Steps to Reproduce

Open linked event.  Click "Show Details" below the stack trace to see the debug info file.

image

Now click the `View` button to look at the details:

### Expected Result

Both the `sources` and `debug` files should show status `OK`.

### Actual Result

The `debug` file shows status `Deleted`. 

image

Hover on the status shows:

image

Hover on the download button shows:

image

Yet despite that, you can still click on the button and download the debug file, which has the `.pdb` extension.  If it truly had been deleted, then you wouldn't be able to download it, and symbolication of future events would fail - but they too succeed.

### PR DESCRIPTION
**Pull request by Swatinem**
The Debug Files project settings will not filter by type at all, since we want to see all the uploaded files.
The Debug Image details filter was out of sync, and the Debug Image details did not show Portable PDB files at all.

fixes https://github.com/getsentry/sentry/issues/44485

### CODE REVIEW

File: static/app/components/events/interfaces/debugMeta/debugImageDetails/index.tsx [hunk 1]
```diff
@@ -70,16 +70,30 @@ export class DebugImageDetails extends AsyncComponent<Props, State> {
...
         'debugFiles',
         `/projects/${organization.slug}/${projSlug}/files/dsyms/?debug_id=${debug_id}`,
         {
           query: {
-            file_formats: ['breakpad', 'macho', 'elf', 'pe', 'pdb', 'sourcebundle'],
+            // FIXME(swatinem): Ideally we should not filter here at all,
+            // though Symbolicator does not currently report `bcsymbolmap` and `il2cpp`
+            // candidates, and we would thus show bogus "unapplied" entries for those,
+            // which would probably confuse people more than not seeing successfully
+            // fetched candidates for those two types of files.
```
Comment (Swatinem) [inline static/app/components/events/interfaces/debugMeta/debugImageDetails/index.tsx:86]: A workaround for this would be to filter these candidates (on the symbolicator side) to only those from the internal sentry source.

File: static/app/components/events/interfaces/debugMeta/debugImageDetails/index.tsx [hunk 2]
```diff
@@ -70,16 +70,30 @@ export class DebugImageDetails extends AsyncComponent<Props, State> {
...
+            file_formats: [
+              'breakpad',
```
Comment (priscilawebdev) [inline static/app/components/events/interfaces/debugMeta/debugImageDetails/index.tsx:88]: should we create an enum for these values? we could reuse it in the file https://github.com/getsentry/sentry/blob/807eb1ca1d2015d37df0bb1b9538887e6b143582/static/app/views/settings/projectDebugFiles/utils.tsx#L4

**Review by priscilawebdev — APPROVED** [review]
code looks good to me...thanks for fixing it!

File: static/app/components/events/interfaces/debugMeta/debugImageDetails/index.tsx (hunk 2 above)
Comment (Swatinem) [reply static/app/components/events/interfaces/debugMeta/debugImageDetails/index.tsx:88]: Not sure if thats worth doing. possibly…
