### PR TITLE
fix(replays): Do not render older index responses that are replaced

### LINKED ISSUE #39252: Bug: Clicking into the Replays index from the sidebar does not respect the "locked" project
If you have a project that is "locked" in the project selector, and you click into the Replays page from the main nav bar, it will show replays for *all* projects instead of the locked project that will be selected in the project selector.

Image

### PR DESCRIPTION
**Pull request by ryan953**
Add an AbortController so that when updated props appear we only update state with the most recent response. Older requests will not hijack the page.

For example, we may have an in-flight request but then something causes `location` to change, resulting in a new index request. If the 2nd request is fast it may complete before the 1st. We want to abort the 1st request in that case and not update state.

| Before | After |
| --- | --- |
| Screen Shot 2022-10-21 at 4 45 23 PM | Screen Shot 2022-10-21 at 4 45 54 PM |

Fixes #39252

### CODE REVIEW

File: static/app/utils/replays/fetchReplayList.tsx [hunk 1]
```diff
@@ -26,12 +30,19 @@ type State = {
 
 type Result = State;
 
+type Props = {
+  api: Client;
+  eventView: EventView;
+  location: Location;
+  organization: Organization;
+};
```
Comment (ryan953) [inline static/app/utils/replays/fetchReplayList.tsx:38]: i was looking at adding an `AbortSignal` prop here, but `api.requestPromise` can't do anything with it, so it seemed easier to keep it in the hook layer, not put anything into this util.

With a signal here or not... the server is still going to do all the work and send data back down the pipe. So it's not worth the messier code.

**Review by billyvg — APPROVED** [review]
Not a blocker, have you looked into the possibility of not making the request at all?

**Comment by ryan953** [comment]
> Not a blocker, have you looked into the possibility of not making the request at all?

Yes I can! I added a quick guard into the fetchReplayList util, must have something in the `project` list.
