### PR TITLE
fix(framework-modal): Scale with screen height

### LINKED ISSUE #54927: Auto-size the framework selection modal
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

select one of the vanilla platforms (.NET for exampl)
modal appears with scroll and bottom buttons to skip cut off 
so whether you want to skip, or you do select, it is not celar what button to click since it does not appear
must scroll outside the modal to get to the skip & configure buttons

### Expected Result

modal window should autosize to fit screen or be small enough by default to fit in 13 inch mac type screen sizes

### Actual Result

image

### Product Area

Projects - Project Creation

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by ArthurKnaus**
New minimal supported screen height (before the whole modal scrolls) is 625px.

Screenshot 2023-08-28 at 13 44 36

Closes https://github.com/getsentry/sentry/issues/54927

### CODE REVIEW

File: static/app/components/onboarding/frameworkSuggestionModal.tsx [hunk 1]
```diff
@@ -387,6 +398,17 @@ const Actions = styled('div')`
...
+    display: flex;
+    flex-direction: column;
+    max-height: 80vh;
+    min-height: 500px;
+  }
+  section {
+    display: flex;
+    flex-direction: column;
+    min-height: 0;
+  }
```
Comment (ArthurKnaus) [inline static/app/components/onboarding/frameworkSuggestionModal.tsx:411]: I would have preferred not to overwrite the modal styles like this, but I did not find any other solution with the current structure 🤔

Comment (matejminar) [reply static/app/components/onboarding/frameworkSuggestionModal.tsx:411]: Can we please add a comment explaining why we are doing this?

**Review by matejminar — APPROVED** [review]
