### PR TITLE
fix(ui): admin dark mode fixes and refactor

### LINKED ISSUE #24954: Issue with Sentry's Dark Theme
### Version Information

Version: 21.4.0.dev0

### Steps to Reproduce

1. Switch to Dark Theme in user settings.

### Expected Result

Dark theme to work perfectly.

### Actual Result

It looks like the theme has some issues, for example, in the Admin Settings UI, the navbar's background color is in white, which makes it harder to read. I have noticed this in some other pages as well.

https://user-images.githubusercontent.com/67003720/113502159-80b6ba00-953b-11eb-9eed-72630fe161d4.mp4

Hope there'll be a fix for this.

Thanks,
[cosmicice](https://github.com/catcosmicice)

### PR DESCRIPTION
**Pull request by alxu-sentry**
Fixes #24954.

Admin page also unnecessarily duplicates many settings components which can be
reused, so refactor it.

Some pages still aren't perfect but it should be an improvement.

Before:

image

After:

image

### CODE REVIEW

File: src/sentry/static/sentry/app/styles/global.tsx [hunk 1]
```diff
@@ -62,6 +62,9 @@ const styles = (theme: Theme, isDark: boolean) => css`
   /* Override css in LESS files here as we want to manually control dark mode for now */
   ${isDark
     ? css`
+        .box {
+          background: ${theme.background};
+        }
```
Comment (billyvg) [inline src/sentry/static/sentry/app/styles/global.tsx:67]: Does this impact the main app anywhere?

File: src/sentry/static/sentry/app/views/admin/adminLayout.tsx [hunk 2]
```diff
@@ -1,64 +1,64 @@
...
-  flex-grow: 0;
-  width: ${p => p.theme.settings.sidebarWidth};
-  background: ${p => p.theme.white};
-  border-right: 1px solid ${p => p.theme.border};
-`;
+type Props = {
+  children: React.ReactNode;
+} & RouteComponentProps<{}, {}>;
+
+class AdminLayout extends React.Component<Props> {
```
Comment (EvanPurkhiser) [inline src/sentry/static/sentry/app/views/admin/adminLayout.tsx:43]: Doesn't need to be a class component.

**Review by evanpurkhiser — APPROVED** [review]

File: src/sentry/static/sentry/app/styles/global.tsx (hunk 1 above)
Comment (alxu-sentry) [reply src/sentry/static/sentry/app/styles/global.tsx:67]: i didn't comprehensively check but since `theme.background` is white in light mode, i think the worst case scenario is that dark mode black-on-white turns into black-on-gray, but that's already wrong in dark mode. i feel like we should be able to address those on a case-by-case basis as they arise.

File: src/sentry/static/sentry/app/views/admin/adminLayout.tsx (hunk 2 above)
Comment (alxu-sentry) [reply src/sentry/static/sentry/app/views/admin/adminLayout.tsx:43]: I think I was under the impression that class components are preferred, but I'm coming to the conclusion that React upstream is moving towards functional components instead, so I'll change this back. Thank you for the feedback.

Comment (EvanPurkhiser) [reply src/sentry/static/sentry/app/views/admin/adminLayout.tsx:43]: https://github.com/getsentry/develop/pull/293 check this out

File: src/sentry/static/sentry/app/views/admin/adminLayout.tsx [hunk 3]
```diff
@@ -1,64 +1,59 @@
...
+      },
+    ]}
+  />
+);
+
+type Props = {
+  children: React.ReactNode;
+} & RouteComponentProps<{}, {}>;
+
+const AdminLayout: React.FC<Props> = ({children, ...props}) => (
```
Comment (priscilawebdev) [inline src/sentry/static/sentry/app/views/admin/adminLayout.tsx:43]: should we remove `React.FC `as `children` is already part of `Props`? 
```suggestion
const AdminLayout = ({children, ...props}: Props) => (
```

**Review by priscilawebdev — APPROVED** [review]
