### PR TITLE
fix(replays): Add conditions for when no replay id exist in the transaction

### LINKED ISSUE #39979: Empty state for Replay column on Transaction Summary Mini-table (Currently triggers error and shows icon)
Image

Follows https://github.com/getsentry/sentry/pull/39798

### PR DESCRIPTION
**Pull request by jesus4497**
### Changes
- Added conditions to control and show a value when no `replayId` is found in the transaction

Closes #39979

image

### Test notes

- Made sure unit tests of summary page were passing
- Tested it didn't render a link
- Tested it shows the right value when no `replay id` is found

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/utils/discover/fieldRenderers.tsx [hunk 1]
```diff
@@ -343,8 +343,8 @@ const SPECIAL_FIELDS: SpecialFields = {
     sortField: 'replayId',
     renderFunc: data => {
       const replayId = data?.replayId;
-      if (typeof replayId !== 'string') {
-        return null;
+      if (typeof replayId !== 'string' || !replayId) {
+        return <Container>{t('N/A')}</Container>;
```
Comment (ryan953) [inline static/app/utils/discover/fieldRenderers.tsx:347]: `emptyValue` is a good variable to use here.

Comment (jesus4497) [reply static/app/utils/discover/fieldRenderers.tsx]: Screenshot updated!

**Review by ryan953 — APPROVED** [review]
