### PR TITLE
fix(discover): Pass the dataset query param to chart query

### LINKED ISSUE #47401: Use issue platform dataset in discover chart query when linked from an issue
Reproduction steps:

- Go to profiling issue
- Click "Open in Discover"
- See that the results in the chart widget do not match the returned rows

We need to ensure that the chart queries are querying the correct and same dataset that the table is.

### PR DESCRIPTION
**Pull request by malwilley**
Closes https://github.com/getsentry/sentry/issues/47401

Hopefully we can dynamically search the correct dataset soon, but until then this will make sure that the chart query is querying the same dataset as the table beneath it.

Before:

CleanShot 2023-04-20 at 15 56 55

After:

CleanShot 2023-04-20 at 15 54 53

### CODE REVIEW

File: static/app/utils/performance/constants.tsx [hunk 1]
```diff
@@ -2,4 +2,4 @@ import {URL_PARAM} from 'sentry/constants/pageFilters';
 
 export const MAX_TEAM_KEY_TRANSACTIONS = 100;
 
-export const PERFORMANCE_URL_PARAM = ['team', ...Object.values(URL_PARAM)];
+export const PERFORMANCE_URL_PARAM = ['team', 'dataset', ...Object.values(URL_PARAM)];
```
Comment (scefali) [inline static/app/utils/performance/constants.tsx:5]: @malwilley what does this constant do? a comment might be nice

**Review by scefali — APPROVED** [review]
