### PR TITLE
fix(replays): display unique frame colors in prioritized order

### LINKED ISSUE #50308: Replay: Busy timeline can have Clicks and Navigation occlude Errors
From: @realkosty 

> right now in the “timeline” bar at the top we seem to render event dots in such way that Navigation and User Click event dots can occlude the error event dot ([example replay](https://sentry.sentry.io/replays/b3b4bdc8ee1e47879f527ef09f6385a0/?referrer=%2Fissues%2F%3AgroupId%2F&t=6&t_main=console)). As a user this prevents me from knowing where the error happened on the overall session timeline (in example 00:06, but I only see that by looking at Console or Breadcrumbs, not the timeline).

image

---

When we render the colors in the Timeline we only show a maximum of 3 'rings' at once, so you can get up to 3 colors to represent all the data that's in that flowout. 

In the example screen shot we can see the flyout has 12 items in it, using 4 colors (gray, green, purple and red. yellow/warning is also possible but not shown). The most important data is the error (red). 

Therefore we should sort the colors we display in the order: red, yellow, green, blue, gray.

Should we render each color only once? We don't seem to do that currently (notice the green circle is larger, it's taking up 2 rings). TBD, ideas welcome!
Image

### PR DESCRIPTION
**Pull request by michellewzhang**
Fixes #50308 by displaying the frame colors in the replays timeline in a prioritized order, and only displaying unique colors (e.g. not displaying 2 rings of green, only displaying 1 ring of green).

Before prioritization:
Screenshot 2023-07-13 at 1 49 51 PM
Colors are not sorted by priority, leading the red color to be hidden.

After prioritization:
Screenshot 2023-07-13 at 1 49 31 PM
Red is now the outermost ring.

Before only displaying unique colors:
Screenshot 2023-07-13 at 1 50 02 PM
Bubble size is larger.

After only displaying unique colors:
Screenshot 2023-07-13 at 1 49 45 PM
Bubble size is smaller because only unique colors are displayed.

### CODE REVIEW

File: static/app/components/replays/breadcrumbs/replayTimelineEvents.tsx [hunk 1]
```diff
@@ -97,16 +97,26 @@ function Event({
...
   const uniqueColors = uniq(frames.map(getColor));
 
   // We just need to stack up to 3 times
-  const frameCount = Math.min(frames.length, 3);
+  const frameCount = Math.min(uniqueColors.length, 3);
+
+  // Sort the frame colors by color priority
+  // Priority order: red300, yellow300, green300, purple300, gray300
+  const sortedUniqueColors: Color[] = uniqueColors.sort(function (x, y) {
+    const colorOrder = ['red300', 'yellow300', 'green300', 'purple300', 'gray300'];
```
Comment (ryan953) [inline static/app/components/replays/breadcrumbs/replayTimelineEvents.tsx:109]:
```suggestion
  const sortedUniqueColors = uniqueColors.sort(function (x, y) {
    const colorOrder: Color[] = ['red300', 'yellow300', 'green300', 'purple300', 'gray300'];
```

**Review by ryan953 — APPROVED** [review]

File: static/app/components/replays/breadcrumbs/replayTimelineEvents.tsx [hunk 2]
```diff
@@ -97,16 +97,32 @@ function Event({
     }
   `;
 
-  // If we have more than 3 events we want to make sure of showing all the different colors that we have
+  // We want to make sure of showing all the different colors that we have
```
Comment (ryan953) [inline static/app/components/replays/breadcrumbs/replayTimelineEvents.tsx:100]: // We want to show the full variety of colors available.
