### PR TITLE
fix(alerts): Do not modify duplicate issue alert

### LINKED ISSUE #56409: Duplicating issue alert adds "A new issue is created"
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

duplicate an issue alert that does not have "A new issue is created"

### Expected Result

the alert is an exact duplicate

### Actual Result

"A new issue is created" is added to the duplicate before saving

### Product Area

Alerts

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by scttcper**
Skip adding the "A new issue is created" default condition when duplicating alerts. Fixes #56409

### CODE REVIEW

File: static/app/views/alerts/rules/issue/index.tsx [hunk 1]
```diff
@@ -325,16 +325,11 @@ class IssueRuleEditor extends DeprecatedAsyncView<Props, State> {
...
-    if (!ruleId) {
+
+    if (!ruleId && !this.isDuplicateRule) {
       // now that we've loaded all the possible conditions, we can populate the
       // value of conditions for a new alert
-      const id = 'sentry.rules.conditions.first_seen_event.FirstSeenEventCondition';
-      this.handleChange('conditions', [
-        {
-          id,
-          label: `${CHANGE_ALERT_PLACEHOLDERS_LABELS[id]}...`,
```
Comment (scttcper) [inline static/app/views/alerts/rules/issue/index.tsx:335]: CHANGE_ALERT_PLACEHOLDERS_LABELS was just undefined since this isn't defined there. the label comes from the config object

**Review by jangjodi — APPROVED** [review]
