### PR TITLE
fix(breadcrumbs): Fix breadcrumb resizer

### LINKED ISSUE #62710: Bug: Breadcrumb resizer is separated
Image

### PR DESCRIPTION
**Pull request by 17hogeju**
Closes https://github.com/getsentry/sentry/issues/62710

Before:
Screenshot 2024-01-09 at 11 13 17 AM

After:
Screenshot 2024-01-09 at 11 13 48 AM

### CODE REVIEW

File: static/app/components/events/interfaces/breadcrumbs/breadcrumbs.tsx [hunk 1]
```diff
@@ -330,7 +330,7 @@ const PanelDragHandle = styled('div')`
     content: '';
     height: 5px;
     width: 100%;
-    border-radius: ${p => p.theme.borderRadiusBottom};
+    border-radius: ${p => p.theme.borderRadius};
```
Comment (evanpurkhiser) [inline static/app/components/events/interfaces/breadcrumbs/breadcrumbs.tsx:333]: I think the real fix here is to fix the alignment so that it's correctly aligned to the bottom of the panel.

Not sure what we regressed to cause it to be pushed so far down

Comment (17hogeju) [reply static/app/components/events/interfaces/breadcrumbs/breadcrumbs.tsx:333]: So the bottom corners should be rounded, but remove the gap?

Comment (evanpurkhiser) [reply static/app/components/events/interfaces/breadcrumbs/breadcrumbs.tsx:333]: yeah, it should be aligned to the bottom of the panel so the bottom edge is aligned with the border

File: static/app/components/events/interfaces/breadcrumbs/breadcrumbs.tsx [hunk 2]
```diff
@@ -252,6 +252,7 @@ const StyledPanelTable = styled(PanelTable)`
   display: grid;
   overflow: hidden;
   grid-template-columns: 64px 140px 1fr 106px 100px;
+  margin-bottom: 0px;
```
Comment (evanpurkhiser) [inline static/app/components/events/interfaces/breadcrumbs/breadcrumbs.tsx:255]: I might pull it down one pixel so it covers the border. cc @vuluongj20 maybe

**Review by evanpurkhiser — APPROVED** [review]
