### PR TITLE
fix(ui) Fix error in account settings for new users

### LINKED ISSUE #45577: Unable to set 2FA as join new organisation process.
### Environment

SaaS (https://sentry.io/)

### Version

_No response_

### Link

_No response_

### DSN

_No response_

### Steps to Reproduce

1. Enforce 2FA in an organisation
2. Invite a new member
3. The user creates a new account or login into an existing account (without 2FA)
4. The user gets a prompt informing the organisation requires 2FA
5. The user gets an error when trying to set 2FA in https://sentry.io/settings/account/security/

### Expected Result

The user gets redirected to security settings to set 2FA

### Actual Result

User gets an error page:

Oops! Something went wrong
It looks like you've hit an issue in our client application. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

Sentry issue: https://sentry.sentry.io/issues/3988107425/?project=11276

No workarounds at the moment

### PR DESCRIPTION
**Pull request by markstory**
When a user is new and hasn't completed their membership requirements (setup 2fa) they will not be part of any organizations but will need to be able to view account settings.

Fixes #45577
Fixes JAVASCRIPT-2FHE

### CODE REVIEW

**Review by scttcper — APPROVED** [review]

File: static/app/views/organizationDetails/body.tsx [hunk 1]
```diff
@@ -99,34 +104,35 @@ function DeletionPending({organization}: Props) {
   );
 }
 
-function OrganizationDetailsBody({children, organization}: Props) {
+function OrganizationDetailsBody({children, organization}: BodyProps) {
   const status = organization?.status?.id;
   const routeContext = useRouteContext();
 
-  if (status === 'pending_deletion') {
+  if (organization && status === 'pending_deletion') {
```
Comment (scttcper) [inline static/app/views/organizationDetails/body.tsx:111]: feels like we should change organization to be optional if we have to check the existence

Comment (scttcper) [reply static/app/views/organizationDetails/body.tsx:111]: nevermind looking at the wrong props
