### PR TITLE
fix(replays): preserve entire location query when tabs clicked

### LINKED ISSUE #61231: Clicking on replay tab twice removes project query parameter
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to replays with a specific project selected
2. Click on the already selected tab titled "Replays" at the top of the page

### Expected Result

Nothing (or maybe just a refresh)

### Actual Result

It removes the project query parameter causing it to show me replays for every project, even ones I haven't selected. The odd part is that it fixes itself if it then click on "Selectors" and then back to "Replays".

### Product Area

Replays

### Link

https://sentry.sentry.io/replays/?project=4505800768618496&statsPeriod=30d

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by michellewzhang**
- Fixes https://github.com/getsentry/sentry/issues/61231
- Also added some extraneous style tweaks for the selector table empty state

Before:

https://github.com/getsentry/sentry/assets/56095982/612bfe24-4686-4c46-b95f-f58d9b5900a9

After:

https://github.com/getsentry/sentry/assets/56095982/255895e6-401d-4c74-b672-8347e82ef71f

### CODE REVIEW

File: static/app/views/replays/deadRageClick/selectorTable.tsx [hunk 1]
```diff
@@ -249,6 +249,8 @@ const MessageContainer = styled('div')`
   grid-auto-flow: row;
   gap: ${space(1)};
   justify-items: center;
+  text-align: center;
+  padding: ${space(4)};
```
Comment (ryan953) [inline static/app/views/replays/deadRageClick/selectorTable.tsx:253]: what's this doing?

**Review by ryan953 — APPROVED** [review]

File: static/app/views/replays/deadRageClick/selectorTable.tsx (hunk 1 above)
Comment (michellewzhang) [reply static/app/views/replays/deadRageClick/selectorTable.tsx:253]: I realized as I was testing this that the style here is a bit off when the screen size is small - i added some padding and text alignment to make it look better

Before:

SCR-20231207-pcbg

After:
SCR-20231207-pcdp

Comment (ryan953) [reply static/app/views/replays/deadRageClick/selectorTable.tsx:253]: oof, nice 👍
