### PR TITLE
fix: Sentry Stats page does not respect 24 hour clock format

### LINKED ISSUE #43423: Sentry Stats page does not respect 24 hour clock format
### Environment

SaaS (https://sentry.io/)

### Version

_No response_

### Link

_No response_

### DSN

_No response_

### Steps to Reproduce

1. Set clock to 24h in User Settings -> Account details
2. Go to Stats page

### Expected Result

See all times with 24h format. 

### Actual Result

Screenshot 2023-01-19 at 09 52 50

### PR DESCRIPTION
**Pull request by ajay-sentry**
This PR aims to fix a bug where if a user had their account settings set to use the 24 hour clock, we wouldn't respect their choice on the stats page and still end up showing the 12h clock instead. 

In this PR I use the existing util for getting the user's 24 hour clock setting from the ConfigStore to generate a boolean value that we then use to update the format of the date timestamp if needed.

I saw in the file I was working in that one of the fns was unused so I just removed it as well.

Closes https://github.com/getsentry/sentry/issues/43423

**Setting Off**
Screenshot 2025-03-12 at 3 34 37 PM

**Setting On**
Screenshot 2025-03-12 at 3 34 22 PM

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/views/organizationStats/usageChart/utils.tsx [hunk 1]
```diff
@@ -24,28 +26,29 @@ export const FORMAT_DATETIME_HOURLY = 'MMM D LT';
...
 
-  return parsedInterval
-    ? `${datetime.format(FORMAT_DATETIME_HOURLY)} - ${datetime
-        .add(parsedInterval.period as any, parsedInterval.periodLength as any)
-        .format('LT (Z)')}`
-    : datetime.format(FORMAT_DATETIME_HOURLY);
-}
+  const intervalFormat = use24Hours ? FORMAT_DATETIME_HOURLY_24H : FORMAT_DATETIME_HOURLY;
 
-export function getDateFromUnixTimestamp(timestamp: number) {
```
Comment (ajay-sentry) [inline static/app/views/organizationStats/usageChart/utils.tsx:46]: This was the fn not being used

File: static/app/views/organizationStats/usageChart/utils.tsx [hunk 2]
```diff
@@ -73,7 +76,7 @@ export function getXAxisDates(
 
   while (!start.isAfter(end)) {
     range.push(getDateFromMoment(start, interval, dateUtc));
-    start.add(period as any, periodLength as any); // FIXME(ts): Something odd with momentjs types
```
Comment (ajay-sentry) [inline static/app/views/organizationStats/usageChart/utils.tsx:76]: these as any's weren't needed anymore either

File: static/app/views/organizationStats/usageStatsOrg.tsx [hunk 3]
```diff
@@ -244,8 +247,15 @@ class UsageStatsOrganization<
 
     // If interval is a day or more, use UTC to format date. Otherwise, the date
     // may shift ahead/behind when converting to the user's local time.
-    const FORMAT_DATETIME =
-      intervalHours >= 24 ? FORMAT_DATETIME_DAILY : FORMAT_DATETIME_HOURLY;
+    let FORMAT_DATETIME;
+    if (intervalHours >= 24) {
+      // Daily format doesn't have time, so no change needed
+      FORMAT_DATETIME = FORMAT_DATETIME_DAILY;
+    } else if (shouldUse24Hours()) {
```
Comment (ajay-sentry) [inline static/app/views/organizationStats/usageStatsOrg.tsx:254]: using the ConfigStore value if its truthy

**Review by isabellaenriquez — APPROVED** [review]

File: static/app/views/organizationStats/usageChart/utils.tsx [hunk 4]
```diff
@@ -24,28 +26,29 @@ export const FORMAT_DATETIME_HOURLY = 'MMM D LT';
 export function getDateFromMoment(
   m: moment.Moment,
   interval: IntervalPeriod = '1d',
-  useUtc = false
+  useUtc = false,
+  use24Hours = shouldUse24Hours()
```
Comment (brendanhsentry) [inline static/app/views/organizationStats/usageChart/utils.tsx:30]: are you planning to use this parameter in something other than tests? if not, we can do something like the following (except set it to true) to test the formats.
https://github.com/getsentry/sentry/blob/58769db6f87570d432a417ccb948f8e3a300f0a3/static/app/utils/dates.spec.tsx#L34-L37

**Review by brendanhsentry — APPROVED** [review]
lgtm, left a small comment

File: static/app/views/organizationStats/usageChart/utils.tsx (hunk 4 above)
Comment (brendanhsentry) [reply static/app/views/organizationStats/usageChart/utils.tsx:30]: makes sense 👍

File: static/app/views/organizationStats/usageChart/utils.tsx (hunk 1 above)
Comment (vbro) [reply static/app/views/organizationStats/usageChart/utils.tsx:46]: Luckily, no need to check if this is used in `getsentry` because the frontend has moved to `sentry`.
