### PR TITLE
ref(groupingInfo): Fix contributing frame hidden when showing all values

### LINKED ISSUE #74977: [grouping info] Contributing frame hidden when showing all values
This customer had some pretty aggressive stacktrace rules which made it so only one frame got used for grouping:

Image

Clicking on All Values to see why the other frames were ignored gives this:

Image

Confusingly, in this view, that single contributing frame is hidden under the `+ show 5 similar` link. We should make sure that contributing frames never get collapsed out of view like this.

### PR DESCRIPTION
**Pull request by shayna-ch**
For #74977.

Sometimes contributing values get hidden(collapsed) under non-contributing values when switched to 'All Values'. This sets the default to expand the 'All Values' stacktrace so nothing is hidden.

### CODE REVIEW

File: static/app/components/events/groupingInfo/groupingComponentFrames.tsx [hunk 1]
```diff
@@ -10,16 +10,22 @@ import {GroupingComponentListItem} from './groupingComponent';
 
 interface GroupingComponentFramesProps {
   items: React.ReactNode[];
+  initialCollapsed?: boolean;
```
Comment (scttcper) [inline static/app/components/events/groupingInfo/groupingComponentFrames.tsx]: this component is only used in one place. avoid optional props when possible

File: static/app/components/events/groupingInfo/groupingComponentFrames.tsx [hunk 2]
```diff
@@ -10,16 +10,22 @@ import {GroupingComponentListItem} from './groupingComponent';
...
   maxVisibleItems?: number;
 }
 
 function GroupingComponentFrames({
   items,
   maxVisibleItems = 2,
+  initialCollapsed = true,
```
Comment (scttcper) [inline static/app/components/events/groupingInfo/groupingComponentFrames.tsx]: shouldn't need a default here

**Review by scttcper — APPROVED** [review]
