### PR TITLE
fix(view-hierarchy): Use absolute positions in Flutter

### LINKED ISSUE #44590: Use absolute positioning for Flutter view hierarchies
There were some issues collecting relative positions for VHs from Flutter, but we can easily handle this on the frontend by skipping the operation to add the parent's offset to the child's coordinates.

### PR DESCRIPTION
**Pull request by narsaynorath**
A workaround for it being difficult to get relative positions in Flutter. We have access to the SDK name and version so down the road we can transition these view hierarchies smoothly when the relative position is fixed.

Closes #44590

### CODE REVIEW

File: static/app/components/events/viewHierarchy/wireframe.tsx [hunk 1]
```diff
@@ -45,7 +47,10 @@ function Wireframe({hierarchy, selectedNode, onNodeSelect}: WireframeProps) {
 
   const canvasSize = useResizeCanvasObserver(canvases);
 
-  const hierarchyData = useMemo(() => getHierarchyDimensions(hierarchy), [hierarchy]);
+  const hierarchyData = useMemo(
+    () => getHierarchyDimensions(hierarchy, project.platform === 'flutter'),
```
Comment (edwardgou-sentry) [inline static/app/components/events/viewHierarchy/wireframe.tsx:51]: this is more of a question but do you know if `"dart-flutter"` should also be included in this change (idk if dart-flutter uses absolute positions and couldnt find a test project)? I just saw it listed as one of the platform categories

**Review by edwardgou-sentry — APPROVED** [review]
nice!

File: static/app/components/events/viewHierarchy/wireframe.tsx (hunk 1 above)
Comment (narsaynorath) [reply static/app/components/events/viewHierarchy/wireframe.tsx]: https://github.com/getsentry/sentry/pull/44582/commits/278e445023e269e8f01648dbac69682649f19a41

Thanks for that, added it and did an `.includes()` check now
