### PR TITLE
fix(dashboards): Load dashboard when created from template

### LINKED ISSUE #44783: Creating a dashboard template (via Template → Add Dashboard) should immediately open the created dashboard
### Problem Statement

When you click "Add Dashboard" from a dashboard template it all it does is show a notification in the corner that its been created.

image

Note: Creating a new dashboard via the "Create Dashboard" button opens that dashboard after you click "Save and Finish"

### Solution Brainstorm

When creating a dashboard via a dashboard template's "Add Dashboard", the newly created dashboard should be immediately opened.

### PR DESCRIPTION
**Pull request by om-ray**
This PR will load the dashboard created when you create a dashboard from a template.

Fixes #44783 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by om-ray** [comment]
@brentc @dcramer Please review this pr! I'm looking forward to your feedback!

**Comment by brentc** [comment]
Hi @om-ray. We'll review it shortly!

**Comment by om-ray** [comment]
@brentc Thank you!

File: static/app/views/dashboards/manage/index.tsx [hunk 1]
```diff
@@ -241,6 +241,21 @@ class ManageDashboards extends AsyncView<Props, State> {
     );
     this.onDashboardsChange();
     addSuccessMessage(`${dashboard.title} dashboard template successfully added.`);
+    setTimeout(() => {
+      this.loadDashboard(dashboard.title);
+    }, 500);
```
Comment (narsaynorath) [inline static/app/views/dashboards/manage/index.tsx:246]: We can remove the call to `this.onDashboardsChange()` because if we're redirecting to the dashboard now, there isn't actually much benefit to reloading the dashboards briefly

That also means we can remove the surrounding `setTimeout` because we should just redirect once we know the dashboard's been saved

File: static/app/views/dashboards/manage/index.tsx [hunk 2]
```diff
@@ -241,6 +241,21 @@ class ManageDashboards extends AsyncView<Props, State> {
...
+  }
+
+  loadDashboard(dashboardTitle: string) {
+    const {organization, location} = this.props;
+    const {dashboards} = this.state;
+    const dashboard = dashboards?.find(val => val.title === dashboardTitle);
```
Comment (narsaynorath) [inline static/app/views/dashboards/manage/index.tsx:252]: Instead of passing down the title and using `.find()`, line 233 actually returns the dashboard data in the response so we can directly plug that into the URL you're creating below. I would recommend storing that in a variable, maybe `newDashboard` and passing down `newDashboard.id`.

Doing a `.find()` actually has trouble loading the correct dashboard when there are duplicates. In the request we send the title with what's in the template (e.g. "General Template"), but if our backend detects there's another dashboard with the same name we append "copy N" (e.g. "General Template copy 1") and `.find()` finds the wrong dashboard here

**Review by narsaynorath — COMMENTED** [review]
Hey there @om-ray! Thanks a lot for the contribution, I've just left some comments on improvements I think we can make, please feel free to let me know if you have any questions and once the changes are ready you can re-request me as a reviewer.

I see the pipeline is saying it's failing for now, it's because we need to give access to your PR to successfully run it (this is for external PRs). Let me sort that out for you.

File: static/app/views/dashboards/manage/index.tsx (hunk 1 above)
Comment (om-ray) [reply static/app/views/dashboards/manage/index.tsx:246]: Got it! I'll fix this. Thank you for the review!

File: static/app/views/dashboards/manage/index.tsx (hunk 2 above)
Comment (om-ray) [reply static/app/views/dashboards/manage/index.tsx]: @narsaynorath I;ve fixed the issues you mentioned! Thank you for the feedback!

**Review by narsaynorath — APPROVED** [review]
Changes look good to me! I'm going to sort out the pipeline stuff because I think it's something on our end, but I'll let you know if we need anything else here. Thanks again for the contribution :100:

**Review by dashed — APPROVED** [review]

**Comment by chadwhitacre** [comment]
Hey @om-ray, sorry for the confusion, I don't think the branch actually needs to be up-to-date to merge, syncing just puts us through CI again. Once CI is green here @narsaynorath should be able to merge when ready.

**Comment by chadwhitacre** [comment]
Thanks for the contribution @om-ray! :-)

**Comment by narsaynorath** [comment]
Just wanted to follow up and mention it's been deployed and +1, thanks for the contribution @om-ray

**Comment by om-ray** [comment]
@chadwhitacre @narsaynorath Thank you so much for all your help!

**Comment by chadwhitacre** [comment]
https://twitter.com/chadwhitacre_/status/1656735802829701134 btw ;-)
