### PR TITLE
fix(replays): persist fast forward preference on player

### LINKED ISSUE #69660: Fast-forward inactivity checkbox does not work
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to replay with periods of inactivity.
2. Play until there is a period of inactivity

Screenshot 2024-04-25 at 9 15 36 AM

3. Click on the gear and uncheck `Fast-forward inactivity`
Screenshot 2024-04-25 at 9 16 51 AM

4. See that the banner for "Fast forwarding through inactivity" is removed and the replay has stopped fast forwarding and seems to have worked.
5. Restart the replay, or go to next point of replay where there is inactivity
6. Banner comes back and replay starts fast forwarding again even though box is unchecked.

[Direct link to Replay in my org from the screenshots](https://francisorg.sentry.io/replays/289e60dd82c148e68d73f1ca3d01d28d/?project=-1&query=&referrer=%2Freplays%2F&statsPeriod=90d&yAxis=count%28%29)  (replay starts with inactivity)
 

### Expected Result

Checkbox should work permanently.

### Actual Result

Checkbox only works for the section when it is checked, and then behavior reverts to Fast forward.
Screenshot 2024-04-25 at 9 18 44 AM

### Product Area

Replays

### Version

React 7.110

### PR DESCRIPTION
**Pull request by michellewzhang**
- Fixes https://github.com/getsentry/sentry/issues/69660
- Unchecking "fast-forward inactivity" wasn't working if you seeked somewhere in the timeline (e.g. it would start fast forwarding again, despite the check box remaining unchecked), see before video:

https://github.com/getsentry/sentry/assets/56095982/f8b12465-0b0d-4191-b140-fb20cdf4ff3d

After:

https://github.com/getsentry/sentry/assets/56095982/7df951d4-03be-4f27-b1a1-55bd1e4d3ef9

Fast forwarding still works as expected:

https://github.com/getsentry/sentry/assets/56095982/d4340d73-9293-42cf-be56-3868d95b6a90

### CODE REVIEW

File: static/app/components/replays/replayContext.tsx [hunk 1]
```diff
@@ -289,9 +289,11 @@ function ProviderNonMemo({
   const forceDimensions = (dimension: Dimensions) => {
     setDimensions(dimension);
   };
-  const onFastForwardStart = (e: {speed: number}) => {
-    setFFSpeed(e.speed);
-  };
+  const onFastForwardStart = useCallback((e: {speed: number}) => {
+    if (savedReplayConfigRef.current.isSkippingInactive) {
```
Comment (michellewzhang) [inline static/app/components/replays/replayContext.tsx:293]: only set the ff speed if our config is set to `isSkippingInactive: true`

File: static/app/components/replays/replayContext.tsx [hunk 2]
```diff
@@ -318,13 +320,7 @@ function ProviderNonMemo({
         return;
       }
 
-      const skipInactive = replayer.config;
-      if (skipInactive) {
```
Comment (michellewzhang) [inline static/app/components/replays/replayContext.tsx:322]: this was causing the bug with ff/no ff prefs not saving properly -- removing this bit seemed to fix it

i also wasn't quite sure what "_when the player resumes playing its not stuck_" meant; scrubbing in ff mode seems to work fine when i removed it🤔

File: static/app/components/replays/replayContext.tsx [hunk 3]
```diff
@@ -336,9 +332,9 @@ function ProviderNonMemo({
       if (playTimer.current) {
         window.clearTimeout(playTimer.current);
       }
-      if (skipInactive) {
-        replayer.setConfig({skipInactive: true});
-      }
+
+      replayer.setConfig({skipInactive: skipInactive});
```
Comment (michellewzhang) [inline static/app/components/replays/replayContext.tsx:336]: reset the replay config regardless of the truth of `skipInactive`, just in case

**Review by ryan953 — APPROVED** [review]
seems legit

**Comment by michellewzhang** [comment]
> seems legit

the opposite of what i was thinking

File: static/app/components/replays/replayContext.tsx (hunk 2 above)
Comment (c298lee) [reply static/app/components/replays/replayContext.tsx:322]: I think it might mean that it gets stuck in ff mode even if there is activity.

Comment (c298lee) [reply static/app/components/replays/replayContext.tsx:322]: I was playing around with it and it seemed like it might've been stuck in ff mode but I'm not sure, trying to get a video of it now

File: static/app/components/replays/replayContext.tsx (hunk 3 above)
Comment (billyvg) [inline static/app/components/replays/replayContext.tsx:336]:
```suggestion
      replayer.setConfig({skipInactive});
```

**Review by billyvg — APPROVED** [review]

File: static/app/components/replays/replayContext.tsx (hunk 2 above)
Comment (michellewzhang) [reply static/app/components/replays/replayContext.tsx:322]: hmm the behavior seems the same on my branch + prod for the replay i'm testing, do you have an example replay link?

Comment (c298lee) [reply static/app/components/replays/replayContext.tsx:322]: I tested using this one: https://sentry.sentry.io/replays/554d6125721246de95b56d9715974424. For the prod version, once you hit somewhere with no activity and it ff, if you scrub to a different stop, it will stop ff. However, on your branch if you hit inactivity and it ff, then you scrub to somewhere else, the ff persists. 
On prod:
https://github.com/getsentry/sentry/assets/55311782/eb30068a-9e8f-49e5-8b76-f10f12ee2447
On your branch: 
https://github.com/getsentry/sentry/assets/55311782/649b2adf-31e2-406e-837b-82c9f13bb6db

Comment (michellewzhang) [reply static/app/components/replays/replayContext.tsx:322]: ahh ok i see what you're saying. added this back in -- should be fixed now

Comment (c298lee) [reply static/app/components/replays/replayContext.tsx:322]: looks good ty! removing the videos now cuz pii

**Review by c298lee — APPROVED** [review]
