### PR TITLE
bug(replays): Remember list page filter so Replay header can link back to it

### LINKED ISSUE #42499: Bug: Selected project(s) are not retained in the page filter when using the breadcrumb navigation at the top of Replay Details
**Problem:**

The user-selected project(s) (this is excluding the case when the proj is "locked" on the page filters) is not retained when using the breadcrumb navigation at the top of the Replay Details page (to go back to the Replay Index page). 

The project(s) should be retained. This would match what happens when someone uses the breadcrumb navigation in the Issue Details to go back to the Issues Stream. This also makes for a more seamless user experience.

Image

**Solution:**

Retain user-selected project(s) when using the breadcrumb navigation in Replay Details to go back to Replay Index.

### PR DESCRIPTION
**Pull request by ryan953**
Preserve list-page query params when opening the replay details page, so that we can use those params in the Replay Header to link you back to where you came from.

Fixed workflow:
1. Do a search on the Replay List page (project/env/date/search-terms)
2. Click through to view a replay
3. Click here in the header to get back to your search: 
  SCR-20221220-j7q

Fixes #42499

### CODE REVIEW

File: static/app/views/replays/replayTable.tsx [hunk 1]
```diff
@@ -234,6 +241,7 @@ function ReplayTableRow({
               pathname: `/organizations/${organization.slug}/replays/${project?.slug}:${replay.id}/`,
               query: {
                 referrer,
+                ...eventView.generateQueryStringObject(),
```
Comment (billyvg) [inline static/app/views/replays/replayTable.tsx:244]: Will this also preserve pagination-related params?

**Review by billyvg — APPROVED** [review]

File: static/app/views/replays/replayTable.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/views/replays/replayTable.tsx:244]: good thinking ,looks like cursor is not in there. I'll marshal it manually.

Comment (billyvg) [reply static/app/views/replays/replayTable.tsx:244]: @ryan953 (I think not having cursor in there is preferable fwiw), it will be hard to maintain the user's position in the list as new Replays roll in

Comment (ryan953) [reply static/app/views/replays/replayTable.tsx:244]: ah, true. ok we're good to go then!
