### PR TITLE
fix(ui): Style hover state on webhook subscriptions

### LINKED ISSUE #93883: Small UI improvement - Fix styles when hovering over checkbox
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Setting up an internal integration, happens when hovering over checkboxes, such as 'error'. 

### Expected Result

Hovering styles should be same size as checkbox

### Actual Result

Hovering styles are not the same size as checkbox

Image

### Product Area

Settings - Developer Settings

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by leeandher**
The interaction state layer needed some additional CSS to apply properly
Resolves https://github.com/getsentry/sentry/issues/93883

**Before**
image

**After**
image

### CODE REVIEW

File: static/app/views/settings/organizationDeveloperSettings/subscriptionBox.tsx [hunk 1]
```diff
@@ -85,6 +85,7 @@ export default withOrganization(SubscriptionBox);
 const SubscriptionGridItem = styled('div')<{disabled: boolean}>`
   display: flex;
   justify-content: space-between;
+  align-items: flex-start;
```
Comment (Christinarlong) [inline static/app/views/settings/organizationDeveloperSettings/subscriptionBox.tsx:88]: css noob here - how does flex-start align the hover shadow to the box 👀 .

**Review by Christinarlong — APPROVED** [review]

File: static/app/views/settings/organizationDeveloperSettings/subscriptionBox.tsx (hunk 1 above)
Comment (leeandher) [reply static/app/views/settings/organizationDeveloperSettings/subscriptionBox.tsx:88]: @Christinarlong  this visualization makes it a little clearer, `stretch` is default so giving it excess vertical space will cause this overflow (since height on the checkbox is fixed)

https://css-tricks.com/snippets/css/a-guide-to-flexbox/#aa-align-items

Comment (Christinarlong) [reply static/app/views/settings/organizationDeveloperSettings/subscriptionBox.tsx:88]: ohhhhh I see, I didn't know stretch was the default
