### PR TITLE
ref(stacktrace): Add space between function name and file name

### LINKED ISSUE #50698: Native stack trace: Add space between function name and file
Image

### PR DESCRIPTION
**Pull request by 17hogeju**
Closes https://github.com/getsentry/sentry/issues/50698

### Before: 
Screenshot 2023-06-29 at 11 54 34 AM

### After: 
Screenshot 2023-06-29 at 11 54 45 AM

### CODE REVIEW

File: static/app/components/events/interfaces/nativeFrame.tsx [hunk 1]
```diff
@@ -273,6 +273,7 @@ function NativeFrame({
             ) : (
               `<${t('unknown')}>`
             )}
+            &nbsp;
```
Comment (evanpurkhiser) [inline static/app/components/events/interfaces/nativeFrame.tsx:276]:
```suggestion
            {' '}
```

Comment (evanpurkhiser) [reply static/app/components/events/interfaces/nativeFrame.tsx:276]: This is what you actually want I think

**Comment by evanpurkhiser** [comment]
Updated the PR title to follow our [commit guidelines](https://develop.sentry.dev/commit-messages/#commit-message-format)

**Review by malwilley — APPROVED** [review]
