### PR TITLE
fix(issues): Sanitize issue breadcrumb link

### LINKED ISSUE #59426: Sort key '-timestamp' not supported while navigating
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to an issue
2. Click the event count 
3. In the table event view reorder the event by clicking the timestamp column
4. Click on Issues in the breadcrumb of the page to navigate away to the issues list
5. 
Screenshot 2023-11-06 at 14 48 10

### Expected Result

No error and a sanitised URL.

May be the component should sanitise the URL or the retry action should strip the part that causes the error in the first place.

### Actual Result

Screenshot 2023-11-06 at 14 48 10

### Product Area

Dashboards

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by jangjodi**
Sanitize sort out of the issue breadcrumb link

fixes https://github.com/getsentry/sentry/issues/59426

### CODE REVIEW

File: static/app/views/issueDetails/header.tsx [hunk 1]
```diff
@@ -162,6 +162,11 @@ function GroupHeaderTabs({
   );
 }
 
+function sanitizeIssueBreadcrumbQuery(query: string): string {
+  const sanitizedQuery = query.replace('&sort=timestamp', '');
```
Comment (malwilley) [inline static/app/views/issueDetails/header.tsx:166]: Manipulating the string is error-prone, but luckily you can access the query string as an object like so:

```
const location = useLocation();

const query = location.query
```

And when you link to it, you can pass an object instead of a string:

```
to: { pathname: '/organizations/whatever/...', query: {...} }
```

**Review by malwilley — CHANGES_REQUESTED** [review]

File: static/app/views/issueDetails/header.tsx (hunk 1 above)
Comment (AdrienFromToulouse) [reply static/app/views/issueDetails/header.tsx:166]: May I jump in to say that the original issue point at a specific query param, although it would also break for any query params that is added from the previous view such as `Sort key '-runtime' not supported.` and many more.
You may want to filter out the ones that a certain view does not support may be (intersection of the filters)? however from the particular use case of moving from `/issues/123/events/` to `/issues` I don't think there is any filters that would work on both.

Cheers,

Comment (jangjodi) [reply static/app/views/issueDetails/header.tsx]: @malwilley @AdrienFromToulouse Thank you both for your feedback!

File: static/app/views/issueDetails/header.tsx [hunk 2]
```diff
@@ -245,7 +245,15 @@ function GroupHeader({
...
                 label: 'Issues',
-                to: `/organizations/${organization.slug}/issues/${location.search}`,
+                to: {
+                  pathname: `/organizations/${organization.slug}/issues/`,
+                  // Sanitize sort queries from query
+                  query: {
+                    project: location.query.project,
+                    referrer: location.query.referrer,
+                    stream_index: location.query.referrer,
+                  },
```
[the remark this answers is not in the document]
Comment (jangjodi) [reply static/app/views/issueDetails/header.tsx]: Thank you for the suggestion! That's definitely a better approach

**Review by scttcper — APPROVED** [review]

**Review by malwilley — APPROVED** [review]
