### PR TITLE
fix: adjusted time so that absolute is shown on hover and not relative

### LINKED ISSUE #34842: Console should show Relative time by default in the right hand column, hover for absolute time

### PR DESCRIPTION
**Pull request by Danondso**
Closes #34842 
Swapped Relative and absolute times on the console view.
image

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 1]
```diff
@@ -87,8 +86,8 @@ function ConsoleMessage({
         <MessageFormatter breadcrumb={breadcrumb} />
       </Message>
       <ConsoleTimestamp isLast={isLast} level={breadcrumb.level}>
-        <Hovercard body={`${t('Relative Time')}: ${relativeTimestamp}`}>
-          <DateTime date={breadcrumb.timestamp} timeOnly />
+        <Hovercard body={<DateTime date={breadcrumb.timestamp} timeOnly />}>
+          {relativeTimestamp}
```
Comment (evanpurkhiser) [inline static/app/views/replays/detail/console/consoleMessage.tsx:90]: Side note. Should this just be a `<Tooltip>` instead of hovercard?

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 2]
```diff
@@ -92,20 +91,15 @@ function ConsoleMessage({breadcrumb, isLast, startTimestamp = 0}: ConsoleMessage
...
-        <Hovercard
-          body={`${t('Relative Time')}: ${showPlayerTime(
-            breadcrumb.timestamp || '',
-            startTimestamp
-          )}`}
-        >
-          <DateTime
-            timeOnly
-            date={breadcrumb.timestamp}
+        <Tooltip title={<DateTime date={breadcrumb.timestamp} format="LTS" />}>
```
Comment (billyvg) [inline static/app/views/replays/detail/console/consoleMessage.tsx:94]: Let's use a format that already exists in `<DateTime>` -- also we should probably display the date here. I think in the console it's a bit noisy, but in a tooltip users will want the extra details.

I think passing `seconds` prop is all we need.

Comment (Danondso) [reply static/app/views/replays/detail/console/consoleMessage.tsx:94]: Changed and pushed, this is what it looks like now 
image

Comment (billyvg) [reply static/app/views/replays/detail/console/consoleMessage.tsx]: lgtm

**Review by billyvg — APPROVED** [review]
