### PR TITLE
fix(replays): only show dropdown filters on replay index main table

### LINKED ISSUE #55199: Remove filter options when Replay table is shown on Issue Details > Replays and Transaction Summary > Replays
Image

Note: This is a demo error.

Same issue on Txn Summary > Replays.

### PR DESCRIPTION
**Pull request by michellewzhang**
Closes https://github.com/getsentry/sentry/issues/55199

https://github.com/getsentry/sentry/assets/56095982/53ffd766-014c-45de-8b19-c1dc0780f9af

### CODE REVIEW

File: static/app/views/replays/replayTable/index.tsx [hunk 1]
```diff
@@ -152,41 +152,85 @@ function ReplayTable({
...
 
                 case ReplayColumn.COUNT_DEAD_CLICKS_NO_HEADER:
-                  return <DeadClickCountCell key="countDeadClicks" replay={replay} />;
+                  return (
+                    <DeadClickCountCell
+                      key="countDeadClicks"
+                      replay={replay}
+                      showDropdownFilters={false}
+                    />
+                  );
```
Comment (ryan953) [inline static/app/views/replays/replayTable/index.tsx:188]: are these the same case?

**Review by ryan953 — APPROVED** [review]
