### PR TITLE
fix(rulesnooze): Change default mute for integrations

### LINKED ISSUE #49494: Change default mute to mute for everyone if alert action is Slack
If you just click "mute" on the alert details page, the alert will be muted just for the user, as opposed to muted for everyone (which is in the dropdown). For alerts that have actions that directly go to a Slack channel or Slack user (e.g. "Send a notification to the {workspace} Slack workspace to {channel or user}") the only mute available should be "mute for everyone".

We can potentially change the button and banner language if the alert action is going to a user, since "mute for everyone" sounds a little odd (but on the backend that's how we need to process it) if that's not too much trouble.

If the alert has multiple actions this might get a bit hairy. If the actions go to multiple Slack channels, keep as "mute for everyone". If the actions go to a bunch of different places, maybe just keep the current behavior and let the user figure it out.

Ensure the link in the emails obey this behavior as well.

### PR DESCRIPTION
**Pull request by roggenkemper**
this pr changes how we deal with muting alerts depending on their rule actions. we created 3 categories that an alert rule can fall into. 

1. All the actions are the default (sentry.mail.actions.NotifyEmailAction) 
2. Some of the actions are the default while some are other integrations (Slack, Jira, etc.)
3. All of the actions are other integrations. 

We created these categories because muting an alert means different things for each of them. The main difference is that if an integration action is being used, mute for me is the only way to stop notifications for that action (what does mute for me for a slack notification going to an entire channel mean?). So if an integration action exists, we will make mute for everyone the default mute. If they are all integration actions, then we don't want to provide mute for me as an option while if there are still some of the default notifications, we do want to provide that (muting for me in this situation would only silence the non-integration notifications). 

Scenario 1: 
Screenshot 2023-05-24 at 1 46 13 PM

Scenario 2:
Screenshot 2023-05-24 at 1 40 40 PM

Scenario 3:
Screenshot 2023-05-24 at 1 45 43 PM

Closes https://github.com/getsentry/sentry/issues/49494

### CODE REVIEW

File: static/app/components/alerts/snoozeAlert.tsx [hunk 1]
```diff
@@ -106,20 +115,24 @@ function SnoozeAlert({isSnoozed, onSnooze, projectSlug, ruleId, hasAccess}: Prop
...
     }
-  }, [location.query, isSnoozed, handleMute]);
+  }, [location.query, isSnoozed, handleMute, ruleActionCategory]);
 
   const dropdownItems: MenuItemProps[] = [
     {
       key: 'me',
       label: t('Mute for me'),
       onAction: () => handleMute('me'),
+      hidden: ruleActionCategory !== RuleActionsCategories.SomeDefault,
```
Comment (malwilley) [inline static/app/components/alerts/snoozeAlert.tsx:129]: Would love a comment over these `hidden` props explaining why this option should be disabled for these cases

File: static/app/components/alerts/snoozeAlert.tsx [hunk 2]
```diff
@@ -141,22 +154,31 @@ function SnoozeAlert({isSnoozed, onSnooze, projectSlug, ruleId, hasAccess}: Prop
...
-        onClick={() => handleMute('me')}
+        hasDropdown={ruleActionCategory !== RuleActionsCategories.NoDefault}
+        onClick={() => {
+          const target =
+            ruleActionCategory !== RuleActionsCategories.AllDefault ? 'everyone' : 'me';
+          handleMute(target);
+        }}
       >
-        {t('Mute')}
+        {ruleActionCategory === RuleActionsCategories.AllDefault
```
Comment (malwilley) [inline static/app/components/alerts/snoozeAlert.tsx:164]: Is there a reason why this logic is slightly different from the one in the `onClick`? Would make me feel better if they both shared logic so they can't diverge, maybe earlier do something like 

`const primaryMuteAction = RuleActionsCategories.AllDefault ? 'me' : 'everyone'`

Could even simplify a little more and do

`const primaryMuteAction = dropdownItems.find(item => !item.hidden)`

File: static/app/components/alerts/snoozeAlert.tsx [hunk 3]
```diff
@@ -141,22 +154,31 @@ function SnoozeAlert({isSnoozed, onSnooze, projectSlug, ruleId, hasAccess}: Prop
...
-          <DropdownTrigger
-            {...triggerProps}
-            aria-label={t('Mute alert options')}
-            icon={<IconChevron direction="down" size="xs" />}
-          />
-        )}
-        items={dropdownItems}
-        isDisabled={disabled || !hasAccess}
-      />
+      {ruleActionCategory !== RuleActionsCategories.NoDefault && (
```
Comment (malwilley) [inline static/app/components/alerts/snoozeAlert.tsx:168]: nit: could simplify the logic a bit if you wanted and do 

`const hasDropdown = dropdownItems.filter(item => !item.hidden).length > 0`

**Review by scefali — APPROVED** [review]

File: static/app/components/alerts/snoozeAlert.tsx (hunk 2 above)
Comment (roggenkemper) [reply static/app/components/alerts/snoozeAlert.tsx:164]: no specific reason, i just flipped the check but having shared logic makes sense. i think having it go off the dropdown might make it a little more confusing though? especially since if there are no default integrations then there are no dropdown items since both are hidden.

Comment (malwilley) [reply static/app/components/alerts/snoozeAlert.tsx:164]: Ah yeah that's fair, just tossing out ideas that may be worse 😄

**Review by malwilley — APPROVED** [review]
