### PR TITLE
bug(replay): Refactor the replay memory charts and render correct start/end times

### LINKED ISSUE #51492: Bug: Replay Details Memory Chart hooks are called out of order
Image

Same with DOM nodes chart on the same tab

### PR DESCRIPTION
**Pull request by ryan953**
This is a bit of a refactor for our Replay Details memory & dom nodes charts

"Big" changes include:

1. Insert a data series with start/end timestamps that align to the replay. So the time axis matches the Timeline component.
There may be gaps at the start/end of that chart now like this, which is a good thing! SCR-20240325-liiw

2. Simplify the memoization story by using useMemo more
3. Let the charts adjust in height when the window resizes
4. Change the x-axis to be 'time with replay' instead of absolute timestamp, so strings fit better side by side. Aligns timestamps with the Timeline component. SCR-20240325-ljox

Fixes https://github.com/getsentry/sentry/issues/51492
Related to https://github.com/getsentry/sentry/issues/51465
Related to https://github.com/getsentry/sentry/issues/65542

### CODE REVIEW

**Comment by billyvg** [comment]
We current show free + used heap -- do you think we can remove "free"? I think the most common case will be looking for memory leaks which only used will be helpful for

**Comment by ryan953** [comment]
> We current show free + used heap -- do you think we can remove "free"? I think the most common case will be looking for memory leaks which only used will be helpful for

@billyvg Ya, it's no problem to remove that!

File: static/app/views/replays/detail/memoryPanel/domNodesChart.tsx [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+        label: {show: false},
+        lineStyle: {type: 'solid', color: theme.purple200, width: 2},
+      },
+    }),
+    [currentHoverTime, theme.purple200]
+  );
+
+  return (
+    <AreaChart
+      series={staticSeries.concat(currentTimeSeries, hoverTimeSeries)}
```
Comment (billyvg) [inline static/app/views/replays/detail/memoryPanel/domNodesChart.tsx:180]: Does `useMemo` do here since we're always creating a new array?

File: static/app/views/replays/detail/memoryPanel/domNodesChart.tsx [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+      data: [],
+      markLine: {
+        symbol: ['', ''],
+        data: [{xAxis: currentTime}],
+        label: {show: false},
+        lineStyle: {type: 'solid', color: theme.purple300, width: 2},
+      },
+    }),
+
+    [currentTime, theme.purple300]
```
Comment (billyvg) [inline static/app/views/replays/detail/memoryPanel/domNodesChart.tsx:160]: Is `useMemo` the right thing to use here since currentTime is alway changing (assuming replay is playing).

**Review by billyvg — APPROVED** [review]

File: static/app/views/replays/detail/memoryPanel/domNodesChart.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/views/replays/detail/memoryPanel/domNodesChart.tsx:180]: yeah, i could wrap this in a useMemo too. I was thinking that hoverTime changes all the time, but that's not true when you hover over the chart. The click/hover targets are really small inside the chart, so if you're interacting with it it's actually really stable props wise.

File: static/app/views/replays/detail/memoryPanel/domNodesChart.tsx (hunk 2 above)
Comment (ryan953) [reply static/app/views/replays/detail/memoryPanel/domNodesChart.tsx:160]: if the replay is paused then that timestamp won't change
