### PR TITLE
bug(replays): Fix resizing the video player area

### LINKED ISSUE #36778: Bug: Replay sidebar can be resized to cutoff the video box
It's possible to resize the sizebar and cutoff the video controls.

Image

The video itself shouldn't be having it's own min-height, but maybe it does?
-> I think it shouldn't because the resizable `<SplitPanel>` should be doing the min/max height settings, not the video window itself. 
It might not be that there's a min set, instead it could be something else.

### LINKED ISSUE #36780: Design Nit: `VideoSection` has a black background in fullscreen mode
Go into fullscreen mode and notice the black background behind everything:

Image

### PR DESCRIPTION
**Pull request by ryan953**
This fixes an issue where the video area can be cutoff by the resize handler

**Before:**
Screen Shot 2022-07-22 at 1 49 14 PM

What was happening is that that area is composed of 3 parts top to bottom: url bar + video + play/pause controls.

The area was sized with flexbox, so it didn't have an explicit height. The inner bits of the video did use `height: 100%` however, so when resizing the make things smaller the video stay equal to the height of the overall area. It would then shrink after the height of the url bar + play/pause controls was hidden.

TL/DR: use flexbox for all inner elements. `flex-direction: column; flex-grow: 1;` achieves the same as `height: 100%;` in there.

Other Changes
1. Quick thing that's caused a lot of lines to be changed: `isFullscreen` wasn't needed by anything anymore. So that prop is removed from a bunch of layers.
2. Fixed the background color when in fullscreen mode, this bug was copy+pasted into `eventReplay.tsx` too.
3. Tested the player that appears on the Event Details page, and it still looks proper.
Issues:
1. The Scrubber isn't inside a `<Panel>` anymore. So there's no border around it. It functions as the bottom-border for the player area which I think is kind of neat. The reason for this is that the `overflow:hidden` was cutting off the bottom of the circular nub, so i had to +padding -margin shift to make space.
3. Open issue: The scrubber nub is cutoff on the left+right edge. This is because of the `overflow:hidden` we need everywhere in order to force containers to shrink their content.
It looks like this, I don't think it's the end of the world. There are ways to fix it, like rendering that elem (much much) higher up in the dom.
Screen Shot 2022-07-22 at 1 55 17 PM

Fixes #36778 
Fixes #36780

### CODE REVIEW

File: static/app/components/replays/replayView.tsx [hunk 1]
```diff
@@ -10,54 +9,48 @@ import ReplayPlayer from 'sentry/components/replays/replayPlayer';
...
+  overflow: hidden;
 
-const PanelNoMargin = styled(Panel)<{isFullscreen: boolean}>`
-  margin-top: ${space(1)};
-  margin-bottom: 0;
-  height: 100%;
-  display: grid;
-  grid-template-rows: 1fr auto;
+  padding-bottom: ${space(1)};
+  margin-bottom: -${space(1)};
```
Comment (ryan953) [inline static/app/components/replays/replayView.tsx:40]: These are here because of the first issue i mentioned in the desc.

The scrubber nub was being cutoff on the bottom by overflow:hidden. So we fudge some space. css is awesome!

File: static/app/components/replays/replayView.tsx [hunk 2]
```diff
@@ -10,54 +9,48 @@ import ReplayPlayer from 'sentry/components/replays/replayPlayer';
...
-      </ReplayControllerWrapper>
+      </PlayerContainer>
+      <ReplayController toggleFullscreen={toggleFullscreen} />
     </Fragment>
   );
 }
 
-const ReplayControllerWrapper = styled(PanelBody)`
-  padding-top: ${space(1)};
-`;
```
Comment (ryan953) [inline static/app/components/replays/replayView.tsx:38]: replaced with `gap` in index.tsx and eventReplay.tsx, so the extra dom node can go away too.

File: static/app/components/replays/replayView.tsx [hunk 3]
```diff
@@ -10,54 +9,48 @@ import ReplayPlayer from 'sentry/components/replays/replayPlayer';
...
+const PlayerContainer = styled('div')`
+  display: flex;
+  flex-direction: column;
+  flex-wrap: nowrap;
+  flex-grow: 1;
+  overflow: hidden;
 
-const PanelNoMargin = styled(Panel)<{isFullscreen: boolean}>`
```
Comment (ryan953) [inline static/app/components/replays/replayView.tsx:40]: stopped using Panel here because a) was overriding a lot of stuff b) the scrubber nub was cutoff at the border

So if we add border and manage radius manually anyway, don't need this panel anymore. Replace with `const Panel = ...`

File: static/app/components/events/eventReplay.tsx [hunk 4]
```diff
@@ -51,4 +46,12 @@ export default function EventReplay({replayId, orgSlug, projectSlug}: Props) {
...
   max-width: 420px;
   margin-top: ${space(2)};
+
+  background: ${p => p.theme.background};
+  display: flex;
+  flex-direction: column;
+  flex-wrap: nowrap;
+  flex-grow: 1;
+  overflow: hidden;
+  gap: ${space(1)};
```
Comment (billyvg) [inline static/app/components/events/eventReplay.tsx:56]: This CSS seems to be repeated a bit, wonder if it's worth making as its own [styled] component?

**Review by billyvg — APPROVED** [review]

File: static/app/components/events/eventReplay.tsx (hunk 4 above)
Comment (ryan953) [reply static/app/components/events/eventReplay.tsx:56]: it is! it's used 4 times in `styled('div')...` statements.

I was able to put the shared css into a new component `FluidHeight` which all 4 of those examples.
