### PR TITLE
fix(global-search): Remove scroll logic on mouse hover and keep open after focus is lost

### LINKED ISSUE #41935: Global search (⌘+K) results scrolling jitters and results disappears on input blur
On ⌘+K, if search results are scrollable, the overflow can jitter due to keyboard navigation. Additionally, on input blur (which can be reproduced by focusing in a different window) results disappear.

Image

### PR DESCRIPTION
**Pull request by malwilley**
Closes https://github.com/getsentry/sentry/issues/41935

- Fixes jittery scrolling in the global search. This logic is no longer necessary because Autocomplete does this on keyboard events.
- Keeps the search open at all times, even after focus is lost. Since it's a full page component, there shouldn't be a reason we need to ever close it

### CODE REVIEW

File: static/app/components/search/searchResultWrapper.tsx [hunk 1]
```diff
@@ -1,17 +1,7 @@
 import {css} from '@emotion/react';
 import styled from '@emotion/styled';
 
-interface Props extends React.HTMLAttributes<HTMLDivElement> {
-  highlighted?: boolean;
-}
-
-function scrollIntoView(element: HTMLDivElement) {
-  element?.scrollIntoView?.({block: 'nearest'});
```
Comment (evanpurkhiser) [inline static/app/components/search/searchResultWrapper.tsx:9]: Wait but how does it scroll with keyboard navigation then?

IMO Having keyboard navigation scrolling is more important than fixing some jitter from the mouse hover.

If we want to fix this, we should try and keep the auto-scrolling behavior when navigating with the keyboard (in my opinion at least)

Comment (malwilley) [reply static/app/components/search/searchResultWrapper.tsx:9]: `Autocomplete` handles the scrolling logic, which was added in https://github.com/getsentry/sentry/pull/38809

Looks like this was something I should have removed when I made that change but missed

Comment (evanpurkhiser) [reply static/app/components/search/searchResultWrapper.tsx:9]: Awesome!

**Review by evanpurkhiser — APPROVED** [review]
