### PR TITLE
fix(dynamic-sampling): Fix unsupported search query FE

### LINKED ISSUE #72857: Fix the front-end of discover so the API is not called with default wrong arguments

### PR DESCRIPTION
**Pull request by priscilawebdev**
closes https://github.com/getsentry/sentry/issues/72857
relates https://github.com/getsentry/sentry/issues/72300

### CODE REVIEW

File: static/app/components/dynamicSampling/investigationRule.tsx [hunk 1]
```diff
@@ -174,34 +178,20 @@ const InvestigationInProgressNotification = styled('span')`
   gap: ${space(0.5)};
 `;
 
-function checkIsTransactionQueryMissing(error: RequestError | null) {
```
Comment (priscilawebdev) [inline static/app/components/dynamicSampling/investigationRule.tsx:177]: since the request won't be fired if `event.type='transaction'` is not present in the query, this won't happen anymore - therefore I am removing this code

File: static/app/components/dynamicSampling/investigationRule.tsx [hunk 2]
```diff
@@ -174,34 +178,20 @@ const InvestigationInProgressNotification = styled('span')`
...
   const organization = props.organization;
   const period = props.eventView.statsPeriod || null;
   const query = props.eventView.getQuery();
+  const isTransactionQueryMissing =
+    getQueryDatasource(query)?.source !== Datasource.TRANSACTION;
   const createInvestigationRule = useCreateInvestigationRuleMutation();
   const {
     data: rule,
-    isLoading,
+    isFetching: isLoading,
```
Comment (priscilawebdev) [inline static/app/components/dynamicSampling/investigationRule.tsx:191]: had to use `isFetching` instead of `isLoading`, because, in this current version of react-query, the `isLoading` state is always `true` if `enabled` equals `false`

**Review by ArthurKnaus — APPROVED** [review]
