### PR TITLE
fix(replays): remove slow click and multiclick surfacing on DOM events tab

### LINKED ISSUE #54068: [Replay Details] Round the number of ms we show for slow/dead/rage clicks
Image

### PR DESCRIPTION
**Pull request by michellewzhang**
We want to hide slow clicks and multiclicks on the UI, specifically in the DOM events tab.

Before (slow clicks):
SCR-20230803-jwfu

After (no slow clicks):
SCR-20230803-jwex

Before (multi clicks in the "unknown" category):
SCR-20230803-kfif

After (no unknown category --> no multi clicks):
SCR-20230803-kfov

Also closes https://github.com/getsentry/sentry/issues/54068.

### CODE REVIEW

File: static/app/utils/replays/replayReader.tsx [hunk 1]
```diff
@@ -195,7 +195,13 @@ export default class ReplayReader {
...
   getDomNodes = memoize(() =>
     extractDomNodes({
-      frames: this.getDOMFrames(),
+      frames: this.getDOMFrames().filter(
+        frame =>
+          !(
+            (frame as SlowClickFrame).category === 'ui.slowClickDetected' &&
+            !isDeadClick(frame as SlowClickFrame)
+          )
+      ),
```
Comment (ryan953) [inline static/app/utils/replays/replayReader.tsx:204]: Can we put this inside of `getDOMFrames`
That way the list of frames (getDOMFrames) and the list of Node (getDomNodes) are both based on the same filtered array

File: static/app/utils/replays/replayReader.tsx [hunk 2]
```diff
@@ -188,10 +189,19 @@ export default class ReplayReader {
...
+  getDOMFrames = memoize(() =>
+    [
+      ...this._sortedBreadcrumbFrames.filter(frame => 'nodeId' in (frame.data ?? {})),
+      ...this._sortedSpanFrames.filter(frame => 'nodeId' in (frame.data ?? {})),
+    ].filter(
+      frame =>
+        !(
+          ((frame as SlowClickFrame).category === 'ui.slowClickDetected' &&
+            !isDeadClick(frame as SlowClickFrame)) ||
+          (frame as MultiClickFrame).category === 'ui.multiClick'
```
Comment (ryan953) [inline static/app/utils/replays/replayReader.tsx:201]:
```suggestion
          (frame.category === 'ui.slowClickDetected' &&
            !isDeadClick(frame as SlowClickFrame)) ||
          frame.category === 'ui.multiClick'
```

**Review by ryan953 — APPROVED** [review]
