### PR TITLE
fix(replays): Fix the Replay Network table so it highlights error status codes in red at all times

### LINKED ISSUE #39154: [bug] Network table gray font color is taking precedence over red
When a Network request has a bad status (like 404, 500, etc) it currently will have red font _but only if the video timestamp is after the time that network request was started.

The gray color is taking precedence over the red. I think this is the wrong way around, when i load up the page I don't get that color to attract me to the problems. The red could be faded or something.

Image
Image

Related to https://github.com/getsentry/sentry/pull/39123 & https://github.com/getsentry/sentry/issues/38947

### PR DESCRIPTION
**Pull request by ryan953**
Tested all the combos (see table). Not shown but also checked that if the table is sorted by another column we always go with the red.

| | Normal Sort order (first event at top)  | Reverse sort order |
| --- | ------------- | ------------- |
| 404 not yet happened | normal sort, not yet at the 404  | reverse sort, not yet at the 404  |
| 404 has occurred | normal sort, after 404  | reverse sort, after the 404  |

Also fixing a bug where the "Missing" text wasn't highlighted:
Before:
Screen Shot 2022-09-22 at 12 07 36 PM

Fixes #39154

### CODE REVIEW

File: static/app/views/replays/detail/network/index.tsx [hunk 1]
```diff
@@ -296,51 +295,49 @@ const EmptyText = styled(Text)`
 `;
 
 const Item = styled('div')<{
+  hasOccurred: boolean;
+  isCurrent: boolean;
+  isStatusError: boolean;
+  timestampSortDir: SortDirection | undefined;
```
Comment (ryan953) [inline static/app/views/replays/detail/network/index.tsx:301]: turns out all these are always set, so we don't need default params down below
ie: no more:
`color: ${({hasOccurred = true, isStatusError, timestampSort, ...p}) => { ...`

just keep it simple: `color $(p => { ...`

File: static/app/views/replays/detail/network/index.tsx [hunk 2]
```diff
@@ -296,51 +295,49 @@ const EmptyText = styled(Text)`
...
-    color: ${({hasOccurred = true, timestampSort, ...p}) => {
-      if (hasOccurred || !timestampSort) {
-        return p.theme.gray400;
+    color: ${p => {
+      if (p.isStatusError) {
+        return p.hasOccurred || !p.timestampSortDir ? p.theme.red400 : p.theme.red200;
       }
-      return p.theme.gray300;
+      return p.hasOccurred || !p.timestampSortDir ? p.theme.gray400 : p.theme.gray300;
     }};
```
Comment (ryan953) [inline static/app/views/replays/detail/network/index.tsx:341]: This is the same color logic thats we use on line ~310

Comment (billyvg) [reply static/app/views/replays/detail/network/index.tsx:341]: If it's the same, it would be worth extracting into function to use in both places

**Review by billyvg — APPROVED** [review]
