### PR TITLE
ref(types): Fix PlatformKey type

### LINKED ISSUE #55906: Generate PlatformKey type from platform definitions
Currently the type `PlatformKey` is generated from the platform category definitions. Those however do not include all platforms.

Proposed solution:
1. Generate the type from the platforms array in `platforms.tsx`
2. Make the platform categories type save by giving them the type `PlatformKey[]`

References:
* [static/app/data/platformCategories.tsx](https://github.com/getsentry/sentry/blob/f9e62f5767804f9844f92348cb4b8cb4f22d8195/static/app/data/platformCategories.tsx)
* [static/app/views/projectInstall/platform.tsx](https://github.com/getsentry/sentry/blob/4d864b21ccf389465a7ba14490faefdd9acf5ffc/static/app/views/projectInstall/platform.tsx)

### PR DESCRIPTION
**Pull request by ArthurKnaus**
Create an explicit type for `PlatformKey`.

The main change is in [ref(types): Add hard-coded PlatformKey type](https://github.com/getsentry/sentry/pull/56920/commits/c5e463eaf2c40424bfab53127bf33b8343c316ce) 
[ref(types): Adjust imports](https://github.com/getsentry/sentry/pull/56920/commits/7555075f3faa25b9e5fdd487ed75813fac7c45b9) is about updating the imports of `PlatformKey`.

Background:
We already had a few cases of missing platforms in `PlatformKey` as the key was only deduced from the `platformCategories`.

Closes https://github.com/getsentry/sentry/issues/55906

### CODE REVIEW

File: static/app/types/project.tsx [hunk 1]
```diff
@@ -120,6 +118,127 @@ export interface TeamWithProjects extends Team {
...
+  | 'native-crashpad'
+  | 'native-minidump'
+  | 'perl'
+  | 'php-monolog'
+  | 'php-symfony'
+  | 'python-azurefunctions'
+  // TODO(aknaus): check if those are really platform keys and clean up
+  | 'python-tracing'
+  | 'node-tracing'
+  | 'react-native-tracing';
```
Comment (ArthurKnaus) [inline static/app/types/project.tsx:240]: Those are used to load docs in https://github.com/getsentry/sentry/blob/242fd1dd0654e85bf027df59131db516a0b55395/static/app/components/events/interfaces/spans/inlineDocs.tsx

I doubt that they are real platforms in the DB called like this 🤔

File: static/app/types/event.tsx
Comment (ArthurKnaus) [inline static/app/types/event.tsx:1]: In this file we have the definition of
```ts
export type PlatformType = PlatformKey | 'objc' | 'cocoa';
```
It is widely used  in our codebase.
Should this be consolidated it with `PlatformKey` in the future?

**Review by ryan953 — APPROVED** [review]
Update all the imports!
