### PR TITLE
fix(replays): Fix replay query on the Transaction/Replays list page

### LINKED ISSUE #37940: Make sure the Tabs on Transaction/Summary and Issue/Details show the correct count of replays
You're going to see more than `1`:

Screen Shot 2022-08-17 at 12 05 28 PM

### PR DESCRIPTION
**Pull request by ryan953**
Fixes #37940

### CODE REVIEW

File: static/app/utils/replays/hooks/useReplayList.tsx [hunk 1]
```diff
@@ -36,6 +36,42 @@ type State = {
...
+  } catch (error) {
+    Sentry.captureException(error);
+    return {
+      fetchError: error,
+      isFetching: false,
+      pageLinks: null,
+      replays: [],
+    };
+  }
+}
```
Comment (ryan953) [inline static/app/utils/replays/hooks/useReplayList.tsx:73]: refactor so I could call the function without the hooks wrapper stuff in the way.
Because there's a new hook with an async step in the middle, so this is the first way i sorted out how to solve for that and code share.

File: static/app/views/performance/transactionSummary/transactionReplays/content.tsx [hunk 2]
```diff
@@ -76,7 +77,7 @@ function ReplaysContent({
         isFetching={isFetching}
         replays={replays}
         showProjectColumn={false}
-        sort={eventView.sorts[0]}
+        sort={first(eventView.sorts) || {field: 'createdAt', kind: 'asc'}}
```
Comment (ryan953) [inline static/app/views/performance/transactionSummary/transactionReplays/content.tsx:80]: Using `[0]` was unsafe, it could return `undefined` if the array is empty.

**Review by billyvg — APPROVED** [review]

File: static/app/views/performance/transactionSummary/transactionReplays/content.tsx (hunk 2 above)
Comment (ryan953) [reply static/app/views/performance/transactionSummary/transactionReplays/content.tsx:80]: I like to avoid lodash too; but that's not 100% the same it's more like 'if the var is not an array' and the problem is that i have an array, but the length could be zero. `noUncheckedIndexedAccess` seems like the compilerOption, maybe we can enable that separately actually.

https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

File: static/app/views/performance/transactionSummary/transactionReplays/index.tsx [hunk 3]
```diff
@@ -67,9 +64,12 @@ function ReplaysContentWrapper({
   organization,
   setError,
 }: ChildProps) {
-  const {replays, pageLinks, isFetching, fetchError} = useReplayList({
+  const api = useApi();
```
[the remark this answers is not in the document]
Comment (ryan953) [reply static/app/views/performance/transactionSummary/transactionReplays/index.tsx:67]: there's no reason right now, test mocking could be a good reason, but `useApi` accepts an option for that pupose. i'll tidy it up.

File: static/app/views/performance/transactionSummary/transactionReplays/index.tsx [hunk 4]
```diff
@@ -115,25 +115,14 @@ function generateEventView({
   location: Location;
   transactionName: string;
 }) {
-  const query = decodeScalar(location.query.query, '');
```
[the remark this answers is not in the document]
Comment (ryan953) [reply static/app/views/performance/transactionSummary/transactionReplays/index.tsx:118]: damnit, there is. missed that completely

File: static/app/views/performance/transactionSummary/transactionReplays/content.tsx (hunk 2 above)
Comment (billyvg) [reply static/app/views/performance/transactionSummary/transactionReplays/content.tsx:80]: Ah right -- assuming we had that rule, would adding the default value appease the compiler? Or would we need an explicit length check?

Comment (ryan953) [reply static/app/views/performance/transactionSummary/transactionReplays/content.tsx]: with/without the rule the types are:
```
const a: string[] = [];

// Without rule:
const first = a[0]; // type == string

// With rule:
const first = a[0]; // type == string | undefined
```
