### PR TITLE
fix(user-settings): Generate timezone offset labels dynamically to account for daylight savings

### LINKED ISSUE #50527: Timezone labels in account preferences do not account for daylight savings
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to timezone preferences at `/settings/account/details/#timezone`
2. Look at timezones and see that the offset labels to the right do not account for daylight savings

Note that selecting this timezone still results in the app showing time correctly, just that the labels are off during daylight savings.

### Expected Result

Would expect to see the Los Angeles timezone to show as UTC -7 during daylight savings time.

### Actual Result

image

### Product Area

Settings

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by malwilley**
Fixes https://github.com/getsentry/sentry/issues/50527

Before:

CleanShot 2023-06-07 at 15 03 28

After:

CleanShot 2023-06-07 at 15 02 49

### CODE REVIEW

File: static/app/data/timezones.tsx [hunk 1]
```diff
@@ -482,12 +478,15 @@ const groupedTimezones = Object.entries(groupBy(timezones, ([group]) => group));
...
 const timezoneOptions: SelectValue<string>[] = groupedTimezones.map(([group, zones]) => ({
   label: group,
-  options: zones.map(([_, offsetLabel, value, label]) => ({
-    value,
-    trailingItems: <OffsetLabel>UTC {offsetLabel}</OffsetLabel>,
-    label,
-    textValue: `${group} ${label} ${offsetLabel}`,
-  })),
+  options: zones.map(([_, value, label]) => {
+    const offsetLabel = moment.tz(value).format('Z');
```
Comment (evanpurkhiser) [inline static/app/data/timezones.tsx:482]: should we do this lazily? it's not slow right?

**Review by evanpurkhiser — APPROVED** [review]

File: static/app/data/timezones.tsx (hunk 1 above)
Comment (evanpurkhiser) [reply static/app/data/timezones.tsx:482]: love it
