### PR TITLE
fix(issue-views): Fixes only project in URL case

### LINKED ISSUE #85100: `?project=[PROJECT_SLUG]` does not get applied to the Project filter
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The Dev Toolbar's project can be configured [either with a Project ID or a Project Slug](https://github.com/getsentry/sentry-toolbar/blob/main/src/lib/types/config.ts#L31-L36). When we're using a slug, the toolbar lets us jump to our project's issues and it passes the project's slug, but the platform doesn't pick it up. If we use the project ID instead of the slug it works fine. Example:
- https://sentry-devrel.sentry.io/issues/?project=flashcards < no filter gets applied - all projects are selected
- https://sentry-devrel.sentry.io/issues/?project=4506045517135872 < filter gets applied - only that project's issues are displayed

I'm not sure if this is an issue on the platform, or the dev toolbar, just wanted to raise it.

### Expected Result

The project filter gets applied when using a slug as well

### Actual Result

The project filter isn't applied and all projects are selected

### Product Area

Issues (but might be other areas where the project filter is present)

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by MichaelSun48**
Fixes a bug where having only a project query param in your URL would overwrite the project and just redirect you to your first view. This PR includes some new product logic that is detailed in the diff. 

Fixes #85100 and #85629

### CODE REVIEW

File: static/app/views/issueList/issueViewsHeaderPF.tsx [hunk 1]
```diff
@@ -198,35 +198,6 @@ function IssueViewsIssueListHeaderTabsContent({
...
-            project: projects,
-            environment: environments,
-            ...normalizeDateTimeParams(timeFilters),
-          },
-        }),
-        {replace: true}
-      );
-      tabListState?.setSelectedKey(views[0]!.key);
-      return;
-    }
```
Comment (MichaelSun48) [inline static/app/views/issueList/issueViewsHeaderPF.tsx:229]: Previously, this logic was: 

If a URL comes in with no viewId, query, or sort, then the user navigates to /issues/, and we should bring them to the first tab. This is the path that you would go down if you only had a project in your query params, which is why users just got redirected to their first tab.

File: static/app/views/issueList/issueViewsHeaderPF.tsx [hunk 2]
```diff
@@ -237,6 +208,54 @@ function IssueViewsIssueListHeaderTabsContent({
...
+              environment: environments,
+              ...normalizeDateTimeParams(timeFilters),
+            },
+          }),
+          {replace: true}
+        );
+        tabListState?.setSelectedKey(views[0]!.key);
+        return;
+      }
+    }
```
Comment (MichaelSun48) [inline static/app/views/issueList/issueViewsHeaderPF.tsx:258]: This logic has been updated to now be: 

If no view id in the url, first check if there are project or time filters. If there are, apply the first tab's filters, with the project or time filters. 

If there are no filters in the query, navigate to the first tab as normal. 

One could make a reasonable argument that it would make more sense to navigate to a temporary tab with only the project selected instead, but I think this logic is more in line with what the user would expect.

**Review by malwilley — APPROVED** [review]
Makes sense to me!
