### PR TITLE
fix edge select element bug

### LINKED ISSUE #3999: Unable to add a new rule in Edge 14
https://app.getsentry.com/<>/<>/settings/rules/new/

I see an error rectangle pop up that says "You must choose an item from the list". Tried the same data input in Firefox with no issue.

### PR DESCRIPTION
**Pull request by MaxBittker**
Edge browser doesn't read the state of select tags correctly for form submission,
this workaround makes it work.
https://github.com/facebook/react/issues/7655

fixes #3999

cc @getsentry/team

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/4195)

### CODE REVIEW

**Review by benvinegar — CHANGES_REQUESTED** [review]
Okay, so now we need to have _the talk_.

Stylistically, the Sentry ES6 codebases uses `let` by default, and `const` when something is truly, truly constant. For example, React component declarations, or uppercase `CONSTANT` values.

Until such a time that we decide to convert _everything_ to use `const` by default, I'd prefer that we remained consistent and followed these style guidelines.

**Comment by MaxBittker** [comment]
@benvinegar thanks, that makes sense. switched to let

File: src/sentry/static/sentry/app/components/selectInput.jsx [hunk 1]
```diff
@@ -29,6 +29,17 @@ const SelectInput = React.createClass({
 
   componentDidMount() {
     this.create();
+    /*below is a hack for a bug in edge related to form submitting.
+    see: https://github.com/facebook/react/issues/7655
+    (@maxbittker)*/
+    let selectedIndex = this.refs.select.selectedIndex;
+    if (this.refs.select && selectedIndex >= 0) {
```
Comment (benvinegar) [inline src/sentry/static/sentry/app/components/selectInput.jsx]: Should the check for `this.refs.select` occur earlier? Because you access a property of it (`selectedIndex`) the line before (L35). If `select` is truly falsy, then L35 will blow up because it cannot access property `selectedIndex` of null/undefined/0/etc.

**Review by benvinegar — CHANGES_REQUESTED** [review]

File: src/sentry/static/sentry/app/components/selectInput.jsx (hunk 1 above)
Comment (MaxBittker) [inline src/sentry/static/sentry/app/components/selectInput.jsx]: good catch, updated

File: src/sentry/static/sentry/app/components/selectInput.jsx [hunk 2]
```diff
@@ -32,13 +32,15 @@ const SelectInput = React.createClass({
     /*below is a hack for a bug in edge related to form submitting.
     see: https://github.com/facebook/react/issues/7655
     (@maxbittker)*/
-    let selectedIndex = this.refs.select.selectedIndex;
-    if (this.refs.select && selectedIndex >= 0) {
-     let options = this.refs.select.options;
-     let tempIndex = (selectedIndex + 1) % options.length;
+    if(this.refs.select){
```
Comment (benvinegar) [inline src/sentry/static/sentry/app/components/selectInput.jsx]: Hmm, should be two spaces here:

```javascript
if (this.refs.select) {
```

My bad, this should be enforced via eslint ([keyword-spacing](http://eslint.org/docs/rules/keyword-spacing)).

**Review by benvinegar — CHANGES_REQUESTED** [review]

**Comment by MaxBittker** [comment]
good to merge? @benvinegar

**Review by benvinegar — APPROVED** [review]
