### PR TITLE
fix(ui): Prevent palette hotkeys when any modal is open

### LINKED ISSUE #87340: Disable Sentry hotkeys within Create Issue Modal
### Problem Statement

Filing on behalf of a user on a [zendesk ticket](https://sentry.zendesk.com/agent/tickets/147820)

Hitting ctrl + k in Sentry opens the command palette search bar.  If you open this during the Create Issue modal, it will close the modal and open the palette instead.  The user then loses all work done up to that point in the issue modal.  Reopening the modal creates a new fetch request for a fields in the modal and the user needs to start fresh. 

ctrl + k is a default mac keybinding that deletes text so accidentally hitting ctrl + k is not going to be uncommon

### Solution Brainstorm

Disabling Sentry hotkeys or at least the ones that can close/open other modals can help this poor user experience.

Or maybe we can add a confirmation prompt for when the window is closed?

### Product Area

Issues

### PR DESCRIPTION
**Pull request by leeandher**
Fixes https://github.com/getsentry/sentry/issues/87340

The command palette is itself a modal which means it'd override whatever modal was currently in view, which isn't the best experience, the ticket was specifically talking about issue linking but I think it makes sense to be universal. 

There was also a very good point about `ctrl+k` on mac being a shortcut to delete text, so I removed `includeInputs` but i'm open to other solutions.

### CODE REVIEW

File: static/app/views/app/index.tsx [hunk 1]
```diff
@@ -57,18 +58,23 @@ function App({children, params}: Props) {
...
   const user = useUser();
   const config = useLegacyStore(ConfigStore);
+  const {visible: isModalOpen} = useGlobalModal();
   const preloadData = shouldPreloadData(config);
 
   // Command palette global-shortcut
   const commandPaletteHotkeys = useMemo(() => {
-    return {
-      match: ['command+shift+p', 'command+k', 'ctrl+shift+p', 'ctrl+k'],
-      includeInputs: true,
```
Comment (leeandher) [inline static/app/views/app/index.tsx:66]: I'm not a big command-palette user but this might be pretty annoying to relearn, so the other option was to just move `ctrl+k` out into an entry without `includeInputs`, so all the other commands still work as expected in text inputs. Having one command act differently felt a little weird too though.

**Review by scttcper — APPROVED** [review]
makes sense
