### PR TITLE
fix(replays): Fix a bug where the url origin was printed twice

### LINKED ISSUE #34923: Add test for getCurrentUrl feature
### Problem Statement

Add test for replays/getCurrentUrl() feature

### PR DESCRIPTION
**Pull request by ryan953**
Fix the `getCurrentUrl` helper so that if the SDK captures full urls we don't naively prefix them.

Also, updated the method signature to make mocking in unit tests easier.

Fixes #34923

### CODE REVIEW

File: static/app/utils/replays/getCurrentUrl.tsx [hunk 1]
```diff
@@ -1,22 +1,23 @@
...
-
+function getCurrentUrl(
+  event: EventTransaction,
+  crumbs: Crumb[],
+  currentOffsetMS: number
+) {
   const startTimestampMs = event.startTimestamp * 1000;
   const currentTimeMs = startTimestampMs + Math.floor(currentOffsetMS);
 
-  const navigationCrumbs = transformCrumbs(crumbs).filter(
```
Comment (ryan953) [inline static/app/utils/replays/getCurrentUrl.tsx:19]: This isn't needed anymore because it's already called as part of `replay.getRawCrumbs()`

**Review by billyvg — APPROVED** [review]
