### PR TITLE
fix(replay): fix timeline tooltip following mouse

### LINKED ISSUE #91150: [Replay Details] Timeline tooltip no longer follows mouse
https://github.com/user-attachments/assets/2da86ad6-e3f7-4ca2-ab78-c7b4f7adbb41

seems like a regression -- the tooltip used to follow the mouse when hovering over the timeline: see https://github.com/getsentry/sentry/pull/59436

### PR DESCRIPTION
**Pull request by michellewzhang**
before:

https://github.com/user-attachments/assets/09a65a7c-afe4-4166-907a-22796f9ddd1f

after:

https://github.com/user-attachments/assets/7f359874-0248-4594-a026-84bbe88c9e7d

closes https://github.com/getsentry/sentry/issues/91150

### CODE REVIEW

File: static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx [hunk 1]
```diff
@@ -21,51 +21,45 @@ type Props = {
...
-      // within the containerRect. This proves to be less glitchy as some
-      // elements within the container may trigger an onMouseLeave even when
-      // the mouse is still "inside" of the container
-      const isInsideContainer =
-        e.clientX > containerRect.left &&
-        e.clientX < containerRect.right &&
-        e.clientY > containerRect.top &&
-        e.clientY < containerRect.bottom;
+      const portal = document.getElementById('replay-timeline-player');
+      portalRef.current = portal;
```
Comment (billyvg) [inline static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx:32]: does this get read at all?

File: static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx [hunk 2]
```diff
@@ -21,51 +21,45 @@ type Props = {
...
-      // Instead of using onMouseEnter / onMouseLeave we check if the mouse is
-      // within the containerRect. This proves to be less glitchy as some
-      // elements within the container may trigger an onMouseLeave even when
-      // the mouse is still "inside" of the container
-      const isInsideContainer =
-        e.clientX > containerRect.left &&
-        e.clientX < containerRect.right &&
-        e.clientY > containerRect.top &&
-        e.clientY < containerRect.bottom;
+      const portal = document.getElementById('replay-timeline-player');
```
Comment (billyvg) [inline static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx:31]: this means we'll have to query the DOM on every mousemove, though it's not as bad since it's `getElementById` which should be O(1). Do we need this be called on every mouse move or can we cache in a ref?

File: static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx (hunk 1 above)
Comment (michellewzhang) [reply static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx:32]: nope... that was definitely cursor, not me

File: static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx (hunk 2 above)
Comment (michellewzhang) [reply static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx:30]: hmm, would it be fine to move the `portal` query back outside the `useCallback`, where it was before? or is that the same problem

Comment (michellewzhang) [reply static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx]: added back the `portalRef` actually to help with the caching

File: static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx [hunk 3]
```diff
@@ -21,51 +21,48 @@ type Props = {
...
+  const [position, setPosition] = useState({x: 100, y: FIXED_Y_POSITION});
+  const [isVisible, setIsVisible] = useState(true);
 
-  const [isVisible, setIsVisible] = useState(false);
-  const [offsetLeft, setOffsetLeft] = useState(0);
-
-  const portal = document.getElementById('replay-timeline-player');
+  useEffect(() => {
+    portalRef.current = document.getElementById('replay-timeline-player');
+  }, []);
```
Comment (billyvg) [inline static/app/components/replays/breadcrumbs/replayTimelineTooltip.tsx:31]: Hmm I'd probably try to avoid `useEffect` if possible.

Could we check if `portalRef.current` exists inside of the mouseMove handler, and if not, set it?

**Review by billyvg — APPROVED** [review]
