### PR TITLE
fix(alerts): Correct the total events count in alerts

### LINKED ISSUE #48325: Alerts UI not using metrics
Image

The chart uses metrics, but the `Total Events` number is not.
The `/events` API is not being called with `metricsEnhanced` param.

### PR DESCRIPTION
**Pull request by priscilawebdev**
closes https://github.com/getsentry/sentry/issues/48325

### CODE REVIEW

File: static/app/views/alerts/rules/metric/triggers/chart/index.tsx [hunk 1]
```diff
@@ -207,15 +208,35 @@ class TriggersChart extends PureComponent<Props, State> {
...
+    const queryDataset = queryExtras.dataset as undefined | DiscoverDatasets;
+
     try {
       const totalCount = await fetchTotalCount(api, organization.slug, {
         field: [],
         project: projects.map(({id}) => id),
         query,
         statsPeriod,
         environment: environment ? [environment] : [],
+        dataset: queryDataset,
```
Comment (priscilawebdev) [inline static/app/views/alerts/rules/metric/triggers/chart/index.tsx:239]: `metricsEnhanced` was not being sent when it should

**Review by matejminar — APPROVED** [review]
