### PR TITLE
fix(ui): Improve getFileExtension function

### LINKED ISSUE #24002: Stacktrace icon not showing for `dart`
We've added `dart` to the list:

https://github.com/getsentry/sentry/blob/cff15915141949579e332c15681ed3c79222ba6a/src/sentry/static/sentry/app/utils/fileExtension.tsx#L25

But it's not showing up for Dart:

image

Example stack trace:

```
 "exception": {
    "values": [
      {
        "type": "SocketException",
        "value": "SocketException: Failed to create server socket (OS Error: The shared flag to bind() needs to be `true` if binding multiple times on the same (address, port) combination.), address = 127.0.0.1, port = 31337",
        "stacktrace": {
          "frames": [
            {
              "function": "_RawReceivePortImpl._handleMessage",
              "filename": "isolate_patch.dart",
              "abs_path": "dart:isolate-patch/isolate_patch.dart",
              "lineno": 168,
              "colno": 12,
              "in_app": false
            },

```

[Link to it on sentry.io](https://sentry.io/organizations/bruno-garcia/issues/2229758255/events/b8bfe1d7718840b39fd027c1e509b0ac/?project=1857674&statsPeriod=14d)

### PR DESCRIPTION
**Pull request by matejminar**
Closes https://github.com/getsentry/sentry/issues/24002

### CODE REVIEW

File: src/sentry/static/sentry/app/utils/fileExtension.tsx [hunk 1]
```diff
@@ -33,7 +33,11 @@ const FILE_EXTENSION_TO_PLATFORM = {
  */
 export function getFileExtension(fileName: string): string | undefined {
   // this won't work for something like .spec.jsx
-  return fileName.split('.').pop();
+  const segments = fileName.split('.');
```
Comment (dashed) [inline src/sentry/static/sentry/app/utils/fileExtension.tsx:36]: Which filename wasn't working for dart?

Comment (matejminar) [reply src/sentry/static/sentry/app/utils/fileExtension.tsx:36]: This is handling the edge-case where there is no file extension at all.

**Review by dashed — APPROVED** [review]

**Review by bruno-garcia — APPROVED** [review]
Nice! thanks

**Review by priscilawebdev — APPROVED** [review]
