### PR TITLE
fix(replays): Make sure `?cursor` appears in the url after we splat vars, not `?limit`

### LINKED ISSUE #37931: Bug: Pagination seems broken, the links don't light up
Ideally this will solve it: https://github.com/getsentry/replay-backend/issues/84

EDIT:
`jferg/fix-pagination-replays-index` is a branch that should have the `Links` response header.

With that branch we can instead remove `getPageLinks()` from `useReplayList.tsx` and pass along the `Links` header into `pageLinks`.

We've got more than 10 replays captured, these button should be active at the bottom of the list page:
Screen Shot 2022-08-17 at 11 30 52 AM

---

Previous Content: 

~~But we can't wait for that, need to fixup the shim that's in there now. See `getPageLinks()` inside `useReplayList.tsx`.~~

### PR DESCRIPTION
**Pull request by ryan953**
Follows #37960

Fixes https://github.com/getsentry/sentry/issues/37931

### CODE REVIEW

File: static/app/views/replays/replays.tsx [hunk 1]
```diff
@@ -107,10 +107,10 @@ function Replays({location}: Props) {
           />
           <Pagination
             pageLinks={pageLinks}
-            onCursor={(offset, path, searchQuery) => {
+            onCursor={(cursor, path, searchQuery) => {
               browserHistory.push({
                 pathname: path,
-                query: {...searchQuery, offset},
```
Comment (ryan953) [inline static/app/views/replays/replays.tsx:113]: This is the important rename. 
`{offset}` is the same as `{offset: offset}` which gets turned into `?offset=123` in the query string.
Should all be called cursor.

**Review by JoshFerge — APPROVED** [review]
