### PR TITLE
fix(replays): Issues Replay List Double Load

### LINKED ISSUE #38568: Bug: Clicking into Replays tab from Issue Details results in a double load
See https://sentry.io/organizations/sentry-emerging-tech/replays/billy-test:e51d028949274518879bf3cb9b072689/?referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&t=11 for a replay 😎

### PR DESCRIPTION
**Pull request by danecando**
### Changes
- Adds a ref to track the url search and only execute query on changes

### Notes
The queries track location which changes after the page loads which is causing the query to fire multiple times. 

Closes #38568 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/utils/replays/hooks/useReplayList.tsx [hunk 1]
```diff
@@ -27,24 +27,15 @@ function useReplayList({eventView, organization}: Options): Result {
     replays: [],
   });
 
-  const init = useCallback(async () => {
-    setData(prev => ({
-      ...prev,
-      isFetching: true,
-    }));
```
Comment (billyvg) [inline static/app/utils/replays/hooks/useReplayList.tsx:34]: Doesn't this mean that we will never get a loading state again after the first load?

File: static/app/utils/replays/hooks/useReplayList.tsx [hunk 2]
```diff
@@ -42,8 +43,11 @@ function useReplayList({eventView, organization}: Options): Result {
   }, [api, organization, location, eventView]);
 
   useEffect(() => {
-    init();
-  }, [init]);
+    if (!querySearchRef.current || querySearchRef.current !== location.search) {
+      querySearchRef.current = location.search;
+      handleFetch();
+    }
+  }, [handleFetch, location.search]);
```
Comment (ryan953) [inline static/app/utils/replays/hooks/useReplayList.tsx:50]: i think there's a `usePrevious` which could be doing about the same thing

```
lastSearch = usePrevious(location.search)

if (lastSearch !== location.search) { ...
```

File: static/app/utils/replays/hooks/useReplayList.tsx [hunk 3]
```diff
@@ -27,7 +28,7 @@ function useReplayList({eventView, organization}: Options): Result {
     replays: [],
   });
 
-  const init = useCallback(async () => {
+  const handleFetch = useCallback(async () => {
```
Comment (ryan953) [inline static/app/utils/replays/hooks/useReplayList.tsx:31]: handle sounds like it's in response to something, but this method is being commanded to execute the fetch.

maybe like `loadReplays` or idk

File: static/app/utils/replays/hooks/useReplayList.tsx (hunk 2 above)
Comment (danecando) [reply static/app/utils/replays/hooks/useReplayList.tsx]: I didn't use usePrevious here because it gets initialized to the first value right away, so it won't actually run because the search string doesn't change. The location.key and action type are what change causing the effects to re-fire. This way it runs initially and then only on actual changes to the query aftewards

**Review by ryan953 — APPROVED** [review]

File: static/app/utils/replays/hooks/useReplayList.tsx (hunk 2 above)
Comment (ryan953) [reply static/app/utils/replays/hooks/useReplayList.tsx]: ahh, cool 👍
