### PR TITLE
fix(replays): Memory Chart Tooltip Overflow

### LINKED ISSUE #37238: Memory Tab tooltip gets hidden at the boundaries of the scrollable area
Not sure how to fix this, we might need to build our own tooltips so they attach to a dom node that's outside of the scrollable area. (maybe there is a config for this in the graph library?)

Image

### PR DESCRIPTION
**Pull request by danecando**
### Changes
- Configures the tooltip to be portalled out of the container
- Injects global styles that target the portalled tooltip
- tooltip accepts a new `chartId` prop to allow the tooltips to calculate position within a chart when portalled with `appendToBody`

### Notes
Portalling the tooltips broke the styles since they were scoped to the chart container. I needed to duplicate and inject those styles in the scope of the portalled tooltip. I'm not an emotion expert so if you know a better way to accomplish that let me know

Closes #37238 

Screen Shot 2022-09-13 at 12 21 52 PM

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/views/replays/detail/memoryChart.tsx [hunk 1]
```diff
@@ -294,8 +297,71 @@ function MemoryChartContainer({
   }, [currentHoverTime, startTimestampMs, theme]);
 
   return (
-    <MemoizedMemoryChart ref={chart} startTimestampMs={startTimestampMs} {...props} />
+    <Fragment>
+      <Global styles={getChartTooltipStyles(theme)} />
```
Comment (ryan953) [inline static/app/views/replays/detail/memoryChart.tsx:301]: would it be beneficial if the charting library did this itself?
Then when someone else uses `appendToBody: true` it a) just works b) reduces copy+pasted global styles

File: static/app/views/replays/detail/memoryChart.tsx [hunk 2]
```diff
@@ -56,7 +56,9 @@ function MemoryChart({
       right: space(1),
     }),
     tooltip: Tooltip({
+      appendToBody: true,
       trigger: 'axis',
+      renderMode: 'html',
```
Comment (ryan953) [inline static/app/views/replays/detail/memoryChart.tsx:61]: what does this do?

File: static/app/components/charts/baseChart.tsx [hunk 3]
```diff
@@ -662,6 +668,95 @@ const ChartContainer = styled('div')<{autoHeightResize: boolean}>`
   }
 `;
 
+// Global styles to inject with the chart. (for portalled tooltips)
+const getPortalledTooltipStyles = (
+  theme: Theme
+): Record<string, Record<string, string | number>> => ({
+  '.chart-tooltip-portal .tooltip-series, .chart-tooltip-portal .tooltip-date': {
```
Comment (ryan953) [inline static/app/components/charts/baseChart.tsx:675]: can you link me to the file where the css came from?

**Review by ryan953 — APPROVED** [review]

**Comment by ryan953** [comment]
I was poking at this for about 2mins and thought it was going to be annoying. I'm happy this is such a tidy looking solution!

File: static/app/components/charts/baseChart.tsx (hunk 3 above)
Comment (danecando) [reply static/app/components/charts/baseChart.tsx:675]: https://github.com/getsentry/sentry/blob/30663eec9a49d7f1757d41b79d9e29761983c3d1/static/app/components/charts/baseChart.tsx#L570-L669

File: static/app/views/replays/detail/memoryChart.tsx (hunk 2 above)
Comment (danecando) [reply static/app/views/replays/detail/memoryChart.tsx:61]: From the type def for the tooltips says the renderMode should be html if using appendToBody

```
    /**
     * 'auto': use html by default, and use non-html if `document` is not defined
     * 'html': use html for tooltip
     * 'richText': use canvas, svg, and etc. for tooltip
     */
    renderMode?: 'auto' | TooltipRenderMode;
    /**
     * If append popup dom to document.body
     * Only available when renderMode is html
     */
    appendToBody?: boolean;
    /**
     * specified class name of tooltip dom
     * Only available when renderMode is html
     */
    className?: string;
    ```

File: static/app/components/charts/baseChart.tsx (hunk 3 above)
Comment (ryan953) [reply static/app/components/charts/baseChart.tsx:675]: I wonder if something like this would work:

```typescript
import {css} from '@emotion/react';
import styled from '@emotion/styled';

const TooltipStyles = css`... copy+paste it all ...`;

const ChartContainer = styled('div')`
  ${TooltipStyles}
`;

const portalledTooltipStyles = css`
  .chart-tooltip-portal ${TooltipStyles};
`;
```
🤞  the portalled styles do the right thing with nested classnames

Comment (danecando) [reply static/app/components/charts/baseChart.tsx:675]: It seems to work but TS is not happy and it looks like because of the use of `${p => p.theme... }` inside the css string

Is that allowed? I didn't see an examples of that being done in the docs with css
Screen Shot 2022-09-13 at 2 27 15 PM

Comment (danecando) [reply static/app/components/charts/baseChart.tsx]: I just pushed an updated commit I think I got it right based on looking at other uses of css`` in the codebase

Comment (ryan953) [reply static/app/components/charts/baseChart.tsx]: tbh i don't know any of the ins-and-outs of emotion. I was kind of guessing at what the api might be able to do 😨 

but it's working and i think it's better not to have to copy+paste all those css rules.

**Comment by ryan953** [comment]
the tooltip does go off the edge of the page now:
Screen Shot 2022-09-13 at 12 46 43 PM


before there were some checks that kept it within the window bounds and moved the nub to accomodate:

Screen Shot 2022-09-13 at 12 47 39 PM

**Comment by danecando** [comment]
Added a new option `chartId` to the tooltip so that it can get a reference to the chart node when using `appendToBody`  for calculating relative tooltip positions.
Screen Shot 2022-09-14 at 2 46 08 PM

**Comment by ryan953** [comment]
@danecando update the description to match the code please
