### PR TITLE
fix assigneeSelector selection when filtering

### LINKED ISSUE #2785: Can't click assignee when filtering
assignee

No JavaScript errors, but after filtering your selection, you can't actually choose anyone.

### PR DESCRIPTION
**Pull request by macqueen**
@getsentry/ui 

fixes #2785

### CODE REVIEW

**Comment by mattrobenolt** [comment]
🍰 🍪 🍨 🎉 🎅 ⛄

File: src/sentry/static/sentry/app/components/dropdownLink.jsx [hunk 1]
```diff
@@ -37,10 +37,15 @@ const DropdownLink = React.createClass({
...
-        this.props.onClose && this.props.onClose(e);
+        setTimeout(() => {
+          if (!this.isMounted()) {
+            return;
+          }
+          this.setState({
+            isOpen: false,
+          });
+          this.props.onClose && this.props.onClose(e);
+        }, 0);
```
Comment (benvinegar) [inline src/sentry/static/sentry/app/components/dropdownLink.jsx]: You can omit `0`:

> delay is the number of milliseconds (thousandths of a second) that the function call should be delayed by. If omitted, it defaults to 0.

https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout
