### PR TITLE
fix(2fa): Handle sms authenticator unavailable in recovery options

### LINKED ISSUE #9573: Sentry 9.0.0: Frontend errors when adding U2F
Sentry version: 9.0.0
Installation method: official docker images

Issue has been noticed after updating to 9.0.0.
After enabling 2FA on account, an empty popup dialog opens.

There's following issue in the JS console:

```
TypeError: Cannot read property 'id' of undefined
    at t.value (recoveryOptionsModal.jsx:86)
    at t.value (asyncComponent.jsx:228)
    at t.value (asyncComponent.jsx:232)
    at t.render (asyncComponent.jsx:239)
    at f (react-dom.production.min.js:131)
    at beginWork (react-dom.production.min.js:138)
    at i (react-dom.production.min.js:176)
    at a (react-dom.production.min.js:176)
    at y (react-dom.production.min.js:182)
    at g (react-dom.production.min.js:181)
    at m (react-dom.production.min.js:181)
    at h (react-dom.production.min.js:180)
    at u (react-dom.production.min.js:179)
    at Object.enqueueSetState (react-dom.production.min.js:110)
    at t.o.setState (react.production.min.js:12)
    at t.i.handleRequestSuccess (asyncComponent.jsx:128)
    at e.success (asyncComponent.jsx:113)
    at Object.success (api.jsx:62)
    at u (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at n (jquery.js:8264)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)
    at XMLHttpRequest.r (raven.js:374)
```
What I believe to be a problem here is this line:
https://github.com/getsentry/sentry/blob/9.0.0/src/sentry/static/sentry/app/components/modals/recoveryOptionsModal.jsx#L77

In this context, ```sms``` variable is null (```authenticators``` object doesn't have sms entry), because of that ```smsEnrolled``` is set to ```false``` (L44), ```skipSms``` is also set to false so the condition in L77 is true. However, the code does reference ```sms.id``` in L86.

### PR DESCRIPTION
**Pull request by maheskett**
Relevant for on-prem customers without twilio setup. Fixes #9573

### CODE REVIEW

File: src/sentry/static/sentry/app/components/modals/recoveryOptionsModal.jsx [hunk 1]
```diff
@@ -58,7 +56,7 @@ class RecoveryOptionsModal extends AsyncComponent {
             {t('You should now set up recovery options to secure your account.')}
           </TextBlock>
 
-          {!skipSms && !smsEnrolled ? (
+          {sms && !sms.isEnrolled && !skipSms ? (
```
Comment (markstory) [inline src/sentry/static/sentry/app/components/modals/recoveryOptionsModal.jsx]: You repeat this condition in a few places you could hoist it into another variable.

```js
let displaySmsPrompt = sms && !sms.isEnrolled && !skipSms
```

**Review by markstory — APPROVED** [review]
Looks good. The additional `sms` check will prevent ReferenceError.
