### PR TITLE
fix(stacktrace): Render native stack trace component when all frames are native

### LINKED ISSUE #61572: Mixed platform events sometimes render the wrong stack trace component
For platforms like React Native, the event platform may differ from the stack trace frame platform.

When the event has a non-native platform, but the frames do, we render a native stack trace frame inside the non-native stack trace component. The result is a stack trace that looks strange and inconsistent. We should use the native stack trace component for cases such as this.

[Internal link to a React Native issue](https://sentry-sdks.sentry.io/issues/4589159265)

Screenshot of the stack trace:

Image

### PR DESCRIPTION
**Pull request by malwilley**
Fixes https://github.com/getsentry/sentry/issues/61572

See https://sentry-sdks.sentry.io/issues/4589159265

I thought that this code path wasn't being hit, but it turns out that it does when the event platform is non-native and the stack trace has frames that are native. I've deleted the native code paths in the non-native stack trace and check earlier whether or not we should render it.

Before:

CleanShot 2023-12-11 at 15 50 50

After:

CleanShot 2023-12-11 at 15 50 58

### CODE REVIEW

File: static/app/components/events/interfaces/crashContent/exception/stackTrace.tsx [hunk 1]
```diff
@@ -30,6 +32,17 @@ type Props = {
   threadId?: number;
 };
 
+// Render native stacktrace when:
+// 1. All frames have a native platform override in `frame.platform`, or
+// 2. The event platform is native
+function shouldRenderNativeContent({data, platform}: Pick<Props, 'data' | 'platform'>) {
+  const framePlatforms = uniq(data?.frames?.map(frame => frame.platform) ?? []);
```
Comment (anonrig) [inline static/app/components/events/interfaces/crashContent/exception/stackTrace.tsx:39]: Can you put this in a Set? We don't need lodash for uniqueness check.

Comment (malwilley) [reply static/app/components/events/interfaces/crashContent/exception/stackTrace.tsx]: Can do! I see now that you're cutting down on lodash usage in another PR which seems good.

**Review by NisanthanNanthakumar — APPROVED** [review]

**Review by anonrig — APPROVED** [review]
