### PR TITLE
fix(onboarding) conditionally show minimum version for profiling notice for all python packages

### LINKED ISSUE #76804: [Django] minimum profiling version notice shouldn't be there
https://sentry.rewatch.com/video/k2caoj8sv0v077uj-django-onboarding-walkthrough?t=236

Image

### PR DESCRIPTION
**Pull request by vgrozdanic**
Conditionally show information about minimal version of SDK needed for profiling at the beginning of the onboarding. information should be shown only if the user has opened onboarding docs inside a profile page, while it should be hidden on issues page.

We are showing that info to the user before they could even realise what is profiling, and since they have just installed the latest version, there is no need to mention info about minimum version at this place.

Example how it used to look for one of the python's framworks:
image

Closes https://github.com/getsentry/sentry/issues/76804

### CODE REVIEW

**Comment by ArthurKnaus** [comment]
The onboarding is re-used for the profiling onboarding sidebar, where it makes sense to show the SDK requirements.

**Comment by vgrozdanic** [comment]
@ArthurKnaus this is now fixed, the profiling version text is shown conditionally only on the Profiling page

File: static/app/components/onboarding/gettingStartedDoc/types.ts [hunk 1]
```diff
@@ -54,6 +59,10 @@ export interface DocsParams<
     screenshot?: boolean;
   };
   newOrg?: boolean;
+  /**
+   * The page where the docs are being displayed
+   */
+  page?: DocsPageLocation;
```
Comment (ArthurKnaus) [inline static/app/components/onboarding/gettingStartedDoc/types.ts:65]: hmm, would choose something more generic than `page`. As e.g. a sidebar may be opened on different pages.
Maybe `docsLocation`?

File: static/app/components/onboarding/gettingStartedDoc/types.ts [hunk 2]
```diff
@@ -34,6 +34,11 @@ export type SelectedPlatformOptions<
   [key in keyof PlatformOptions]: PlatformOptions[key]['items'][number]['value'];
 };
 
+export enum DocsPageLocation {
+  ISSUES_PAGE = 0,
+  PROFILING_PAGE = 1,
+}
```
Comment (ArthurKnaus) [inline static/app/components/onboarding/gettingStartedDoc/types.ts:40]: Why only issues and profiling?
For now I would restrict it to `PROFILING_SIDEBAR` and add new ones if needed.

**Review by ArthurKnaus — APPROVED** [review]
lgtm 👍 
In the future we should find a different mechanism for it that only shows this notice if we detect an older SDK is in use for the project.

File: static/app/components/onboarding/gettingStartedDoc/types.ts (hunk 2 above)
Comment (vgrozdanic) [reply static/app/components/onboarding/gettingStartedDoc/types.ts:40]: Those are the only 2 pages where it is being used, if it will be added to some other page, this could easily be extended.

I didn't want to make it an optional parameter, since this way is more explicit how it is being used
