### PR TITLE
fix(feedback): crash report issue links to correct event with user report

### LINKED ISSUE #60872: New User Feedback interface does not link to the exact event the feedback originates from
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Enable the new user feeback interface from Organization Settings > General Settings > Early Adopter
2. Set up a basic JS application with the corresponding Sentry SDK that collects user feedback through the [Embeddable JavaScript Widget](https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/user-feedback/#embeddable-javascript-widget)
3. Run the app and trigger a test error and send user feedback through the pop-up window
4. Head to the User Feedback tab in the Sentry Web UI
5. Click on the issue name that shows up in [the user feedback](https://dragonfruit-dev.sentry.io/feedback/?feedbackSlug=javascript-react%3A4684745097&referrer=feedback_list_page&statsPeriod=90d) that we just submitted

### Expected Result

We are redirected to the exact event inside the issue that the feedback originates from.

### Actual Result

We are redirected to [the latest event](https://dragonfruit-dev.sentry.io/issues/4680186801/?referrer=event-or-group-header&statsPeriod=90d) of the associated issue.

However, if we return to [the old User Feedback](https://dragonfruit-dev.sentry.io/user-feedback/?feedbackSlug=javascript-react%3A4684745097&referrer=feedback_list_page&statsPeriod=90d) interface and click on the associated issue, we are redirected to [the exact event](https://dragonfruit-dev.sentry.io/issues/4680186801/events/e6a145dee9b74d23afae6e222abd77b7/?project=4504179109068800&referrer=compact-issue) within the issue that the feedback originated from.

Screenshot 2023-11-30 at 15 57 44

### Product Area

User Feedback

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by michellewzhang**
Before, we weren't linking to the correct event instance for the crash report issue. 

I'm modifying the linked issue component to manually pass in the crash report event ID, which forces the link to the correct event with the user report associated.

https://github.com/getsentry/sentry/assets/56095982/2165d127-7007-4b92-a10b-750839d1fa14

Fixes https://github.com/getsentry/sentry/issues/60872

### CODE REVIEW

File: static/app/components/eventOrGroupHeader.tsx [hunk 1]
```diff
@@ -103,13 +105,16 @@ function EventOrGroupHeader({
...
+    // If we have passed in a custom event ID, use it; otherwise use default
+    const finalEventId = eventId ?? eventID;
+
     return (
       <TitleWithLink
         {...commonEleProps}
         to={{
           pathname: `/organizations/${organization.slug}/issues/${
             eventID ? groupID : id
-          }/${eventID ? `events/${eventID}/` : ''}`,
```
Comment (ryan953) [inline static/app/components/eventOrGroupHeader.tsx:112]: before, were we generating links with all the parts included, like  `/issues/{$groupID}/event/${eventID}/`?

or were the links only the first bit like `/issues/${id}/`?

Comment (michellewzhang) [reply static/app/components/eventOrGroupHeader.tsx:112]: the link didn't include `/event/${eventID}/`; it wasn't getting the `eventID` at all in our situation

Comment (michellewzhang) [reply static/app/components/eventOrGroupHeader.tsx:112]: something with casting the issue as en `Event` was going wrong

Comment (ryan953) [reply static/app/components/eventOrGroupHeader.tsx:112]: it seems like before, if we passed a `Group` in, then the extra `/event/xyz/` part of the url would not appear here. 

We should be careful not to break other callsites. However the logic for what's rendered is unnecessarily complex imo

Comment (ryan953) [reply static/app/components/eventOrGroupHeader.tsx:112]: kk, cool. as long as that `finalEventId` ternary check is still there i think it's good.

**Review by ryan953 — APPROVED** [review]
