### PR TITLE
fix(settings): Redirect to settings project list after proj deletion

### LINKED ISSUE #91785: [Project Settings] Redirect After Clicking Remove Project
### Problem Statement

After removing a project the user is redirected to the issue stream. This is an annoyance if the user is deleting more than one project via the UI.

### Solution Brainstorm

Redirect user to the projects list instead

### Product Area

Settings - Projects

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Fixes https://github.com/getsentry/sentry/issues/91785
Fixes [RTC-964: \[Project Settings\] Redirect After Clicking Remove Project](https://linear.app/getsentry/issue/RTC-964/project-settings-redirect-after-clicking-remove-project)

Requires https://github.com/getsentry/sentry/pull/92851

### CODE REVIEW

**Review by malwilley — APPROVED** [review]

File: static/app/views/settings/projectGeneralSettings/index.tsx [hunk 1]
```diff
@@ -82,37 +82,27 @@ function ProjectGeneralSettings({onChangeSlug}: Props) {
...
-          );
-        },
-        err => {
-          addErrorMessage(tct('Error removing [project]', {project: project.slug}));
-          throw err;
-        }
-      )
-      .then(
-        () => {
-          // Need to hard reload because lots of components do not listen to Projects Store
```
Comment (evanpurkhiser) [inline static/app/views/settings/projectGeneralSettings/index.tsx:111]: This is an old assumption. We can do better now
