### PR TITLE
ref(groupingInfo): Move contributing values/all values switch to section header

### LINKED ISSUE #97590: [grouping info] Move contributing values/all values switch to section header
Right now, the contributing values/all values toggle exists separately for each variant. This should move to the section header for two reasons:

- There's no reason we need to control it separately for each variant, and so it's a little redundant to have it twice in cases where we have both an in-app and full stacktrace.
- If we're going to have it control the showing and hiding of entire variants (as when the message variant doesn't contribute because we have stacktraces), then it needs to be outside of any single variant.

### PR DESCRIPTION
**Pull request by shayna-ch**
For issue #97590.

Moves contributing values/all values toggle to section header because having it for each variant is redundant. 

image

### CODE REVIEW

File: static/app/components/events/groupingInfo/groupingInfo.tsx [hunk 1]
```diff
@@ -81,12 +84,29 @@ export default function GroupingInfo({
...
       </ConfigHeader>
+      <div style={{display: 'flex', justifyContent: 'flex-end', width: '100%'}}>
+        <SegmentedControl
+          aria-label={t('Filter by contribution')}
+          size="xs"
+          value={showNonContributing ? 'all' : 'relevant'}
+          onChange={key => setShowNonContributing(key === 'all')}
+        >
+          <SegmentedControl.Item key="relevant">
+            {t('Contributing values')}
```
Comment (roggenkemper) [inline static/app/components/events/groupingInfo/groupingInfo.tsx]: It looks like in most other places in the app we would capitalize "Values"

File: static/app/components/events/groupingInfo/groupingInfo.tsx [hunk 2]
```diff
@@ -81,12 +84,29 @@ export default function GroupingInfo({
           </div>
         )}
       </ConfigHeader>
+      <div style={{display: 'flex', justifyContent: 'flex-end', width: '100%'}}>
```
Comment (roggenkemper) [inline static/app/components/events/groupingInfo/groupingInfo.tsx]: might need a real designer's opinion on this but i feel like this should either be more aligned with the groupedby/grouping info section (not on it's own line) or left aligned. right aligned and on its own seems a little odd

File: static/app/components/events/groupingInfo/groupingInfo.tsx [hunk 3]
```diff
@@ -81,12 +84,29 @@ export default function GroupingInfo({
           </div>
```
Comment (roggenkemper) [inline static/app/components/events/groupingInfo/groupingInfo.tsx:84]: unrelated to this PR specifically but when you open the fold section for the first time the feedback button loads outside the fold section
Screenshot 2025-08-12 at 3 06 59 PM

File: static/app/components/events/groupingInfo/groupingInfo.tsx (hunk 2 above)
Comment (roggenkemper) [reply static/app/components/events/groupingInfo/groupingInfo.tsx]: this also seems like a good place to either use a styled component or `Flex`

File: static/app/components/events/groupingInfo/groupingInfo.tsx [hunk 4]
```diff
@@ -81,12 +84,36 @@ export default function GroupingInfo({
...
+          justifyContent: 'flex-start',
+          width: '100%',
+          paddingBottom: '20px',
+        }}
+      >
+        <SegmentedControl
+          aria-label={t('Filter by contribution')}
+          size="xs"
+          value={showNonContributing ? 'all' : 'relevant'}
+          onChange={key => setShowNonContributing(key === 'all')}
```
Comment (roggenkemper) [inline static/app/components/events/groupingInfo/groupingInfo.tsx:92]: is it worth tracking analytics on how often people are using this?

File: static/app/components/events/groupingInfo/groupingInfo.tsx [hunk 5]
```diff
@@ -81,12 +84,36 @@ export default function GroupingInfo({
           </div>
         )}
       </ConfigHeader>
+      <div
+        style={{
+          display: 'flex',
+          justifyContent: 'flex-start',
+          width: '100%',
+          paddingBottom: '20px',
```
Comment (roggenkemper) [inline static/app/components/events/groupingInfo/groupingInfo.tsx]: let's try to use `p.theme.space.X` instead of hardcoding values here

File: static/app/components/events/groupingInfo/groupingInfo.tsx (hunk 4 above)
Comment (shayna-ch) [reply static/app/components/events/groupingInfo/groupingInfo.tsx:92]: @lobsterkatie thoughts on this?

Comment (shayna-ch) [reply static/app/components/events/groupingInfo/groupingInfo.tsx:92]: After talking with Katie we decided its probably not worth it to track this right now.

File: static/app/components/events/groupingInfo/groupingInfo.tsx [hunk 6]
```diff
@@ -99,7 +127,12 @@ const ConfigHeader = styled('div')`
   display: flex;
   justify-content: space-between;
   gap: ${space(1)};
```
Comment (roggenkemper) [inline static/app/components/events/groupingInfo/groupingInfo.tsx]: definitely not required but while you're in this file - might be worth replacing all the usages of `space` with `theme.space`

**Review by roggenkemper — APPROVED** [review]

File: static/app/components/events/groupingInfo/groupingInfo.tsx (hunk 3 above)
Comment (shayna-ch) [reply static/app/components/events/groupingInfo/groupingInfo.tsx:84]: Probably because of #96908, will follow up

File: static/app/components/events/groupingInfo/groupingInfo.tsx [hunk 7]
```diff
@@ -81,12 +84,29 @@ export default function GroupingInfo({
...
+          size="xs"
+          value={showNonContributing ? 'all' : 'relevant'}
+          onChange={key => setShowNonContributing(key === 'all')}
+        >
+          <SegmentedControl.Item key="relevant">
+            {t('Contributing Values')}
+          </SegmentedControl.Item>
+          <SegmentedControl.Item key="all">{t('All Values')}</SegmentedControl.Item>
+        </SegmentedControl>
+      </ToggleContainer>
```
[the remark this answers is not in the document]
Comment (shayna-ch) [reply static/app/components/events/groupingInfo/groupingInfo.tsx:99]: We decided to keep this always visible for now, as it is unlikely that there will be no non-contributing components. May follow up with a PR in the future though.
