### PR TITLE
fix(replays): Remove user focus and blur crumbs from timeline and breadcrumbs tab

### LINKED ISSUE #38591: Remove "User Blur/User Focus" from breadcrumbs and timeline
This has been confusing for users, let's remove them from the UI.

Don't render them in the Breadcrumbs list, and not in the Timeline

Image
Image

### PR DESCRIPTION
**Pull request by jesus4497**
### Changes
- Added new filter condition to avoid crumbs with the categories `ui.blur` and `ui.focus`. Closes #38591 

Before:
image

After: 
image

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by billyvg — APPROVED** [review]

File: static/app/utils/replays/replayDataUtils.tsx [hunk 1]
```diff
@@ -119,13 +121,23 @@ export function breadcrumbFactory(
...
+    acc.push({
       ...crumb,
       type: BreadcrumbType.DEFAULT,
-      timestamp: new Date(timestamp * 1000).toISOString(),
-    })) as RawCrumb[]),
+      timestamp: new Date(crumb.timestamp * 1000).toISOString(),
+    });
+
+    return acc;
+  }, [] as RawCrumb[]);
```
Comment (billyvg) [inline static/app/utils/replays/replayDataUtils.tsx:136]: I would use a `.filter().map()` instead of a `reduce()` here

**Review by billyvg — APPROVED** [review]
