### PR TITLE
fix(accept-org-invite): Add frontend check for shouldPreloadData

### LINKED ISSUE #85046: Investigate why routes such as 'accept org invite' are not working with yarn dev-ui
This is the [thread](https://sentry.slack.com/archives/C8V02RHC7/p1738870330912989) (sorry internal only)

### PR DESCRIPTION
**Pull request by priscilawebdev**
This PR adds a frontend check to skip data preloading when the user is on the invitation acceptance page. This works alongside the backend validation, which can be found [here](https://github.com/getsentry/sentry/blob/cac47187ae98f105b39edf80a0fd3105c95e1cb5/src/sentry/web/client_config.py#L402-L414).

The check is needed because when using `yarn dev-ui`, the app is a Single Page Application (SPA), so routing happens client-side without a full page reload.

- closes https://github.com/getsentry/sentry/issues/85046

### CODE REVIEW

File: static/app/bootstrap/index.tsx [hunk 1]
```diff
@@ -75,7 +76,7 @@ async function promiseRequest(url: string) {
 }
 
 function preloadOrganizationData(config: Config) {
-  if (!config.shouldPreloadData) {
+  if (!config.shouldPreloadData || EXPERIMENTAL_SPA) {
```
Comment (scttcper) [inline static/app/bootstrap/index.tsx:79]: this function only runs for EXPERIMENTAL_SPA so in essence you've just turned this feature off

Comment (priscilawebdev) [reply static/app/bootstrap/index.tsx]: you're right, @scttcper! That’s why I was running into errors after accepting the invite and landing on the org page. I’ve updated the code to use regex to check for invite routes using pure javascript + window. I’ve just tested everything, and it’s all working smoothly now.

File: static/app/utils/shouldPreloadData.tsx [hunk 2]
```diff
@@ -0,0 +1,56 @@
+import type {Config} from 'sentry/types/system';
+
+function getPathParams(path: string):
```
Comment (malwilley) [inline static/app/utils/shouldPreloadData.tsx:3]: Do we need all this logic? Couldn't we just check if the pathname starts with `/accept/` and in that case set shouldPreload to false?

File: static/app/utils/shouldPreloadData.tsx [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+    };
+  }
+
+  return undefined;
+}
+
+// Skips data preload if the user is on an invitation acceptance page as they might not have access to the data yet, leading to a 403 error.
+// This frontend check is needed along with the backend check (see: https://github.com/getsentry/sentry/blob/cac47187ae98f105b39edf80a0fd3105c95e1cb5/src/sentry/web/client_config.py#L402-L414).
+// It's necessary because when using `yarn dev-ui`, the app is Single Page Application (SPA), and routing happens client-side without a full page reload.
+export function shouldPreloadData(config: Config): boolean {
```
[the remark this answers is not in the document]
Comment (priscilawebdev) [reply static/app/utils/shouldPreloadData.tsx:40]: Yes, since I'm using this logic not only in the "bootstrap/index" file but also wherever we check for "shouldPreloadData," we can remove the backend logic. I think that having everything in one single place makes things more clear.

File: static/app/utils/shouldPreloadData.tsx (hunk 2 above)
Comment (priscilawebdev) [reply static/app/utils/shouldPreloadData.tsx:3]: We could, but typically we perform a full pathname check, and I thought it was best to stick with that. However, on second thought, I believe it won’t cause any issues. Let me simplify it 🙂

**Review by markstory — APPROVED** [review]

File: static/app/utils/shouldPreloadData.tsx [hunk 4]
```diff
@@ -1,56 +1,11 @@
...
-    };
-  }
-
-  return undefined;
-}
-
 // Skips data preload if the user is on an invitation acceptance page as they might not have access to the data yet, leading to a 403 error.
-// This frontend check is needed along with the backend check (see: https://github.com/getsentry/sentry/blob/cac47187ae98f105b39edf80a0fd3105c95e1cb5/src/sentry/web/client_config.py#L402-L414).
-// It's necessary because when using `yarn dev-ui`, the app is Single Page Application (SPA), and routing happens client-side without a full page reload.
+// This frontend check is needed because when using `yarn dev-ui`, the app is Single Page Application (SPA), and routing happens client-side without a full page reload.
```
Comment (malwilley) [inline static/app/utils/shouldPreloadData.tsx:4]: small nit, but this comment doesn't really make sense anymore if the backend check doesn't exist. It's more that we need to skip for `/accept/*` because the user doesn't need org data for that route

**Review by malwilley — APPROVED** [review]

File: static/app/utils/shouldPreloadData.tsx [hunk 5]
```diff
@@ -0,0 +1,11 @@
+import type {Config} from 'sentry/types/system';
+
+// Skips data preload if the user is on an invitation acceptance page as they might not have access to the data yet, leading to a 403 error.
+// This frontend check is needed because when using `yarn dev-ui`, the app is Single Page Application (SPA), and routing happens client-side without a full page reload.
```
Comment (priscilawebdev) [inline static/app/utils/shouldPreloadData.tsx:4]:
```suggestion
```
