### PR TITLE
fix(replays): Remove empty DOM code snippets and truncate large ones

### LINKED ISSUE #37469: DOM Event component shouldn't render html snippets when someone clicks on 'body' or other nodes with too much content. (dont render megabytes of html snippets)
If someone clicks on 'body' then we're just going to repeat the whole captured html document into the snippet view, it's heavy and will break things.

### LINKED ISSUE #37619: Bug: Sometimes there is no HTML related to a DOM Event
Example replay: https://dev.getsentry.net:7999/organizations/sentry-emerging-tech/replays/billy-test:146ac08c784d4dcdbfb6b37b1d660ad8/?l_page=topbar&t_main=dom&t_side=tags

Clicks and LCP events where no HTML snippet was extracted:

Image
Image

It looks weird, we should investigate why this is happening and make a plan to improve things.

### PR DESCRIPTION
**Pull request by danecando**
### Changes
- Does not add items that have empty code contents
- Limits rendered DOM node depth to 2 and writes amount of child nodes that were truncated
- Removes `<style>` tag text content (inline css)
- Removes SVG child nodes

Closes #37619 
Closes #37469

Screen Shot 2022-08-16 at 11 06 18 AM

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by ryan953** [comment]
is there a screen shot showing a truncated html snippet?

File: static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx [hunk 1]
```diff
@@ -22,6 +22,7 @@ type Extraction = {
   crumb: Crumb;
   html: string;
   timestamp: number;
+  truncated: boolean;
```
Comment (ryan953) [inline static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx:25]: is something meant to read this value? it looks unused so far.

**Comment by benvinegar** [comment]
I do feel, if we could get away with it, it would be more meaningful to truncate inner HTML nodes instead of arbitrary characters. E.g. I'd rather see `<body><div> <!-- 256 descendents --></div></body>` or something like that.

File: static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx (hunk 1 above)
Comment (danecando) [reply static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx:25]: > is there a screen shot showing a truncated html snippet?

Added a screenshot to the desc. You can see right now it just cuts off the snippet after x characters. I'm not doing anything with that value yet I wanted to see if anyone had suggestions about how these truncated snippets should be shown

**Comment by danecando** [comment]
> I do feel, if we could get away with it, it would be more meaningful to truncate inner HTML nodes instead of arbitrary characters. E.g. I'd rather see `<body><div> <!-- 256 descendents --></div></body>` or something like that.

I agree I like that much better. Do you think also instead of counting characters to truncate we should try to check how many levels deep it is and shorten it based on that? Will require some regex or something probably but that seems like it would be a lot nicer and more consistent

**Comment by danecando** [comment]
Based on @benvinegar suggestion I made some changes and I think it's much improved. Let me know what you think !

Screen Shot 2022-08-11 at 1 49 15 PM

File: static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx]: We can probably put that ticket in jesse's queue to think about. Right now it looks broken because the line just trails off and has no syntax highlighting.

File: static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx [hunk 2]
```diff
@@ -135,11 +137,21 @@ class BreadcrumbReferencesPlugin {
...
+          truncated = truncated.substring(0, 2000);
+        }
+
+        if (truncated) {
+          this.activities.push({
+            crumb,
+            html: truncated,
+            timestamp: nextTimestamp,
+          });
+        }
```
Comment (ryan953) [inline static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx:153]:
```suggestion
        this.activities.push({
          crumb,
          html: truncated,
          timestamp: nextTimestamp,
        });
```

**Review by ryan953 — APPROVED** [review]

File: static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx [hunk 3]
```diff
@@ -6,6 +6,7 @@ import {eventWithTime} from 'rrweb/typings/types';
 
 import type {Crumb} from 'sentry/types/breadcrumbs';
 import type ReplayReader from 'sentry/utils/replays/replayReader';
+import {element} from 'prop-types';
```
Comment (ryan953) [inline static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx:9]:
```suggestion
```

File: static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx (hunk 2 above)
Comment (danecando) [reply static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx:153]: I thought we wanted to not include empty code blocks?

Comment (ryan953) [reply static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx:152]: oh yeah. i guess i was reading it funny. i was reading it like "if we got a string back after calling removeNodesAtLevel and possibly calling  substring..." and i was like, sure we'll get something back.
