### PR TITLE
fix(insights): all projects selected shows no data insight modules in superuser mode

### LINKED ISSUE #82035: Fix(insights) module hasData returns false always in admin
In admin mode, module data isn’t showing up with all projects selected. When all projects are selected in admin mode specifically, pageFilters.projects.selection = [] (see code below). In this condition we filters to projects you’re a member of (which is none of them), and then check if any of those projects have data. If they don’t have data we show a no data screen.

https://github.com/getsentry/sentry/blob/a8a4d7c133ecc179c273f79000b2757ff248d459/static/app/views/insights/common/queries/useHasFirstSpan.tsx#L43-L45

### PR DESCRIPTION
**Pull request by DominikB2014**
closes https://github.com/getsentry/sentry/issues/82035

Basically, in superuser, sometimes `pageFilters.selection.projects` returns `[]` when all projects are selected. However the code assumes empty array is "my projects".

### CODE REVIEW

File: static/app/views/insights/common/queries/useHasFirstSpan.tsx [hunk 1]
```diff
@@ -52,6 +53,9 @@ export function useHasFirstSpan(module: ModuleName, projects?: Project[]): boole
   //  - [] empty list represents "My Projects"
   //  - [-1] represents "All Projects"
   //  - [.., ..] otherwise, represents a list of project IDs
+  if (pageFilters.selection.projects.length === 0 && isActiveSuperuser()) {
+    selectedProjects = allProjects; // when superuser is enabled, My Projects isn't applicable, and in reality all projects are selected when projects.length === 0
+  }
   if (pageFilters.selection.projects.length === 0) {
     selectedProjects = allProjects.filter(p => p.isMember);
```
Comment (edwardgou-sentry) [inline static/app/views/insights/common/queries/useHasFirstSpan.tsx:60]:
```suggestion
    selectedProjects = allProjects.filter(p => p.isMember || isActiveSuperuser());
```
same thing but shorter, maybe less obvious what it does though 🤷

**Review by edwardgou-sentry — APPROVED** [review]

File: static/app/views/insights/common/queries/useHasFirstSpan.tsx (hunk 1 above)
Comment (DominikB2014) [reply static/app/views/insights/common/queries/useHasFirstSpan.tsx:60]: Yeah, that's a good call out, thanks! I do think it is less obvious what's going on, so I decided to leave as is for now

Comment (DominikB2014) [reply static/app/views/insights/common/queries/useHasFirstSpan.tsx:60]: At first I thought it wasn't obvious, but it makes sense actually as they are both conditions on the user (isMemeber or isSuperusuer).
It is an unnecessary filter, but the performance of that is negligible
