### PR TITLE
fix(ddm): Scratchpad project selection

### LINKED ISSUE #59703: Refresh scratchpad page
I set a scratchpad as default, I reload the page, and I do see all my graphs but the scratchpad selector is not set on the actual saved scratchpad. This happens only if I refresh the page and not when I come back.

### LINKED ISSUE #59705: Scratchpads don't remember projects
I have to re-select the project in order to see my scratchpad.

Screenshot%202023-10-30%20at%2014 13 34

### LINKED ISSUE #62365: scratchpad with projects is not great

### PR DESCRIPTION
**Pull request by ArthurKnaus**
Select default scratchpad on page load if query matches.
Persist page filters if no scratchpad is selected.

- closes https://github.com/getsentry/sentry/issues/59703
- closes https://github.com/getsentry/sentry/issues/62365
- closes https://github.com/getsentry/sentry/issues/59705

### CODE REVIEW

**Review by obostjancic — APPROVED** [review]

File: static/app/components/replaysOnboarding/sidebar.tsx [hunk 1]
```diff
@@ -337,10 +337,20 @@ function OnboardingContent({currentProject}: {currentProject: Project}) {
...
+              {
+                link: (
+                  <ExternalLink href="https://docs.sentry.io/product/session-replay/getting-started/#:~:text=Make%20sure%20you%27ve%20set%20up%20trace%20propagation%20in%20your%20backend%20projects." />
+                ),
+              }
+            )}
+          </div>
+        ) : (
+          ''
+        )}
```
Comment (ArthurKnaus) [inline static/app/components/replaysOnboarding/sidebar.tsx:353]: auto generated diff by linter on merging master
