### PR TITLE
fix(replays): Fix Replay Issues tab to use fewer queries

### LINKED ISSUE #40126: Bug: Issues tab is not showing any issues for some customers
This looks related to the multi-group events permission issue that we've seen before.

### PR DESCRIPTION
**Pull request by ryan953**
I'm changing the Replay Issues tab from needing 3 ajax calls down only running 1. 

Previously we were doing sequential calls:
- `/issues/` gets all issue data
- `/issues-stats/` re-fetches some of the issue fields
- `<DiscoverQuery>` fetch the list of errors that we want to show issues for, it's the same query that we started with

This was all overkill. All the data that we use for rendering comes in the first call to `/issues/`.

I also noticed that the DiscoverQuery has guards for `organizations:global-views`. This was causing trouble for orgs because the list of projects wasn't specified so they would get a 400 response on that 3rd ajax call, causing the whole section to fail to render. That's not happening anymore.

| | `organizations:global-views=false`  | `organizations:global-views=false` |
| --- | ------------- | ------------- |
| Before | before - global-views | before |
| After | after - global-views | after |
| Note | Now we show that there are no rows, instead of the silent 400 | The sort order has changed, but rendering is still fine. It seemed like arbitrary sort order anyway because N errors from M issues could have happened in the replay. | 

Fixes #40126

### CODE REVIEW

File: static/app/views/replays/detail/issueList.tsx [hunk 1]
```diff
@@ -10,174 +10,131 @@ import {DEFAULT_STREAM_GROUP_STATS_PERIOD} from 'sentry/components/stream/group'
...
-            headers={
-              isScreenLarge ? columns : columns.filter(column => column !== t('Graph'))
-            }
-          >
-            {data.tableData?.data.map(renderTableRow) || null}
-          </StyledPanelTable>
-        );
-      }}
-    </DiscoverQuery>
+      <Item>{issue.userCount ? issue.userCount : <Placeholder height="24px" />}</Item>
```
Comment (billyvg) [inline static/app/views/replays/detail/issueList.tsx:134]: Are these placeholders still needed since you've reduced this down to the 1 request, they should always exist.

Comment (ryan953) [reply static/app/views/replays/detail/issueList.tsx]: indeed they are not!

**Review by billyvg — APPROVED** [review]
