### PR TITLE
ref(stats): Link to project issues, not settings

### LINKED ISSUE #15431: Navigating to a project from the Stats page takes me to Settings for the project
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ √ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I'm using the Stats page (https://sentry.io/organizations/[ORG]/stats/) to determine which projects have the highest rate of issues/events. When I click on a project name I expect that I'll be brought to the project's page with issues listed. (https://sentry.io/organizations/[ORG]/issues/?project=[PROJ_NUM]) Instead I'm brought to the settings for the project, which is a little confusing.

## Steps to Reproduce

1. navigate to https://sentry.io/organizations/[ORG]/stats/
2. find a project, and click on the name (you can also view the link's href)
3. you'll arrive at the project's settings page https://sentry.io/settings/[ORG]/projects/[PROJ]/

### What you expected to happen

Based on the context of what's shown on the Stats page, I expect that I'll be brought to the project's page, listing issues for that project.

### Possible Solution

I'm sure you all have this under control, but I'm going to guess using an incorrect url util function in a template somewhere? 😃 🤷‍♂

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Fixes https://github.com/getsentry/sentry/issues/15431

### CODE REVIEW

**Review by billyvg — APPROVED** [review]

File: src/sentry/static/sentry/app/views/organizationStats/projectTable.tsx [hunk 1]
```diff
@@ -41,7 +41,7 @@ const ProjectTable = ({projectMap, projectTotals, orgTotal, organization}: Props
         return null;
       }
 
-      const projectLink = `/settings/${organization.slug}/projects/${project.slug}/`;
+      const projectLink = `/organizations/${organization.slug}/issues/?project_id=${project.id}`;
```
Comment (billyvg) [inline src/sentry/static/sentry/app/views/organizationStats/projectTable.tsx:44]: Wait this should be 
```suggestion
      const projectLink = `/organizations/${organization.slug}/issues/?project=${project.id}`;
```

**Review by billyvg — DISMISSED** [review]

**Review by matejminar — APPROVED** [review]

File: src/sentry/static/sentry/app/views/organizationStats/projectTable.tsx (hunk 1 above)
Comment (EvanPurkhiser) [reply src/sentry/static/sentry/app/views/organizationStats/projectTable.tsx:44]: oh wait maybe I didn't commit this hmm
