### PR TITLE
fix(settings): Change `formPanel` to expand when clicked anywhere

### LINKED ISSUE #54146: Performance issue threshold settings have small hitbox
On the URL `/settings/projects/<project_slug>/performance/#detector-threshold-settings`, it is difficult to expand the accordions because the only clickable element is quite small.

CleanShot 2023-08-03 at 15 34 14@2x

### PR DESCRIPTION
**Pull request by 0Calories**
Adjusts `formPanel.tsx` by changing it so that the expand/collapse function can be activated by clicking anywhere on the component instead of just on the chevron, which felt like too small of an area. 

Fixes https://github.com/getsentry/sentry/issues/54146

### CODE REVIEW

File: static/app/components/forms/formPanel.tsx [hunk 1]
```diff
@@ -62,12 +62,21 @@ function FormPanel({
   const handleCollapseToggle = useCallback(() => setCollapse(current => !current), []);
 
   return (
-    <Panel id={typeof title === 'string' ? sanitizeQuerySelector(title) : undefined}>
+    <Panel
+      id={typeof title === 'string' ? sanitizeQuerySelector(title) : undefined}
+      onClick={collapsible ? handleCollapseToggle : undefined}
+      style={collapsible ? {cursor: 'pointer'} : undefined}
```
Comment (leeandher) [inline static/app/components/forms/formPanel.tsx:68]: Since Panel is a `div`, I'd add a `role="button"` when collapsible is set. Maybe `aria-label` and `aria-expanded` as well.

Comment (0Calories) [reply static/app/components/forms/formPanel.tsx:69]: good callout, thanks @leeandher 🙏 
updated it with your suggestions

**Review by leeandher — APPROVED** [review]
