### PR TITLE
bug(replays): Replay>Network>Details should hide setup code snippets if the url is Filtered

### LINKED ISSUE #48730: [Replay Details] Replay Network shouldn't suggest adding "[Filtered]" urls to the config
Image

### PR DESCRIPTION
**Pull request by ryan953**
Fixes https://github.com/getsentry/sentry/issues/48730

### CODE REVIEW

**Review by billyvg — APPROVED** [review]

File: static/app/views/replays/detail/network/details/onboarding.tsx [hunk 1]
```diff
@@ -240,10 +237,12 @@ function SetupInstructions({
...
-
-      <CodeSnippet filename="JavaScript" language="javascript">
-        {code}
-      </CodeSnippet>
+      {url !== '[Filtered]' && (
+        <CodeSnippet filename="JavaScript" language="javascript">
+          {code}
+        </CodeSnippet>
+      )}
+      › has copy, print and download buttons
```
Comment (billyvg) [inline static/app/views/replays/detail/network/details/onboarding.tsx:245]: What's this?

**Review by billyvg — APPROVED** [review]

File: static/app/views/replays/detail/network/details/onboarding.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/views/replays/detail/network/details/onboarding.tsx:245]: that's someething extra. idk

File: static/app/views/replays/detail/network/details/onboarding.tsx [hunk 2]
```diff
@@ -210,24 +210,21 @@ function SetupInstructions({
...
-      {showSnippet === Output.URL_SKIPPED && (
+      {showSnippet === Output.URL_SKIPPED && url !== '[Filtered]' && (
         <Alert type="warning">
           {tct('Add [url] to your [field] list to start capturing data.', {
             url: <kbd>{url}</kbd>,
             field: <kbd>networkDetailAllowUrls</kbd>,
           })}
         </Alert>
       )}
-
```
Comment (ryan953) [inline static/app/views/replays/detail/network/details/onboarding.tsx:222]: linter is doing this
