### PR TITLE
fix(attachments): Fix issue where attachment name would overflow off card

### LINKED ISSUE #92151: Screenshot preview not truncating file name which overflows
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

[Example event](https://sentry-sdks.sentry.io/issues/6609574800/events/00bbcdc7e44f456dbda9328a4bf05455/attachments/?attachmentFilter=screenshot&project=4509276197879808)

We're not able to see all screenshots in the preview screen, which is great:
* https://github.com/getsentry/sentry/pull/91602

But since the name isn't fixed `screenshot.jpg` anymore, it could be quite large and needs to be wrapped or truncated

### Expected Result

Names are wrapped or truncated

### Actual Result

names overflow passed the attachment section of the page

Image

### Product Area

Issues

### Link

https://sentry-sdks.sentry.io/issues/6609574800/events/00bbcdc7e44f456dbda9328a4bf05455/attachments/?attachmentFilter=screenshot&project=4509276197879808

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by MichaelSun48**
fixes #92151

Fixes an issue where the event attachment name would overflow off the card and obscure the ellipsis menu. Also cleans up some styles. 

Before: 

Screenshot 2025-06-05 at 1 13 32 PM

After: 

Screenshot 2025-06-05 at 1 14 02 PM

### CODE REVIEW

File: static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx [hunk 1]
```diff
@@ -82,8 +82,15 @@ export function ScreenshotCard({
   return (
     <StyledCard>
       <CardHeader>
-        <div>
-          <AttachmentName>{eventAttachment.name}</AttachmentName>
+        <ScreenshotInfo>
+          <AttachmentName
+            position="top"
```
Comment (evanpurkhiser) [inline static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx]: Does it need this?

File: static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx [hunk 2]
```diff
@@ -82,8 +82,15 @@ export function ScreenshotCard({
...
+            title={eventAttachment.name}
+            showOnlyOnOverflow
+            skipWrapper
+          >
+            {eventAttachment.name}
+          </AttachmentName>
```
Comment (evanpurkhiser) [inline static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx]: nit: instead of styling tooltip itself I would keep the `AttachmentName` as a span or whatever and just use regular `Tooltip` component

```suggestion
        <ScreenshotInfo>
          <Tooltip
            title={eventAttachment.name}
            showOnlyOnOverflow
            skipWrapper
          >
            <AttachmentName>{eventAttachment.name}</AttachmentName>
          </Tooltip>
```

I think this is a bit more clear what's happening, before it was unclear that `AttachmentName` was a tooltip

File: static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx (hunk 1 above)
Comment (MichaelSun48) [reply static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx]: Nope, removed.

File: static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx [hunk 3]
```diff
@@ -155,24 +158,34 @@ export function ScreenshotCard({
...
   margin: 0;
+  padding: ${space(1)} ${space(1.5)};
 `;
 
-const AttachmentName = styled('div')`
-  font-weight: bold;
+const AttachmentName = styled('span')`
+  font-weight: ${p => p.theme.fontWeightBold};
+  display: flex;
   ${p => p.theme.overflowEllipsis};
```
Comment (evanpurkhiser) [inline static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx:175]: wait doens't overflowEllipsis give us some of these styles too?

Comment (MichaelSun48) [reply static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx:175]: yeah good point, the styles under this are redundant. removed

**Review by evanpurkhiser — APPROVED** [review]
