### PR TITLE
fix(metrics): aggregate select overflow

### LINKED ISSUE #68984: Sets "group by" display issue (Safari)
Fine in Chrome, seems to be a Safari thing.

Image

### PR DESCRIPTION
**Pull request by obostjancic**
- fixes: #68984 

Removes fixed width of _Agg_ dropdown

### Before

Safari
image

Chrome
image

### After

Safari
image

Chrome
image

### CODE REVIEW

**Review by ArthurKnaus — APPROVED** [review]

File: static/app/views/metrics/queryBuilder.tsx [hunk 1]
```diff
@@ -372,8 +372,6 @@ const MetricSelect = styled(CompactSelect)`
 `;
 
 const OpSelect = styled(CompactSelect)`
-  width: 128px;
-  min-width: min-content;
```
Comment (ArthurKnaus) [inline static/app/views/metrics/queryBuilder.tsx:376]: Does it work when you only remove the `width` but keep `min-width`?
