### PR TITLE
feat(ddm): Fix yAxis formatting

### LINKED ISSUE #60879: Fix decimal rounding when formatting DDM values
There are 2 problems we've seen:
# Number 1
Image

Ideally, we should see here 800ms, 700ms, etc.

# Number 2
Image

Because we are forcing 3 decimal points, when the value is lower than 0.001, we are rendering all 0s (both yAxis and tooltip)

### PR DESCRIPTION
**Pull request by ArthurKnaus**
Fix yAxis formatting by:

- not stripping significant decimal points: `0.00000123 -> 0.0000012` (before `0.00`)
- not forcing `.00` decimal points: `100.00012 -> 100` (before `100.00`)
- supporting micro- and nanoseconds 

closes https://github.com/getsentry/sentry/issues/60879

### CODE REVIEW

File: static/app/utils/metrics/index.tsx [hunk 1]
```diff
@@ -223,6 +231,51 @@ export function getReadableMetricType(type?: string) {
   return metricTypeToReadable[type as MetricType] ?? t('unknown');
 }
 
+const MILLISECOND = 1;
+const MICROSECOND = MILLISECOND / 1000;
+
+export function formatDuration(seconds: number): string {
+  if (!seconds) {
+    return '0ms';
```
Comment (ArthurKnaus) [inline static/app/utils/metrics/index.tsx:239]: The current implementation would also fall back to `ms`. Ideally the formatter would be aware of the chart's series and use the same unit here as for the second smallest axis value. 🤔

**Review by matejminar — APPROVED** [review]
