### PR TITLE
fix(tab): Use default cursor for disabled items

### LINKED ISSUE #63579: Disabled Code Location tab
Bruno:

Image

I found this confusing at first, I realize a tooltip shows up but it still looks like a button and the cursor changes to indicate a button so I clicked a ton before I realize it’s not just slow.

Here’s the Replay: https://sentry.sentry.io/replays/a0a2ac4934c84529b45cf8def23eb9d9/?project=11276&query=&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=24h&yAxis=count%28%29&t=93. 
I’m surprised it didn’t fire a Rage click, but I checked and it’s not a button nor an anchor so we don’t trigger one.

### PR DESCRIPTION
**Pull request by ArthurKnaus**
### Problem
Tab items use the pointer cursor style when they are disabled. Therefore indicating they are clickable.
Other disabled components (buttons , dropdown items, ...) use the default cursor style in this case.

https://github.com/getsentry/sentry/assets/7033940/52620d18-d817-473a-995f-69c58fe1a680

### Solution
Use the default cursor style for disabled tab items.

https://github.com/getsentry/sentry/assets/7033940/59ca44d8-95d2-43f6-a069-0146a11ec9df

- closes https://github.com/getsentry/sentry/issues/63579

### CODE REVIEW

File: static/app/components/tabs/tab.tsx [hunk 1]
```diff
@@ -123,6 +123,7 @@ const TabWrap = styled('li', {shouldForwardProp: tabsShouldForwardProp})<{
       &, &:hover {
         color: ${p.theme.subText};
         pointer-events: none;
+        cursor: default;
```
Comment (JonasBa) [inline static/app/components/tabs/tab.tsx:126]: @ArthurKnaus is the disabled attribute set on the tab? That should be the correct fix here and we should target that state with the `:disabled` CSS selector

Comment (ArthurKnaus) [reply static/app/components/tabs/tab.tsx:126]: The tab is a `li` element. The disabled attribute is set on it, though since it is an `li` you cannot use the `:disabled` selector. I guess is is actually an oversight that the disabled attribute ends up on it.
Will change it to a "no js" style version that selects `[aria-disabled='true']` instead.

File: static/app/components/tabs/tab.tsx [hunk 2]
```diff
@@ -80,7 +76,6 @@ function BaseTab(
     <TabWrap
       {...tabProps}
       hidden={hidden}
-      disabled={isDisabled}
```
Comment (ArthurKnaus) [inline static/app/components/tabs/tab.tsx:83]: `aria-disabled` is provided via `tabProps` and should be sufficient, given that `disabled` is not supported by `li`.

File: static/app/components/tabs/tab.tsx (hunk 1 above)
Comment (ArthurKnaus) [reply static/app/components/tabs/tab.tsx]: not sure if we need it though,`react-aria` seems to provide all necessary attributes for it to be accessible 🤔

**Review by JonasBa — APPROVED** [review]
