### PR TITLE
fix: Update lastUpdated when codeowner is synced

### LINKED ISSUE #56624: Codeowners `dateUpdated` not updating even though file syncs
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to the codeowners file in the codeowners page.
Click on the "Sync" button for a codeowners file.
Observe that the "Last Sync" time does not update as expected. 

Workaround:
Delete the codeowners file and then re-import it. 

### Expected Result

The "Last Sync" time should update immediately after clicking the "Sync" button, indicating that the codeowners file changes have been successfully synced.

### Actual Result

The "Last Sync" time remains unchanged, even after attempting to sync the codeowners file.

### Product Area

Settings

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by jangjodi**
Update lastUpdated when codeowner is synced

fixes https://github.com/getsentry/sentry/issues/56624

### CODE REVIEW

File: static/app/views/settings/project/projectOwnership/codeOwnerFileTable.tsx [hunk 1]
```diff
@@ -62,7 +62,7 @@ export function CodeOwnerFileTable({
         `/projects/${organization.slug}/${project.slug}/codeowners/${codeowner.id}/`,
         {
           method: 'PUT',
-          data: {raw: codeownerFile.raw},
+          data: {raw: codeownerFile.raw, date_updated: new Date()},
```
Comment (scttcper) [inline static/app/views/settings/project/projectOwnership/codeOwnerFileTable.tsx:65]: we're going to want to use an iso string here since passing a date to the json parser uses toString which looks like `Wed Oct 04 2023 11:56:45 GMT-0700 (Pacific Daylight Time)`
```suggestion
          data: {raw: codeownerFile.raw, date_updated: new Date().toISOString()},
```

the mock api isn't great for testing this

**Review by scttcper — APPROVED** [review]
