### PR TITLE
fix(alerts): Fix display text of sessions alert filter in sidebar

### LINKED ISSUE #49727: Issue alert details sidebar tech debt
- [ ] Our types for issue alert conditions and templates are very loose, for example [the condition types](https://github.com/getsentry/sentry/blob/dbc6be2df1e745ec850d0eaa2e5f84f8249e7531/static/app/types/alerts.tsx#L55-L63) are pretty loose as to what properties will be present. Would like to see a base type with a more accurate type that represents each filter/condition. eg `id: sentry.rules.conditions.event_frequency.EventFrequencyPercentCondition` + `comparisonInterval: string`
- [ ] We do a mix of string parsing and custom strings when [rendering the actions/filters](https://github.com/getsentry/sentry/blob/dbc6be2df1e745ec850d0eaa2e5f84f8249e7531/static/app/views/alerts/rules/issue/details/textRule.tsx#L83-L106) because the strings we get from the backend are not accurate. We should stop using the "name" from the backend and add components for each id. Parsing the strings is brittle and often incorrect, along with the types not existing.

More examples of weird string rendering because we're just using what the backend says

Image
becomes
Image

Image
becomes
Image

### PR DESCRIPTION
**Pull request by scttcper**
fixes "percent of sessions affected by an issue" being displayed as "number of events in an issue"

fixes #49727

### CODE REVIEW

File: static/app/views/alerts/rules/issue/details/textRule.tsx [hunk 1]
```diff
@@ -21,26 +21,18 @@ export function TextCondition({
...
-              condition.value,
-              condition.interval,
-              condition.comparisonInterval
-            )}
-          </Fragment>
-        );
-      }
       return (
         <Fragment>
           {t(
```
Comment (malwilley) [inline static/app/views/alerts/rules/issue/details/textRule.tsx:33]: Is this even translatable? `subject` is an english phrase, so it would end up being two different languages mixed up

Comment (scttcper) [reply static/app/views/alerts/rules/issue/details/textRule.tsx:33]: it probably is not

**Review by malwilley — APPROVED** [review]
