### PR TITLE
fix(solid-onboarding): Update configure snippet

### LINKED ISSUE #77908: Onboarding: Solid - Update snippet
Replace
```
const app = document.getElementById("app");

if (!app) throw new Error("No #app element found in the DOM.");

render(() => <App />, app);
```
with
```
const root = document.getElementById("root");

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    "Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?"
  );
}

render(() => <App />, root);
```

### PR DESCRIPTION
**Pull request by ArthurKnaus**
closes https://github.com/getsentry/sentry/issues/77908

### CODE REVIEW

File: static/app/gettingStartedDocs/javascript/solid.tsx [hunk 1]
```diff
@@ -88,11 +88,15 @@ ${getFeedbackConfigOptions(params.feedbackOptions)}}),`
 }
 });
 
-const app = document.getElementById("app");
+const root = document.getElementById("root");
 
-if (!app) throw new Error("No #app element found in the DOM.");
+if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
```
Comment (priscilawebdev) [inline static/app/gettingStartedDocs/javascript/solid.tsx:93]: why do we need to check for `import.meta.env.DEV`? do solid projects always have `env`?

Comment (ArthurKnaus) [reply static/app/gettingStartedDocs/javascript/solid.tsx:93]: This code is included in the solid boilerplate. We are just updating the snippet to match it.

**Review by priscilawebdev — APPROVED** [review]
