### PR TITLE
fix(replays): onHover onClick now hover/click to correct times and no longer break the player

### LINKED ISSUE #34840: Memory Chart hover&re-render breaks click events
Hovering over a point on the chart causes the chart to re-render and causes chart state to be reset.

This makes us unable to click on chart to change the player time. Ex: After clicking a point on the line of the memory chart, the video time becomes `NaN:NaN`
Image

It's only the container that is re-rendering:

Image

### PR DESCRIPTION
**Pull request by Danondso**
Closes #34840 

https://user-images.githubusercontent.com/7014871/169607726-32f2276c-b4ee-48ce-8f74-6237cb42dc37.mov

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/views/replays/detail/memoryChart.tsx [hunk 1]
```diff
@@ -240,7 +244,6 @@ function MemoryChartContainer({
 }: MemoryChartContainerProps) {
   const chart = useRef<ReactEchartsRef>(null);
   const theme = useTheme();
-
```
Comment (billyvg) [inline static/app/views/replays/detail/memoryChart.tsx:243]: Let's keep this newline

**Review by billyvg — APPROVED** [review]
