### PR TITLE
fix(replays): merge click and dead clicks in the UI

### LINKED ISSUE #54031: [Replay Details] Merge click + dead click breadcrumbs in UI

### PR DESCRIPTION
**Pull request by michellewzhang**
- renamed DOM filter from "click" to "user click" for more specificity, since that filter only shows user clicks now
- removed duplicate user clicks & dead/rage clicks in the DOM events tab
- removed duplicates in the timeline
- removed duplicates in the breadcrumbs

Before:
SCR-20230803-khtx
SCR-20230803-khvj
SCR-20230803-khwo

After:
SCR-20230803-sxgc
SCR-20230803-sxdb
SCR-20230803-sxjg

Fixes https://github.com/getsentry/sentry/issues/54031!

### CODE REVIEW

File: static/app/utils/replays/replayReader.tsx [hunk 1]
```diff
@@ -61,6 +61,32 @@ type RequiredNotNull<T> = {
...
 const sortFrames = (a, b) => a.timestampMs - b.timestampMs;
 
+function removeDuplicateClicks(frames: BreadcrumbFrame[]) {
+  const slowClickFrames = frames.filter(
+    frame => frame.category === 'ui.slowClickDetected'
+  );
+
+  const clickFrames = frames.filter(frame => frame.category === 'ui.click');
+
+  const noClickFrames = frames.filter(
```
Comment (ryan953) [inline static/app/utils/replays/replayReader.tsx:71]: the name matches the pattern of the other two, but it might read better as like `const otherFrames`

**Review by ryan953 — COMMENTED** [review]
We should add a test for this new method. We can test that it's working as part of the existing  `getDOMFrames` and/or `getChapterFrames` tests which are meant to test the filtering.

File: static/app/utils/replays/replayReader.spec.tsx [hunk 2]
```diff
@@ -157,16 +169,10 @@ describe('ReplayReader', () => {
         method: 'getChapterFrames',
         expected: [
           expect.objectContaining({category: 'replay.init'}),
-          expect.objectContaining({category: 'ui.click'}),
+          expect.objectContaining({category: 'ui.slowClickDetected'}),
           expect.objectContaining({op: 'navigation.navigate'}),
-        ],
-      },
-      {
-        method: 'getTimelineFrames',
```
Comment (michellewzhang) [inline static/app/utils/replays/replayReader.spec.tsx:165]: removed this test since the `getTimelineFrames` isn't used anywhere

**Review by ryan953 — APPROVED** [review]
looks awesome!
