### PR TITLE
fix(replay): fix mobile replay issue preview no height

### LINKED ISSUE #87139: Replay player has no height on Issue Detail (renders OK in replay details)
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Event: https://demo.sentry.io/issues/6395032325/?project=4508968167538688

Image

You can actually click on that small purple link. The full Replay does render: https://demo.sentry.io/replays/c88d3e95221b42cab797aeb0ffa137f3/?referrer=%2Fissues%3AgroupId%2F&t=0&t_main=errors

Image

### PR DESCRIPTION
**Pull request by michellewzhang**
this no height bug was happening on issue details in the replay preview:

SCR-20250414-mjwb

what was happening: 

1. the error happened before the replay started recording
2. the clip window is then outside the range of the replay timestamps (the entire clip window is before the replay event starts): https://github.com/getsentry/sentry/blob/affc8f2758cbf3df3492b62d81b3f85ea2a28405/static/app/components/events/eventReplay/replayClipSection.tsx#L44-L47
https://github.com/getsentry/sentry/blob/affc8f2758cbf3df3492b62d81b3f85ea2a28405/static/app/components/events/eventReplay/replayClipPreview.tsx#L28-L34
4. in `replayReader`, we know there's a clip window that needs to be applied. when we applied the clip window before, the clamp got messed up because the clip window was outside the range of the replay timestamp --> clip end + start became the same number, leading the clip duration to become 0. this sets the `replay.duration` to be 0.

example with old clamp logic:
```
    // imagine clipWindow is [3, 8] and replay timestamp is [10, 20]

    const clipStartTimestampMs = clamp(
      clipWindow.startTimestampMs,                       // 3
      this._replayRecord.started_at.getTime(),           // 10
      this._replayRecord.finished_at.getTime()           // 20
    ); 
    // this becomes 10

    const clipEndTimestampMs = clamp(
      clipWindow.endTimestampMs,                       // 8
      clipStartTimestampMs,                            // 10
      this._replayRecord.finished_at.getTime()         // 20
    ); 
    // this is also 10

    // this is 0
    this._duration = duration(clipEndTimestampMs - clipStartTimestampMs); 
```

6. causing this code to be executed: https://github.com/getsentry/sentry/blob/affc8f2758cbf3df3492b62d81b3f85ea2a28405/static/app/components/events/eventReplay/replayClipPreviewPlayer.tsx#L118-L129
something went wrong here, which led to a replay preview with no height.

the solution i'm suggesting here is: 
- if the error happens before the replay starts recording, then just show the first 10 seconds of the replay. 
- add a note that the error happened before the replay for more clarity. 

after:

SCR-20250414-mwkj

fixes https://github.com/getsentry/sentry/issues/87139

### CODE REVIEW

**Review by ryan953 — APPROVED** [review]

File: static/app/utils/replays/replayReader.tsx [hunk 1]
```diff
@@ -300,18 +300,26 @@ export default class ReplayReader {
...
-    );
+    let clipStartTimestampMs;
+    let clipEndTimestampMs;
+    const replayStart = this._replayRecord.started_at.getTime();
+    const replayEnd = this._replayRecord.finished_at.getTime();
+
+    // error event is before the replay started. use the start of the replay as the start of the clip
+    if (clipWindow.startTimestampMs < this._replayRecord.started_at.getTime()) {
+      clipStartTimestampMs = replayStart;
+      clipEndTimestampMs = Math.min(replayStart + 5000, replayEnd);
```
Comment (ryan953) [inline static/app/utils/replays/replayReader.tsx:311]: is this `+ 5000` too much of a hard-coded thing? would the same `clamp()` call work in here?

Comment (michellewzhang) [reply static/app/utils/replays/replayReader.tsx:311]: not really, we do the same thing here
https://github.com/getsentry/sentry/blob/bafca93a33dcf3017dcd69b931aeecae18f1df35/static/app/utils/replays/hooks/useLoadReplayReader.tsx#L49-L52

i think it should actually be 10 seconds

Comment (ryan953) [reply static/app/utils/replays/replayReader.tsx:311]: it's 5s before, and 5s after. so `+ 5000` in here seems fine.
