### PR TITLE
fix(browser-starfish): fix cls on resource image view, fix confusing images sizes when 0

### LINKED ISSUE #62861: Largest Images Component should not cause CLS
We probably want the component to have a min-height to prevent CLS. Right now it pops up on the page.

I also think we should avoid stretching the image https://sentry.sentry.io/performance/browser/resources/spans/span/7eb0c1ac912da397/?project=11276&span.op=resource.img&statsPeriod=7d

image

Let's keep same aspect ratio

### LINKED ISSUE #62862: Size of 0.0 bytes is confusing for largest images
https://sentry.sentry.io/performance/browser/resources/spans/span/720f31daf4f509d6/?project=11276&span.op=resource.img&statsPeriod=7d

image

^ I think above is a tracking pixel 😭 

Should say size unknown if it's 0 bytes?

### PR DESCRIPTION
**Pull request by DominikB2014**
fixes #62861 
fixes #62862 

This PR adds
1. Loading indicator with a fixed container height to minimize/prevent CLS
image

2. Center images, and do not stretch them
image

3. Grabs the resource type from the URL so that we don't have to wait for the type from the api request in order to either render the sample images or not

4. Handles the case where there are no images 
image

5. Display `--` when image size is 0, the same as we do on all the tables
image

### CODE REVIEW

File: static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx [hunk 1]
```diff
@@ -43,27 +46,40 @@ function SampleImages({groupId}: Props) {
...
+  let body: React.ReactNode;
+
+  if (!showImages) {
+    body = <DisabledImages onClickShowLinks={() => setShowImages(true)} />;
+  } else if (showImages && isLoadingImagesLoading) {
+    body = <LoadingIndicator />;
+  } else if (showImages && !hasImages) {
+    body = (
+      <EmptyStateWarning>
+        <p>{t('No results found for your query')}</p>
```
Comment (AbhiPrasad) [inline static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx:60]:
```suggestion
        <p>{t('No images detected')}</p>
```

I wonder if we should capture a Sentry error when we hit this so that we gather some examples of when someone goes to an images resource summary and sees no images. Do you think that is a good idea?

File: static/app/views/performance/browser/resources/resourceSummaryPage/index.tsx [hunk 2]
```diff
@@ -57,10 +57,7 @@ function ResourceSummary() {
     ],
   });
   const spanMetrics = data[0] ?? {};
-
-  const isImage = IMAGE_FILE_EXTENSIONS.includes(
-    spanMetrics[SpanMetricsField.SPAN_DESCRIPTION]?.split('.').pop() || ''
-  );
+  const isImage = spanOp === 'resource.img';
```
Comment (AbhiPrasad) [inline static/app/views/performance/browser/resources/resourceSummaryPage/index.tsx:60]: l: Ideally `resource.img` is extracted to a constant

File: static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx [hunk 3]
```diff
@@ -43,27 +46,40 @@ function SampleImages({groupId}: Props) {
     })
     .splice(0, 5);
 
+  const hasImages = filteredResources.length > 0;
+
+  let body: React.ReactNode;
```
Comment (AbhiPrasad) [inline static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx:51]: m: Can we extract this into it's own component?

File: static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx (hunk 1 above)
Comment (DominikB2014) [reply static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx:60]: I def l ike the idea, it does not entirely fall into an error category I would say, as we do expect missing images when there simply isn't enough volume and we sample them out. But we will get a bunch of data on this to help us optimize sampling if needed. Is this a better case for DDM, or would we not get any context like the customer itself.

File: static/app/views/performance/browser/resources/resourceSummaryPage/index.tsx (hunk 2 above)
Comment (DominikB2014) [reply static/app/views/performance/browser/resources/resourceSummaryPage/index.tsx]: done!

File: static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx (hunk 3 above)
Comment (DominikB2014) [reply static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx]: I extract everything in the body into its own component

**Comment by DominikB2014** [comment]
@AbhiPrasad I addressed all your comments! lmk if you have any further thoughts

File: static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx (hunk 1 above)
Comment (AbhiPrasad) [reply static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx]: We can't use DDM because of cardinality with trying to attach org, errors you can at least see org slug tagged hence why I suggested that.

**Review by AbhiPrasad — APPROVED** [review]

File: static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx (hunk 1 above)
Comment (DominikB2014) [reply static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx]: Makes sense!

File: static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx [hunk 4]
```diff
@@ -46,28 +49,60 @@ function SampleImages({groupId}: Props) {
...
+  const hasImages = images.length > 0;
+
+  if (!showImages) {
+    return <DisabledImages onClickShowLinks={onClickShowLinks} />;
+  }
+  if (showImages && isLoadingImages) {
+    return <LoadingIndicator />;
+  }
+  if (showImages && !hasImages) {
+    Sentry.captureException(new Error('No sample images missing'));
```
Comment (AbhiPrasad) [inline static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx:81]: wait sorry I didn't see this sooner, @DominikB2014 `Sentry.captureException` needs to be in a `useEffect` call because it is a side effect of the render.

Comment (DominikB2014) [reply static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.tsx:81]: I'll make the change!
