### PR TITLE
Native stack trace: Reduce size of frame address hitbox

### LINKED ISSUE #50696: Native stack trace: Reduce size of frame address hitbox
## Problem

The hitbox for the frame address is too large - see video:

https://user-images.githubusercontent.com/10888943/244822245-b1bd18c4-a2ea-4d7b-ba96-4701d0cbcd56.mp4

## Solution

Make sure that clicking outside the link text does not navigate you to the loaded image section.

### PR DESCRIPTION
**Pull request by 17hogeju**
Closes https://github.com/getsentry/sentry/issues/50696

### Before: 
https://github.com/getsentry/sentry/assets/22582037/ada02b04-f609-4db7-b835-9ccbb1a466df

### After:
https://github.com/getsentry/sentry/assets/22582037/83539344-8272-4b51-b817-d1ffeca8db43

### CODE REVIEW

File: static/app/components/events/interfaces/nativeFrame.tsx [hunk 1]
```diff
@@ -340,6 +342,11 @@ function NativeFrame({
 
 export default withSentryAppComponents(NativeFrame, {componentType: 'stacktrace-link'});
 
+const AddressCellWrapper = styled('div')`
+  display: flex;
+  justify-content: center;
```
Comment (malwilley) [inline static/app/components/events/interfaces/nativeFrame.tsx:347]: I think we want this to be left aligned so no need for centering here

**Review by malwilley — APPROVED** [review]
