### PR TITLE
fix(issue-details): Ensure that filtered data inside objects/arrays are annotated correctly 

### LINKED ISSUE #65985: Filtered event data is not properly annotated when inside an object or array
In the following example,  the only place that should have annotation is the `...` of `body[3].items`. However, currently each key is being highlighted when a single key has an associated filter. 

CleanShot 2024-02-28 at 10 09 24

### PR DESCRIPTION
**Pull request by malwilley**
Fixes https://github.com/getsentry/sentry/issues/65985

The issue was that `meta` was not being passed correctly in multiple locations. For objects/arrays it was falling back to the initial meta object when a key did not exist which is not correct.

Before:

CleanShot 2024-02-28 at 10 34 41@2x

After:

CleanShot 2024-02-28 at 10 34 32@2x

### CODE REVIEW

File: static/app/components/contextData/index.tsx [hunk 1]
```diff
@@ -30,29 +46,36 @@ function walk({
...
   let i = 0;
 
   const children: React.ReactNode[] = [];
 
   if (value === null) {
     return (
       <span className="val-null">
-        <AnnotatedText value={jsonConsts ? 'null' : 'None'} meta={meta?.[''] ?? meta} />
+        <ContextValue
+          value={jsonConsts ? 'null' : 'None'}
```
Comment (scefali) [inline static/app/components/contextData/index.tsx:64]: @malwilley literal 'null' and 'None` strings seem janky

File: static/app/components/events/interfaces/request/index.spec.tsx [hunk 2]
```diff
@@ -53,48 +53,50 @@ describe('Request entry', function () {
...
-                    len: 1,
-                    chunks: [
-                      {
-                        type: 'redaction',
-                        text: '',
-                        rule_id: 'organization:0',
-                        remark: 's',
-                      },
-                    ],
+                0: {
```
Comment (malwilley) [inline static/app/components/events/interfaces/request/index.spec.tsx:56]: This test was in correct, should have had a 0 index here. the new logic causes it to fail (as it should in the old state)

File: static/app/components/contextData/index.tsx (hunk 1 above)
Comment (malwilley) [reply static/app/components/contextData/index.tsx:64]: I am changing this in a future PR, this is the current behavior

**Review by scefali — APPROVED** [review]
