### PR TITLE
fix: Alpha badges for Replay nav items and rename DOM tab

### LINKED ISSUE #37021: Add the 'Alpha' badge to the sidebar nav
Profiling has the badge, we should too!

Image

### LINKED ISSUE #37124: Rename "Dom" tab to "Dom Events"

### LINKED ISSUE #37144: Add the 'Alpha' badge to the "Replays" tab at the top of the Events/Issues page
We should have a little badge there to attract folks

Image

### PR DESCRIPTION
**Pull request by danecando**
### Changes
- Adds alpha badge to replays link in sidebar navigation
- Adds alpha badge to replays link in issues detail tabs
- Rename DOM tab on replay details to DOM Events

Screen Shot 2022-07-28 at 3 23 37 PM
Screen Shot 2022-07-28 at 3 23 40 PM
Screen Shot 2022-07-28 at 3 23 50 PM

Closes #37124 
Closes #37021 
Closes #37144 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by billyvg — APPROVED** [review]

File: static/app/components/sidebar/index.tsx [hunk 1]
```diff
@@ -228,6 +228,7 @@ function Sidebar({location, organization}: Props) {
         label={t('Replays')}
         to={`/organizations/${organization.slug}/replays/`}
         id="replays"
+        isAlpha
```
Comment (ryan953) [inline static/app/components/sidebar/index.tsx:231]: oh, no badge reuse :(

but that was easier!

**Review by ryan953 — APPROVED** [review]
