### PR TITLE
fix(replays): sync replay timer with shown duration

### LINKED ISSUE #68496: Mobile Replay: Video playback passed the end of the recording
Sentry Feedback: [JAVASCRIPT-2SED](https://sentry.sentry.io/feedback/?referrer=github_integration&feedbackSlug=javascript%3A5161453235&project=11276)

Video playback passed the end of the recording

https://github.com/getsentry/sentry/assets/1633368/518f025f-ea4e-4aed-b5ed-57e3f8468466

Part of:
* https://github.com/getsentry/sentry/issues/63255

### LINKED ISSUE #68509: Mobile Replay: Seeking shows Play on first half and Restart on second half
Sentry Feedback: [JAVASCRIPT-2SEE](https://sentry.sentry.io/feedback/?referrer=github_integration&feedbackSlug=javascript%3A5161549608&project=11276)

Seeking passed the half of the video changes the button from Play to Restart. Seeking within the first half goes back to Play

https://github.com/getsentry/sentry/assets/1633368/dc1767be-193a-43a3-8fd0-f7feb38ab3ee

### PR DESCRIPTION
**Pull request by michellewzhang**
This PR fixes 2 bugs related to the video replay timer:

SCR-20240416-oqes

### 1. If the replay has a gap at the end (e.g. the segment ends but for some reason the duration we get from the SDK extends beyond that), the old behavior was that the replay would just stop.

BEFORE:

https://github.com/getsentry/sentry/assets/56095982/9f76acc1-d9e6-4a15-a357-0c711da17b4a

Notice how the replay stops after 9 seconds. This is because the rest of the replay (the other 4 hours) is junk. The ideal behavior would be to have the replay play until the end, so that it doesn't look weird on the UI.

AFTER:

https://github.com/getsentry/sentry/assets/56095982/e300e349-d606-4a57-88df-3c49d612a24a

Notice how the replay keeps going after 9 seconds (even though technically there isn't any video content to display. It's just showing the previous segment)

### 2. If we seek into the gap at the end of the video, the old behavior of the video replayer was to keep running the timer infinitely. This is because the replayer wanted to run the timer until we can play the next segment (which doesn't exist in this case).

BEFORE (video trimmed because you'd be watching paint dry but i seeked to somewhere about 10s from the end):

https://github.com/getsentry/sentry/assets/56095982/67ce3e16-2ac5-4432-9bee-defd5fc61a34

Notice how the timer continues running even after the replay "ends".

The fix here is to add a notification to the timer to stop at the replay duration (passed in from `replayContext`) when we seek into a gap at the end. This lets the replayer know that we should stop searching for the next (nonexistent) segment.

AFTER (video trimmed, same seeking place):

https://github.com/getsentry/sentry/assets/56095982/d05b9f49-e4c4-4e49-98d6-49a652b65b9a

Video ends at the expected timestamp.

Fixes https://github.com/getsentry/sentry/issues/68496
Also fixes https://github.com/getsentry/sentry/issues/68509

### CODE REVIEW

File: static/app/components/replays/videoReplayer.tsx [hunk 1]
```diff
@@ -297,7 +301,12 @@ export class VideoReplayer {
 
     // No more segments
     if (nextIndex >= this._attachments.length) {
-      this.stopReplay();
+      // If we're at the end of a segment, but there's a gap
+      // at the end, force the replay to play until the end duration
+      // rather than stopping right away.
+      this._timer.addNotificationAtTime(this._duration, () => {
+        this.stopReplay();
+      });
```
Comment (billyvg) [inline static/app/components/replays/videoReplayer.tsx:309]: Is there a chance of a race condition here where by the time this notification is added, the timer is already passed duration and will continue on?

File: static/app/components/replays/replayContext.tsx [hunk 2]
```diff
@@ -495,6 +495,7 @@ function ProviderNonMemo({
           setVideoBuffering(buffering);
         },
         clipWindow,
+        duration: durationMs,
```
Comment (billyvg) [inline static/app/components/replays/replayContext.tsx:498]: Should we call this `durationMs` to be consistent?

**Review by billyvg — COMMENTED** [review]
Let's add some tests, but otherwise LGTM!

File: static/app/components/replays/videoReplayer.tsx (hunk 1 above)
Comment (michellewzhang) [reply static/app/components/replays/videoReplayer.tsx:309]: this one relates to the case where the replay stops early because we've hit a gap/the end of the segment -- the old code here was just `this.stopReplay()`. i think we might be okay here because we don't want to stop early, but rather keep playing until the end, which means we haven't hit `duration` yet

Comment (billyvg) [reply static/app/components/replays/videoReplayer.tsx]: I'm thinking about the case where we do not have a gap, and we want to stop the replay:

- segment ends -> handleSegmentEnd is called
- no next segment so this code block is called
- add notification for duration (e.g. 20)
- due to external factors (data, hardware, etc), the current time is > 20
- ?? does the callback get fired in this case?

File: static/app/components/replays/replayContext.tsx [hunk 3]
```diff
@@ -495,6 +495,7 @@ function ProviderNonMemo({
           setVideoBuffering(buffering);
         },
         clipWindow,
+        durationMs: durationMs,
```
Comment (billyvg) [inline static/app/components/replays/replayContext.tsx:498]:
```suggestion
        durationMs,
```

File: static/app/components/replays/videoReplayer.tsx (hunk 1 above)
Comment (michellewzhang) [reply static/app/components/replays/videoReplayer.tsx]: ohhh i see what you're saying! let me add another check that stops the replay if the time is over

Comment (michellewzhang) [reply static/app/components/replays/videoReplayer.tsx]: something like

```
    // No more segments
    if (nextIndex >= this._attachments.length) {
      if (this.getCurrentTime() < this._durationMs) {
        // If we're at the end of a segment, but there's a gap
        // at the end, force the replay to play until the end duration
        // rather than stopping right away.
        this._timer.addNotificationAtTime(this._durationMs, () => {
          this.stopReplay();
        });
        return;
      }
      this.stopReplay();
    }
```

File: static/app/components/replays/videoReplayer.tsx [hunk 4]
```diff
@@ -247,12 +255,16 @@ export class VideoReplayer {
...
+    // This is used when a replay is restarted
     // Add another stop notification so the timer doesn't run over
     if (this._clipDuration) {
       this._timer.addNotificationAtTime(this._clipDuration, () => {
         this.stopReplay();
       });
+    } else {
+      this._timer.addNotificationAtTime(this._durationMs, () => {
+        this.stopReplay();
+      });
```
Comment (billyvg) [inline static/app/components/replays/videoReplayer.tsx:267]: You can move the if/else logic into the addNotificationAtTime argument to save some duplication/nesting

File: static/app/components/replays/videoReplayer.tsx [hunk 5]
```diff
@@ -297,8 +309,16 @@ export class VideoReplayer {
...
     if (nextIndex >= this._attachments.length) {
+      if (this.getCurrentTime() < this._durationMs) {
+        // If we're at the end of a segment, but there's a gap
+        // at the end, force the replay to play until the end duration
+        // rather than stopping right away.
+        this._timer.addNotificationAtTime(this._durationMs, () => {
+          this.stopReplay();
+        });
+        return;
+      }
```
Comment (billyvg) [inline static/app/components/replays/videoReplayer.tsx:320]: Is this tested?

File: static/app/components/replays/videoReplayer.spec.tsx [hunk 6]
```diff
@@ -352,3 +361,115 @@ describe('VideoReplayer - with starting gap', () => {
...
+    jest.advanceTimersByTime(5000);
+    // @ts-expect-error private
+    expect(inst._isPlaying).toEqual(true);
+
+    // a long time passes
+    // ensure the timer stops at the end duration (50s)
+    jest.advanceTimersByTime(60000);
+    expect(inst.getCurrentTime()).toEqual(50000);
+    // @ts-expect-error private
+    expect(inst._isPlaying).toEqual(false);
```
Comment (michellewzhang) [inline static/app/components/replays/videoReplayer.spec.tsx:441]: @billyvg i tried to test that here

File: static/app/components/replays/videoReplayer.tsx (hunk 5 above)
Comment (michellewzhang) [reply static/app/components/replays/videoReplayer.tsx:320]: https://github.com/getsentry/sentry/pull/69074#discussion_r1569399619

**Review by billyvg — APPROVED** [review]
✨
