### PR TITLE
fix(replay): Fix event icon alignment in the `<Timeline>` so it starts at the event startTimestamp

### LINKED ISSUE #34489: Timeline scale is incorrect, icons & network span ranges appear outside the timeline and in weird spots
Example https://sentry.io/organizations/sentry/replays/replay-test:843e1a6f3c9e4af293a0ce15172ae2cd/

### PR DESCRIPTION
**Pull request by ryan953**
Fixes event alignment in the Timeline so that the position is based on the event startTimestamp, not the timestamp of the first breadcrumb.

**Before:**
the first event was placed at the very left edge:
Screen Shot 2022-05-12 at 1 49 10 AM

**After:**
events appear next to the timestamp label when they happened:
Screen Shot 2022-05-12 at 1 49 18 AM

Fixes #34489

### CODE REVIEW

**Comment by ryan953** [comment]
Current dependencies on/for this PR:
* master
  * **PR #34465** <a href="https://app.graphite.dev/github/pr/getsentry/sentry/34465" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/getsentry/sentry/34500?utm_source=stack-comment).

File: static/app/components/replays/utils.tsx [hunk 1]
```diff
@@ -102,20 +102,13 @@ export function countColumns(duration: number, width: number, minWidth: number =
  * This function groups crumbs into columns based on the number of columns available
  * and the timestamp of the crumb.
  */
-export function getCrumbsByColumn(crumbs: Crumb[], totalColumns: number) {
-  // TODO(replay): we should pass in the startTimestamp and not rely on the first breadcrumb time
```
Comment (billyvg) [inline static/app/components/replays/utils.tsx:106]: 😄

**Review by billyvg — APPROVED** [review]

File: static/app/components/replays/utils.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/components/replays/utils.tsx:106]: To-Done!
