### PR TITLE
fix(workflow): Allow Superuser invite via UI 

### LINKED ISSUE #6533: Superusers cannot invite members to teams
With the changes made to the invite form (converting to React) it no longer loads if you're not a current team member. I think this is due to the 404 on 'what is my membership'.

This is a problem, as superusers should be able to access that page (or we need to provide an alternative solution) to be able to administrate an account and invite new users.

### PR DESCRIPTION
**Pull request by MaxBittker**
fixes #6533 let superusers get themselves for member invite

EDIT: now doing this via the frontend.

### CODE REVIEW

File: src/sentry/static/sentry/app/views/inviteMember/inviteMember.jsx [hunk 1]
```diff
@@ -42,6 +70,13 @@ const InviteMember = createReactClass({
 
   componentDidMount() {
     let {slug} = this.getOrganization();
+    let {isSuperuser} = ConfigStore.get('user');
```
Comment (billyvg) [inline src/sentry/static/sentry/app/views/inviteMember/inviteMember.jsx]: I think it'd be cleaner if we handled this in the requests's error handler and just allow the request to fail so that lifecycle proceeds consistently

Comment (MaxBittker) [reply src/sentry/static/sentry/app/views/inviteMember/inviteMember.jsx]: 👍

**Review by billyvg — APPROVED** [review]
