### PR TITLE
fix(metrics): sample position with 0 series

### LINKED ISSUE #70318: Min shows all 0s and samples are in the wrong location
Image

### PR DESCRIPTION
**Pull request by obostjancic**
- fixes #70318

Before:
image

After:
image

### CODE REVIEW

File: static/app/views/metrics/chart/useMetricChartSamples.tsx [hunk 1]
```diff
@@ -40,12 +40,19 @@ function getValueRectFromSeries(series: Series[]) {
...
 
-  return {
+  const rect = {
     xMin: Math.min(...xValues),
     xMax: Math.max(...xValues),
     yMin: Math.min(0, ...yValues) / scalingFactor,
     yMax: Math.max(0, ...yValues) / scalingFactor,
   };
+
+  // happens when refenceSeries has all 0 values, commonlt seen when using min() aggregation
```
Comment (shellmayr) [inline static/app/views/metrics/chart/useMetricChartSamples.tsx:50]:
```suggestion
  // happens when refenceSeries has all 0 values, commonly seen when using min() aggregation
```

**Review by matejminar — APPROVED** [review]
sweet!
so this fixes the samples - what about the line? is it expected/correct that we have all 0s for min?

**Comment by obostjancic** [comment]
> sweet! so this fixes the samples - what about the line? is it expected/correct that we have all 0s for min?

yeah, the line is ok, we really get back all zeroes
