### PR TITLE
fix(dashboards): hide add widget card behind feature flag

### LINKED ISSUE #71641: Remove "add widget" on team plans
Custom dashboards are a Business plan feature only. On Free you don’t see any dashboards, but on Team you have a default dashboard visible. The “Add Widget” card currently appears on Team plans, but results in errors.

Example: https://qweebi.sentry.io/dashboard/default-overview/?project=4507192978636800&statsPeriod=14d

### PR DESCRIPTION
**Pull request by obostjancic**
- closes: #71641

### CODE REVIEW

File: static/app/views/dashboards/addWidget.tsx [hunk 1]
```diff
@@ -43,44 +44,46 @@ function AddWidget({onAddWidget}: Props) {
...
-        <InnerWrapper onClick={() => onAddWidget(DataSet.EVENTS)}>
-          <AddButton
-            data-test-id="widget-add"
-            icon={<IconAdd size="lg" isCircled color="inactive" />}
-            aria-label={t('Add widget')}
-          />
-        </InnerWrapper>
-      )}
-    </WidgetWrapper>
+    <Feature features={'dashboards-edit'}>
```
Comment (matejminar) [inline static/app/views/dashboards/addWidget.tsx:47]:
```suggestion
    <Feature features="dashboards-edit">
```

**Review by matejminar — APPROVED** [review]
