### PR TITLE
fix(ddm): Clicking chart hides tooltip

### LINKED ISSUE #64451: Clicking on the graph cause the number popups to disappear until the page is refreshed.

### PR DESCRIPTION
**Pull request by ArthurKnaus**
- closes https://github.com/getsentry/sentry/issues/64451

### CODE REVIEW

File: static/app/views/ddm/focusArea.tsx [hunk 1]
```diff
@@ -76,22 +76,27 @@ export function useFocusArea({
...
-      const rect = chartRef.current?.ele.getBoundingClientRect();
+    const chartElement = chartRef.current?.ele;
+    const handleMouseDown = () => {
+      isDrawingRef.current = true;
+      startBrush();
+    };
 
-      if (isInRect(event.clientX, event.clientY, rect)) {
-        startBrush();
-      }
```
Comment (ArthurKnaus) [inline static/app/views/ddm/focusArea.tsx:88]: @obostjancic it seems to work fine without this. Do you remember the reason behind this?

Comment (obostjancic) [reply static/app/views/ddm/focusArea.tsx:88]: I think there were cases around borders of the chart where clicking would activate the brush, but i could not reproduce it now.

**Review by obostjancic — APPROVED** [review]
