### PR TITLE
fix(stacktrace): Fix frame registers not aligning to grid or being truncated by ClippedBox

### LINKED ISSUE #60013: Native crash Registers layout regressed
Native crashes Registers layout seems to have regressed - [example issue](https://sentry-sdks.sentry.io/issues/4534210628). Previously they were laid out in columns to use the horizontal space better.

See below - before / now (not the same crashes):
before
now

### PR DESCRIPTION
**Pull request by malwilley**
Fixes https://github.com/getsentry/sentry/issues/60013

I believe this regression is due to the refactor of ClippedBox here: https://github.com/getsentry/sentry/pull/59524

This component was adding a lot of custom behavior to the ClippedBox component which seemed to break after the refactor. IMO those customizations did not add enough value to be worth the inconsistency and additional maintenance. 

Before:

CleanShot 2023-11-15 at 09 53 31

After:

https://github.com/getsentry/sentry/assets/10888943/34a210f9-8760-4292-ab2f-0b250e33f124

### CODE REVIEW

File: static/app/components/events/interfaces/frame/frameRegisters/index.tsx [hunk 1]
```diff
@@ -93,49 +79,6 @@ const Register = styled('div')`
...
-
-const ClipFade = styled('div')`
-  background: ${p => p.theme.background};
-  display: flex;
-  justify-content: flex-end;
-  /* Let pointer-events pass through ClipFade to visible elements underneath it */
-  pointer-events: none;
-  /* Ensure pointer-events trigger event listeners on "Expand" button */
-  > * {
-    pointer-events: auto;
```
Comment (scttcper) [inline static/app/components/events/interfaces/frame/frameRegisters/index.tsx:139]: yes

**Review by scttcper — APPROVED** [review]
