### PR TITLE
fix(replays): Fix Replay Console and Dom tabs resetting scroll position on hover

### LINKED ISSUE #9151: Can't configure Slack integration on project level
When I try to edit Slack integration configuration on project level I can see only information `No Integrations Enabled` even if this integration is enabled on Organisation level (see screenshots)
screen shot 2018-07-23 at 16 57 53

screen shot 2018-07-23 at 16 57 30

Also not that I can see only the `Install` button on already installed Slack integration.
This integration has been installed and configured before and currently, it is working ok. The only issue is that I cannot change anything related to Slack integration.

### PR DESCRIPTION
**Pull request by ryan953**
I noticed that the <Console> component was re-rendering whenever the `hoverTime` gets updated. This means all the items get re-rendered, but also re-measured, which causes scroll to be reset. DomMutations have the same problem, it's more obviously when the html snippets are different heights from each other.

So to deal with that I added `memo()` to the component, and refactored the ConsoleLogRow props so that they're much more static. (Basically moved useReplayContext into the row component). So when the `hoverTime` is updated each row will re-render, and each row has to do some repeated work, but since things are virtualized there's not that many rows displayed at at time. 

I also made some simplifications to the css inside DomMutationRow to remove an extra div and rename things.

Fixes https://github.com/getsentry/getsentry/issues/9151

### CODE REVIEW

File: static/app/views/replays/detail/domMutations/domMutationRow.tsx [hunk 1]
```diff
@@ -0,0 +1,197 @@
...
+import {getPrevReplayEvent} from 'sentry/utils/replays/getReplayEvent';
+import useCrumbHandlers from 'sentry/utils/replays/hooks/useCrumbHandlers';
+import type {Extraction} from 'sentry/utils/replays/hooks/useExtractedCrumbHtml';
+import TimestampButton from 'sentry/views/replays/detail/timestampButton';
+
+type Props = {
+  mutation: Extraction;
+  mutations: Extraction[];
+  startTimestampMs: number;
+  style: CSSProperties;
```
Comment (billyvg) [inline static/app/views/replays/detail/domMutations/domMutationRow.tsx:20]: What uses this prop? is it the virtualization?

**Review by billyvg — APPROVED** [review]
Good fix, the re-rendering from current time has been a constant nuisance to deal with

File: static/app/views/replays/detail/domMutations/domMutationRow.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/views/replays/detail/domMutations/domMutationRow.tsx:20]: yup! the virtual table sets absolute positioning on the list-items or table-cells.
