### PR TITLE
fix(github): Correct default and allow empty array to MultiSelect

### LINKED ISSUE #58851: Error with labels when trying to create a GitHub issue
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create an issue on GitHub from a Sentry issue
image

2. Make sure to leave labels empty
image

### Expected Result

No error and correct creation of an issue on GitHub

### Actual Result

image

### Product Area

Issues

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by schew2381**
We previously defaulted to an empty string for multi-select fields because the MultiSelect component would error on empty arrays. However, after testing this we actually do allow empty arrays.

The frontend + backend changes are fine deploying in either order.

### Testing with No Labels
https://github.com/getsentry/sentry/assets/67301797/2c3866b9-85f8-4828-915b-33b75a8ba724

Fixes https://github.com/getsentry/sentry/issues/58851

### CODE REVIEW

File: static/app/components/externalIssues/abstractExternalIssueForm.tsx [hunk 1]
```diff
@@ -336,9 +336,7 @@ export default class AbstractExternalIssueForm<
   ) => {
     const initialData: {[key: string]: any} = (formFields || []).reduce(
       (accumulator, field: FormField) => {
-        accumulator[field.name] =
-          // Passing an empty array breaks MultiSelect.
```
Comment (nhsiehgit) [inline static/app/components/externalIssues/abstractExternalIssueForm.tsx:340]: does passing an empty array no longer break multiselect?

**Review by nhsiehgit — APPROVED** [review]

File: static/app/components/externalIssues/abstractExternalIssueForm.tsx (hunk 1 above)
Comment (schew2381) [reply static/app/components/externalIssues/abstractExternalIssueForm.tsx:340]: Yes it works as intended 👍
