### PR TITLE
fix(settings): show success message after avatar upload

### LINKED ISSUE #54105: "Save avatar" seems like it freezes
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. go to accounts/settings, upload an avatar, hit save.
2. notice that there is no feedback that the upload was successful

https://sentry.sentry.io/replays/6bafe772745049059ab9bee197a79d18/?f_d_type=ui.slowClickDetected&query=&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=14d&t_main=dom&yAxis=count%28%29&t=317

### Expected Result

there should be an "upload succeeded" toast or something, and show that its your new avatar after uploading.

### Actual Result

the avatar settings page appears to "freeze"

### Product Area

Settings

### Link

https://sentry.sentry.io/replays/6bafe772745049059ab9bee197a79d18/?f_d_type=ui.slowClickDetected&query=&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=14d&t_main=dom&yAxis=count%28%29&t=317

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by michellewzhang**
Closes https://github.com/getsentry/sentry/issues/54105

Before:

https://github.com/getsentry/sentry/assets/56095982/a7a58c50-069d-4010-8e57-2f415585e9ef

After:

https://github.com/getsentry/sentry/assets/56095982/6451a456-b2bd-4082-81c3-5f388f309a60

### CODE REVIEW

File: static/app/components/avatarChooser.tsx [hunk 1]
```diff
@@ -105,10 +105,10 @@ class AvatarChooser extends Component<Props, State> {
   }
 
   handleSuccess(model: Model) {
+    addSuccessMessage(t('Successfully saved avatar preferences'));
     const {onSave} = this.props;
     this.setState({model});
     onSave(model);
-    addSuccessMessage(t('Successfully saved avatar preferences'));
```
Comment (billyvg) [inline static/app/components/avatarChooser.tsx:111]: That's odd... any ideas why this doesn't get hit?

Comment (michellewzhang) [reply static/app/components/avatarChooser.tsx:111]: Did some console logging, and it seems like nothing gets reached after `onSave(model);` -- possibly because it returns?

Comment (billyvg) [reply static/app/components/avatarChooser.tsx:111]: 👀 That shouldn't happen unless an exception is thrown in `onSave` -- let's pair on this a bit tomorrow?

File: static/app/utils/useColorscheme.tsx [hunk 2]
```diff
@@ -28,7 +28,7 @@ function setFaviconTheme(theme: 'dark' | 'light'): void {
 
 export function useColorscheme() {
   const {user} = useLegacyStore(ConfigStore);
-  const configuredTheme = user?.options.theme ?? 'system';
+  const configuredTheme = user?.options?.theme ?? 'light';
```
Comment (michellewzhang) [inline static/app/utils/useColorscheme.tsx:31]: Default sentry theme is light, so if the user hasn't selected a theme, should default to light.

Comment (ryan953) [reply static/app/utils/useColorscheme.tsx:31]: what about this line below: 
```
const theme = configuredTheme === 'system' ? preferredTheme : configuredTheme;
```

Comment (billyvg) [reply static/app/utils/useColorscheme.tsx:31]: Yeah I think default is to match system prefs unless overridden

File: static/app/views/settings/account/accountDetails.tsx [hunk 3]
```diff
@@ -24,10 +58,10 @@ class AccountDetails extends DeprecatedAsyncView<Props> {
     return [['user', ENDPOINT]];
   }
 
-  handleSubmitSuccess = (user: User) => {
+  handleSubmitSuccess = (user: ChangeAvatarUser) => {
     // the updateUser method updates our Config Store
     // No components listen to the ConfigStore, they just access it directly
-    updateUser(user);
+    updateUser(user as User);
```
Comment (billyvg) [inline static/app/views/settings/account/accountDetails.tsx:64]: Casting this as `User` means we are throwing away the `ChangeAvatarUser` type. This means in that `updateUser`, typescript will incorrectly allow us to access `user.options.theme` because `User` has `options` as always defined.

File: static/app/views/settings/account/accountDetails.tsx [hunk 4]
```diff
@@ -12,6 +12,23 @@ import withOrganization from 'sentry/utils/withOrganization';
 import DeprecatedAsyncView, {AsyncViewProps} from 'sentry/views/deprecatedAsyncView';
 import SettingsPageHeader from 'sentry/views/settings/components/settingsPageHeader';
 
+// The avatar endpoint ("/users/me/avatar/") returns a user type without options and other properties that are present in User
```
Comment (billyvg) [inline static/app/views/settings/account/accountDetails.tsx:15]:
```suggestion
// The avatar endpoint ("/users/me/avatar/") returns a User-like type without `options` and other properties that are present in User
```

File: static/app/actionCreators/account.tsx [hunk 5]
```diff
@@ -25,20 +26,23 @@ export async function disconnectIdentity(
...
     user.options.theme !== 'system'
   ) {
     ConfigStore.set('theme', user.options.theme);
   }
 
+  const options = {...previousUser.options, ...user.options};
+
   // Ideally we'd fire an action but this is gonna get refactored soon anyway
-  ConfigStore.set('user', user);
+  ConfigStore.set('user', {...previousUser, ...user, options});
```
Comment (billyvg) [inline static/app/actionCreators/account.tsx:45]: Maybe explain here we are merging because the avatar endpoint doesn't return a full `User`

**Review by billyvg — APPROVED** [review]

**Review by ryan953 — APPROVED** [review]
