### PR TITLE
fix(highlights): Allow custom properties on user to be highlighted

### LINKED ISSUE #71246: Missing user data from issue event
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Set a custom user data, the data is sent and also stored on Sentry (as  you can see on the actual result ) but the user interface hides the custom data.

### Expected Result

the user context to show the additional user data set by the user.

### Actual Result

https://[us.sentry.io/api/0/projects/sentry-sdks/sentry-capacitor/events/c15bc11c29a842488d8891b37416a211/json/](https://us.sentry.io/api/0/projects/sentry-sdks/sentry-capacitor/events/c15bc11c29a842488d8891b37416a211/json/)
image

https://sentry-sdks.sentry.io/issues/5061824231/events/351f306ce50c401694c2bb040b80546f/?project=5522756
image

### Product Area

Issues

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by leeandher**
Resolves https://github.com/getsentry/sentry/issues/71246

Allows custom properties on User context to be highlighted as well as displayed on the context UI. In the screenshots, `location` and `other` are custom properties.

**context on issue**
image

**highlights modal**
image

Added a bonus fix for hiding 'Add to Event Highlights' from the dropdowns in the highlights section.

image

### CODE REVIEW

File: static/app/components/events/contexts/index.tsx [hunk 1]
```diff
@@ -35,12 +35,13 @@ export interface ContextItem {
...
 export function getOrderedContextItems(event): ContextItem[] {
   const {user, contexts} = event;
+  const {data: customUserData, ...userContext} = user;
 
   const {feedback, response, ...otherContexts} = contexts ?? {};
   const orderedContext: [ContextItem['alias'], ContextValue][] = [
     ['response', response],
     ['feedback', feedback],
-    ['user', user],
+    ['user', {...userContext, ...customUserData}],
```
Comment (leeandher) [inline static/app/components/events/contexts/index.tsx:44]: Custom properties are storied on the user object under the 'data' field. We do this to flatten it and remove the `data` key.

**Review by JoshFerge — APPROVED** [review]

**Review by scttcper — APPROVED** [review]
