### PR TITLE
Fix(replays): console.error not rendering properly

### LINKED ISSUE #35701: console.error not rendering properly
See https://dev.getsentry.net:7999/organizations/sentry-emerging-tech/replays/ben-test:cd7824017b744d3b88473be9c2f72ebc/ in the Console tab.

Image

It should render the messsage and ignore `data.arguments` because there are no placeholders in message?

Image

### PR DESCRIPTION
**Pull request by jesus4497**
Now renders the messsage and ignore data.arguments when there are no placeholders in message or objects to print. Closes #35701 

Before: 
image

After:
image

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 1]
```diff
@@ -45,35 +49,45 @@ function MessageFormatter({breadcrumb}: MessageFormatterProps) {
...
 
-  // Attempt to stringify the rest of the args
-  const restArgs = args.slice(placeholders.length).map(renderString);
-
-  const formattedMessage = isMessageString
-    ? vsprintf(message.replaceAll('%c', ''), messageArgs)
-    : renderString(message);
-
-  // TODO(replays): Add better support for AnnotatedText (e.g. we use message
-  // args from breadcrumb.data.arguments and not breadcrumb.message directly)
```
Comment (billyvg) [inline static/app/views/replays/detail/console/consoleMessage.tsx:70]: Let's keep this comment

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 2]
```diff
@@ -45,35 +49,45 @@ function MessageFormatter({breadcrumb}: MessageFormatterProps) {
...
-    .filter(([placeholder]) => placeholder === '%c')
-    .map((_, i) => i);
-
-  // Retrieve message formatting args
-  const messageArgs = args.slice(0, placeholders.length);
-
-  // Filter out args that were for %c
-  for (const colorIndex of consoleColorPlaceholderIndexes) {
-    messageArgs.splice(colorIndex, 1);
+  if (placeholders.length) {
```
[the remark this answers is not in the document]
Comment (billyvg) [reply static/app/views/replays/detail/console/consoleMessage.tsx:52]: I'm not positive what's going on with the data we're using, but instead of checking placeholders length, I think a safer option would be to handle this case more specifically. Let's run this case when `breadcrumb.message !== message` (I would generally expect `breadcrumb.message` to equal `breadcrumb.data.arguments[0]` and I'm not sure why this wasn't the case here).

We should also add a comment about it.

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 3]
```diff
@@ -45,35 +49,45 @@ function MessageFormatter({breadcrumb}: MessageFormatterProps) {
...
+      ? vsprintf(message.replaceAll('%c', ''), messageArgs)
+      : renderString(message);
+
+    logMessage = [formattedMessage, ...restArgs].join(' ').trim();
+  } else {
+    // Make sure there are no objects to print in order to not get a "[Object object]"
+    const argValues: (string | number | boolean)[] = [];
+
+    for (const arg of breadcrumb.data?.arguments) {
+      if (isObject(arg) && !objectIsEmpty(arg)) {
```
Comment (billyvg) [inline static/app/views/replays/detail/console/consoleMessage.tsx:80]: We shouldn't need to do this because `renderString` should handle pretty printing objects. If it's printing `[Object object]`, then we should fix renderString to be able to print it, instead of ignoring them.

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 4]
```diff
@@ -45,35 +49,45 @@ function MessageFormatter({breadcrumb}: MessageFormatterProps) {
...
+        argValues.push(renderString(arg));
+      }
+    }
+
+    if (argValues.length) {
+      logMessage = argValues.join(' ').trim();
+    }
```
Comment (billyvg) [inline static/app/views/replays/detail/console/consoleMessage.tsx:87]: We should print `breadcrumb.message` and `argValues` (separated by spaces)

Comment (billyvg) [reply static/app/views/replays/detail/console/consoleMessage.tsx:87]: Ignore this, explanation here: https://github.com/getsentry/sentry/pull/35877/files#r903966994

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 5]
```diff
@@ -45,33 +47,45 @@ function MessageFormatter({breadcrumb}: MessageFormatterProps) {
...
+    logMessage = argValues.join(' ').trim();
+  }
 
   // TODO(replays): Add better support for AnnotatedText (e.g. we use message
   // args from breadcrumb.data.arguments and not breadcrumb.message directly)
   return (
     <AnnotatedText
       meta={getMeta(breadcrumb, 'message')}
-      value={[formattedMessage, ...restArgs].join(' ')}
+      value={logMessage || breadcrumb.message}
```
Comment (danecando) [inline static/app/views/replays/detail/console/consoleMessage.tsx:88]: I think you probably want to use ?? instead of || here since logMessage is always at least ''

Comment (danecando) [reply static/app/views/replays/detail/console/consoleMessage.tsx:88]: disregard it's the end of the day and I had the operators mixed up lol

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 6]
```diff
@@ -45,33 +47,45 @@ function MessageFormatter({breadcrumb}: MessageFormatterProps) {
...
+      : renderString(message);
 
-  const formattedMessage = isMessageString
-    ? vsprintf(message.replaceAll('%c', ''), messageArgs)
-    : renderString(message);
+    logMessage = [formattedMessage, ...restArgs].join(' ').trim();
+
+    // If there're no placeholders then we should make sure there are no objects that we want to print
+    // as the message prop do not print this objects correctly we need to handle pretty printing them
+  } else if (breadcrumb.message?.includes('[object Object]')) {
```
Comment (billyvg) [inline static/app/views/replays/detail/console/consoleMessage.tsx:77]:
```suggestion
  } else if (breadcrumb.message?.includes('[object Object]')) {
    // If the string `[object Object]` is found in message, it means the SDK attempted to stringify an object,
    // but the actual object should be captured in the arguments.
    // We can pretty print every argument that was passed to the logger instead of using
    // the SDK's serialization.
```

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 7]
```diff
@@ -45,33 +47,45 @@ function MessageFormatter({breadcrumb}: MessageFormatterProps) {
...
+    const argValues = breadcrumb.data?.arguments.map(renderString);
+
+    logMessage = argValues.join(' ').trim();
+  }
```
Comment (billyvg) [inline static/app/views/replays/detail/console/consoleMessage.tsx:82]: I would add an explicit `else` here so that we can add some more comments:

```suggestion
  } else {
    // There is a special case where `console.error()` is called with an Error object.
    // The SDK uses the Error's `message` property as the breadcrumb message, but we lose the Error type,
    // resulting in an empty object in the breadcrumb arguments. In this case, we
    // only want to use `breadcrumb.message`.
    logMessage = breadcrumb.message;
  }
  
```

Comment (billyvg) [reply static/app/views/replays/detail/console/consoleMessage.tsx:82]: Actually, now that I read the comments here, having this as the default case might not be ideal. If you add a test for `console.log(['test', 'test'])`, the SDK will serialize it to `test, test`, and in that case, we'll want to use our pretty printer instead.

File: tests/js/spec/views/replays/detail/console/messageFormatter.spec.tsx [hunk 8]
```diff
@@ -0,0 +1,87 @@
...
+      ],
+      logger: 'console',
+    },
+    level: BreadcrumbLevelType.LOG,
+    message: '%c prev state color: #9E9E9E; font-weight: bold [object Object]',
+    timestamp: '2022-06-09T00:50:25.273Z',
+  },
+];
+
+describe('MessageFormatter', () => {
```
Comment (billyvg) [inline tests/js/spec/views/replays/detail/console/messageFormatter.spec.tsx:63]: Woo, thanks for adding these tests!

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 9]
```diff
@@ -45,35 +47,56 @@ function MessageFormatter({breadcrumb}: MessageFormatterProps) {
...
+
+    const formattedMessage = isMessageString
+      ? vsprintf(message.replaceAll('%c', ''), messageArgs)
+      : renderString(message);
+
+    logMessage = [formattedMessage, ...restArgs].join(' ').trim();
+  } else if (
+    breadcrumb.message?.includes('[object Object]') ||
+    Array.isArray(message) ||
+    args.length
```
Comment (billyvg) [inline static/app/views/replays/detail/console/consoleMessage.tsx:78]: I think there's going to be too many cases to account for, instead we should make this the default case (i.e. the `else`), and try to use the else if to target the "error" case.

e.g. we could have `console.log('foo', ['test', 'test'])`

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 10]
```diff
@@ -73,25 +75,26 @@ export function MessageFormatter({breadcrumb}: MessageFormatterProps) {
...
-    args.length
+    breadcrumb.data?.arguments.length === 1 &&
+    isObject(message) &&
+    objectIsEmpty(message)
   ) {
+    // There is a special case where `console.error()` is called with an Error object.
+    // The SDK uses the Error's `message` property as the breadcrumb message, but we lose the Error type,
+    // resulting in an empty object in the breadcrumb arguments. In this case, we
+    // only want to use `breadcrumb.message`.
+    logMessage = breadcrumb.message || JSON.stringify(message);
```
Comment (billyvg) [inline static/app/views/replays/detail/console/consoleMessage.tsx:86]: In what cases do we need the `JSON.stringify()`? Is it covered in a test case?

File: tests/js/spec/views/replays/detail/console/messageFormatter.spec.tsx [hunk 11]
```diff
@@ -0,0 +1,104 @@
...
+    type: BreadcrumbType.DEBUG,
+    category: 'console',
+    data: {
+      arguments: [{}],
+      logger: 'console',
+    },
+    level: BreadcrumbLevelType.ERROR,
+    message: 'Error: this is my error message',
+    timestamp: '2022-06-22T20:00:39.958Z',
+  },
```
Comment (billyvg) [inline tests/js/spec/views/replays/detail/console/messageFormatter.spec.tsx:43]:
```suggestion
  {
    type: BreadcrumbType.DEBUG,
    category: 'console',
    data: {
      arguments: [{}],
      logger: 'console',
    },
    level: BreadcrumbLevelType.ERROR,
    message: 'Error: this is my error message',
    timestamp: '2022-06-22T20:00:39.958Z',
  },
```

Can we add a test case for `log('test', ['foo', 'bar'])`

**Review by billyvg — COMMENTED** [review]
Let's add a few more test cases, but otherwise, looks good!

File: static/app/views/replays/detail/console/consoleMessage.tsx (hunk 10 above)
Comment (jesus4497) [reply static/app/views/replays/detail/console/consoleMessage.tsx:86]: Just in case breadcrumb.message is undefined, then we can print the empty object

**Review by billyvg — APPROVED** [review]
:shipit: !
