### PR TITLE
ref(ui): Move Security & Privacy Fields to another file

### LINKED ISSUE #20878: Can't disable data scrubber
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

https://sentry.io/settings/***/projects/***/#dataScrubber links doesn't work

### What you expected to happen

I'm trying to disable scrubbing (following this article https://help.sentry.io/hc/en-us/articles/115000154594-Why-am-I-seeing-Filtered-in-my-event-data-#:~:text=If%20you%20feel%20Sentry%20is,%E2%86%92%20uncheck%20%22Data%20Scrubber%22.), but I can't find these options

### PR DESCRIPTION
**Pull request by priscilawebdev**
closes: https://github.com/getsentry/sentry/issues/20878

**Description:**
When going to general project settings and searching for data scrubbing, the user is forwarded to the anchor `#dataScrubbers` or `#dataScrubbersDefaults` as if the old settings, in General, were still there.

This removes data scrubbing Fields from `projectGeneralSettings.tsx` to the new file `/projectSecurityAndPrivacyGroups.tsx`

### CODE REVIEW

**Review by untitaker — APPROVED** [review]

File: src/sentry/static/sentry/app/data/forms/organizationSecurityAndPrivacyGroups.tsx [hunk 1]
```diff
@@ -7,7 +7,9 @@ import {
 } from 'app/utils/crashReports';
 import {JsonFormObject} from 'app/views/settings/components/forms/type';
 
-const organizationSecurityAndPrivacy: JsonFormObject[] = [
+// Export route to make these forms searchable by label/help
+export const route = '/settings/:orgId/security-and-privacy/';
```
Comment (untitaker) [inline src/sentry/static/sentry/app/data/forms/organizationSecurityAndPrivacyGroups.tsx:11]: Nice! Can we replicate this for Relay as well? (not in this PR)

Comment (priscilawebdev) [reply src/sentry/static/sentry/app/data/forms/organizationSecurityAndPrivacyGroups.tsx:11]: sure
