### PR TITLE
fix(metrics) Add support for pagination when displaying investigation rule UI

### LINKED ISSUE #57752: Do not show investigation bias if you don't have enough samples on page 2+
We can check against `transactionCursor` and `cursor` in the URL.

### PR DESCRIPTION
**Pull request by RaduW**
This PR fixes the investigation UI for the cases when the table containing the transactions is paginated.

When there is pagination and the user is on the last page it may appear that there are not enough samples ( just by looking at the last page), the fix takes in consideration the offset contained in the cursor and corrects the number of available samples.

Resolves https://github.com/getsentry/sentry/issues/57752

### CODE REVIEW

File: static/app/utils/cursor.tsx [hunk 1]
```diff
@@ -0,0 +1,26 @@
+export type CursorInfo = {
+  isPrev: boolean;
+  offset: number;
+  value: number;
+};
```
Comment (iambriccardo) [inline static/app/utils/cursor.tsx:5]: Is there the need to store all of this information? Looks like you only need the `offset`.

Comment (RaduW) [reply static/app/utils/cursor.tsx:5]: This is a generic function that parses a cursor ( that's why I put it in app/utils/cursor.tsx), hence I extract all the information in the Cursor for anybody to use.

I only use the offset, if I had it as a local util I would have only looked for the offset but I decided it is a potentially useful util (since we have cursors and pagination all over the UI, and we always seem to parse it locally).

**Review by iambriccardo — APPROVED** [review]

File: static/app/views/discover/table/tableActions.tsx [hunk 2]
```diff
@@ -12,12 +12,14 @@ import {IconDownload, IconStack, IconTag} from 'sentry/icons';
...
 import {OrganizationSummary} from 'sentry/types';
 import {trackAnalytics} from 'sentry/utils/analytics';
+import {parseCursor} from 'sentry/utils/cursor';
 import {TableData} from 'sentry/utils/discover/discoverQuery';
 import EventView from 'sentry/utils/discover/eventView';
 
 import {downloadAsCsv} from '../utils';
 
 type Props = {
+  cursor: string | undefined;
```
Comment (ArthurKnaus) [inline static/app/views/discover/table/tableActions.tsx:22]: To fix the ts errors:
```suggestion
  cursor?: string;
```

**Review by ArthurKnaus — APPROVED** [review]
Looks good to me 👍

File: static/app/views/discover/table/index.tsx [hunk 3]
```diff
@@ -204,6 +204,18 @@ class Table extends PureComponent<TableProps, TableState> {
...
+
+    const onCursorInternal = (
+      cursor: string | undefined,
+      path: string,
+      query: Query,
+      delta: number
+    ): void => {
+      cursorVal = cursor;
+      return onCursor(cursor, path, query, delta);
+    };
```
Comment (matejminar) [inline static/app/views/discover/table/index.tsx:217]: I'm not a big fan of having this handler in the render method and changing a variable. I would probably prefer if we would reuse the `isFirstPage` boolean that's above this code block. Not a blocker, your call.

Comment (RaduW) [reply static/app/views/discover/table/index.tsx:217]: Yes, re-working the code since the cursor is only set when there is a navigation done by the current user( i.e. the user presses prev/next buttons on the paginator), if the user opens a link at page 2 the cursor will not be set and the component will calculate the numSamples wrongly.
Looking how we get the cursor from the url since that is the proper place to look for it.
