### PR TITLE
fix(replays): Make sure minimum Timeline Event position is >=1 for visual alignment

### LINKED ISSUE #116: Bug: Timeline first event pushing the rest to the bottom
The first event seems to be misplaced thus pushing the rest of the events to the bottom.

Replay example: https://sentry.io/organizations/sentry-emerging-tech/replays/billy-test:5c7177578ca842f5ac699c9768d04525/

Image

### PR DESCRIPTION
**Pull request by jesus4497**
Added new condition to make sure the minimum crumb position in the timeline would be the first column.

before (This happened because the first element was being positioned at column 0): 

image

After: 
image

Fixes https://github.com/getsentry/sentry-replay/issues/116

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/components/replays/utils.tsx [hunk 1]
```diff
@@ -122,7 +122,12 @@ export function getCrumbsByColumn(
     const sinceStart = isNaN(timestampMilliSeconds)
       ? 0
       : timestampMilliSeconds - startMilliSeconds;
-    const column = Math.floor((sinceStart / safeDuration) * (totalColumns - 1)) + 1;
+
+    const columnPositionCalc =
+      Math.floor((sinceStart / safeDuration) * (totalColumns - 1)) + 1;
+
+    // Should start at minimum in the first column
+    const column = columnPositionCalc <= 0 ? 1 : columnPositionCalc;
```
Comment (ryan953) [inline static/app/components/replays/utils.tsx:130]: is this the same as using max?

```suggestion
    const column = Math.max(1, columnPositionCalc);
```

**Review by ryan953 — APPROVED** [review]
