### PR TITLE
fix(ui): Adjust sizing of page filter components to prevent overflow in more cases

### LINKED ISSUE #41932: In the grouped project selector with environment and date range filters, a long project or env name truncates the time period
Image

In the issues list, if you select a project or an environment that has a long name, the date range filter is truncated making it difficult to know which period is currently selected.

 I'm thinking since most selections will be 2-3 characters long, we could only truncate it if it is longer (which happens when a custom time range is selected).

### PR DESCRIPTION
**Pull request by malwilley**
Fixes https://github.com/getsentry/sentry/issues/41932

Before:

CleanShot 2022-12-02 at 12 01 58

CleanShot 2022-12-02 at 12 07 38

After:

CleanShot 2022-12-02 at 12 01 53

CleanShot 2022-12-02 at 12 08 26

### CODE REVIEW

File: static/app/components/organizations/pageFilterBar.tsx [hunk 1]
```diff
@@ -37,7 +37,7 @@ const PageFilterBar = styled('div')<{condensed?: boolean}>`
   }
 
   & > * {
-    min-width: 6rem;
+    min-width: 7rem;
```
Comment (malwilley) [inline static/app/components/organizations/pageFilterBar.tsx:40]: Increasing this to 7rem ensures that `24h` and other 3 character time range selections don't overflow

File: static/app/components/projectPageFilter.tsx [hunk 2]
```diff
@@ -80,7 +80,7 @@ type Props = {
 
 function ProjectPageFilter({
   specificProjectSlugs,
-  maxTitleLength = 30,
+  maxTitleLength = 25,
```
Comment (malwilley) [inline static/app/components/projectPageFilter.tsx:83]: Decreased this from 30 to 25 because it was taking up too much of the maximum `30rem` width allowed by the page filter bar.

**Review by evanpurkhiser — COMMENTED** [review]
Code looks fine. Will let @vuluongj20 take this one

**Review by vuluongj20 — APPROVED** [review]
