### PR TITLE
fix(replays): Adjust highlight timestamp of console row at hovering over them

### LINKED ISSUE #36014: Bug: Fix Console so that hovering over rows highlights the timestamp in the other components, currently this works when hovering the timestamp
If you hover over a timestamp in the Console component then the `currentHoverTime` is set and the rest of the page lights up 

Example Replay:
https://dev.getsentry.net:7999/organizations/sentry-emerging-tech/replays/ben-test:cd7824017b744d3b88473be9c2f72ebc/#console

Image

Hovered putting the cursor to the left of the timestamp doesn't have the same effect. It should.

Also it looks like the hovered time is wrong, it's probably using `less-than` somewhere, and it should be `less-than-equal`.

### LINKED ISSUE #37358: Console tab should use `button` elem to render clickable items for accessibility reasons
Looks like we've got a bunch of divs now in the Console component:

Image

The timestamp should have a button in there, because it's clickable.

### PR DESCRIPTION
**Pull request by jesus4497**
### Changes
- Fixed the type for the console component from `BreadcrumbTypeDefault` to `Crumb`
- Changed the function to get the closest crumb at hovering over a row timestamp
- Added hover and click functionality to all columns instead of just having it on the timestamp

Closes #36014 
Closes #37358 
Before: 
image

Now: 
image

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/views/replays/detail/console/index.tsx [hunk 1]
```diff
@@ -94,9 +71,9 @@ function Console({breadcrumbs, startTimestampMs = 0}: Props) {
           {filteredBreadcrumbs.map((breadcrumb, i) => {
             return (
               <ConsoleMessage
-                isActive={i >= activeConsoleBounds[0] && i <= activeConsoleBounds[1]}
+                isActive={closestUserAction?.id === breadcrumb.id}
```
Comment (jesus4497) [inline static/app/views/replays/detail/console/index.tsx:74]: > Fixing this `Crumb` thing seems like a whole separate issue. It looks like we should be [starting with ReplayReader](https://github.com/thisdot/sentry/blob/45fc69c8f7e4d4bb857f6677de769ff5a985a144/static/app/utils/replays/replayReader.tsx#L20) and working outward to fix a lot of places.
> 
> Maybe we should reduce the amount of change here to prevent extra merge conflicts with that bigger clearup

@ryan953 so I made this change because I needed the id of the breadcrumb to check when it was active - Should I look for a workaround?

Comment (ryan953) [reply static/app/views/replays/detail/console/index.tsx:74]: naw, it's all good

**Review by ryan953 — APPROVED** [review]
