### PR TITLE
fix(metrics) fix max length on small width screens

### LINKED ISSUE #75052: Visualize field and ellipisis value
On the metrics page, we decided to make the visualization field wider than it previously was to avoid an odd-looking empty space. This [PR](https://github.com/getsentry/sentry/pull/74944) introduces these changes, but on small viewports, the selected value does not display ellipses (three dots) when it overflows the space. The fix is not straightforward, as selecting another value from the dropdown causes the ellipses to disappear, possibly due to the layout calculations performed for this field in the Combobox component.

Additionally, we are using the function from [this link](https://github.com/getsentry/sentry/blob/0067c2809f76a9dc9b3885d3181cb42b909e4740/static/app/utils/string/middleEllipsis.tsx#L15) to trim very long values. This means that even if the field takes up the whole available space, it can still display with ellipses, even though it would have enough space to render the full value.

### PR DESCRIPTION
**Pull request by vgrozdanic**
Fix breaking of the metric name on smaller screens.

Closes https://github.com/getsentry/sentry/issues/75052

### CODE REVIEW

File: static/app/components/comboBox/index.tsx [hunk 1]
```diff
@@ -242,15 +242,17 @@ function ControlledComboBox<Value extends string>({
 
   // Sync input value with value prop
   const previousValue = useRef(value);
-  if (previousValue.current !== value) {
-    const selectedLabel = options
-      .flatMap(item => ('options' in item ? item.options : [item]))
-      .find(option => option.value === value)?.label;
-    if (selectedLabel) {
-      setInputValue(selectedLabel);
+  useEffect(() => {
```
Comment (obostjancic) [inline static/app/components/comboBox/index.tsx:245]: is this `useEffect` needed? I'm not very familiar with this code but I assume that we are storing value in the ref in order to avoid a re-render every time the value changes.

**Review by obostjancic — APPROVED** [review]

File: static/app/components/comboBox/index.tsx (hunk 1 above)
Comment (vgrozdanic) [reply static/app/components/comboBox/index.tsx:245]: But I have missed to remove `useRef` here, now that is fixed

File: static/app/components/metrics/mriSelect/index.tsx [hunk 2]
```diff
@@ -214,6 +216,19 @@ export const MRISelect = memo(function MRISelect({
...
+    if (breakpoints.small) {
+      // at least small size screen, no problem with fitting 100 characters
+      return 100;
+    }
+    if (breakpoints.xsmall) {
+      return 35; // at least xsmall size screen, no problem with fitting 35 characters
+    }
+
+    // screen smaller than xsmall, 22 characters is optimal
+    return 22;
```
Comment (priscilawebdev) [inline static/app/components/metrics/mriSelect/index.tsx:229]: please let's change it to '20' so the string fits for the iPhone see as well 

image

image

File: static/app/components/metrics/mriSelect/index.tsx [hunk 3]
```diff
@@ -214,6 +216,19 @@ export const MRISelect = memo(function MRISelect({
     [onChange]
   );
 
+  const maxLength = useMemo(() => {
+    if (breakpoints.small) {
+      // at least small size screen, no problem with fitting 100 characters
+      return 100;
+    }
+    if (breakpoints.xsmall) {
+      return 35; // at least xsmall size screen, no problem with fitting 35 characters
```
Comment (priscilawebdev) [inline static/app/components/metrics/mriSelect/index.tsx:225]: yes 35 looks good here :)

image

File: static/app/components/comboBox/index.tsx (hunk 1 above)
Comment (priscilawebdev) [inline static/app/components/comboBox/index.tsx:243]: did we decide to use `useEffect` because the change of the values is a side effect?

Comment (vgrozdanic) [reply static/app/components/comboBox/index.tsx:243]: Yes, value comes from `options` list, and it should be updated if that list is updated. And that list might get updated if the screen size changes

**Review by priscilawebdev — APPROVED** [review]
great work 🚀 tested the changes and it looks good to me!
