### PR TITLE
fix(replays): Fixes broken link to replays list on issue/event

### LINKED ISSUE #36155: Event Page shows broken link to Replays tab
https://sentry.io/organizations/sentry-emerging-tech/issues/3385540397/events/1933947c30e643d69e1ed411e4a6bf3a/?project=6518400

Clicking on the Replays tab takes you to this url: https://sentry.io/organizations/sentry-emerging-tech/issues/3385540397/events/1933947c30e643d69e1ed411e4a6bf3a/replays/?project=6518400 which shows a "Page not found" error.

We should make that url/page work so it shows the list of replays related.

Image

### PR DESCRIPTION
**Pull request by danecando**
### Changes
- Adds an additional route for replay list in the issue detail -> event view

Closes #36155 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/routes.tsx [hunk 1]
```diff
@@ -1346,6 +1346,16 @@ function buildRoutes() {
...
           }}
         />
+        <Route
+          path="replays/"
+          component={make(
+            () => import('sentry/views/organizationGroupDetails/groupReplays')
+          )}
+          props={{
+            currentTab: Tab.REPLAYS,
+            isEventRoute: false,
```
Comment (ryan953) [inline static/app/routes.tsx:1356]:
```suggestion
            isEventRoute: true,
```

**Review by ryan953 — APPROVED** [review]
