### PR TITLE
fix(replay): Fix some errors with replay breadcrumb rendering

### LINKED ISSUE #68570: [Replay Details] Some replay crumbs render with `[object Object]` as the description
Image

screenshot_2024-04-10_at_10 59 43

### PR DESCRIPTION
**Pull request by ryan953**
This fixes some issues with rendering replay breadcrumbs inside the details page.

Specifically:
- Don't render `[object Object]` as a description anymore, specifically Mutation & Rage Click crumbs
    321000140-d3ed57cc-3af6-4f57-bffa-a8aba5aa0bdb
    
- Remove trailing `/` from links to feedbacks & tweak margin above
    SCR-20240410-kaxt
    SCR-20240410-kilw

I've also reduced extra type narrowing and casting to streamline things a bit.

Fixes https://github.com/getsentry/sentry/issues/68570

### CODE REVIEW

**Review by c298lee — APPROVED** [review]
nice refactoring!!

File: static/app/utils/replays/getFrameDetails.tsx [hunk 1]
```diff
@@ -74,7 +76,7 @@ const MAPPER_FOR_FRAME: Record<string, (frame) => Details> = {
     color: 'red300',
     description: frame.message,
     tabKey: TabKey.ERRORS,
-    title: defaultTitle(frame),
+    title: <CrumbErrorTitle frame={frame} />,
```
Comment (ryan953) [inline static/app/utils/replays/getFrameDetails.tsx:79]: @c298lee check this out: by putting this title business up here (and the ui.click description change also in this file) we can avoid having to check the type again inside breadcrumbItem.tsx. 

If breadcrumbItem.tsx were a person it might say:  "I'm going to call getFrameDetails and just print whatever title i get"

File: static/app/utils/replays/types.tsx [hunk 2]
```diff
@@ -75,9 +75,7 @@ export function isBreadcrumbFrame(
   return Boolean(frame && 'category' in frame && frame.category !== 'issue');
 }
 
-export function isFeedbackFrame(
-  frame: ReplayFrame | undefined
-): frame is BreadcrumbFrame {
```
Comment (ryan953) [inline static/app/utils/replays/types.tsx:80]: We can be more specific than `frame is BreadcrumbFrame` to make the type narrowing string. Seems like this was a typo/copy-paste problem

File: static/app/components/replays/breadcrumbs/breadcrumbItem.tsx [hunk 3]
```diff
@@ -156,34 +142,14 @@ function BreadcrumbItem({
         ))}
 
         {isErrorFrame(frame) || isFeedbackFrame(frame) ? (
-          <CrumbErrorIssue frame={frame as ErrorFrame} />
```
Comment (ryan953) [inline static/app/components/replays/breadcrumbs/breadcrumbItem.tsx:159]: Since the code just checked that frame is one of these types, we shouldn't re-cast it again. 

using the typescript `as` keyword is a code smell.

File: static/app/components/replays/breadcrumbs/breadcrumbItem.tsx [hunk 4]
```diff
@@ -338,7 +274,6 @@ const CrumbItem = styled(PanelItem)<{isErrorFrame?: boolean}>`
 `;
 
 const CodeContainer = styled('div')`
-  margin-top: ${space(1)};
```
Comment (ryan953) [inline static/app/components/replays/breadcrumbs/breadcrumbItem.tsx:341]: I used `<Flex>` above to group the title+description, which means I can remove the margin and use `gap` instead for anything that sits below the description 👍

File: static/app/utils/replays/getFrameDetails.tsx (hunk 1 above)
Comment (c298lee) [reply static/app/utils/replays/getFrameDetails.tsx:79]: yea that's a great change :D so much cleaner now!

**Review by billyvg — APPROVED** [review]
