### PR TITLE
fix(replay): Canvas does not disappear when rewinding replay

### LINKED ISSUE #79804: Rewinding replay with canvas doesn't reset/hide canvas
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open [the replay](https://nugettrends.sentry.io/replays/3eb753ff3e294c01b784e09d1ddf4786/?event_t=1727137637449&fov=1446.5%2C999&node=txn-4d5ad4a223c04ed5bc7bee09491b2138&referrer=%2Finsights%2Fbrowser%2Fpageloads%2Foverview%2F&t_main=trace)
2. Note no canvas is visible
3. Let it play (or skip ahead with the timeline) to 10 seconds.
4. Canvas shows up
5. Click back on 1 (or 2 or 3.. ) seconds, before canvas showed up
6. Note that canvas continues to be displayed

If you reload the page at any point the canvas won't show until playback reaches the point where it's first displayed

### Expected Result

Canvas disappears at the point where it shows up in the first place

### Actual Result

Canvas is always visible once it shows up the first time

### PR DESCRIPTION
**Pull request by billyvg**
When rewinding a replay to a point in time where canvas does not exist, the player would not clear it (if it had played and rendered a canvas already). This is now fixed by identifying canvas ids that exist in the replayer but do not exist in the events before the point in time user seeks to.

Closes https://github.com/getsentry/sentry/issues/79804

### CODE REVIEW

File: static/app/components/replays/canvasReplayerPlugin.tsx [hunk 1]
```diff
@@ -314,11 +338,7 @@ export function CanvasReplayerPlugin(events: eventWithTime[]): ReplayPlugin {
         // Only do this when isSync is true, meaning there was a seek, since we
         // don't know where next index is
         nextPreloadIndex = -1;
-
-        if (isCanvas) {
-          processEventSync(e, {replayer});
-        }
-
```
Comment (billyvg) [inline static/app/components/replays/canvasReplayerPlugin.tsx:321]: Moved the isCanvas check to inside `processEventSync` so that we can trigger `debouncedProcessQueuedEvents()` as we need to know when `handleQueue` is empty as well.

File: static/app/components/replays/canvasReplayerPlugin.tsx [hunk 2]
```diff
@@ -201,8 +201,30 @@ export function CanvasReplayerPlugin(events: eventWithTime[]): ReplayPlugin {
     }
   }
 
+  // Debounce so that `processEvent` is not called immediately. We want to only
+  // process the most recent event, otherwise it will look like the canvas is
+  // animatinng when we seek throughout replay.
```
Comment (ryan953) [inline static/app/components/replays/canvasReplayerPlugin.tsx:206]:
```suggestion
  // animating when we seek throughout replay.
```

File: static/app/components/replays/canvasReplayerPlugin.tsx [hunk 3]
```diff
@@ -201,8 +201,30 @@ export function CanvasReplayerPlugin(events: eventWithTime[]): ReplayPlugin {
...
-    function () {
+    function processQueuedEvents() {
+      const canvasIds = Array.from(canvases.keys());
+      const queuedEventIds = Array.from(handleQueue.keys());
+      const queuedEventIdsSet = new Set(queuedEventIds);
+      const unusedCanvases = canvasIds.filter(id => !queuedEventIdsSet.has(id));
+
+      // Compare the canvas ids from canvas mutation events against existing
+      // canvases and remove the canvas snapshot for previously drawn to
+      // canvases that do not currently exist int his new point of time
```
Comment (ryan953) [inline static/app/components/replays/canvasReplayerPlugin.tsx:219]:
```suggestion
      // canvases that do not currently exist in this new point of time
```

**Review by ryan953 — APPROVED** [review]
