### PR TITLE
fix(feature-flags): Add Node.js support to feature flag onboarding

### LINKED ISSUE #112647: [Feature Flags] NodeJS projects are marked unsupported
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a NodeJS Project
2. Go to the `Feature Flags` page under organization settings

### Expected Result

The instruction to setup the feature flag should be shown, given that `NodeJS` is under JavaScript SDK

### Actual Result

Received **"Tracking flag evaluations is not supported for Node.js yet. It is currently available for Python and JavaScript projects through the Feature Flags SDK."** error instead

### Product Area

Settings

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by scttcper**
Node.js projects were incorrectly shown the "not supported" message on the Feature Flags page even though `@sentry/node` exports `featureFlagsIntegration`. The platform filter in `platformCategories.tsx` only matched `javascript` and `python` prefixes, missing `node`.

Adds `featureFlagOnboarding` docs for all 13 node platform variants. Uses the generic `featureFlagsIntegration` for all provider selections since the vendor-specific integrations (LaunchDarkly, OpenFeature, Statsig, Unleash) are browser-only in `@sentry/browser` - the node package only has [no-op shims](https://github.com/getsentry/sentry-javascript/tree/develop/packages/node/src/integrations/featureFlagShims) to prevent crashes in meta-frameworks like Next.js.

Fixes https://github.com/getsentry/sentry/issues/112647

### CODE REVIEW

**Comment by scttcper** [comment]
feels like it maybe wasn't documented because its missing all the integrations? I'll let the team that worked on this decide

File: static/app/components/events/featureFlags/onboarding/featureFlagOnboardingSidebar.tsx [hunk 1]
```diff
@@ -294,7 +294,7 @@ function OnboardingContent({currentProject}: {currentProject: Project}) {
     <Fragment>
       <div>
         {tct(
-          'Tracking flag evaluations is not supported for [platform] yet. It is currently available for Python and JavaScript projects through the Feature Flags SDK. You can [link:read the docs] to learn more.',
+          'Tracking flag evaluations is not supported for [platform] yet. It is currently available for Python, JavaScript, and Node.js projects through the Feature Flags SDK. You can [link:read the docs] to learn more.',
```
Comment (chargome) [inline static/app/components/events/featureFlags/onboarding/featureFlagOnboardingSidebar.tsx:297]: L: Would leave the wording as is as this covers all runtimes then.

**Review by chargome — APPROVED** [review]
LGTM! Theoretically the generic `featureFlagsIntegration` also works in Bun and in Deno
