### PR TITLE
fix(replay): Remove browser from table if all mobile replays

### LINKED ISSUE #74747: [Mobile Replay] Issue Detail Tab: Browser showing as `null null` with `<>` icon.
Image

For mobile projects we should hide the browser tab. Similar to how we did for the Replay Index.

Image

Example:

https://sentry-sdks.sentry.io/issues/5607602092/replays/?project=4507596011798528&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&selected_replay_index=0&statsPeriod=30d&stream_index=0

### PR DESCRIPTION
**Pull request by c298lee**
Fixes https://github.com/getsentry/sentry/issues/74747

### CODE REVIEW

**Review by ryan953 — APPROVED** [review]

File: static/app/views/issueDetails/groupReplays/groupReplays.tsx [hunk 1]
```diff
@@ -80,7 +88,7 @@ function GroupReplays({group}: Props) {
           isFetching={isFetching}
           replays={[]}
           sort={undefined}
-          visibleColumns={VISIBLE_COLUMNS}
+          visibleColumns={allMobileProj ? VISIBLE_COLUMNS_MOBILE : VISIBLE_COLUMNS}
```
Comment (michellewzhang) [inline static/app/views/issueDetails/groupReplays/groupReplays.tsx:91]: this ternary seems to be used a lot throughout this file, can we make it a constant up top?

File: static/app/views/issueDetails/groupReplays/groupReplays.tsx [hunk 2]
```diff
@@ -52,6 +62,7 @@ function GroupReplays({group}: Props) {
     location,
     organization,
   });
+  const {allMobileProj} = useAllMobileProj();
```
Comment (michellewzhang) [inline static/app/views/issueDetails/groupReplays/groupReplays.tsx:65]: oo sorry, i meant, can we move the `visibleColumns` definition to under here so that we don't need a function? (we don't need to pass in `allMobileProj` then, can just case directly on `allMobileProj`

Comment (michellewzhang) [reply static/app/views/issueDetails/groupReplays/groupReplays.tsx:65]: actually, what do you think is better🤔 because i see with that method we'd have to define the const twice

Comment (c298lee) [reply static/app/views/issueDetails/groupReplays/groupReplays.tsx:65]: there's three functional components using `VISIBLE_COLUMNS` in this file so I don't think we can do it without a function :(

**Review by michellewzhang — APPROVED** [review]
