### PR TITLE
fix(insights): Fix padding around small charts on domain landing pages

### LINKED ISSUE #82459: Widget error states on Performance landing pages have bad padding
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the Performance landing page for an of the domains
2. Set the time range to 90 days
3. Pick a project with a lot of data

The goal is to get the queries to time out.

### Expected Result

The little 3-row widgets have a nice error state.

### Actual Result

The 3-row widgets have gross padding that bumps the icon against the edges!Image

### Product Area

Performance

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by gggritso**
In a column flexbox context, the `height` of the `ErrorPanel` doesn't do
anything. We need to make sure it has a _minimum_ height.

Closes https://github.com/getsentry/sentry/issues/82459

**Before:**
Screenshot 2025-02-24 at 4 29 37 PM

**After:**
Screenshot 2025-02-24 at 4 31 13 PM

### CODE REVIEW

File: static/app/views/performance/landing/widgets/components/performanceWidget.tsx [hunk 1]
```diff
@@ -176,9 +176,12 @@ export function DataDisplay<T extends WidgetDataConstraint>(
 
 function DefaultErrorComponent(props: {height: number}) {
   return (
-    <ErrorPanel data-test-id="widget-state-is-errored" height={`${props.height}px`}>
+    <ErrorPanelWithMinHeight
+      data-test-id="widget-state-is-errored"
+      height={`${props.height}px`}
```
Comment (JonasBa) [inline static/app/views/performance/landing/widgets/components/performanceWidget.tsx:181]:
```suggestion
      minHeight={`${props.height}px`}
```

File: static/app/views/performance/landing/widgets/components/performanceWidget.tsx [hunk 2]
```diff
@@ -189,6 +192,10 @@ const defaultGrid = {
   bottom: space(1),
 };
 
+const ErrorPanelWithMinHeight = styled(ErrorPanel)<{height: string}>`
+  min-height: ${p => p.height};
```
Comment (JonasBa) [inline static/app/views/performance/landing/widgets/components/performanceWidget.tsx:196]:
```suggestion
  min-height: ${p => p.minHeight};
```

File: static/app/views/performance/landing/widgets/components/performanceWidget.tsx [hunk 3]
```diff
@@ -189,6 +192,10 @@ const defaultGrid = {
   bottom: space(1),
 };
 
+const ErrorPanelWithMinHeight = styled(ErrorPanel)<{height: string}>`
```
Comment (JonasBa) [inline static/app/views/performance/landing/widgets/components/performanceWidget.tsx:195]:
```suggestion
const ErrorPanelWithMinHeight = styled(ErrorPanel)<{minHeight: string}>`
```

File: static/app/views/performance/landing/widgets/components/performanceWidget.tsx [hunk 4]
```diff
@@ -176,9 +176,12 @@ export function DataDisplay<T extends WidgetDataConstraint>(
 
 function DefaultErrorComponent(props: {height: number}) {
```
Comment (JonasBa) [inline static/app/views/performance/landing/widgets/components/performanceWidget.tsx:177]:
```suggestion
function DefaultErrorComponent(props: {minHeight: number}) {
```

File: static/app/views/performance/landing/widgets/components/performanceWidget.tsx (hunk 2 above)
Comment (JonasBa) [reply static/app/views/performance/landing/widgets/components/performanceWidget.tsx:196]: Nit, but it might make sense to convert to px here and keep that value closer to CSS.

**Review by JonasBa — APPROVED** [review]
Non blocking comment on naming 🚢
