### PR TITLE
bug(replays): Fix loading and paging through the Issues>Replays tab

### LINKED ISSUE #41836: Permissions Error on issues replays tab
- when loading the replays tab, we hit the endpoint `https://sentry.io/api/0/organizations/{org_slug}/events`. if the org isn't on a business plan, the endpoint returns a 400 `{"detail":"You cannot view events from multiple projects."}`.

for whatever reason, if you refresh the page, the query then works.

### PR DESCRIPTION
**Pull request by ryan953**
Basically a few things are happening:
1. Call `useLocation` less often
  Because sometimes we're going to pass in our own value instead of using the real location.

2. Don't fetch replayIds inside static/app/views/organizationGroupDetails/groupDetails.tsx anymore.
  We used to do it in here because there was some code-sharing between the count that appears in the tab, and the list contents. That's fixed now -> the tab loads it's own count now. Now we can delegate fetching data only when the specific tab is open, and drop the `this.getCurrentTab() === Tab.REPLAYS` checks. (which had issues)

3. `<GroupReplays>` now has a new child: `<GroupReplaysTable>`
  Its is mostly there so I can do `return null` in the parent and conditionally call `useReplayList()` in the child
  All the replayIds fetching logic that was previously inside groupDetails.tsx is moved, and improved, into `<GroupReplays>`
   

**Test Plan:**
1. Visit the Issues>Replay tab
2. Click from another Issues tab into Replays tab
3. Click from All Events (page 2 or beyond) into Replays tab

- Notice the tab loads
- No flash & re-fetching/re-render of content
- Pagination works

Fixes #39464
Fixes #41836

### CODE REVIEW

File: static/app/utils/useCleanQueryParamsOnRouteLeave.tsx [hunk 1]
```diff
@@ -0,0 +1,50 @@
+import {useCallback, useEffect} from 'react';
```
Comment (ryan953) [inline static/app/utils/useCleanQueryParamsOnRouteLeave.tsx:1]: This file will be added first in #41719

File: static/app/components/replays/useReplaysCount.tsx [hunk 2]
```diff
@@ -57,18 +56,15 @@ function useReplaysCount({groupIds, transactionNames, organization, project}: Op
...
-          name: `Errors within replay`,
-          version: 2,
-          fields: ['count_unique(replayId)', String(fieldName)],
-          query: `!replayId:"" ${condition}`,
-          projects: [],
-        },
-        location
-      ),
-    [location, condition, fieldName]
+      EventView.fromSavedQuery({
```
Comment (JoshFerge) [inline static/app/components/replays/useReplaysCount.tsx:59]: do these queries take into account the current statsPeriod selected?

File: static/app/components/replays/useReplaysCount.tsx [hunk 3]
```diff
@@ -57,18 +56,15 @@ function useReplaysCount({groupIds, transactionNames, organization, project}: Op
...
+        id: '',
+        name: `Errors within replay`,
+        version: 2,
+        fields: ['count_unique(replayId)', String(fieldName)],
+        query: `!replayId:"" ${condition}`,
+        projects: [Number(project?.id)],
```
Comment (billyvg) [inline static/app/components/replays/useReplaysCount.tsx:65]: Is it actually possible that project is null?

**Review by billyvg — APPROVED** [review]
