### PR TITLE
ref(replay): redirect based on referrer after replay deletion

### LINKED ISSUE #62831: Bug: After deleting a replay send the user back to `/replay` or `/issues/:id/replays`, depending on how they got to the details page
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. We get an option to delete the replay on the replay detail page. 
But it should be "Archive Replay" instead of "Delete Replay".
image

2. And on the Replay listing page, once the replay is deleted(archived in action), it says Deleted replay and still remains present in the list. It should be removed from the list, and we should have some filters or tabs as we have in issues which will list the archived replays. 
3. Also, it says Deleted Replay but it should be Archived Replay.
image

4. Replay opened from an issue -> deleted the replay -> user is redirected to /replays instead of  /issues/:id/replays/

### Expected Result

^

### Actual Result

^

### Product Area

Replays

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by michellewzhang**
closes https://github.com/getsentry/sentry/issues/62831

now, when a replay is deleted from replay details, redirect the user back to either the replay list or the issues replay tab, depending on where they came from before.

BEFORE: issues replay tab -> replay details -> delete replay -> replay list

https://github.com/user-attachments/assets/35dfbe79-04f5-4b43-ae04-94162a71001f

AFTER: issues (either event or replay tab) -> replay details -> delete replay -> back to issues replay tab

https://github.com/user-attachments/assets/c0867a1a-fa35-42ae-adfb-fb8ecced7642

https://github.com/user-attachments/assets/4372792f-2454-4914-a0f1-7837a1550e57

AFTER: replay list -> replay details -> delete replay -> replay list (same behavior as before)

https://github.com/user-attachments/assets/04020f62-086c-4295-8bf2-0e0667b21d2e

### CODE REVIEW

File: static/app/utils/replays/hooks/useDeleteReplay.tsx [hunk 1]
```diff
@@ -19,6 +19,11 @@ export default function useDeleteReplay({projectSlug, replayId}: DeleteButtonPro
   const navigate = useNavigate();
   const organization = useOrganization();
 
+  const queryParams = new URLSearchParams(location.search);
+  const referrer = queryParams.get('referrer');
+  const groupId = queryParams.get('groupId');
```
Comment (billyvg) [inline static/app/utils/replays/hooks/useDeleteReplay.tsx:24]: Should we use `useLocationQuery`?

**Review by billyvg — APPROVED** [review]

File: static/app/utils/replays/hooks/useDeleteReplay.tsx [hunk 2]
```diff
@@ -19,6 +19,11 @@ export default function useDeleteReplay({projectSlug, replayId}: DeleteButtonPro
...
+  const issueReferrer = !!referrer?.includes('issues');
```
Comment (aliu39) [inline static/app/utils/replays/hooks/useDeleteReplay.tsx:25]:
```suggestion
  const issueReferrer = Boolean(referrer?.includes('issues') && groupId)
```
To be extra sure groupId is non-empty below
