### PR TITLE
ref(replay): delete rage click banner on index

### LINKED ISSUE #90599: Replay: Wrong banner being displayed
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This banner is relevant for the Web SDK only (the version listed is of the JS SDK)
but shows for .NET:

Image

### Expected Result

see https://sentry-sdks.sentry.io/explore/replays/?project=5428537&query=&statsPeriod=14d&yAxis=count%28%29

### Actual Result

useless theme

### Product Area

Unknown

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by michellewzhang**
closes https://github.com/getsentry/sentry/issues/90599

the rage click banner is pretty old (around 2 years old). also, the SDK version in the banner is only relevant for JS platforms. seems like a good time to remove it altogether.

### CODE REVIEW

File: static/app/views/replays/list/listContent.tsx [hunk 1]
```diff
@@ -67,14 +68,14 @@ export default function ListContent() {
...
-  if (rageClicksSdkVersion.needsUpdate && !allMobileProj) {
+  // not eligible for dead/rage clicks
+  if (rageClicksSdkVersion.needsUpdate || allMobileProj) {
     return (
       <Fragment>
         <FiltersContainer>
           <ReplaysFilters />
           <ReplaysSearch />
         </FiltersContainer>
-        <ReplayRageClickSdkVersionBanner />
```
Comment (billyvg) [inline static/app/views/replays/list/listContent.tsx:77]: So no more of this? In what conditions is `rageClicksSdkVersion.needsUpdate` == true?

Comment (michellewzhang) [reply static/app/views/replays/list/listContent.tsx:77]: if the JS sdk is not update to date enough for rage click detection for example -- this value is fetched from a hook

**Review by billyvg — APPROVED** [review]

**Review by bruno-garcia — APPROVED** [review]
