### PR TITLE
fix: Display Nintendo Switch Logo on issue details page

### LINKED ISSUE #95514: Nintendo Switch Logo not showing up after OS name was renamed
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Nintendo recently renamed how they report the `os.name` of events. From `Nintendo` to `Nintendo OS`.
Now events coming from the Nintendo integration (as well as SDKs that have also corrected the OS name) no longer show the correct logo.

Before, the logo showed up next to `Device`, but that has changed too and no logo appears there:

Before:

Image

After:

Image

### Expected Result

Show the Nintendo Switch logo (next to device or OS) logo somewhere in the event. Wherever we today show a generic **N**

### Actual Result

A generic **N** logo at the top of the screen like in the new issues layout:

Image

### Product Area

Issues

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by priscilawebdev**
We no longer want to display the generic "N".

I didn’t remove switch-2 yet, since we might still update the code to use it. I'm just waiting to find out how to check for it.

closes https://github.com/getsentry/sentry/issues/95514

### CODE REVIEW

File: static/app/components/events/contexts/contextIcon.tsx [hunk 1]
```diff
@@ -27,7 +27,6 @@ import logoMonogorilla from 'sentry-logos/logo-monogorilla.svg';
 import logoMotorola from 'sentry-logos/logo-motorola.svg';
 import logoNetcore from 'sentry-logos/logo-netcore.svg';
 import logoNetframework from 'sentry-logos/logo-netframework.svg';
-import logoNintendo from 'sentry-logos/logo-nintendo.svg';
 import logoNintendoSwitch from 'sentry-logos/logo-nintendo-switch.svg';
 import logoNintendoSwitch2 from 'sentry-logos/logo-nintendo-switch-2.svg';
```
Comment (vgrozdanic) [inline static/app/components/events/contexts/contextIcon.tsx:31]: this is removed in a separate PR, right?

**Review by vgrozdanic — APPROVED** [review]

File: static/app/components/events/contexts/contextIcon.tsx (hunk 1 above)
Comment (priscilawebdev) [reply static/app/components/events/contexts/contextIcon.tsx:31]: no. I did it all together here, why?

Comment (vgrozdanic) [reply static/app/components/events/contexts/contextIcon.tsx:31]: Since we are removing switch 2 to avoid confusion, are we keeping `logoNintendoSwitch2` or should we also remove it?

Comment (priscilawebdev) [reply static/app/components/events/contexts/contextIcon.tsx:31]: based on the changes in this PR, it should be removed too, but I am waiting for something before doing that as we might still use it. There is a note about this in the description 😉

Comment (vgrozdanic) [reply static/app/components/events/contexts/contextIcon.tsx:31]: sorry, missed it :/

Comment (priscilawebdev) [reply static/app/components/events/contexts/contextIcon.tsx:31]: no problem :)
