### PR TITLE
bug(replay): Fix useAggregatedQueryKeys (& useReplayCount) to support multiple hook instances

### LINKED ISSUE #62237: Replay: count_errors greater than 0 shows a Replay with 0 error
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This is happening for a customer Org. Details in Slack. 

### Expected Result

We should only see Replays that have at least 1 error associated and not Replays that have 0 errors in them

### Actual Result

We are seeing a Replay event with 0 Errors in it. 
Screenshot 2023-12-21 at 2 27 06 PM

### Product Area

Replays

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### LINKED ISSUE #62617: Replay count stuck loading when no records returned
From Scrott C:

> the replay count badge seems to get stuck loading when there's zero replays. 

image

The API response format didn't change so might be related to changes on the frontend.

### PR DESCRIPTION
**Pull request by ryan953**
Previously the each `useAggregatedQueryKeys()` wasn't built correctly, it didnt' handle cases where there are multiple instances of the hook on the page.
Before what happened was:
- You'd call buffer() against one hook instance.
- The hook would setup it own timeout
    - There could be N hooks with timeouts running now
- Eventually one one of the instances would fire off a request
    - The other instances would have their timeouts fire too, but there is no work to do because everything is `inFlight`
- The instance that sent the request will get the response too, and can update it's own state.
    - **The Problem** is that all the other instances don't get to update state, there's no signal sent to them. The queryCache has everything, it's waiting.

So this change brings in a `cache.subscribe` call, so each instance can listen to changes and update it's own state when requests are being resolved. 
To support that each instance directly tracks the params that have been sent into it's instance of `buffer()`, so we know what we're expected to be returning. This is the `prevQueryKeys` ref.

Along the way I wrote some tests and fixed some bugs. For example, now when a new hook instance is created it'll look at the cache and read anything that's already existing.

Also fixed the bug with `useReplayCount`, before if a count wasn't returned in the response, we assumed it to be zero. Now we have that behavior back. You'll see the value as `undefined` until the _next_ (not guaranteed to be the _correct_, but with the buffering it's a good chance) `/replay-count/` fetch calls returns.

I also did some manual testing just by visiting pages like `sentry.io/issues/` and seeing that most issues have some kind of replay count icon appearing again.

Fixes https://github.com/getsentry/sentry/issues/62617
Fixes https://github.com/getsentry/sentry/issues/62237
Related to https://github.com/getsentry/sentry/pull/62530

### CODE REVIEW

File: static/app/components/replays/replayCountBadge.tsx [hunk 1]
```diff
@@ -2,9 +2,6 @@ import Badge from 'sentry/components/badge';
 
 function ReplayCountBadge({count}: {count: undefined | number}) {
   const display = count && count > 50 ? '50+' : count ?? null;
-  if (display === null) {
-    return null;
-  }
```
Comment (ryan953) [inline static/app/components/replays/replayCountBadge.tsx:7]: We shouldn't need this check anymore with the correct data fetching happening. 

The hooks will return `undefined` when data is still loading

**Review by malwilley — APPROVED** [review]
Great tests!
