### PR TITLE
fix(replays): default mask/block setting in project creation should be true

### LINKED ISSUE #68688: default mask/block setting for replay in project creation should be true
Hey team, when we create a new JS project and are presented with the code to paste into our app, we have masking turned off for the replay integration. However, in the docs this option is set to true (and the default value for this option is true as well). We received feedback from a customer about this, and they want the option to be set to true upon project creation, so that their other org users will not create new projects that transfer PII. Can we change the code we show upon project creation so that it’s the same as the docs?
Here’s their feedback:

```We would like to enforce masking in replays for every app so that the app does not have to possibility to turn off masking. Is this possible? Also on a side-note, you are pretty clear about using masking in your documentation, but when I create an new app, the config comes with masking off. Shouldn't this be default true instead of default false?```

### PR DESCRIPTION
**Pull request by michellewzhang**
fixes https://github.com/getsentry/sentry/issues/68688

for project creation, pass in a default `replayOptions` param since one isn't set:

SCR-20240411-hwpk

### CODE REVIEW

File: static/app/gettingStartedDocs/javascript/javascript.tsx [hunk 1]
```diff
@@ -46,7 +46,7 @@ ${getFeedbackConfigOptions(params.feedbackOptions)}}),`
   }${
     params.isReplaySelected
       ? `
-        Sentry.replayIntegration(${getReplayConfigOptions(params.replayOptions)}),`
+        Sentry.replayIntegration(${getReplayConfigOptions(params.replayOptions ?? {block: true, mask: true})}),`
```
Comment (ArthurKnaus) [inline static/app/gettingStartedDocs/javascript/javascript.tsx:49]: I would rather pass it in `https://github.com/getsentry/sentry/blob/master/static/app/components/onboarding/gettingStartedDoc/onboardingLayout.tsx`, then it is done at a central point for all platforms during creation.

Comment (michellewzhang) [reply static/app/gettingStartedDocs/javascript/javascript.tsx]: good catch @ArthurKnaus! fixed

**Review by ArthurKnaus — APPROVED** [review]
