### PR TITLE
fix(replays): Fix a case where no replay_ids are found in useReplaysFromIssue

### LINKED ISSUE #45692: Bug for Session Replay: Infinite Loading Spinner on Issue Details > Replays tab
**Problem:**

There have been multiple reports that there is an infinite loading spinner when viewing the Replays tab in Issue Details. 

For the reports, they've happened when Replays tab count == 0.

- [Example for Sentry org
](https://testorg-az.sentry.io/issues/3988198587/replays/?project=6300031&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d)

**Solution:**
The Replays tab should state there are no replays available for this project. 

**Technical Solution:**
TBD

### PR DESCRIPTION
**Pull request by ryan953**
Fixes #45692

### CODE REVIEW

File: static/app/views/issueDetails/groupReplays/useReplaysFromIssue.tsx [hunk 1]
```diff
@@ -45,7 +45,7 @@ function useReplayFromIssue({
   }, [api, organization.slug, group.id, group.project.id]);
 
   const eventView = useMemo(() => {
-    if (!replayIds.length) {
+    if (!replayIds) {
```
Comment (ryan953) [inline static/app/views/issueDetails/groupReplays/useReplaysFromIssue.tsx:48]: This was an important check.

Before we had no way to differentiate between 'the fetch hasn't happened yet' and 'the fetched returned no replayIds' because we used `[]` for both cases.

Now we have `undefined` for the former, and `[]` for the latter.

**Review by JoshFerge — APPROVED** [review]
