### PR TITLE
fix(stat-detectors): Update span anlaysis table 

### LINKED ISSUE #58761: Update Span Analysis table for new API response
update span analysis table columns to use single column to describe changes in state
* spans per minute (before -> after)
* p95 (before -> after)

### PR DESCRIPTION
**Pull request by narsaynorath**
* Updates to account for new endpoint response
* uses built in field renderers
* Renders each change in the same column

When we would render a change of 0% (due to rounding), I made the change show as a single value with "No significant change". I wasn't sure if I should do the same with newly added spans because it felt a little unclear to just have a number with "New" next to it, although I'm willing to go either way.

Screenshot 2023-10-25 at 3 17 40 PM

Closes #58761

### CODE REVIEW

File: static/app/components/events/eventStatisticalDetector/aggregateSpanDiff.tsx [hunk 1]
```diff
@@ -84,39 +86,76 @@ function useFetchAdvancedAnalysis({
...
 
+function NumericChange({
+  columnKey,
+  beforeRawValue,
+  afterRawValue,
+}: {
+  afterRawValue: number;
+  beforeRawValue: number;
+  columnKey: string;
+  isDuration?: boolean;
```
Comment (Zylphrex) [inline static/app/components/events/eventStatisticalDetector/aggregateSpanDiff.tsx:115]: This seems unused.

**Review by Zylphrex — APPROVED** [review]
