### PR TITLE
fix(replays): Truncate the middle UrlWalker segment when it is not a summary

### LINKED ISSUE #38108: UrlWalker should truncate all three sections when the middle section is a url and not a summary (summaries are never truncated)
In this example all three sections should be truncated to be the same length:

Image

### LINKED ISSUE #38328: UrlWalker emits "Two children with the same key, `0`.`" error

### PR DESCRIPTION
**Pull request by ryan953**
Fixes #38328
Fixes #38108

### CODE REVIEW

File: static/app/components/replays/walker/splitCrumbs.tsx [hunk 1]
```diff
@@ -103,9 +103,9 @@ function SummarySegment({
 }) {
   const {handleMouseEnter, handleMouseLeave} = useCrumbHandlers(startTimestampMs);
 
-  const summaryItems = crumbs.map(crumb => (
+  const summaryItems = crumbs.map((crumb, i) => (
     <BreadcrumbItem
-      key={crumb.id}
+      key={crumb.id || i}
```
Comment (ryan953) [inline static/app/components/replays/walker/splitCrumbs.tsx:108]: on the index page the navigation crumbs that we use here are not fully hydrated. We've just turned the list of urls into crumbs for display reasons
(see https://github.com/getsentry/sentry/blob/master/static/app/components/replays/walker/urlWalker.tsx#L65-L77)

So react was spewing "Two children with the same key, 0" errors because that 0 is hard-coded. Array index isn't 100% perfect, there are linters out there who will warn, but it's fine here.

File: static/app/components/replays/walker/chevronDividedList.tsx [hunk 2]
```diff
@@ -36,9 +36,11 @@ const List = styled('ul')<{cols: number}>`
...
   gap: ${space(1)};
   grid-template-columns: ${p =>
-    `minmax(auto, max-content) repeat(${
-      (p.cols - 2) * 2 + 1
-    }, max-content) minmax(auto, max-content)`};
+    p.cols <= 3
+      ? `minmax(auto, max-content) max-content minmax(auto, max-content) max-content minmax(auto, max-content)`
+      : `minmax(auto, max-content) repeat(${
+          (p.cols - 2) * 2 + 1
+        }, max-content) minmax(auto, max-content)`};
```
Comment (ryan953) [inline static/app/components/replays/walker/chevronDividedList.tsx:43]: in the <=3 case we're defining 5 columns: `$content divider $content divider $content` and we will use either 1, 3, or all of those columns to render

In the previous case, we are more specific, it's always 5 columns, but the middle isn't going to truncate.

File: static/app/components/replays/walker/chevronDividedList.tsx [hunk 3]
```diff
@@ -36,9 +36,9 @@ const List = styled('ul')<{cols: number}>`
   display: grid;
   gap: ${space(1)};
   grid-template-columns: ${p =>
-    `minmax(auto, max-content) repeat(${
-      (p.cols - 2) * 2 + 1
-    }, max-content) minmax(auto, max-content)`};
+    p.cols <= 3
+      ? `minmax(auto, max-content) max-content minmax(auto, max-content) max-content minmax(auto, max-content)`
+      : `minmax(auto, max-content) repeat(3, max-content) minmax(auto, max-content)`};
```
Comment (ryan953) [inline static/app/components/replays/walker/chevronDividedList.tsx:41]: in the <=3 case we're defining 5 columns: $content divider $content divider $content and we will use either 1, 3, or all of those columns to render

In the previous case, we are more specific, it's always 5 columns (3 content, 2 dividers), and the middle section isn't going to truncate.
This change means the component only works with up to 3 content columns max now.

**Review by billyvg — APPROVED** [review]
