### PR TITLE
fix(project-create): Improve project creation UX

### LINKED ISSUE #53791: Project creation confusing UX around custom alert
the custom alert placeholder text would make you think you can submit the form, but you have to fill in a value. we should either make the placeholder text an actual value, or provide a validation message when the form is attempted to be submitted. 

Context:
https://sentry.sentry.io/replays/908d64ebc1014edeb98a6469ad8b5b6c/?f_d_type=ui.slowClickDetected&query=&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=14d&t_main=dom&yAxis=count%28%29&t=16
Screenshot 2023-07-28 at 11 59 56 AM

```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by ArthurKnaus**
Add default value to the alert threshold field.
Add descriptive tooltip to disabled submit button.

Fixes #53791

### CODE REVIEW

File: static/app/views/projectInstall/issueAlertOptions.tsx [hunk 1]
```diff
@@ -46,8 +46,6 @@ const METRIC_CONDITION_MAP = {
   [MetricValues.USERS]: UNIQUE_USER_FREQUENCY_CONDITION,
 } as const;
 
-const DEFAULT_PLACEHOLDER_VALUE = '10';
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/issueAlertOptions.tsx:49]: since this is a string and it is being used in 2x different places, shouldn't we keep it in a constant so it is easier to update if we want to change this value?

File: static/app/views/projectInstall/createProject.spec.tsx [hunk 2]
```diff
@@ -490,29 +490,30 @@ describe('CreateProject', function () {
     it('should enabled the submit button if and only if all the required information has been filled', async function () {
       render(<CreateProject />);
 
-      const createProjectButton = screen.getByRole('button', {name: 'Create Project'});
+      // We need to query for the submit button every time we want to access it
+      // as re-renders can create new DOM nodes
+      const getSubmitButton = () => screen.getByRole('button', {name: 'Create Project'});
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/createProject.spec.tsx:495]: great note 👍

File: static/app/views/projectInstall/createProject.tsx [hunk 3]
```diff
@@ -358,14 +359,19 @@ function CreateProject() {
...
         )}
         <div>
-          <Button
-            type="submit"
-            data-test-id="create-project"
-            priority="primary"
-            disabled={!canSubmitForm}
+          <Tooltip
+            title={t('Please provide a project name')}
+            disabled={Boolean(canSubmitForm)}
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/createProject.tsx:364]: it is fine to use `Boolean` but usually we use `!`

File: static/app/views/projectInstall/createProject.tsx [hunk 4]
```diff
@@ -358,14 +359,19 @@ function CreateProject() {
           </div>
         )}
         <div>
-          <Button
-            type="submit"
-            data-test-id="create-project"
-            priority="primary"
-            disabled={!canSubmitForm}
+          <Tooltip
+            title={t('Please provide a project name')}
```
[the remark this answers is not in the document]
Comment (priscilawebdev) [reply static/app/views/projectInstall/createProject.tsx:363]: I think sometimes the team field can be empty and the user has to select a value, but we need to double check it

File: static/app/views/projectInstall/issueAlertOptions.tsx (hunk 1 above)
Comment (ArthurKnaus) [reply static/app/views/projectInstall/issueAlertOptions.tsx:49]: hmm, my thinking was that default value and placeholder are not necessarily the same value + it is not critical that they are the same.
e.g. we may want to have a placeholder text like "Enter a number..." in the future
That's why I hardcoded the values to improve readability. 🤔

**Comment by priscilawebdev** [comment]
a project cannot be created if other required fields are empty 

https://github.com/getsentry/sentry/assets/29228205/96f4901f-f965-4143-a27e-f5937ba95445

File: static/app/views/projectInstall/createProject.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (ArthurKnaus) [reply static/app/views/projectInstall/createProject.tsx:363]: hmm, you are right, thx 👍 
For now, I would just handle the missing project name and alert threshold.
From what I can see the team select can only be empty if all teams in the account were deleted (no options available).
I think that this case can be neglected for now by just not showing a tooltip.

[the remark this answers is not in the document]
Comment (ArthurKnaus) [reply static/app/views/projectInstall/createProject.tsx]: I added additional checks for the team and the threshold fields 👍

File: static/app/views/projectInstall/createProject.tsx [hunk 5]
```diff
@@ -260,12 +261,29 @@ function CreateProject() {
...
+
+  let submitTooltipText: string | null = null;
+  if (formErrorCount > 1) {
+    submitTooltipText = t('Please fill out all the required fields');
+  } else if (isMissingProjectName) {
+    submitTooltipText = t('Please provide a project name');
+  } else if (isMissingAlertThreshold) {
+    submitTooltipText = t('Please provide an alert threshold');
+  } else {
+    submitTooltipText = t('Please select a team');
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/createProject.tsx:285]: since this is in `else`, shouldn't it be the default value? so then we can remove the `null`?

File: static/app/views/projectInstall/createProject.tsx [hunk 6]
```diff
@@ -260,12 +261,29 @@ function CreateProject() {
...
+  const isMissingTeam = !isOrgMemberWithNoAccess && !team;
+  const isMissingProjectName = projectName === '';
+  const isMissingAlertThreshold =
+    shouldCreateCustomRule && !conditions?.every?.(condition => condition.value);
+
+  const formErrorCount = [
+    isMissingTeam,
+    isMissingProjectName,
+    isMissingAlertThreshold,
+  ].filter(value => value).length;
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/createProject.tsx:273]:
```suggestion
  const hasFormErrors = [
    isMissingTeam,
    isMissingProjectName,
    isMissingAlertThreshold,
  ].every(value => !value)
```

an alternative 🙂

**Review by priscilawebdev — APPROVED** [review]
left a minor suggestion but it lgtm! 👏

File: static/app/views/projectInstall/createProject.tsx (hunk 6 above)
Comment (ArthurKnaus) [reply static/app/views/projectInstall/createProject.tsx:273]: hmm, I still need the count so I can display `Please fill out all the required fields` if there is more then 1 error, right?

Comment (priscilawebdev) [reply static/app/views/projectInstall/createProject.tsx:273]: I see...yes makes sense 👍
