### PR TITLE
Native stack traces: registers are hidden, button to show them is displaced

### LINKED ISSUE #82371: Native stack traces: registers are hidden, button to show them is displaced
Native stack traces can show registers in the top frame. Currently, they are hidden initially/by default and need to be expanded manually, but the way to do so is easy to miss and unintuitive - an unlabelled button:

Image

Also, if the top frame is followed by a system frame, it shows a `Show/Hide x more frame(s)` label, which causes the button to break into the next line, all the way to the left:

Image

Besides fixing the above displacement of the button, I suggest to always show the "teaser" view of the registers initially, like this:

Image

### PR DESCRIPTION
**Pull request by nipunh**
Native stack traces: registers are hidden, button to show them is displaced #82371

1) Resolved the overflow issue
2) Always showing the "teaser" view of the registers initially

Screenshot 2024-12-28 at 11 30 51 AM

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/components/events/interfaces/nativeFrame.tsx [hunk 1]
```diff
@@ -91,7 +91,6 @@ function NativeFrame({
   isShowFramesToggleExpanded,
   isSubFrame,
   onShowFramesToggle,
-  isExpanded,
```
Comment (ryan953) [inline static/app/components/events/interfaces/nativeFrame.tsx:94]: This should also be removed from the `Props` type above. Any callsites that are passing it in will have to be updated as well.

File: static/app/components/events/interfaces/nativeFrame.tsx [hunk 2]
```diff
@@ -522,14 +520,13 @@ const FileName = styled('span')`
...
-  expanded: boolean;
   isInAppFrame: boolean;
   isSubFrame: boolean;
 }>`
   position: relative;
   display: grid;
-  grid-template-columns: repeat(2, auto) 1fr repeat(2, auto) ${space(2)};
-  grid-template-rows: repeat(2, auto);
+  grid-template-columns: auto 150px 120px 4fr repeat(3, auto) ${space(2)}; /* Adjusted to account for the extra element */
+  grid-template-rows: 1fr; /* Ensures a single row */
```
Comment (ryan953) [inline static/app/components/events/interfaces/nativeFrame.tsx:529]: I suspect that the grid columns will depend on the values of `expandable` and `hiddenFrameCount`. I will find some sample data to look at before I can know what to do here.

File: static/app/components/events/interfaces/nativeFrame.tsx (hunk 1 above)
Comment (nipunh) [reply static/app/components/events/interfaces/nativeFrame.tsx:94]: I will take a look and make required changes for it.

File: static/app/components/events/interfaces/nativeFrame.tsx (hunk 2 above)
Comment (nipunh) [reply static/app/components/events/interfaces/nativeFrame.tsx:529]: Thanks for the feedback, Once we have clarity from the data, I can help refine the grid logic further. Let me know your findings!

Just to make sure, I am on the right path here, The button (show/hide count) doesn't add a data column but instead adds an extra row header without a corresponding data column. This mismatch causes layout issues like pushing the ExpandCell to the next line.

Comment (ryan953) [reply static/app/components/events/interfaces/nativeFrame.tsx:529]: It looks like it's supposed to go into two rows on purpose when the window is narrow. But the colunm widths in that case are kind of broken right now: 

SCR-20241231-ktft

Can you just re-test with a normal-width browser, and a narrow browser window, and share screenshots of the results.

I think you'll want to have something like `grid-template-rows: repeat(2, auto);` with appropriate widths defined for the narrow @media breakpoint.

Comment (nipunh) [reply static/app/components/events/interfaces/nativeFrame.tsx:529]: Sure, I will test and share the screenshots.

Comment (nipunh) [reply static/app/components/events/interfaces/nativeFrame.tsx:529]: Hi @ryan953,

These are the screenshots for existing setup
Screenshot 2025-01-04 at 6 45 16 PM
Screenshot 2025-01-04 at 6 46 34 PM
Screenshot 2025-01-04 at 6 46 48 PM


These are the screenshots after the change
Screenshot 2025-01-04 at 6 43 18 PM
Screenshot 2025-01-04 at 6 43 44 PM

Comment (nipunh) [reply static/app/components/events/interfaces/nativeFrame.tsx:529]: Hi @ryan953 

These are the screen
Screenshot 2025-01-04 at 6 43 18 PM
Screenshot 2025-01-04 at 6 43 44 PM
Screenshot 2025-01-04 at 6 45 16 PM
shots for the existing code.

These are the screenshots after the change
Screenshot 2025-01-04 at 6 46 34 PM
Screenshot 2025-01-04 at 6 46 48 PM

I have also included the screen size in the screenshots.

Comment (ryan953) [reply static/app/components/events/interfaces/nativeFrame.tsx:529]: awesome! I wanted to see if stuff like that `In App` tag was still moved down to the second row, looks like it is!

Comment (nipunh) [reply static/app/components/events/interfaces/nativeFrame.tsx:529]: Great! Is there anything else I can update here?

File: static/app/components/events/interfaces/nativeFrame.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/components/events/interfaces/nativeFrame.tsx:94]: Don't forget about cleaning up this extra prop in the types and callsites ^

File: static/app/components/events/interfaces/nativeFrame.tsx (hunk 2 above)
Comment (ryan953) [reply static/app/components/events/interfaces/nativeFrame.tsx:529]: @nipunh don't forget about that extra `isExpanded` prop, we don't need it in the Props definition or at the callsites anymore.

Comment (nipunh) [reply static/app/components/events/interfaces/nativeFrame.tsx:529]: Yes, Verifying that and will push the changes soon.

File: static/app/components/events/interfaces/nativeFrame.tsx (hunk 1 above)
Comment (nipunh) [reply static/app/components/events/interfaces/nativeFrame.tsx:94]: Hi @ryan953, I have used the changes after clean this up.

Comment (ryan953) [reply static/app/components/events/interfaces/nativeFrame.tsx:94]: @nipunh Please also delete line 63 from this file, the content is `  isExpanded?: boolean;` 
Then typescript should be happy, and we'll be all set!

Comment (nipunh) [reply static/app/components/events/interfaces/nativeFrame.tsx:94]: All set!

**Review by ryan953 — APPROVED** [review]
