### PR TITLE
fix(replays): fix error/durations on Replays for page >1

### LINKED ISSUE #35163: Error/durations on Replays list does not work for page > 1
This is because the outer query (in Replays list) has a `cursor` which is present in the URL parameters and the `<DiscoverQuery>` inside of `<ReplayTable>` will use that cursor value in the inner query that shows durations/errors. (i.e. the inner query will request page 2, only a single page will exist).

### PR DESCRIPTION
**Pull request by SDaian**
### Description

Error/durations on Replays list does not work for page > 1

Fixes: #35163

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/views/replays/replayTable.tsx [hunk 1]
```diff
@@ -39,18 +35,16 @@ type ReplayDurationAndErrors = {
...
 
-  const getEventView = () => {
-    const query = replayList.map(item => `replayId:${item[idKey]}`).join(' OR ');
-    const eventQueryParams: NewQuery = {
+  const query = replayList.map(item => `replayId:${item[idKey]}`).join(' OR ');
+
+  const discoverQuery = useMemo(
+    () => ({
       id: '',
       name: '',
```
Comment (billyvg) [inline static/app/views/replays/replayTable.tsx:47]: let's remove these too

File: static/app/views/replays/replayTable.tsx [hunk 2]
```diff
@@ -59,113 +53,95 @@ function ReplayTable({replayList, idKey, showProjectColumn}: Props) {
...
-                displayName={
-                  <Link
-                    to={`/organizations/${organization.slug}/replays/${generateEventSlug({
-                      project: replay.project,
-                      id: replay[idKey],
-                    })}/`}
-                  >
-                    {replay['user.display']}
-                  </Link>
+    <Fragment>
```
Comment (billyvg) [inline static/app/views/replays/replayTable.tsx:68]: Is this Fragment needed? you should be able to return the `replayList.map` directly

Comment (SDaian) [reply static/app/views/replays/replayTable.tsx:68]: Was thinking about that `Fragment`, one of the first options was not send it, but Typescript is complaining about this:

`'ReplayTable' cannot be used as a JSX component.
  Its return type 'Element[]' is not a valid JSX element.`

**Review by billyvg — APPROVED** [review]
