### PR TITLE
fix: useAggregatedQueryKeys should use an Observer to persist fetch results

### LINKED ISSUE #66973: Replays tab count fails to load in Issue Details
See replay at 6s for repro: https://sentry.sentry.io/replays/172fdc6b992943068d7d7d16ad85c7da/?project=11276&query=user.email%3Ajosh.ferge%40sentry.io+url%3A*sentry.io%2Fissues*&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=90d&t=6&t_main=network&yAxis=count%28%29

Screenshot 2024-03-14 at 12 31 40 PM

### PR DESCRIPTION
**Pull request by ryan953**
What was happening before is that I was doing some manual tracking of which queryKeys had been requested, and then tracked the 'done' state in the query cache. 

This was causing trouble because over time the query cache will have items evicted, so the actual result might be gone, while the record that we used to have a result remained. This is bad and causes us to not re-fetch data. 

So the change is minor, big deal if you didn't read all the docs like me earlier... But basically we can setup a QueryObserver which will help hold onto the query results so they don't get evicted quite so fast. We also drop the 'done' state from the cache to unblock re-fetches. The rest of the PR is just a little cleanup function for the observers which fires on unmount... and we can put the `inFlight` state stuff into the observer callback, replacing the async/await keywords.

---

The repro steps for the bug are simple. 
1. Visit this issue stream page: https://sentry.sentry.io/issues/?project=11276&query=useOrganization&referrer=issue-list&statsPeriod=30d
2. Notice how issue `JAVASCRIPT-2RZ7` has no replays (no icon, no count)
3. Notice how other issues do have replay counts appearing
4. Click on `JAVASCRIPT-2RZ7` to visit the details page
5. Expected: The replays tab on the details page should say 'Replays (0)'. Actual: the count icon is empty, it shows 'Replays ()'
6. Refresh the details page (ctrl+r) and you'll see the count appear 'Replays(0)' as expected

Fixes https://github.com/getsentry/sentry/issues/66973

### CODE REVIEW

File: static/app/utils/api/useAggregatedQueryKeys.tsx [hunk 1]
```diff
@@ -139,25 +149,24 @@ export default function useAggregatedQueryKeys<AggregatableQueryKey, Data>({
...
-
-      // When the promise resolves, it will trigger the cache subscription to fire
-      await promise;
-
-      queryClient.removeQueries({
-        queryKey: ['aggregate', cacheKey, key, 'inFlight'],
-        predicate: isQueryKeyInBatch,
-      });
-      queuedAggregatableBatch.forEach(queryKey => {
-        queryClient.setQueryData(['aggregate', cacheKey, key, 'done', queryKey], true);
```
Comment (malwilley) [inline static/app/utils/api/useAggregatedQueryKeys.tsx:159]: I'm a bit confused about this `done` key, I see it is set here but did anything read from this cache key?

File: static/app/utils/api/useAggregatedQueryKeys.tsx [hunk 2]
```diff
@@ -90,6 +92,14 @@ export default function useAggregatedQueryKeys<AggregatableQueryKey, Data>({
 
   const key = getQueryKey([]).at(0);
 
+  const subscriptions = useRef<Subscription[]>([]);
+  useEffect(() => {
+    const subs = subscriptions.current;
+    return () => {
+      subs.forEach(unsubscribe => unsubscribe());
```
Comment (malwilley) [inline static/app/utils/api/useAggregatedQueryKeys.tsx:99]: Since we unsubscribe on unmount, seems the cache keys can be evicted if you go to another page (which we probably want). Are there any possible bugs in this scenario or should this hook handle it gracefully?

**Review by malwilley — APPROVED** [review]
Overall a good improvement, just have a couple questions. Didn't know about QueryObserver until now!

File: static/app/utils/api/useAggregatedQueryKeys.tsx (hunk 2 above)
Comment (ryan953) [reply static/app/utils/api/useAggregatedQueryKeys.tsx:99]: I think the hook will handle it fine, if the keys are evicted then we'll re-fetch. 

Also, because it's a buffer, we could often be re-fetching a different list of id's. For example, you're on the issue stream and have issues `abc-3, abc-2, abc-1` captured so far. We'll fetch `/issue-count/?id=3,2,1`. If you navigate away then back a new issue `abc-4` might've appeared, we'll either fetch only `?id=4` if the cache is still full, or `?id=4,3,2,1` and get new counts for each.

File: static/app/utils/api/useAggregatedQueryKeys.tsx (hunk 1 above)
Comment (malwilley) [reply static/app/utils/api/useAggregatedQueryKeys.tsx:159]: Ahh okay I see now, that makes sense
