### PR TITLE
Fix stream poller ignoring active query, filters (fixes #1884)

### LINKED ISSUE #1884: [8.0.0] When filtering (by using search, bookmarks, assigned) after a bit, all results come back
If i run a filter, after a few seconds, all results show up again, even though its filtered view.

Steps to repo:

Events view.
- "All Events"
- "is: unresolved" in search
- stream is running

Click on "bookmarks"

- See your bookmarked items for 2-5 seconds
- After certain time, all events show up.

What should happen:

Click on "bookmarks"

- See your bookmarked items for all time. 

If the stream is paused, this works as expected, so if there is technical limitations, stream should pause if you try to filter your events in any way.

### PR DESCRIPTION
**Pull request by benvinegar**

### CODE REVIEW

File: src/sentry/static/sentry/app/views/stream.jsx [hunk 1]
```diff
@@ -220,11 +219,13 @@ var Stream = React.createClass({
...
       },
-      complete: () => {
+      complete: (jqXHR) => {
         this.lastRequest = null;
 
+        var links = parseLinkHeader(jqXHR.getResponseHeader('Link'));
+        this._poller.setEndpoint(links.previous.href);
+
         if (this.state.realtimeActive) {
-          this._poller.setEndpoint(url);
```
Comment (dcramer) [inline src/sentry/static/sentry/app/views/stream.jsx]: was this basically broken?

**Comment by dcramer** [comment]
:+1:

File: src/sentry/static/sentry/app/views/stream.jsx (hunk 1 above)
Comment (benvinegar) [inline src/sentry/static/sentry/app/views/stream.jsx]: Yes. Among other things, if realtime wasn't activated at the time when the first request finished, it would never get the new URL.
