### PR TITLE
fix(ddm): concurrent enhance draw

### LINKED ISSUE #64050: Enhance area selection crops after first zoom

### PR DESCRIPTION
**Pull request by obostjancic**
- closes #64050

### CODE REVIEW

File: static/app/views/ddm/focusArea.tsx [hunk 1]
```diff
@@ -240,13 +241,17 @@ function BrushRectOverlay({
...
       top: resultTop,
       width: `${width.toPrecision(5)}px`,
       height: resultHeight,
-    });
-  }, [rect, chartInstance, useFullYAxis]);
+    };
+
+    if (JSON.stringify(newPosition) !== JSON.stringify(position)) {
+      setPosition(newPosition);
+    }
```
Comment (ArthurKnaus) [inline static/app/views/ddm/focusArea.tsx:253]: Let's rather stay with `isEqual` seems to be more established in the code base?

**Review by ArthurKnaus — APPROVED** [review]
