### PR TITLE
fix(releases): Use query parameter when switching filters

### LINKED ISSUE #52880: [Releases] Page switches to "Regressed" tab after refreshing while the "Unhandled" tab is selected and vice versa
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

On any org, click on "Releases" in the side bar

Case 1

- Click on the "Unhandled" tab and pay attention to the URL
- Refresh page

Case 2

- Click on the "Regressed" tab and pay attention to the URL
- Refresh page

### Expected Result

URL with `?issuesType=unhandled` should show the "Unhandled" tab when loading/refreshing
URL with `?issuesType=regressed` should show the "Regressed" tab when loading/refreshing

### Actual Result

URL with `?issuesType=unhandled` shows the "Regressed" tab when loading/refreshing
URL with `?issuesType=regressed` shows the "Unhandled" tab when loading/refreshing

### Product Area

Releases

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by scttcper**
There was a large ternary with a mistake setting the current filter to the wrong option. We can use the query parameter instead of state altogether.

fixes #52880

### CODE REVIEW

File: static/app/views/releases/detail/overview/releaseIssues.tsx [hunk 1]
```diff
@@ -79,24 +77,7 @@ class ReleaseIssues extends Component<Props, State> {
...
-    const {location} = this.props;
-    const query = location.query ? location.query.issuesType : null;
-    const issuesTypeState = !query
-      ? IssuesType.NEW
-      : query.includes(IssuesType.NEW)
-      ? IssuesType.NEW
-      : query.includes(IssuesType.UNHANDLED)
-      ? IssuesType.REGRESSED
-      : query.includes(IssuesType.REGRESSED)
-      ? IssuesType.UNHANDLED
```
Comment (scttcper) [inline static/app/views/releases/detail/overview/releaseIssues.tsx:91]: This was the mistake, but the real mistake was this massive ternary

File: static/app/views/releases/detail/overview/releaseIssues.tsx [hunk 2]
```diff
@@ -56,7 +56,6 @@ type Props = {
   location: Location;
   organization: Organization;
   releaseBounds: ReleaseBounds;
-  selection: PageFilters;
```
Comment (scttcper) [inline static/app/views/releases/detail/overview/releaseIssues.tsx:59]: unused

**Review by malwilley — APPROVED** [review]
Logic is much better now 💯
