### PR TITLE
fix(issues): Escape status tag on search

### LINKED ISSUE #89369: Custom tag search is broken
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open the issue, click on Custom next to Tags
2. Select the custom tag "status", then click on the three dot dropdown menu next to it
3. Click on _Search issues with this tag value_

For more information, please check the [shadow Jira ticket.](https://getsentry.atlassian.net/jira/software/c/projects/FEEDBACK/boards/52?selectedIssue=ISSUE-1726)

### Expected Result

All issues that have this tag value should appear on the issues page

### Actual Result

An error appears that says: Error parsing search query: invalid status value of '500'

### Product Area

Issues

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by scttcper**
Tag keys that conflict with our issue keys must be escaped

fixes #89369

### CODE REVIEW

File: static/app/utils/fields/index.ts [hunk 1]
```diff
@@ -1993,6 +1999,7 @@ export const ISSUE_EVENT_FIELDS_THAT_MAY_CONFLICT_WITH_TAGS: Set<FieldKey> = new
   FieldKey.STACK_MODULE,
   FieldKey.STACK_PACKAGE,
   FieldKey.STACK_STACK_LEVEL,
+  FieldKey.STATUS,
```
Comment (scttcper) [inline static/app/utils/fields/index.ts:2002]: @malwilley i wasn't totally sure about this change and how these are used already

Comment (malwilley) [reply static/app/utils/fields/index.ts:2002]: Yeah this is exactly what this was set was meant to solve so it belongs here

**Review by malwilley — APPROVED** [review]
We may want to add `status` to the autocomplete (with suggestions), but this is a good change already
