### PR TITLE
ref(dropdownMenu): Prevent submenu overflow

### LINKED ISSUE #42821: [Cannot Ignore Issues from Mobile Web] Drop Down is off-screen
### Environment

SaaS (https://sentry.io/)

### Version

_No response_

### Link

https://sentry.io/organizations/sentry/issues/2514807901/?query=is%3Aunresolved&referrer=issue-stream

### DSN

_No response_

### Steps to Reproduce

1. Got to an issue in a mobile browser
2. select the kebab menu ...
3. Attempt to navigate through the Ignore Drop-down List

### Expected Result

Some kind of responsive behaviour

### Actual Result

List appears out of view
 
image

### PR DESCRIPTION
**Pull request by vuluongj20**
Fixes https://github.com/getsentry/sentry/issues/42821

**Before:**
Screenshot 2023-01-10 at 2 06 22 PM

**After:**
Screenshot 2023-01-10 at 2 05 45 PM

### CODE REVIEW

File: static/app/components/dropdownMenuControl.tsx [hunk 1]
```diff
@@ -163,7 +163,7 @@ function DropdownMenuControl({
       triggerRef.current !== target &&
       !triggerRef.current?.contains(target),
     // Necessary for submenus to be correctly positioned
-    ...(isSubmenu && {preventOverflowOptions: {boundary: document.body}}),
+    ...(isSubmenu && {preventOverflowOptions: {boundary: document.body, altAxis: true}}),
```
Comment (vuluongj20) [inline static/app/components/dropdownMenuControl.tsx:166]: Tell PopperJS to prevent overflow on the alt axis (which in this case is the horizontal axis)

**Review by malwilley — APPROVED** [review]

**Review by evanpurkhiser — APPROVED** [review]
