### PR TITLE
fix(ui): Disable member invitation button when organization:invite-members is disabled

### LINKED ISSUE #30256: disable invite not working
### Environment

self-hosted (`onpremise` deployment)

### Version

21.5.0

### Steps to Reproduce

add in sentry.conf.py 

    ############
    # Features #
    ############

    SENTRY_FEATURES["projects:sample-events"] = False
    SENTRY_FEATURES["organizations:invite-members"] = False

### Expected Result

the invite must be disabled

### Actual Result

image

image
image

### PR DESCRIPTION
**Pull request by ryan953**
Wrap the "Invite Members" button on the members setting page with a customization hook, where the default implementation looks at the feature `organizations:invite-members` to control whether the button is enabled/disabled.

Fixes #30256
Relates to https://github.com/getsentry/getsentry/pull/7194

Tested by toggling the feature in server.py

When the feature is off we get the disabled button and a tooltip explaining how to turn it on:
OSS - invites disabled

And when it's enabled the modal will send invites:
OSS - invites enabled

### CODE REVIEW

File: static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx [hunk 1]
```diff
@@ -41,12 +41,14 @@ class OrganizationMembersWrapper extends AsyncView<Props, State> {
 
   get hasWriteAccess() {
     const {organization} = this.props;
-    if (!organization || !organization.access) {
-      return false;
-    }
```
Comment (ryan953) [inline static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx:46]: I noticed that the TS types have `organization` and `access` as non-optional:
https://github.com/getsentry/sentry/blob/7d89cea153e73cf28a8b71c8a8abee2799b00eb1/static/app/types/organization.tsx#L15

So if those are correct we won't need to check that they're available

**Comment by maheskett** [comment]
@ryan953 There's a saas flow where customers on free plans can automatically start a trial to invite members. I think this change would prevent that. Instead, have you taken a look at the [InviteModalHook](https://github.com/getsentry/sentry/blob/master/static/app/components/modals/inviteMembersModal/index.tsx#L39-L43) `defaultComponent` to update the behavior for oss? 

Screen Shot 2022-03-17 at 10 22 24 AM

**Comment by ryan953** [comment]
> @ryan953 There's a saas flow where customers on free plans can automatically start a trial to invite members. I think this change would prevent that. Instead, have you taken a look at the [InviteModalHook](https://github.com/getsentry/sentry/blob/master/static/app/components/modals/inviteMembersModal/index.tsx#L39-L43) `defaultComponent` to update the behavior for oss?

Ah, don't want to block that flow. I'll check out that hook.

**Review by billyvg — COMMENTED** [review]
Code looks good to me, I'm going to leave this for @maheskett for the final stamp

**Comment by ryan953** [comment]
@maheskett I've been looking into this, trying to repro the saas workflow with mixed luck there. I ran getsentry and saw the `Inviting members will start your 14 day Business Plan trial` TrialInfo message, but something else breaks when I try to start the trial so I am kind of stuck to test it.

However I was looking at `memberInviteModalCustomization.tsx` and all the conditions in there, it really seems to boil down to this line: `canSend: !trialStarting && canTrial && allowedToStartTrial,` where we've implemented the [`InviteModalCustomizationHook`](https://github.com/getsentry/sentry/blob/5319a3c40a92c776f0a0086da0da10fca01cf38b/static/app/types/hooks.tsx#L531-L535).

However, I noticed that the modal/form works [in two ways](https://github.com/getsentry/sentry/blob/5319a3c40a92c776f0a0086da0da10fca01cf38b/static/app/components/modals/inviteMembersModal/index.tsx#L124-L126): send the invite directly or make a request which an admin can approve, based on the [member:write](https://github.com/getsentry/sentry/blob/5319a3c40a92c776f0a0086da0da10fca01cf38b/static/app/components/modals/inviteMembersModal/index.tsx#L295-L297) permission. 
The first case calls to https://github.com/getsentry/sentry/blob/ryan953/disable-invites/src/sentry/api/endpoints/organization_member_index.py/#L211-L214 which guards invites with the feature flag.
The second case goes through the request flow, but eventually also get guarded by the feature flag when we're saving the member model: https://github.com/getsentry/sentry/blob/ryan953/disable-invites/src/sentry/models/organizationmember.py/#L396-L398

This is what I've found so far. If I could get the start-trial button working, or if i knew for sure that getsentry runs with/without the `organizations:invite-members` feature that'd be better... So I'm working on learning those answers.

**Comment by maheskett** [comment]
We resolved the error in getsentry and chatted about adding a hook on the invite member button. That way the button could be disabled for open source with a tooltip explaining how to update their sentry config. @evanpurkhiser What do you think?

File: static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx [hunk 2]
```diff
@@ -20,6 +24,54 @@ type State = AsyncView['state'] & {
   inviteRequests: Member[];
 };
 
+function DisabledInviteMembersTooltip({children}: any) {
+  const title = tct(
+    `Enable this feature on your sentry installation by adding the
+    following configuration into your [configFile:sentry.conf.py].
+    See [configLink:the configuration documentation] for more
+    details.`,
```
Comment (ryan953) [inline static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx:32]: whoop, this needs some love

Comment (evanpurkhiser) [reply static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx:32]: Doesn't it say this by default somewhere in the disabled feature component?

Comment (evanpurkhiser) [reply static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx:32]: https://github.com/getsentry/sentry/blob/c51404d69b08f7e249edb9a480b039754bcace72/static/app/components/acl/featureDisabled.tsx#L106-L117

you should be able to just use the `FeatureDisabled` component

Comment (ryan953) [reply static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx]: Yeah, `<FeatureDisabled>` is working good imo. This is my fav layout so far:
Screen Shot 2022-03-22 at 1 37 00 PM
Screen Shot 2022-03-22 at 1 37 08 PM

Earlier I was thinking that `<FeatureDisabled>` is too big and chunky in that part of the page. I was playing around, copy pasting, and came up with this kind of thing which I don't love:
Screen Shot 2022-03-22 at 11 59 31 AM

Comment (evanpurkhiser) [reply static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx]: You can use the hovercard variant which might be more what you want

Comment (ryan953) [reply static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx]: Would it be crazy to copy+aste a bunch of the stuff from FeatureDisabled and put it inside a Hovercard? Could be a new reusable thing along the lines of `<FeatureDisableHovercard>`

Comment (evanpurkhiser) [reply static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx]: Yes it would, because you can just do this :) https://github.com/getsentry/sentry/blob/master/static/app/views/alerts/wizard/index.tsx#L91-L104

**Comment by ryan953** [comment]
@evanpurkhiser @maheskett thanks for looking at this before, I'm done poking at the code and tests have been working locally... 
So while they're still running in CI I think I can invite you back for a final review

File: static/app/views/settings/organizationMembers/components/inviteMembersButton.tsx [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+  disabled?: boolean;
+};
+
+function InviteMembersButton({disabled, onClick}: InviteMembersButtonProps) {
+  const action = (
+    <Button
+      priority="primary"
+      size="small"
+      onClick={onClick}
+      data-test-id="email-invite"
```
Comment (billyvg) [inline static/app/views/settings/organizationMembers/components/inviteMembersButton.tsx:20]: Does this get used?

Comment (ryan953) [reply static/app/views/settings/organizationMembers/components/inviteMembersButton.tsx:20]: the test id was there before, so i left it the way it was. 

the tests that i saw are calling `wrapper.find('StyledButton');` which seems not as specific as they could be

File: static/app/views/settings/organizationMembers/components/inviteMembersButton.tsx [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+      icon={<IconMail />}
+      disabled={disabled}
+    >
+      {t('Invite Members')}
+    </Button>
+  );
+
+  return disabled ? (
+    <Hovercard
```
Comment (evanpurkhiser) [inline static/app/views/settings/organizationMembers/components/inviteMembersButton.tsx:29]: If possible, can we actually keep this all co-located near the feature hook stuff?

I would probably write things similar to this https://github.com/getsentry/sentry/blob/3a09b483dc327a280d74ca7634f125f5a71fb659/static/app/views/dashboardsV2/controls.tsx#L172-L203

File: static/app/types/hooks.tsx [hunk 5]
```diff
@@ -115,6 +115,7 @@ export type ComponentHooks = {
  */
 export type CustomizationHooks = {
   'integrations:feature-gates': IntegrationsFeatureGatesHook;
+  'member-invite-buttom:customization': InviteButtonCustomizationHook;
```
Comment (maheskett) [inline static/app/types/hooks.tsx:118]:
```suggestion
  'member-invite-button:customization': InviteButtonCustomizationHook;
```

File: static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx [hunk 6]
```diff
@@ -20,6 +21,15 @@ type State = AsyncView['state'] & {
   inviteRequests: Member[];
 };
 
+const InviteMembersButtonHook = HookOrDefault({
+  hookName: 'member-invite-buttom:customization',
```
Comment (maheskett) [inline static/app/views/settings/organizationMembers/organizationMembersWrapper.tsx:25]:
```suggestion
  hookName: 'member-invite-button:customization',
```

File: static/app/views/settings/organizationMembers/components/inviteMembersButton.tsx (hunk 4 above)
Comment (ryan953) [reply static/app/views/settings/organizationMembers/components/inviteMembersButton.tsx]: sounds good. I inlined the `InviteMembersButton` component into organizationMembersWrapper.tsx

**Comment by ryan953** [comment]
@maheskett can I get the acceptance on this and also https://github.com/getsentry/getsentry/pull/7194 to send out together?

The flakiness has finally subsided and checks are green in both

**Review by maheskett — APPROVED** [review]
Lgtm
