### PR TITLE
ref(invites): Disable team selector when non-team role is selected

### LINKED ISSUE #67427: Unable to invite new user as Billing when a team is selected
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Organisation Settings -> Members
2. Try to invite a new user with Billing role and add this new user to a team (sometimes auto populated)

### Expected Result

The UI clearly displays why the invite cannot be sent:
```
The user with a 'billing' role cannot have team-level permissions.
```

### Actual Result

The invite fails with an error with no details on the same.

### Product Area

Settings - Members

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by leeandher**
Fixes https://github.com/getsentry/sentry/issues/67427 with better user clarity

Requires https://github.com/getsentry/sentry/pull/67708

Disable the teams field when selecting a role that cannot be applied to teams (e.g. billing).

https://github.com/getsentry/sentry/assets/35509934/d7d39d57-65cf-48e0-a890-2e846a58bfe1

### CODE REVIEW

File: static/app/types/organization.tsx [hunk 1]
```diff
@@ -107,21 +107,20 @@ export interface DetailedTeam extends Team {
   projects: Project[];
 }
 
-// TODO: Rename to BaseRole
-export interface MemberRole {
+export interface BaseRole {
```
Comment (nhsiehgit) [inline static/app/types/organization.tsx:110]: 🎉

**Review by nhsiehgit — APPROVED** [review]
nice, 👍
