### PR TITLE
fix(feedback): reload list after updating feedback status

### LINKED ISSUE #76920: [User Feedback] Inbox and Resolved numbers don't update automatically
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have one or more user feedback entries
2. Resolve/unresolve a user's feedback

### Expected Result

The number shown in the "Inbox" and "Resolved" sections changes once we resolve/unresolve the feedback.

### Actual Result

The number does not change unless we reload the page.

https://github.com/user-attachments/assets/ea84f1e5-9b69-42ee-accd-e547c9b5cf5a

### Product Area

User Feedback

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### LINKED ISSUE #84722: [User Feedback] Reload list when deleting user feedback
When deleting a user feedback, reload the list on the left so that the feedback is also gone from the list. Currently, it shows unable to load feedback on the feedback itself but the list doesn't update to remove that feedback

### PR DESCRIPTION
**Pull request by aliu39**
After a feedback mutation is successful, invalidate the list query response and empty the cache (similar to what we do in "Load new feedback"), causing the list to refetch.

Closes https://github.com/getsentry/sentry/issues/84722
Closes https://github.com/getsentry/sentry/issues/76920

Demo of all actions except delete (I don't have permission):

https://github.com/user-attachments/assets/fe23c1aa-9a81-4ba4-a1b4-aecd57ca783e

### CODE REVIEW

File: static/app/components/feedback/feedbackItem/useFeedbackActions.ts [hunk 1]
```diff
@@ -37,18 +40,31 @@ export default function useFeedbackActions({feedbackItem}: Props) {
...
   const isResolved = feedbackItem.status === GroupStatus.RESOLVED;
   const onResolveClick = useCallback(() => {
     addLoadingMessage(t('Updating feedback...'));
     const newStatus = isResolved ? GroupStatus.UNRESOLVED : GroupStatus.RESOLVED;
     resolve(newStatus, mutationOptions);
-  }, [isResolved, resolve]);
+    reloadListData();
+  }, [isResolved, resolve, reloadListData]);
 
+  // reuse the issues ignored category for spam feedbacks
```
Comment (michellewzhang) [inline static/app/components/feedback/feedbackItem/useFeedbackActions.ts:67]: let's keep this comment?

**Review by michellewzhang — COMMENTED** [review]
for the error message - is the item still getting resolved when you click resolve? but the error message is still displaying?

File: static/app/components/feedback/feedbackItem/useFeedbackActions.ts (hunk 1 above)
Comment (michellewzhang) [reply static/app/components/feedback/feedbackItem/useFeedbackActions.ts:67]: oops sorry

**Comment by aliu39** [comment]
Fixed by moving to the success callback!

**Review by michellewzhang — APPROVED** [review]
