### PR TITLE
fix(issue-stream): Fix bug where replay divider was shown despite no replays

### LINKED ISSUE #79020: Issue Stream Table: Show separators between each item in second line
There is currently a bug where an extra separator will get shown if there are no replays:

Image

### PR DESCRIPTION
**Pull request by MichaelSun48**
closes #79020
before: 

image

after:

image

### CODE REVIEW

File: static/app/components/eventOrGroupExtraDetails.tsx [hunk 1]
```diff
@@ -73,10 +74,13 @@ function EventOrGroupExtraDetails({
...
 
   const issuesPath = `/organizations/${organization.slug}/issues/`;
+  const {getReplayCountForIssue} = useReplayCountForIssues();
 
   const showReplayCount =
     organization.features.includes('session-replay') &&
-    projectCanLinkToReplay(organization, project);
+    projectCanLinkToReplay(organization, project) &&
+    data.issueCategory &&
+    getReplayCountForIssue(data.id, data.issueCategory);
```
Comment (roggenkemper) [inline static/app/components/eventOrGroupExtraDetails.tsx:83]: can we add a ` > 0` here - not that it'll make a big different but at least it'll keep `showReplayCount` a boolean

Comment (MichaelSun48) [reply static/app/components/eventOrGroupExtraDetails.tsx:83]: Good point about keeping it a boolean - that function also can return `undefined`, so i think just converting it to a boolean would achieve the same result without having to do a separate existence check.

**Review by roggenkemper — APPROVED** [review]
