### PR TITLE
fix(breadcrumbs): Resize breadcrumb rows when expanding object properties

### LINKED ISSUE #47301: Cannot Scroll Through Breadcrumb When Expanded
### Environment

SaaS (https://sentry.io/)

### Version

_No response_

### Link

_No response_

### DSN

_No response_

### Steps to Reproduce

1.) Go to Issue Details Page
2.) Go to Breadcrumbs Section
3.) Find object that can expand and select the '+'
4.) You will see that the full details do not show and you are unable to scroll to see the rest. This was tested in the latest version of both Firefox and Chrome. I've pasted an example of this below

image

image

### Expected Result

To be able to scroll when expanding an object in Breadcrumbs to view all associated details

### Actual Result

Breadcrumb expansion does not fully show/is cut off and you cannot scroll to view all associated information.

### PR DESCRIPTION
**Pull request by malwilley**
Fixes https://github.com/getsentry/sentry/issues/47301

- Adds `useResizeObserver` to trigger height recalculations when breadcrumb rows resize
- Adds a wrapper div so that the breadcrumb content doesn't need to have a set `height`

https://user-images.githubusercontent.com/10888943/231891393-e347892e-f4ed-461b-ac47-2e80ae4425ce.mp4

### CODE REVIEW

File: static/app/components/events/interfaces/breadcrumbs/breadcrumb/index.tsx [hunk 1]
```diff
@@ -35,22 +34,31 @@ export const Breadcrumb = memo(function Breadcrumb({
...
   meta,
-  ['data-test-id']: dataTestId,
+  isLastItem,
 }: Props) {
+  const sizingRef = useRef<HTMLDivElement | null>(null);
   const {type, description, color, level, category, timestamp} = breadcrumb;
   const error = breadcrumb.type === BreadcrumbType.ERROR;
 
+  const resizeObserverOnResize = useCallback(() => {
+    onResize();
```
Comment (scefali) [inline static/app/components/events/interfaces/breadcrumbs/breadcrumb/index.tsx:47]: @malwilley nit: couldn't you just do:
```
const resizeObserverOnResize = useCallback(onResize, [onResize])
```

**Review by priscilawebdev — APPROVED** [review]
tested locally and it looks good to me
