### PR TITLE
ref(similarity-embedding): Add analytics for similar issue diff

### LINKED ISSUE #64557: Add analytics to similar issues diff
- Any time a user clicks on a diff on any of the issues in the Similar issues tab, we should log the following in an analytic event
    - Project and Org ids
    - Issue ids for both issues
    - Error messages for both issues
    - Stacktraces for both issues
    - transactions for both issues

### PR DESCRIPTION
**Pull request by jangjodi**
Any time a user clicks on a diff on any of the issues in the Similar issues tab, we should log the following in an analytic event:

- Project and Org ids
- Issue ids for both issues
- Error messages for both issues
- Stacktraces for both issues
- transactions for both issues

closes https://github.com/getsentry/sentry/issues/64557

### CODE REVIEW

File: static/app/components/issueDiff/index.tsx [hunk 1]
```diff
@@ -89,7 +132,16 @@ class IssueDiff extends Component<Props, State> {
...
+    return event;
+  };
+
+  getTransaction = (tags: any[]) => {
+    for (let i = 0; i < tags.length; i++) {
+      if (tags[i].key === 'transaction') {
+        return tags[i].value;
+      }
+    }
+    return undefined;
```
Comment (scttcper) [inline static/app/components/issueDiff/index.tsx:144]: probably prefer a find here
```suggestion
    return tags.find(tag => tag.key === 'transaction')?.value;
```

File: static/app/components/issueDiff/index.tsx [hunk 2]
```diff
@@ -55,28 +57,69 @@ class IssueDiff extends Component<Props, State> {
...
-      .then(([{default: SplitDiffAsync}, baseEvent, targetEvent]) => {
+    const asyncFetch = async () => {
+      try {
+        const [baseEventData, targetEventData] = await Promise.all([
+          this.fetchEvent(baseIssueId, baseEventId ?? 'latest'),
+          this.fetchEvent(targetIssueId, targetEventId ?? 'latest'),
+        ]);
+
+        const [{default: SplitDiffAsync}, baseEvent, targetEvent] = await Promise.all([
+          import('../splitDiff'),
```
Comment (scttcper) [inline static/app/components/issueDiff/index.tsx:81]: lets declare the promise for `import('../splitDiff')` higher which will start the request.
```ts
const splitdiffPromise = import('../splitDiff');
```

and then you can just await it on its own line after, its kinda weird to mix regular requests and a component in a promise.all
```ts
const `{default: SplitDiffAsync} = splitdiffPromise;
```

**Review by scttcper — APPROVED** [review]
