### PR TITLE
fix(search): Use email instead of UUID for managed members

### LINKED ISSUE #6513: "assigned:" search dropdown displays UUID for managed members
the `username` field is a UUID for managed members, so it would be a good idea to use something else for the slug here, possibly email

### PR DESCRIPTION
**Pull request by lynnagara**
Fixes #6513

### CODE REVIEW

File: src/sentry/static/sentry/app/stores/streamTagStore.jsx [hunk 1]
```diff
@@ -4,8 +4,13 @@ import _ from 'lodash';
 import StreamTagActions from '../actions/streamTagActions';
 import MemberListStore from './memberListStore';
 
+const getUsername = user => {
+  const useUsername = !user.isManaged && user.username;
```
Comment (MaxBittker) [inline src/sentry/static/sentry/app/stores/streamTagStore.jsx]: may read nicer to pull ismanaged, username, and email all off user with object destructuring

also, this is pedantic, but we've agreed to use let inside function bodies for variables that aren't reassigned. :/ I dont mind merging this as-is

**Review by MaxBittker — APPROVED** [review]
I think this code makes sense, but you should follow up with support and make sure this works for the people who wrote in about it/ the assumptions about managed users this makes are valid. style nits are up to you.

**Comment by TimPetricola** [comment]
@MaxBittker @lynnagara I wrote about this to support a month ago or something and it fixes the issue. Thanks for that 🙌
