### PR TITLE
fix(metrics): Duplicate name warning spanning use cases

### LINKED ISSUE #73149: Duplicate metrics with different units check needs to take namespace into consideration

### PR DESCRIPTION
**Pull request by ArthurKnaus**
Avoid displaying duplication warnings if the affected metrics are from different use cases. 

Closes https://github.com/getsentry/sentry/issues/73149

### CODE REVIEW

File: static/app/components/metrics/mriSelect/index.tsx [hunk 1]
```diff
@@ -65,7 +65,9 @@ export function getMetricsWithDuplicateNames(metrics: MetricMeta[]): Set<MRI> {
   const duplicateNames: string[] = [];
 
   for (const metric of metrics) {
-    const metricName = parseMRI(metric.mri)?.name;
+    const parsedMri = parseMRI(metric.mri);
+    // Include the use case to avaoid warning of conflicts between different use cases
```
Comment (priscilawebdev) [inline static/app/components/metrics/mriSelect/index.tsx:69]:
```suggestion
    // Include the use case to avoid warning of conflicts between different use cases
```

File: static/app/components/metrics/mriSelect/index.tsx [hunk 2]
```diff
@@ -65,7 +65,9 @@ export function getMetricsWithDuplicateNames(metrics: MetricMeta[]): Set<MRI> {
...
+    const metricName = `${parsedMri?.useCase}_${parsedMri?.name}`;
```
Comment (priscilawebdev) [inline static/app/components/metrics/mriSelect/index.tsx:70]: `metricName` will be always defined because of `_`

Comment (ArthurKnaus) [reply static/app/components/metrics/mriSelect/index.tsx:70]: that is actually fine as the we should always valid MRI's from the BE 👍 
The types of `parseMRI` are a bit lacking...

Comment (ArthurKnaus) [reply static/app/components/metrics/mriSelect/index.tsx:70]: @priscilawebdev  Follow up: https://github.com/getsentry/sentry/pull/73277

Comment (priscilawebdev) [reply static/app/components/metrics/mriSelect/index.tsx:70]: but the code will never go to the `continue` described bellow . shall we remove it?

Comment (ArthurKnaus) [reply static/app/components/metrics/mriSelect/index.tsx:70]: that is true, good catch!
I would merge the other PR first and then remove the `continue` + change all `parsedMri?.` to `parsedMri.` in this file.

Comment (ArthurKnaus) [reply static/app/components/metrics/mriSelect/index.tsx]: done!

**Review by priscilawebdev — APPROVED** [review]
lgtm
