### PR TITLE
fix(settings): invalidate cache in notification settings

### LINKED ISSUE #112143: Person User Notification Updates Not Reflected on Page Until Manual Refresh
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Navigate to User Settings -> [https://sentry.io/settings/account/notifications/](https://sentry.io/settings/account/notifications/)

Try and update any of the following:

- Issue Alert Notifications
- Workflow Notifications
- Deploy Notifications
- Nudges
- Spend notifications
- Spike Protection
- Broken Crons Monitors

### Expected Result

When setting is updated you will see it saved on the page

### Actual Result

Display setting reverts back to prev setting, hard refresh of the browser forces for display setting to update.

For example, if you toggle a settings from Off -> On, immediately you will see Off still displayed. Hard refresh of page then results in On being displayed.

I was able to replicate this in the latest version of Firefox and Chrome in multiple test accounts.

No browser console log errors that I could see, also tested all User Notification Settings and the following where affected:

- Issue Alert Notifications
- Workflow Notifications
- Deploy Notifications
- Nudges
- Spend notifications
- Spike Protection
- Broken Crons Monitors

Didn’t affect the following:

- Workflow Notifications
- Email Routing

Also reported by User in internal ticket [#179032](https://sentry.zendesk.com/agent/tickets/179032)

### Product Area

Settings

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by natemoo-re**
Some notification settings were not updating the underlying data on success, leading to the form being reset with stale `initialData`. In effect, the form appeared to not trigger any update from the frontend—a hard refresh would display the correct values because the backend did process the update.

Closes DE-1043, closes #112143

### CODE REVIEW

File: static/app/views/settings/account/notifications/notificationSettings.tsx [hunk 1]
```diff
@@ -102,8 +103,13 @@ function NotificationSettings({organizations}: NotificationSettingsProps) {
         data,
       });
     },
-    onSuccess: () => {
+    onSuccess: (_, variables) => {
       addSuccessMessage(t('Notification preferences saved'));
+      setApiQueryData<NotificationFields>(
+        queryClient,
+        [NOTIFICATIONS_ENDPOINT],
+        existing => ({...existing!, ...variables})
```
Comment (TkDodo) [inline static/app/views/settings/account/notifications/notificationSettings.tsx]: we can return `undefined` to bail out of updates, avoiding the non-null assertion:

```suggestion
        existing => existing ? ({...existing, ...variables}) : undefined
```

**Review by TkDodo — APPROVED** [review]
