### PR TITLE
fix(feedback): when uf tab loaded, set project in url

### LINKED ISSUE #66712: If no global selection (e.g. on issues) then default sidebar project is not correct

### PR DESCRIPTION
**Pull request by michellewzhang**
Closes https://github.com/getsentry/sentry/issues/66712

There was a bug happening where clicking the "set up now" button in issue details wasn't correctly loading in the right selected project, because the global selection was empty (coming from issues stream). To fix this, set the proj ID in the URL when this tab is loaded, so we know which project to load in right away.

Before:

https://github.com/getsentry/sentry/assets/56095982/01e534bf-d784-4cba-bb69-9691d38ed130

After:

https://github.com/getsentry/sentry/assets/56095982/f52b2052-7348-4576-9c11-755f431747af

### CODE REVIEW

File: static/app/views/userFeedback/userFeedbackEmpty.tsx [hunk 1]
```diff
@@ -31,6 +34,20 @@ export function UserFeedbackEmpty({projectIds}: Props) {
...
+      pathname: location.pathname,
+      query: {...location.query, project: projectIds?.[0]},
+      hash: location.hash,
+    });
+  }, [location.hash, location.query, location.pathname, projectIds, router]);
+
+  useEffect(() => {
+    setProjId();
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, []);
```
Comment (ryan953) [inline static/app/views/userFeedback/userFeedbackEmpty.tsx:49]: This might be a good place for `browserHistory.getCurrentLocation()`:
i'm tinkering: 

```suggestion
import {browserHistory} from 'react-router';
...
  useEffect(() => {
    const location = browserHistory.getCurrentLocation();
    if (!location.query.project) {
      browserHistory.push({
        pathname: location.pathname,
        query: {...location.query, project: projectIds?.[0]},
        hash: location.hash,
      });
    } 
  }, [projectIds]);
```

**Review by ryan953 — APPROVED** [review]

File: static/app/views/userFeedback/userFeedbackEmpty.tsx (hunk 1 above)
Comment (michellewzhang) [reply static/app/views/userFeedback/userFeedbackEmpty.tsx:49]: gave it a try and the odd thing is that even though the URL is setting the project, it's still rendering the wrong project - super weird

Comment (ryan953) [reply static/app/views/userFeedback/userFeedbackEmpty.tsx:49]: :( kk cool

Comment (ryan953) [reply static/app/views/userFeedback/userFeedbackEmpty.tsx:49]: maybe the suggestion isn't triggering the correct 'location updated' callback like i assumed
