### PR TITLE
fix(width): fixed min-width of filter release selection menu

### LINKED ISSUE #60237: To increase width of "FIlter Release" filter in mobile performance page
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

https://vimeo.com/886148363/ec826f856b?share=copy

### Expected Result

Loader should be visible

### Actual Result

Loader is not visible and width can be increase further.

### Product Area

Performance

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by Shubhdeep12**
Fixes: #60237 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/views/starfish/components/releaseSelector.tsx [hunk 1]
```diff
@@ -149,6 +149,7 @@ export function ReleaseComparisonSelector() {
 const StyledCompactSelect = styled(CompactSelect)`
   @media (min-width: ${p => p.theme.breakpoints.medium}) {
     max-width: 275px;
+    min-width: 135px;
```
Comment (shruthilayaj) [inline static/app/views/starfish/components/releaseSelector.tsx:152]: It's not as straightforward as this since we wrap our release selectors in the `<PageFilterBar>` component, and that applies a min width to the last [child](https://github.com/getsentry/sentry/blob/master/static/app/components/organizations/pageFilterBar.tsx#L62) that need to be overridden.

Right now, the min-width only gets applied to the first selector.

Screenshot 2023-11-21 at 12 22 27 PM

You could do something like this:

```
const StyledPageFilterBar = styled(PageFilterBar)`
  & > * {
    /* Prevent date filter from shrinking below 6.5rem */
    &:last-child {
      min-width: 135px;
    }
  }
`;
```

And wrap the release selectors in `<StyledPageFilterBar>` to ensure it gets applied to the last child too

Comment (Shubhdeep12) [reply static/app/views/starfish/components/releaseSelector.tsx:152]: Oh yes, my bad.
Yes adding a wrapper will work fine but,

How about using **_!important_**  with min-width?

**Review by shruthilayaj — APPROVED** [review]
