### PR TITLE
fix(replays): show first frame by default for mobile replays

### LINKED ISSUE #67912: [Replay Details] Show the first frame at the beginning rather than empty panel
may be related to the fact that `startTimestamp` coming from `ReplayContext` doesn't match up exactly with `attachments[0].timestamp`

### PR DESCRIPTION
**Pull request by michellewzhang**
Fixes https://github.com/getsentry/sentry/issues/67912

https://github.com/getsentry/sentry/assets/56095982/d0cb3879-aa67-4dec-8cc6-6a8d1d40e45d

### CODE REVIEW

File: static/app/components/replays/videoReplayer.tsx [hunk 1]
```diff
@@ -418,14 +428,19 @@ export class VideoReplayer {
   public pause(videoOffsetMs: number) {
     const index = this._currentIndex ?? 0;
 
+    // Hide first frame if we seek to a later part of the replay first
+    if (videoOffsetMs > 0) {
+      this.hideVideo(0);
+    }
```
Comment (billyvg) [inline static/app/components/replays/videoReplayer.tsx:434]: Will this hide (or flash) the video if we seek to somewhere else in the first segment?

Comment (michellewzhang) [reply static/app/components/replays/videoReplayer.tsx:434]: it looks all right to me:
https://github.com/getsentry/sentry/assets/56095982/5c5b80d4-b3e9-483f-afcf-aa113268348a

File: static/app/components/replays/videoReplayer.tsx [hunk 2]
```diff
@@ -77,6 +77,9 @@ export class VideoReplayer {
     // Initially, only load some videos
     this.preloadVideos({low: 0, high: PRELOAD_BUFFER});
 
+    // Show first frame by default
+    this.showVideo(this._videos[0]);
```
Comment (billyvg) [inline static/app/components/replays/videoReplayer.tsx:81]: Would calling `loadSegment(0)` here be better instead? I think this could also take care of the above preload call as well. Then this would correctly set `this._currentIndex` in the loadeddata event listener as well.

```suggestion
    this.loadSegment(0);
```

Comment (michellewzhang) [reply static/app/components/replays/videoReplayer.tsx:81]: calling `loadSegment` doesn't work (no frame shows up) :( it also causes the bug we fixed here: https://github.com/getsentry/sentry/pull/67911

**Review by billyvg — APPROVED** [review]

File: static/app/components/replays/videoReplayer.tsx (hunk 2 above)
Comment (billyvg) [reply static/app/components/replays/videoReplayer.tsx:81]: Ahh
