### PR TITLE
fix(feedback): Check to verify that feedback has project, ts is a lie

### LINKED ISSUE #69258: `Cannot read properties of undefined (reading 'id')` when switching to User Feedback from nav bar
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

25.0.5

### Docker Compose Version

3.8.0

### Steps to Reproduce

Switch user feedback to the left-side navigation. However, if I refresh the page, it's able to load normally, which seems to be due to no startPeriod being passed to the request

Screenshot from 2024-04-17 09-23-13

### Expected Result

Show user feedback

### Actual Result

Got error: `Cannot read properties of undefined (reading 'id')`

FireShot Capture 005 - TypeError — Discover — hyperhuman — internal — Sentry - sentry deemos dev

### Event ID

1d5a4d93b97f48e1bf1d72df495e2f90

### LINKED ISSUE #70136: [self-hosted] User feedback: Something went horribly wrong rendering this page
I enabled User feedback on my self-hosted instance of Sentry.

When I try to view User Feedback in Sentry, I get the following error:
```Something went horribly wrong rendering this page.```
```TypeError: u.project is undefined```

This is caused by this line:

https://github.com/getsentry/sentry/blob/56d237c485abdbece0a0c9a4798f398c87d49f8c/static/app/components/feedback/useFetchFeedbackData.tsx#L40C29-L40C52

Version: 24.4.2 (latest at time of writing)
OS : Ubuntu 22.04.4 LTS
Nginx reverse proxy

I ran again install.sh to migrate database after enabling User feedback.

Here is the feature flags :
```SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            "organizations:discover",
            "organizations:events",
            "organizations:global-views",
            "organizations:incidents",
            "organizations:integrations-issue-basic",
            "organizations:integrations-issue-sync",
            "organizations:invite-members",
            "organizations:metric-alert-builder-aggregate",
            "organizations:sso-basic",
            "organizations:sso-rippling",
            "organizations:sso-saml2",
            "organizations:performance-view",
            "organizations:advanced-search",
            "organizations:session-replay",
            "organizations:issue-platform",
            "organizations:profiling",
            "organizations:monitors",
            "organizations:dashboards-mep",
            "organizations:mep-rollout-flag",
            "organizations:dashboards-rh-widget",
            "organizations:metrics-extraction",
            "organizations:transaction-metrics-extraction",
            "projects:custom-inbound-filters",
            "projects:data-forwarding",
            "projects:discard-groups",
            "projects:plugins",
            "projects:rate-limits",
            "projects:servicehooks",
        )
        + (
            "projects:span-metrics-extraction",
            "organizations:starfish-browser-resource-module-image-view",
            "organizations:starfish-browser-resource-module-ui",
            "organizations:starfish-browser-webvitals",
            "organizations:starfish-browser-webvitals-pageoverview-v2",
            "organizations:starfish-browser-webvitals-use-backend-scores",
            "organizations:performance-calculate-score-relay",
            "organizations:starfish-browser-webvitals-replace-fid-with-inp",
            "organizations:deprecate-fid-from-performance-score",
            "organizations:performance-database-view",
            "organizations:performance-screens-view",
            "organizations:mobile-ttid-ttfd-contribution",
            "organizations:starfish-mobile-appstart",
            "organizations:standalone-span-ingestion",
            "organizations:spans-first-ui",
        )  # starfish related flags
        + (
            "organizations:user-feedback-ui",
            "organizations:user-feedback-ingest",
            "organizations:feedback-ingest",
            "organizations:feedback-post-process-group",
            "organizations:feedback-visible",
        )  # user feedback
    }
)
```

Sometimes it will display another error "There was an error loading a component." then I can refresh with F5 and this time it loads without error.

### PR DESCRIPTION
**Pull request by ryan953**
self-hosted users who recently upgraded noticed that some feedback items were not processed fully, and didn't have the expected project field in the response. This adds an extra check so we don't throw on that line of code.

Typescript in this case, is incorrect. It suggests that project is always present.

Self-hosted users, after the retention period, shouldn't need this line anymore... but we'll have to keep it in the codebase forever because folks can upgrade from an old to new version at anytime.

Fixes https://github.com/getsentry/sentry/issues/69258
Fixes https://github.com/getsentry/sentry/issues/70136

### CODE REVIEW

File: static/app/components/feedback/useFetchFeedbackData.tsx [hunk 1]
```diff
@@ -40,7 +40,9 @@ export default function useFetchFeedbackData({feedbackId}: Props) {
   const {markAsRead} = useMutateFeedback({
     feedbackIds: [feedbackId],
     organization,
-    projectIds: issueData ? [issueData?.project.id] : [],
+    // Typescript is a lie. `project` might be missing if feedback didn't go
+    // through the new ingest pipeline. This can happen in new self-hosted upgrades.
```
Comment (aliu3ntry) [inline static/app/components/feedback/useFetchFeedbackData.tsx:44]: I'm confused when exactly the project gets dropped, and what's this have to do with self-hosted?

Comment (ryan953) [reply static/app/components/feedback/useFetchFeedbackData.tsx:44]: What's happening on self-hosted is that people are not having `issueData.project` set for all their feedback instances. 
I hope & believe that it's because old feedbacks (not processed by the new pipelines) are still in the database and don't have everything wired up because they were ingested using the old pipeline. There's no migration to fix things up.

**Review by aliu39 — APPROVED** [review]
