### PR TITLE
fix(replay): fix replay count tab query

### LINKED ISSUE #79086: Replays tab on Transaction summary doesn't load the count
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

[Slack thread](https://sentry.slack.com/archives/C03USURCFBJ/p1728914108645249)

Looking at errors on this endpoint, no huge amount of events. Searching by the user who reported I found no events.

https://sentry.sentry.io/issues/?project=1&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20transaction%3A%2Fapi%2F0%2Forganizations%2F%7Borganization_id_or_slug%7D%2Freplay-count%2F&referrer=issue-list&sort=date&statsPeriod=14d&viewId=default0

### Expected Result

Count loads

### Actual Result

Image

### Product Area

Replays

### Link

https://sentry-sdks.sentry.io/performance/summary/replays/?project=5572016&statsPeriod=90d&transaction=GET%20https%3A%2F%2Fapp.test%2Fhome%2Fhttp

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by michellewzhang**
sometimes transaction names have spaces. having something in the query like:

```
transaction:[/alerts/]
``` 
is fine, but

```
transaction:[GET 123]
``` 
breaks. this PR modifies the query so that we can query for transaction names with spaces and make our `replay-count` endpoint happy.

something like
```
transaction:["GET 123"]
``` 
now works.

before: 
SCR-20241015-kyit
see endpoint failure
SCR-20241015-kyns
this results in badge with no number.

after: 
SCR-20241015-kyju
endpoint is happy, badge shows 0 as expected
SCR-20241015-kypo

closes https://github.com/getsentry/sentry/issues/79086

### CODE REVIEW

**Review by c298lee — APPROVED** [review]

File: static/app/utils/replayCount/useReplayCount.tsx [hunk 1]
```diff
@@ -62,7 +62,10 @@ export default function useReplayCount({
             data_source: dataSource,
             project: -1,
             statsPeriod,
-            query: `${fieldName}:[${ids.join(',')}]`,
+            query:
+              fieldName === 'transaction'
```
Comment (billyvg) [inline static/app/utils/replayCount/useReplayCount.tsx:66]: Is this only applicable to `transaction`? Would it be safe(r) to quote for all fields?

**Review by billyvg — APPROVED** [review]

File: static/app/utils/replayCount/useReplayCount.tsx (hunk 1 above)
Comment (michellewzhang) [reply static/app/utils/replayCount/useReplayCount.tsx:66]: SCR-20241015-lusn
seems to break if we do it for all cases, since `issue.id` expects number(s) not string
