### PR TITLE
fix(feedback) Improve accessibility for user feedback

### LINKED ISSUE #23288: Accessibility Issues with User Feedback Widget
- [x] Review the documentation: https://docs.sentry.io/
- [x] Search for existing issues: https://github.com/getsentry/sentry-javascript/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-javascript/releases
- [x] Provide a link to the affected event from your Sentry account <- Not applicable

## Package + Version

- [x] `@sentry/browser`
- [ ] `@sentry/node`
- [ ] `raven-js`
- [ ] `raven-node` _(raven for node)_
- [ ] other:

### Version:

```
5.29.2
```

## Description

The dialog opened by Sentry.showReportDialog is not accessible. See the [WAI-ARIA Authoring Practices guidance on accessible modals](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal).

Some specific issues which need to be fixed:

- `Tab` and `Shift` + `Tab` should not move focus to elements outside the modal (they currently can)
- When the modal loads, the first input of the form should receive focus (currently nothing in the modal is focused when the modal loads)
- The "Close" button is rendered using an anchor tag without an `href` attribute. As a result it is not in the tab sequence and keyboard users are not able to use it. To fix this, a `button` element should be used instead. Since the element does not cause navigation, the `button` element will also have the proper semantics and will improve the experience for users of assistive technology.
- The outermost div of the dialog needs `role` set to `dialog`
- The outermost div of the dialog needs `aria-modal` set to `true`
- The outermost div of the dialog needs `aria-labelledby` set to the `id` of the modal's h2

### PR DESCRIPTION
**Pull request by markstory**
* Add missing aria attributes to help screenreaders.
* Add tab/focus trapping to help keyboard users.
* Make `close` button able to receive tab focus.

Fixes #23288

### CODE REVIEW

File: src/sentry/templates/sentry/error-page-embed.js [hunk 1]
```diff
@@ -87,25 +91,47 @@
...
-    var linkTags = this.element.getElementsByTagName('a');
-
-    var onclickHandler = function(e) {
+    var cancelHandler = function(e) {
       e.preventDefault();
       self.close();
     };
-
-    for (i = 0; i < linkTags.length; i++) {
-      if (linkTags[i].className === 'close') {
```
Comment (EvanPurkhiser) [inline src/sentry/templates/sentry/error-page-embed.js:98]: nice cleanup, that's some wonky code

File: src/sentry/templates/sentry/error-page-embed.js [hunk 2]
```diff
@@ -87,25 +91,47 @@
...
+            event.preventDefault();
+          }
+        }
+      }
+      document.addEventListener('keydown', handleFocus);
+
+      setTimeout(function () {
+        firstFocus.focus();
+      }, 1)
+    }
```
Comment (EvanPurkhiser) [inline src/sentry/templates/sentry/error-page-embed.js:134]: Clever way to trap focus, feels like the browser should have something built in for this.

**Review by evanpurkhiser — APPROVED** [review]

File: src/sentry/templates/sentry/error-page-embed.js (hunk 1 above)
Comment (markstory) [reply src/sentry/templates/sentry/error-page-embed.js:98]: Looks like a getElementsByClassName() from before that was a thing.

File: src/sentry/templates/sentry/error-page-embed.js (hunk 2 above)
Comment (markstory) [reply src/sentry/templates/sentry/error-page-embed.js:134]: I wish there was a built-in way.

File: src/sentry/templates/sentry/error-page-embed.js (hunk 1 above)
Comment (EvanPurkhiser) [reply src/sentry/templates/sentry/error-page-embed.js:98]: Might have been a browser compatibly thing. Since this is a piece of code that needs to be highly compatible

**Review by priscilawebdev — APPROVED** [review]
