### PR TITLE
fix(issues): Allow all projects "-1" in query parameters

### LINKED ISSUE #62089: Shareable All Projects links
### Problem Statement

Opening this issue on behalf of a customer:

> When I click "Unselect All" it changes to "All Projects" and the URL gains an extra query param project=-1, but if I refresh the page or send that link to someone else, the project=-1 query param gets ignored/removed and it always defaults to My Projects.
I've had this happen a few times where I try to send someone a link but the Sentries aren't in their projects so they see nothing, and I need to explain to them how to Unselect All.

### Solution Brainstorm

If the project param =-1 in a new session, preserve that selection

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2051) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by scttcper**
Previously it was being overridden with "my projects" aka `[]` instead of `[-1]`

fixes #62089

### CODE REVIEW

File: static/app/actionCreators/pageFilters.tsx [hunk 1]
```diff
@@ -212,21 +216,25 @@ export function initializeUrlState({
    * IDs (project was deleted/moved to another org) can still exist in local storage or
    * shared links.
    */
-  function validateProjectId(projectId: number) {
+  function validateProjectId(projectId: number): boolean {
+    if (projectId === ALL_ACCESS_PROJECTS) {
```
Comment (malwilley) [inline static/app/actionCreators/pageFilters.tsx:220]: Do we need to validate that the user can use all projects here? Or is that validation done elsewhere?

**Review by malwilley — APPROVED** [review]
Good fix
