### PR TITLE
fix(ddm): metric select focus

### LINKED ISSUE #65379: DDM: Search bar shouldn't lose focus when hovering over metrics

### PR DESCRIPTION
**Pull request by obostjancic**
- closes #65379

Before:

https://github.com/getsentry/sentry/assets/86684834/6d2f14e5-6f00-4ff6-8972-7ceb9e2da1b8

After:

https://github.com/getsentry/sentry/assets/86684834/c01754d2-d8a2-40e2-9149-220e303d4866

### CODE REVIEW

File: static/app/components/menuListItem.tsx [hunk 1]
```diff
@@ -259,11 +259,13 @@ export const InnerWrap = styled('div', {
...
 
   font-size: ${p => p.theme.form[p.size ?? 'md'].fontSize};
+  color: ${getTextColor};
 
-  &,
   &:hover {
     color: ${getTextColor};
+    background: ${p => p.theme.backgroundSecondary};
   }
+
```
Comment (vuluongj20) [inline static/app/components/menuListItem.tsx:268]: Adding this leads to confusing behaviors like here:
image
…where the second item was focused on via the keyboard, and the fourth item was focused on by hovering over it.

Comment (vuluongj20) [reply static/app/components/menuListItem.tsx:268]: In the future we can better address this by implementing a [combobox](https://codesandbox.io/p/sandbox/hardcore-moon-xzc4r?file=%2Fsrc%2FSearchAutocomplete.tsx) pattern, but that's way more complicated and should be left for later.

**Review by ArthurKnaus — APPROVED** [review]
👍
