### PR TITLE
Fix(metrics) Filter autocomplete fix

### LINKED ISSUE #75437: Environment is not searchable in autocomplete

### PR DESCRIPTION
**Pull request by vgrozdanic**
Autocomplete wasn't showing all the data it could have because of the bug in one custom hook.
Also some fields were excluded by default (e.g. environment) which is now also fixed.

Closes https://github.com/getsentry/sentry/issues/75437

Before
image

Now
image

### CODE REVIEW

File: static/app/views/settings/projectMetrics/metricsExtractionRuleForm.tsx [hunk 1]
```diff
@@ -526,6 +526,7 @@ export function MetricsExtractionRuleForm({
                               placeholder={t('Add span attributes')}
                               organization={organization}
                               supportedTags={supportedTags}
+                              excludedTags={[]}
```
Comment (priscilawebdev) [inline static/app/views/settings/projectMetrics/metricsExtractionRuleForm.tsx:529]: do we need to inform an empty array here?

**Comment by priscilawebdev** [comment]
love that you added 'before' and 'after' screenshots <3

File: static/app/views/settings/projectMetrics/metricsExtractionRuleForm.tsx (hunk 1 above)
Comment (vgrozdanic) [reply static/app/views/settings/projectMetrics/metricsExtractionRuleForm.tsx:529]: Yes, to override the default from the component. E.g. component filters out "environment" tag by default, and we don't want that behaviour

**Review by mjq — APPROVED** [review]

**Comment by priscilawebdev** [comment]
it is not related to your PR but the search feels slow + when I add a '.', for example, 'browser.name' ...the "." position looks odd 

https://github.com/user-attachments/assets/ec0bbc81-6cea-4317-a147-2bd6c1084d41

**Review by priscilawebdev — APPROVED** [review]
lgtm
