### PR TITLE
ref(stacktrace): Ensure frame labels stay aligned

### LINKED ISSUE #50695: Stack trace: Ensure that frame labels (In App or System) stay aligned
## Problem

When some frames can be expanded but others cannot, the frame labels are not aligned:

Image

[Sample event](https://sentry-sdks.sentry.io/issues/3765296906/events/bb35cfa5887840648dd7bd71bb7646ed/)

## Solution

When a frame cannot be expanded, show an empty space there so that the right-aligned labels stay aligned.

### PR DESCRIPTION
**Pull request by 17hogeju**
Closes https://github.com/getsentry/sentry/issues/50695

When a frame cannot be expanded, show an empty space there so that the right-aligned labels stay aligned.

Before: 
Screenshot 2023-07-13 at 2 04 17 PM

After:
Screenshot 2023-07-13 at 2 07 31 PM

### CODE REVIEW

File: static/app/components/events/interfaces/frame/deprecatedLine.tsx [hunk 1]
```diff
@@ -486,7 +486,7 @@ const NativeLineContent = styled('div')<{isFrameAfterLastNonApp: boolean}>`
 
 const DefaultLine = styled('div')`
   display: grid;
-  grid-template-columns: 1fr auto auto;
+  grid-template-columns: 1fr auto ${space(2)} + ${space(1)}; /* sm icon size + left margin */
```
Comment (malwilley) [inline static/app/components/events/interfaces/frame/deprecatedLine.tsx:489]: @17hogeju So this seems to work, but instead of adding the `space(1)` to account for the toggle button's left margin, I'd rather remove the `margin-left` from the `ToggleContextButton` styles.

It looks like if you do that, the toggle button does not fit snugly to the right side, however! You can use `justify-self` to change the justification to `end` for the toggle button to correct that.

**Review by malwilley — CHANGES_REQUESTED** [review]

File: static/app/components/events/interfaces/frame/deprecatedLine.tsx (hunk 1 above)
Comment (17hogeju) [reply static/app/components/events/interfaces/frame/deprecatedLine.tsx]: > Also fyi - the + here doesn't do what you think it should do, since it is outside of the ${}. The + gets stripped out (since it is not valid css) and it adds an additional column

Makes sense. I thought that might be the case.

File: static/app/components/events/interfaces/frame/deprecatedLine.tsx [hunk 2]
```diff
@@ -305,7 +305,11 @@ export class DeprecatedLine extends Component<Props, State> {
               {t('Suspect Frame')}
             </SuspectFrameTag>
           ) : null}
-          {!data.inApp ? <Tag>{t('System')}</Tag> : <Tag type="info">{t('In App')}</Tag>}
+          {!data.inApp ? (
+            <InAppTag>{t('System')}</InAppTag>
```
Comment (malwilley) [inline static/app/components/events/interfaces/frame/deprecatedLine.tsx:309]: `InAppTag` is a bit of a misnomer here since it can have system tags too, but I'll allow it since we are going to remove those soon 😄

**Review by malwilley — APPROVED** [review]
