### PR TITLE
bug(replays): Show zero count in the Issues>Replays tab after data is loaded

### LINKED ISSUE #41653: Bug: Issue>Replay Tab count is sometimes not loading
example issue: https://sentry.io/organizations/sentry/issues/3755306451/?project=4504044640927744

Image

### PR DESCRIPTION
**Pull request by ryan953**
**Before** we were always showing a loading placeholder in the Issues>Replay tab if the count was zero:
SCR-20221122-cyq

**After:**
SCR-20221122-cys

The response included `query: !replayId:"" issue.id:[3755306451]`
But the server doesn't return the fields for `3755306451` if the count is zero.

Here's the response without any keys:
SCR-20221122-cyf

And here's the expected response, with the counts present:
SCR-20221122-d19

Fixes #41653

### CODE REVIEW

File: static/app/components/replays/useReplaysCount.tsx [hunk 1]
```diff
@@ -17,18 +17,35 @@ type Options = {
...
+  const zeroCounts = useMemo(() => {
+    const ids = toArray(groupIds || []);
+    const names = toArray(transactionNames || []);
+    return ([] as string[])
+      .concat(ids)
+      .concat(names)
+      .reduce((record, key) => {
+        record[key] = 0;
+        return record;
+      }, {} as CountState);
```
Comment (scttcper) [inline static/app/components/replays/useReplaysCount.tsx:37]: you can reduce the amount of typecasting
```suggestion
    return [...ids, ...names].reduce<CountState>((record, key) => {
      record[key] = 0;
      return record;
    }, {});
```

**Review by NisanthanNanthakumar — APPROVED** [review]
