### PR TITLE
fix(replays): Missing Replay URL Bug

### LINKED ISSUE #38008: Bug: Replay URL is blank until you start replaying the recording
The replay URL bar is blank until you start playing the recording. It should have an initial value.

Image

### PR DESCRIPTION
**Pull request by danecando**
### Changes
- Updates timestamp comparison
- Updates the fallback initialUrl to use the first item in the `replayRecord.urls` array

### Notes
It seems like getting the initial URL off the tags property is no longer a valid approach as it's an empty object running the latest versions of the replays SDK

Closes #38008 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by danecando** [comment]
@billyvg this PR does fix the uncontrolled input error since getCurrentUrl should always return a string now the broken version was returning undefined

File: static/app/utils/replays/getCurrentUrl.tsx [hunk 1]
```diff
@@ -16,15 +16,14 @@ function getCurrentUrl(
     crumb => crumb.type === BreadcrumbType.NAVIGATION
   ) as BreadcrumbTypeNavigation[];
 
-  const initialUrl = replayRecord.tags.url;
-  const origin = initialUrl ? new URL(initialUrl).origin : '';
```
Comment (billyvg) [inline static/app/utils/replays/getCurrentUrl.tsx:20]: So I cherry picked this commit during hack week and we still need the original `origin`. Otherwise on https://github.com/getsentry/sentry/pull/38092/files#diff-b3b1434537e36c425cc3761c3ed1c3f57bd4ee3830009f1806ec6a8f735ad304R35 it will preserve the file path.

File: static/app/utils/replays/getCurrentUrl.tsx [hunk 2]
```diff
@@ -20,11 +20,11 @@ function getCurrentUrl(
   const origin = initialUrl ? new URL(initialUrl).origin : '';
 
   const mostRecentNavigation = last(
-    navigationCrumbs.filter(({timestamp}) => +new Date(timestamp || 0) < currentTimeMs)
+    navigationCrumbs.filter(({timestamp}) => +new Date(timestamp || 0) <= currentTimeMs)
   )?.data?.to;
 
   if (!mostRecentNavigation) {
-    return initialUrl;
+    return origin;
```
Comment (ryan953) [inline static/app/utils/replays/getCurrentUrl.tsx:27]: looks like this could still return an empty string, because on line 20 we've got the ternary ` a ? b : '';`

File: static/app/utils/replays/getCurrentUrl.tsx [hunk 3]
```diff
@@ -20,11 +20,11 @@ function getCurrentUrl(
   const origin = initialUrl ? new URL(initialUrl).origin : '';
 
   const mostRecentNavigation = last(
-    navigationCrumbs.filter(({timestamp}) => +new Date(timestamp || 0) < currentTimeMs)
+    navigationCrumbs.filter(({timestamp}) => +new Date(timestamp || 0) <= currentTimeMs)
```
Comment (ryan953) [inline static/app/utils/replays/getCurrentUrl.tsx:23]: is this going to be one of the first items in the array more often now?

Comment (danecando) [reply static/app/utils/replays/getCurrentUrl.tsx:23]: This fixed the issue in several cases. I still saw some missing a URL with the current default origin though.

File: static/app/utils/replays/getCurrentUrl.tsx [hunk 4]
```diff
@@ -17,14 +17,14 @@ function getCurrentUrl(
   ) as BreadcrumbTypeNavigation[];
 
   const initialUrl = replayRecord.tags.url;
-  const origin = initialUrl ? new URL(initialUrl).origin : '';
+  const origin = initialUrl ? new URL(initialUrl).origin : replayRecord.urls[0] ?? '';
```
Comment (billyvg) [inline static/app/utils/replays/getCurrentUrl.tsx:20]: I think initialUrl should be what you had previously (`urls[0]`), and `origin` remains the same.

Also if `initialUrl` is invalid URL here, it will throw

Comment (danecando) [reply static/app/utils/replays/getCurrentUrl.tsx:20]: Are we not capturing the url tag anymore? From recent replays it looks like we're not. I've been looking through SDK source this morning trying to figure out whats what because the getCurrentUrl tests need to be updated as well. Might need to update the mocks

Comment (billyvg) [reply static/app/utils/replays/getCurrentUrl.tsx]: Do you have access to this? https://github.com/getsentry/replay-backend/blob/main/blueprints/api.md#replays-organizationsorganization_slugreplays -- we don't capture it as a tag because we collect a list of URLs for the replay so it's a bit redundant.

**Comment by ryan953** [comment]
tests are failing

**Review by ryan953 — APPROVED** [review]
