### PR TITLE
fix(releases): Fix Release Health banner

### LINKED ISSUE #86684: [RELEASES] Fix logic for showing release health banner
Image

This is a nextjs app and it should already have everything for release health instrumented:
https://minarorg-zl.sentry.io/releases/

It's also visible in the screenshot that release rows have session data.

I'd expect this banner not to be visible in this case.

### PR DESCRIPTION
**Pull request by ryan953**
I think the problem is that we had a cached project, so `hasSessions` can be `false` when it shouldn't be (anymore).

This re-fetches the project before we run the logic.
We'll show the banner if:
- there's a selected project
- AND there are some releases
- AND we fetch the project without errors
- AND the project does not have sessions
- AND the project platform can have releases

Fixes #86684

### CODE REVIEW

File: static/app/views/releases/list/releaseHealthCTA.tsx [hunk 1]
```diff
@@ -35,43 +44,35 @@ export default function ReleaseHealthCTA({
     }
   }, [organization, selection]);
 
-  if (!selectedProject || selectedProject?.hasSessions !== false || !releases?.length) {
+  if (isPending || isError) {
     return null;
   }
```
Comment (ryan953) [inline static/app/views/releases/list/releaseHealthCTA.tsx:49]: this `selectedProject?.hasSessions !== false` was so hard to parse quickly. Wrote it as `project.hasSessions` below (because we use the freshly fetched project too).

**Review by billyvg — APPROVED** [review]
