### PR TITLE
fix(workflow): fix assignee selector loading 

### LINKED ISSUE #4434: Assign-to-user dropdown does not populate when loading an issue directly
If I open the url /project/issues/1234/ directly, the "assigned" dropdown is empty:

image

If I first open another url such as /project/, and then navigate to /project/issues/1234/, then the dropdown is filled with users.

### PR DESCRIPTION
**Pull request by billyvg**
fix(workflow): fix assignee selector loading
* problem was due to `shouldComponentUpdate`
* now displays a loader if member list request does not finish before selector is first opened
* still does NOT update assignee selector if `MemberListStore` loads new members
* cleaned up deprecated react string refs

Fixes GH-4434

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

File: src/sentry/static/sentry/app/components/assigneeSelector.jsx [hunk 1]
```diff
@@ -62,7 +64,7 @@ const AssigneeSelector = React.createClass({
 
     return {
       assignedTo: group.assignedTo,
-      memberList: MemberListStore.getAll(),
+      memberList: MemberListStore.loaded ? MemberListStore.getAll() : null,
```
Comment (MaxBittker) [inline src/sentry/static/sentry/app/components/assigneeSelector.jsx]: what are your thoughts on using two variables for memeberlist,one to hold isloaded state, one to hold the data? versus having it be null. just curious, not saying it's def better

Comment (billyvg) [reply src/sentry/static/sentry/app/components/assigneeSelector.jsx]: I didn't want to expose `loaded` at all, I think I prefer that components can derive basic state based on data type (especially when data comes from async source). Initially I wanted the MemberListStore to initialize `items` as null instead of an empty array, but that would involve a larger change with the other components, so I opted for this instead. When you have a separate `loading` property, it's just another piece of state that you need to sync, i.e. on api response, instead of just updating data, you need to also update `isLoaded`.

**Review by MaxBittker — APPROVED** [review]
nice fix! hopefully people on slow connections have a better time now.
