### PR TITLE
fix(replays): show explanation tooltip if replay URL contains Filtered

### LINKED ISSUE #52448: It can be confusing to users when there is a "[Filtered]" portion inside the url, if they copy+paste the url it won't actually work
When there is "[Filtered]" content inside a url, using copy+paste might not be the best idea.

Image

We should disable the copy button, and add a tooltip to explain why it's disabled. People should still be able to click on the whole url to highlight it, scroll to see the right side, and copy it themselves. 

Hopefully by disabling the button and having the tooltip, people can be more aware that the url won't work as-is.

### PR DESCRIPTION
**Pull request by michellewzhang**
Normal URL:
SCR-20230828-nrmg

URL contains [Filtered]:
SCR-20230828-opjf

Closes https://github.com/getsentry/sentry/issues/52448

### CODE REVIEW

File: static/app/components/replays/replayCurrentUrl.tsx [hunk 1]
```diff
@@ -27,6 +29,20 @@ function ReplayCurrentUrl() {
     );
   }
 
+  if (url.includes('[Filtered]')) {
+    return (
+      <Tooltip
+        title={t(
+          'This function is disabled since the URL contains filtered content, which is not a valid path.'
```
Comment (michellewzhang) [inline static/app/components/replays/replayCurrentUrl.tsx:36]: Open to suggestions on improving this wording/explanation!

File: static/app/components/replays/replayCurrentUrl.tsx [hunk 2]
```diff
@@ -27,6 +29,20 @@ function ReplayCurrentUrl() {
     );
   }
 
+  if (url.includes('[Filtered]')) {
+    return (
+      <Tooltip
```
Comment (michellewzhang) [inline static/app/components/replays/replayCurrentUrl.tsx:34]: Disabling the input also means tooltips refuse to show over the disabled copy button, so I'm getting around this by adding a tooltip for the entire input box. i.e. hovering over the URL or the copy button shows the tooltip (only when disabled)

File: static/app/components/replays/replayCurrentUrl.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/components/replays/replayCurrentUrl.tsx:36]: "Copy paste is disabled..."

**Comment by ryan953** [comment]
I like the tooltip. 

When using it, I'm not sure if the whole textbox needs to be disabled though. I still want to scroll the text to see the whole url (which i can do when it's disabled). But disabling it seems like it draws in too much attention.

**Comment by michellewzhang** [comment]
@ryan953 yeah that makes sense -- it's not intuitive that the box/URL is still scrollable since it's disabled, even though it technically; let's see if others have thoughts

File: static/app/components/replays/replayCurrentUrl.tsx (hunk 1 above)
Comment (michellewzhang) [reply static/app/components/replays/replayCurrentUrl.tsx]: updated

File: static/app/components/replays/replayCurrentUrl.tsx [hunk 3]
```diff
@@ -27,6 +29,20 @@ function ReplayCurrentUrl() {
...
+        title={t(
+          'Copy-paste is disabled since the URL contains filtered content, which is not a valid path.'
```
Comment (billyvg) [inline static/app/components/replays/replayCurrentUrl.tsx:36]: It's only copy

```suggestion
          'Copy is disabled because the URL contains filtered content, which can cause it to be invalid.'
```

**Review by billyvg — COMMENTED** [review]
I like the idea of showing tooltip but still allowing them to copy, maybe they have valid reason to copy URL (e.g. URL params are filtered, but root path is sufficient)

**Comment by michellewzhang** [comment]
> I like the idea of showing tooltip but still allowing them to copy, maybe they have valid reason to copy URL (e.g. URL params are filtered, but root path is sufficient)

hmm @ryan953 what are your thoughts on no disable but showing tooltip? 
@billyvg how would you word the tooltip in this case?

**Comment by ryan953** [comment]
> I like the idea of showing tooltip but still allowing them to copy, maybe they have valid reason to copy URL (e.g. URL params are filtered, but root path is sufficient)

> hmm @ryan953 what are your thoughts on no disable but showing tooltip?
@billyvg how would you word the tooltip in this case?

I agree ^


I'd word it like `'Copy The URL contains filtered content, which can cause it to be invalid.'` or something like that

**Comment by billyvg** [comment]
Something like "Warning! URL contains content scrubbed by our PII filters and may no longer be valid."

**Comment by michellewzhang** [comment]
@billyvg @ryan953 removed disable and updated wording on tooltip

**Review by ryan953 — APPROVED** [review]

**Comment by ryan953** [comment]
I like it! thanks for pushing this forward @michellewzhang

**Review by billyvg — APPROVED** [review]
