### PR TITLE
fix(issue-stream): Prevent empty state when triaging entire page

### LINKED ISSUE #45478: Empty inbox illustration shows when an entire page of issues have been triaged
Reproduction steps:

- Go to org with `issue-list-removal-action`
- Navigate to last page of issues
- Select all issues and resolve/ignore

You will see that the issue stream shows the empty illustration even though there are more issues on previous pages.

https://user-images.githubusercontent.com/10888943/223516149-a5a6a3eb-01aa-437f-b8f9-506630d736d6.mp4

### PR DESCRIPTION
**Pull request by malwilley**
Closes https://github.com/getsentry/sentry/issues/45478

Before:

https://user-images.githubusercontent.com/10888943/223574285-c62d68ae-9004-4762-9471-c0616b9c446b.mp4

After:

https://user-images.githubusercontent.com/10888943/223574292-2ff1dfce-ee2e-4502-9de0-ca27d6185243.mp4

### CODE REVIEW

File: static/app/views/issueList/overview.tsx [hunk 1]
```diff
@@ -1099,12 +1099,24 @@ class IssueListOverview extends Component<Props, State> {
...
+    const links = parseLinkHeader(this.state.pageLinks);
+
     GroupStore.remove(itemIds);
-    this.setState(({queryCount}) => ({
+    const queryCount = this.state.queryCount - itemIds.length;
+    this.setState(() => ({
       actionTaken: true,
-      queryCount: queryCount - itemIds.length,
+      queryCount,
     }));
```
Comment (scttcper) [inline static/app/views/issueList/overview.tsx:1109]: this doesn't need to be a function anymore

**Review by scttcper — APPROVED** [review]
