### PR TITLE
fix(clippedbox): Adjust max-height to the content height when revealing

### LINKED ISSUE #61996: Issue detail - KeyValueList on event context data is not fully visible when long list of pairs
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

For this use case:
1. Android Issue with long dependency list in Context
2. Hit "Show more"
3. List stops after X amount of items

- The HTML is still being rendered however the page stops scaling to the right amount of pairs.
- As you can see there are still <tr> elements but we can't scroll down anymore
Screenshot 2023-12-19 at 13 43 44

### Expected Result

either show the whole list or make the list scrollable

### Actual Result

Screenshot 2023-12-19 at 13 43 44

### Product Area

Issues

### Link

_No response_

### DSN

_No response_

### Version

_No response_

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2047) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by malwilley**
Fixes https://github.com/getsentry/sentry/issues/61996

See https://dev.getsentry.net:7999/stories/?name=app/components/clippedBox.stories.tsx

This fixes a couple problems with the ClippedBox component:

1. Content greater than 9999px in height is cut off when revealed
2. The reveal animation speed is inconsistent based on how large the content is

The new logic sets the max-height to the content height when revealing. After the animation finishes, the max-height is cleared so that height changes are reflected.

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]

File: static/app/components/clippedBox.tsx [hunk 1]
```diff
@@ -199,7 +209,11 @@ function ClippedBox(props: ClippedBoxProps) {
   );
 
   return (
-    <Wrapper ref={onWrapperRef} className={props.className}>
+    <Wrapper
+      ref={onWrapperRef}
+      className={props.className}
+      onTransitionEnd={() => clearMaxHeight(wrapperRef)}
```
Comment (JonasBa) [inline static/app/components/clippedBox.tsx:215]: Can we bind to this event from the component and cleanup the listener after the reveal? This way we would avoid this possibly firing multiple times for no reason + we avoid an unstable fn ref

**Review by JonasBa — CHANGES_REQUESTED** [review]

**Comment by JonasBa** [comment]
^ requested changes bc I see it was already approved and don't want the comment to be missed :D

File: static/app/components/clippedBox.tsx (hunk 1 above)
Comment (malwilley) [reply static/app/components/clippedBox.tsx]: Good feedback! That does seem like a safer approach.

Added here, LMK if this is what you were thinking: [`49f71d3` (#62015)](https://github.com/getsentry/sentry/pull/62015/commits/49f71d3ab8d131cc59990321f222815240191194)

While making that change I realized that the height wasn't correct when the wrapper had padding, so I added that as well.

File: static/app/components/clippedBox.tsx [hunk 2]
```diff
@@ -31,9 +56,18 @@ function revealAndDisconnectObserver({
...
-  wrapperRef.current.style.maxHeight = contentRef.current?.clientHeight
-    ? `${contentRef.current.clientHeight}px`
-    : '9999px';
+  const clearMaxHeight = () => {
+    if (wrapperRef.current) {
+      wrapperRef.current.style.maxHeight = 'none';
+    }
+  };
+
+  wrapperRef.current.addEventListener('transitionend', clearMaxHeight, {once: true});
```
Comment (JonasBa) [inline static/app/components/clippedBox.tsx:65]: once: true is ❤️

File: static/app/components/clippedBox.tsx [hunk 3]
```diff
@@ -29,7 +56,18 @@ function revealAndDisconnectObserver({
...
+
+  const revealedWrapperHeight =
+    (contentRef.current?.clientHeight || 9999) + calculateAddedHeight({wrapperRef});
+
+  wrapperRef.current.style.maxHeight = `${revealedWrapperHeight}px`;
```
Comment (JonasBa) [inline static/app/components/clippedBox.tsx:70]: I wonder if we can be smarter about this, querying the DOM on L68 will cause layout thrashing which can snowball into a perf issue if a page has many of these, but I think we should worry about this later since we have profiling instrumentation and can monitor this.

**Review by JonasBa — APPROVED** [review]
