### PR TITLE
fix(replays): only show overflow on replay cell

### LINKED ISSUE #58618: Replay Table has overflow scroll
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to sentry.com and open the replay window.
2. Be on Windows with Chrome 118

### Expected Result

Just see a normal table without scrollbar like it used to be a few days ago

### Actual Result

image

### Product Area

Replays

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by michellewzhang**
Only apply `overflow: scroll` to the replay cell, not all the table cells. Also fixed some overflow with the calendar icon and the shortId.

Before:
SCR-20231023-litu

After:

https://github.com/getsentry/sentry/assets/56095982/ffc2e4b4-ad43-4776-9bbe-9908b4848cd6

Fixes https://github.com/getsentry/sentry/issues/58618

### CODE REVIEW

**Review by JoshFerge — APPROVED** [review]

File: static/app/views/replays/replayTable/tableCell.tsx [hunk 1]
```diff
@@ -634,7 +638,7 @@ const Item = styled('div')<{isArchived?: boolean; isWidget?: boolean}>`
       ? `padding: ${space(0.75)} ${space(1.5)} ${space(1.5)} ${space(1.5)};`
       : `padding: ${space(1.5)};`};
   ${p => (p.isArchived ? 'opacity: 0.5;' : '')};
-  overflow: scroll;
+  ${p => (p.isReplayCell ? 'overflow: scroll;' : '')};
```
Comment (ryan953) [inline static/app/views/replays/replayTable/tableCell.tsx:641]:
```suggestion
  ${p => (p.isReplayCell ? 'overflow: auto;' : '')};
```

not sure about this, but `scroll` might mean scrollbars appear all the time for folks, while auto toggles them as needed

**Review by ryan953 — APPROVED** [review]

File: static/app/views/replays/replayTable/tableCell.tsx (hunk 1 above)
Comment (michellewzhang) [reply static/app/views/replays/replayTable/tableCell.tsx]: `auto` works!
