### PR TITLE
fix(replays): Fix query for replays on issues details

### LINKED ISSUE #37940: Make sure the Tabs on Transaction/Summary and Issue/Details show the correct count of replays
You're going to see more than `1`:

Screen Shot 2022-08-17 at 12 05 28 PM

### PR DESCRIPTION
**Pull request by ryan953**
Fixes #37940

### CODE REVIEW

File: static/app/views/organizationGroupDetails/groupDetails.tsx [hunk 1]
```diff
@@ -609,7 +616,7 @@ class GroupDetails extends Component<Props, State> {
           project={project as Project}
           event={event}
           group={group}
-          replaysCount={replaysCount}
+          replaysCount={undefined}
```
Comment (ryan953) [inline static/app/views/organizationGroupDetails/groupDetails.tsx:619]: I've disabling the count in the tab because it's based on the number of errors that link to replays, but some of those replays might not exist

Before:
Screen Shot 2022-09-06 at 2 42 34 PM

File: static/app/views/organizationGroupDetails/groupDetails.tsx [hunk 2]
```diff
@@ -393,20 +395,23 @@ class GroupDetails extends Component<Props, State> {
...
-      fields: ['count()'],
-      query: `issue.id:${groupId}`,
-      projects: [],
-    });
+    const eventView = EventView.fromNewQueryWithLocation(
+      {
+        id: '',
+        name: `Errors within replay`,
+        version: 2,
+        fields: ['id', 'replayId'],
```
Comment (billyvg) [inline static/app/views/organizationGroupDetails/groupDetails.tsx:409]: Do you need `id` here?

File: static/app/views/organizationGroupDetails/groupDetails.tsx [hunk 3]
```diff
@@ -393,20 +395,23 @@ class GroupDetails extends Component<Props, State> {
...
+        query: `issue.id:${groupId} !replayId:""`,
+        projects: [],
```
Comment (billyvg) [inline static/app/views/organizationGroupDetails/groupDetails.tsx:411]: Does EventView add the current project when querying?

If not: TODO: add current issue detail's project here

File: static/app/views/organizationGroupDetails/groupDetails.tsx [hunk 4]
```diff
@@ -415,14 +420,14 @@ class GroupDetails extends Component<Props, State> {
         eventView.getEventsAPIPayload(location)
       );
 
-      const replaysCount = data.data[0]['count()'].toString();
-
+      const ids = data.data.map(record => String(record.replayId));
```
Comment (billyvg) [inline static/app/views/organizationGroupDetails/groupDetails.tsx:423]: You could add a `count()` field and backend will group by `replayId`, so you'll have unique replayIds: https://sentry.io/organizations/sentry/discover/results/?field=replayId&field=count%28%29&name=RequestError%3A+GET+%22%2Fissues%2F3558727218%2Fevents%2Flatest%2F%22+200&project=11276&query=issue.id%3A3472704105+%21replayId%3A%22%22&sort=-replayId&statsPeriod=14d&yAxis=count%28%29

File: static/app/views/organizationGroupDetails/groupDetails.tsx (hunk 1 above)
Comment (billyvg) [reply static/app/views/organizationGroupDetails/groupDetails.tsx:619]: IMO having an incorrect count (bug) is better than having no count (missing feature). At least with the count it'll accomplish its job and getting people to click into the tab.

**Review by billyvg — APPROVED** [review]

File: static/app/views/organizationGroupDetails/groupDetails.tsx (hunk 2 above)
Comment (ryan953) [reply static/app/views/organizationGroupDetails/groupDetails.tsx:409]: `id` seems like it's included no matter what, i thought i would type it out to be explicit.

File: static/app/views/organizationGroupDetails/groupDetails.tsx (hunk 3 above)
Comment (ryan953) [reply static/app/views/organizationGroupDetails/groupDetails.tsx:411]: it gets added from the `location`. I can check to see if this field needs to be typed out here and put a shot of the final url that it builds

File: static/app/views/organizationGroupDetails/groupDetails.tsx (hunk 4 above)
Comment (ryan953) [reply static/app/views/organizationGroupDetails/groupDetails.tsx:423]: oh, nice!

File: static/app/views/organizationGroupDetails/groupDetails.tsx (hunk 1 above)
Comment (ryan953) [reply static/app/views/organizationGroupDetails/groupDetails.tsx:619]: k, but i don't want to take on flak for buggy things

File: static/app/views/organizationGroupDetails/groupDetails.tsx (hunk 3 above)
Comment (ryan953) [reply static/app/views/organizationGroupDetails/groupDetails.tsx:411]: Here's the query: `projects` and `statsPeriod` are coming from `location`:
Screen Shot 2022-09-06 at 3 37 29 PM

I need to type `projects: []` to satisfy TS

File: static/app/views/organizationGroupDetails/groupDetails.tsx (hunk 2 above)
Comment (ryan953) [reply static/app/views/organizationGroupDetails/groupDetails.tsx:409]: ah, this shouldn't be listed there when the `count()` aggregate is used. Coming out now!

File: static/app/views/organizationGroupDetails/groupDetails.tsx (hunk 1 above)
Comment (benvinegar) [reply static/app/views/organizationGroupDetails/groupDetails.tsx]: Let's open a ticket to figure out the correct count?
