### PR TITLE
fix(pageFilters): Fix reset issue when clicking on sidebar link

### LINKED ISSUE #58961: Selecting the issues tab on the sidebar from the issues page is defaulting to all projects
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Be a user of an organization that is on a dev or team plan
2. navigate to the issues page
3. selects the issues tab on the sidebar
4. the error: "You do not have the multi project stream feature enabled" is returned. Clicking the issues tab again seems to be defaulting to all projects. A dev/team plan should never be able to see "All Projects", since selecting multiple projects is a business feature.
https://github.com/getsentry/sentry/assets/99350819/7cbb2d29-4fa3-470b-a42c-a82124431fb1

### Expected Result

No error is returned.

### Actual Result

Error is returned. 

### Product Area

Issues

### Link

https://test-org-7n.sentry.io/issues/?project=4505308060123136

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by vuluongj20**
Fixes https://github.com/getsentry/sentry/issues/58961

### CODE REVIEW

File: static/app/components/organizations/pageFilters/container.tsx [hunk 1]
```diff
@@ -148,6 +149,15 @@ function Container({
...
 
+    // We may need to re-initialize the URL state if we completely clear
+    // out the global selection URL state, for example by navigating with
+    // the sidebar on the same view.
+    if (location.state?.source === SIDEBAR_NAVIGATION_SOURCE) {
+      doInitialization();
+      lastQuery.current = location.query;
+      return;
+    }
+
```
Comment (vuluongj20) [inline static/app/components/organizations/pageFilters/container.tsx:160]: Returning https://github.com/getsentry/sentry/pull/58634/commits/672455a6f1df0ddc0132bcf3cd2bc231c91a7223#r1372393326, but with a more explicit, targeted condition for re-initialization. This way, we don't reinitialize when user clicks "Reset".

**Review by scttcper — APPROVED** [review]
