### PR TITLE
fix(discover) Fix error clearing condition

### LINKED ISSUE #14597: Discover: clearing a condition input causes the page to crash
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
When editing a query in discover, clearing the condition field crashes the page

failure

[What happened]

## Steps to Reproduce

1. run an query with a condition
2. clear the contents of the condition
3. page crashes

Good items to include here include:

### What you expected to happen
field cleared. no crash.

### Possible Solution

The code here: https://github.com/getsentry/sentry/blob/b2b001334b60995c0dc83dce96d7817fedee2d35/src/sentry/static/sentry/app/views/discover/conditions/condition.tsx#L143-L154 should not be using `evt` inside the `setState`, since that callback is executed async. 

You can call `evt.persist()` to get around this. See: https://reactjs.org/docs/events.html#event-pooling

I tried this locally and it partially solves the problem - the crash doesn't happen, but also there's some wonky defaulting happening. I stopped investigating at that point.

### PR DESCRIPTION
**Pull request by markstory**
When clearing the condition field the event needs to be persisted in order for ~Select2~ react-select to have access to the target later on.

Fixes #14597

### CODE REVIEW

File: src/sentry/static/sentry/app/views/discover/aggregations/aggregation.tsx [hunk 1]
```diff
@@ -28,11 +28,11 @@ export default class AggregationRow extends React.Component<
   AggregationProps,
   AggregationState
 > {
+  state = initalState;
```
Comment (markstory) [inline src/sentry/static/sentry/app/views/discover/aggregations/aggregation.tsx]: This was a low hanging eslint warning that I wanted to clean up.

**Comment by EvanPurkhiser** [comment]
It's react-select, not select2

**Review by evanpurkhiser — APPROVED** [review]

**Comment by EvanPurkhiser** [comment]
I am intimately familiar with this comment trying to upgrade to react-select v2 🔪
