### PR TITLE
fix(ddm): display all code locations

### LINKED ISSUE #62000: Show all code locations in the UI

### PR DESCRIPTION
**Pull request by obostjancic**
Displays all "frames" of the last code location.
Adds *temporary* mapping to the intended api response shape (#61995)

closes #62000

### CODE REVIEW

File: static/app/utils/metrics/useMetricsCodeLocations.tsx [hunk 1]
```diff
@@ -28,29 +28,51 @@ export function useMetricsCodeLocations(mri: string | undefined) {
...
   sortCodeLocations(data);
 
   return {data, isLoading, isError, refetch};
 }
 
+const mapToNewResponseShape = (data: ApiResponse) => {
+  if (data.metrics) {
+    return;
+  }
+  // @ts-expect-error
```
Comment (ArthurKnaus) [inline static/app/utils/metrics/useMetricsCodeLocations.tsx:46]: Can you add a comment there?
```
// @ts-expect-error: Why we expect the error
```

**Review by ArthurKnaus — APPROVED** [review]
