### PR TITLE
fix(replays): Use Tooltip in Network Table "Path" column

### LINKED ISSUE #37192: Network Table needs a way to show text that is too long for the table cell
There's no way to see the right side of this url in the network table :(

Image

### LINKED ISSUE #37239: Design Nit: Network tab is hard to read in dark mode
I assume we're using a hard-coded color somewhere instead of a text-specific color (that changes depending on the theme)

Image

### PR DESCRIPTION
**Pull request by jesus4497**
### Changes
- Added tooltip for the column "Path" in the network table in order to show text that is too long. 
- Fixed colors for dark theme

Closes #37192
Closes #37239

image

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/views/replays/detail/network/index.tsx [hunk 1]
```diff
@@ -91,8 +91,16 @@ function NetworkList({replayRecord, networkSpans}: Props) {
...
-          <Text>{network.description || <Placeholder height="24px" />}</Text>
+        <Item color="gray400">
+          <Tooltip
+            title={network.description}
+            isHoverable
+            overlayStyle={{
+              maxWidth: '500px !important',
+            }}
+          >
+            <Text>{network.description || <Placeholder height="24px" />}</Text>
```
Comment (billyvg) [inline static/app/views/replays/detail/network/index.tsx:102]: When would this case exist where `network` is non-empty but `description` is empty? Should that be considered "loading" or is it just an empty description/bad data?

Comment (jesus4497) [reply static/app/views/replays/detail/network/index.tsx]: I think it would be an empty description/bad data - as its type is optional: 
image

Comment (jesus4497) [reply static/app/views/replays/detail/network/index.tsx]: Uhmm I see what you mean, maybe we should replace the placeholder by something like this? 

image

File: static/app/views/replays/detail/network/index.tsx [hunk 2]
```diff
@@ -123,7 +135,7 @@ const Item = styled('div')<{color?: string; numeric?: boolean}>`
   display: flex;
   align-items: center;
   max-height: 28px;
-  color: ${p => p.color || p.theme.subText};
+  color: ${({theme, color}) => (color ? theme[color] || theme.subText : theme.subText)};
```
Comment (danecando) [inline static/app/views/replays/detail/network/index.tsx:138]: This looks a little strange to me is there a reason you couldn't just do `color ? theme[color] : theme.subText` or `theme[color] ?? theme.subText`

File: static/app/views/replays/detail/network/index.tsx (hunk 1 above)
Comment (danecando) [reply static/app/views/replays/detail/network/index.tsx]: IMO if a column just doesn't have data but the row is loaded it shouldn't use a placeholder that is used for loading. Just leave it blank or maybe some default text like _(No description)_

Comment (jesus4497) [reply static/app/views/replays/detail/network/index.tsx]: This is the result!

image

Comment (danecando) [reply static/app/views/replays/detail/network/index.tsx]: I'm just giving my thoughts maybe Ryan or Billy have a better idea or opinion on it. I think if we do keep something like that I would def dim the text at the least maybe make it smaller since it's a not important piece of info in the table row

Comment (jesus4497) [reply static/app/views/replays/detail/network/index.tsx]: Yeah imo this looks good, it definitely better than what I had before 
image

File: static/app/views/replays/detail/network/index.tsx [hunk 3]
```diff
@@ -181,12 +196,14 @@ const StatusPlaceHolder = styled(Placeholder)`
...
-const Text = styled('p')`
+const Text = styled('p')<{dimmed?: boolean; italic?: boolean}>`
   padding: 0;
   margin: 0;
   text-overflow: ellipsis;
   white-space: nowrap;
   overflow: hidden;
+  ${p => p.italic && 'font-style: italic;'}
+  ${p => p.dimmed && `color: ${p.theme.subText};`}
 `;
```
Comment (billyvg) [inline static/app/views/replays/detail/network/index.tsx:207]: Instead of introducing props and creating dynamic styles for this styled component, it would be better to extend and create a new component

```suggestion
const EmptyText = styled(Text)`
  font-style: italic;
  color: ${p => p.theme.subText};
`;
```

File: static/app/views/replays/detail/network/index.tsx [hunk 4]
```diff
@@ -119,11 +133,12 @@ function NetworkList({replayRecord, networkSpans}: Props) {
...
 
-const Item = styled('div')<{color?: string; numeric?: boolean}>`
+const Item = styled('div')<{center?: boolean; color?: string; numeric?: boolean}>`
   display: flex;
   align-items: center;
+  ${p => p.center && 'justify-content: center;'}
   max-height: 28px;
-  color: ${p => p.color || p.theme.subText};
+  color: ${({theme, color}) => theme[color || ''] ?? theme.subText};
   border-radius: 0;
```
[the remark this answers is not in the document]
Comment (jesus4497) [reply static/app/views/replays/detail/network/index.tsx]: `max-height` was the only one out of these that was not extra - fixed!

**Review by ryan953 — APPROVED** [review]
