### PR TITLE
fix(project details): Drop fe-side crash free rate calculations

### LINKED ISSUE #58396: Mismatch crash free sessions/users values on browser and API for the same time frame
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Select a project and time frame and observe the Crash Free Sessions and Crash Free Users
URL: https://<org_slug>.sentry.io/projects/<project>/?end=2023-09-30T23%3A59%3A59&environment=<environment>&project=<project_id>&start=2023-09-01T00%3A00%3A00&utc=true
image
2. Call the API for the same values in the same timeframe 
URL: https://sentry.io/api/0/organizations/<org_slug>/sessions/?project=<project_id>&field=crash_rate(user)&field=crash_free_rate(user)&field=crash_rate(session)&field=crash_free_rate(session)&start=2023-09-01T00:00:00&end=2023-09-30T23:59:59&environment=<environment>&utc=true
Screenshot 2023-10-18 at 2 47 04 PM

Observe the Crash Free Sessions and Crash Free Users are not the same:

Browser returns:
Crash Free Session Rate: 99.979%
Crash Free User Rate: 99.281%
API returns:
Crash Free Session Rate: 99.978%
Crash Free User Rate: 99.277%

The same issue was discussed [here](https://sentry.slack.com/archives/C011TCYRLF6/p1697564146967759).

### Expected Result

 The Crash Free Sessions and Crash Free Users values are the same via the API and Sentry browser.

### Actual Result

 The Crash Free Sessions and Crash Free Users values are not the same via the API and Sentry browser.

### Product Area

Projects - Project Details

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by ArthurKnaus**
Drop FE side "crash free session rate" and "crash free user rate" calculations in the project details view.
Instead the view now uses the fields `crash_free_rate(user)` & `crash_free_rate(session)` when querying the sessions API.

- closes https://github.com/getsentry/sentry/issues/58396

### CODE REVIEW

File: static/app/views/projectDetail/charts/projectSessionsChartRequest.tsx [hunk 1]
```diff
@@ -124,19 +124,23 @@ class ProjectSessionsChartRequest extends Component<
           query: queryParams,
         }),
       ];
-      // for users, we need to make a separate request to get the total count in period
-      if (displayMode === DisplayModes.STABILITY_USERS) {
+      // for crash free sessions and users, we need to make a separate request to get the total count in period
```
Comment (ArthurKnaus) [inline static/app/views/projectDetail/charts/projectSessionsChartRequest.tsx:127]: @matejminar Is there a way to solve this in one request?

Comment (matejminar) [reply static/app/views/projectDetail/charts/projectSessionsChartRequest.tsx:127]: you can ask API for more fields than one (so you can ask for count AND crash-free), but the problem is that the chart is requesting double the needed period (for the previous backdrop)

in theory, you could add count field to the request that top cards are making and use that

**Review by matejminar — APPROVED** [review]
