### PR TITLE
bug(issues): Remove the cursor query param when navigating Issue tabs

### LINKED ISSUE #41791: Bug: cursor query parameter interferes with Replay tab query
Seen in this replay here: https://sentry.io/organizations/sentry/replays/javascript:27b130cf7e7c429c8f804de5c486492f/?referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&t_main=memory

when a user navigates to the "all events" tab, then clicks to the next page, activating the cursor, the query parameter `?cursor=0%3A50%` gets added to the URL. then, when they navigate to the replays tab, this cursor is added to the query, which will skip the first 50 replays, and make the count incorrect (and even show 0 replays if there are less than 50!)

Originially reported here by @jas-kas  https://github.com/getsentry/replay-backend/issues/190#issuecomment-1329273694

### PR DESCRIPTION
**Pull request by ryan953**
Fixes issue where switching in/out of the Issue>All Events tab can cause query params to persist on the next page.

**Context**
These three tabs all use the `?cursor=` query param: 'All Events', 'Grouping', Replays'. When you switch between the tabs the cursor needs to be reset; otherwise you could be looking at page 10 of the All Events tab, but there aren't even 10 pages in the Grouping table.

**Current State**
To solve this problem the Grouping tab had two bits of code: the `handleRouteLeave()` callback and also `updateUrlWithNewLevel()`. This meant that moving _out_ of "Grouping" into another Tab would strip the grouping specific query params. Also mvoing _into_ "Grouping" would reset the params if both were not set, so Grouping could start over.

This worked when only All Events and Grouping used the same query param. But now that Replays tab is here there are more combinations of to/from links. 
For example, a weird interaction that's happening right now is:
1. Visit 'All Events' Tab
  - Paginate to to the next set of data
2. Visit 'Merged Issues' Tab 
  - notice that `?cursor` is still in the url
3. Go back to 'All Events' 
  - notice that you're still on page 2!
4. Visit 'Grouping'
  - notice you're at page 1
  - Paginate to the next set of data (might need use the "more issues" slider)
5. Visit 'Merged Issues' again
  - notice that `?cursor` is _not_ in the url
6. Go back to 'Grouping'
  - notice that you're back on page 1

**What's changed**
This PR makes it so that each of these three pages adopts the `handleRouteLeave()` method so that query params don't bleed from one tab to the next.

All three tabs need to use this, but i'll add it to Replays in a followup PR because there's some other issues with pagination there right now. #merge-conflicts

Fixes #41791

### CODE REVIEW

File: static/app/utils/useCleanQueryParamsOnRouteLeave.tsx [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+    },
+    [location.pathname, fieldsToClean]
+  );
+
+  useEffect(() => {
+    return browserHistory.listen(onRouteLeave);
+  }, [onRouteLeave]);
+}
+
+export default useCleanQueryParamsOnRouteLeave;
```
Comment (dashed) [inline static/app/utils/useCleanQueryParamsOnRouteLeave.tsx:68]: It'll be nice to have some tests for this hook 👀

Comment (ryan953) [reply static/app/utils/useCleanQueryParamsOnRouteLeave.tsx:68]: can do

File: static/app/utils/useCleanQueryParamsOnRouteLeave.tsx [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+  oldPathname: string;
+}) {
+  const hasSomeValues = fieldsToClean.some(
+    field => newLocation.query[field] !== undefined
+  );
+
+  if (
+    newLocation.pathname === oldPathname ||
+    (newLocation.pathname !== oldPathname && !hasSomeValues)
+  ) {
```
Comment (dashed) [inline static/app/utils/useCleanQueryParamsOnRouteLeave.tsx:27]: You can simplify this to be: 
```suggestion
  if (newLocation.pathname === oldPathname || !hasSomeValues) {
```

Comment (dashed) [reply static/app/utils/useCleanQueryParamsOnRouteLeave.tsx:27]: Simplification according to wolfram alpha: https://www.wolframalpha.com/input?key=&i=a+%7C%7C+%28%21a+%26%26+b%29

**Review by dashed — APPROVED** [review]
