### PR TITLE
fix(replays): Improve console row hovering

### LINKED ISSUE #36014: Bug: Fix Console so that hovering over rows highlights the timestamp in the other components, currently this works when hovering the timestamp
If you hover over a timestamp in the Console component then the `currentHoverTime` is set and the rest of the page lights up 

Example Replay:
https://dev.getsentry.net:7999/organizations/sentry-emerging-tech/replays/ben-test:cd7824017b744d3b88473be9c2f72ebc/#console

Image

Hovered putting the cursor to the left of the timestamp doesn't have the same effect. It should.

Also it looks like the hovered time is wrong, it's probably using `less-than` somewhere, and it should be `less-than-equal`.

### PR DESCRIPTION
**Pull request by jesus4497**
Third approach which combines both #38057 and #37943 ideas. Aims to close #36014.

### Changes
- Same changes as #38057
- Added #37943 idea but with some tweaks, now when hovering it will highlight the closest crumb within 1 second of range in order to avoid this [case](https://github.com/getsentry/sentry/pull/37943#issuecomment-1218669079) which might bring confusion to the user. When hovering into a timestamp that have a crumb within 1 second of range, the bottom line won't appear in order to inform de user which message is occurring at that exact time.

https://user-images.githubusercontent.com/39612839/187756986-1b1487df-7a6d-4519-bf02-dc7cd01c1ad3.mp4

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by danecando** [comment]
I like this a lot better I think it's a lot more clear. It seems to match the behavior of the scrubber 1:1. My only thought is do we really need to side border for timestamps that are within 1 sec with this? Seems like it's not really that important I think the bottom bar is sufficient. 

We'll see what Ryan and Billy think

**Comment by ryan953** [comment]
This is a replacement for the other two:
https://github.com/getsentry/sentry/pull/38057
https://github.com/getsentry/sentry/pull/37943

**Comment by ryan953** [comment]
We should probably only show the left-border when the mouse is hovered inside the network table

currently we're showing both borders, which looks like too many things:
Screen Shot 2022-08-30 at 11 44 51 AM

**Comment by jesus4497** [comment]
> We should probably only show the left-border when the mouse is hovered inside the network table
> 
> currently we're showing both borders, which looks like too many things: Screen Shot 2022-08-30 at 11 44 51 AM

Result!

https://user-images.githubusercontent.com/39612839/187536316-65a145d2-c5a2-4f4f-9d34-250d6e770f02.mp4

**Review by ryan953 — APPROVED** [review]

**Comment by ryan953** [comment]
Wait, there's no hover bar when I hover over the Timeline, but i'm not within 1 second of a console message. I want to see a bar between console messages to represent the cursor position inside the Timeline

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 1]
```diff
@@ -218,6 +231,22 @@ const Common = styled('div')<{
...
+    left: 0;
+    z-index: 1;
+    height: 2px;
+    width: 100%;
+    background-color: ${p => {
+      if (p.isCurrent) {
+        return p.theme.purple300;
+      }
+      return 'transparent';
+    }};
```
Comment (ryan953) [inline static/app/views/replays/detail/console/consoleMessage.tsx:248]:
```suggestion
    background-color: ${p => (p.isCurrent ? p.theme.purple300 : 'transparent')};
```

Comment (jesus4497) [reply static/app/views/replays/detail/console/consoleMessage.tsx]: > Wait, there's no hover bar when I hover over the Timeline, but i'm not within 1 second of a console message. I want to see a bar between console messages to represent the cursor position inside the Timeline

Done!

- Merged master and resolved conflicts
- Changed the bottom line to work as a border bottom instead of a pseudo-element (this was due to some problems with anti-aliasing with the dark mode)

https://user-images.githubusercontent.com/39612839/187756986-1b1487df-7a6d-4519-bf02-dc7cd01c1ad3.mp4

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 2]
```diff
@@ -201,9 +208,24 @@ const Common = styled('div')<{
...
+    if (p.isActive && !p.isOcurring) {
+      return `1px solid ${p.theme.purple200}`;
+    }
+
+    if (p.isLast) {
+      return 'none';
+    }
+
+    return `1px solid ${p.theme.innerBorder}`;
+  }};
```
Comment (ryan953) [inline static/app/views/replays/detail/console/consoleMessage.tsx:228]: nice

**Review by ryan953 — APPROVED** [review]
