### PR TITLE
fix(activity): Update activity message for linked issues

### LINKED ISSUE #77410: Improve activity tab message when linking a Sentry issue to an exsisting Azure issue
### Problem Statement

Currently, when [a Sentry issue](https://org2-w7.sentry.io/issues/5793208489/activity/?project=4507704420139008&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=7) is linked to an Azure issue, the activity tab message is: 
Image
This isn't too clear and has caused confusion with azure issue assignment. 

### Solution Brainstorm

It would be helpful if the message made it clear that the user linked the Sentry issue to an existing Azure issue instead of suggesting a new Azure issue was created. 

Something like the below:
User linked this issue to Azure DevOps issue titled [Error: new next test](https://dev.azure.com/int4sentry/_workitems/edit/5)

### Product Area

Issues

### PR DESCRIPTION
**Pull request by snigdhas**
Use the `new` field added in https://github.com/getsentry/sentry/pull/73069 to update the message shown for the CREATE_ISSUE activity. This should add the distinction of whether an external issue was linked or created. 

Fixes #77410

### CODE REVIEW

**Review by roggenkemper — APPROVED** [review]
ty for adding it to streamline activity too!

File: static/app/views/issueDetails/streamline/sidebar/groupActivityItem.tsx [hunk 1]
```diff
@@ -493,8 +493,15 @@ export default function getGroupActivityItem(
       }
       case GroupActivityType.CREATE_ISSUE: {
         const {data} = activity;
+        let title;
+        if (data.new === true) {
+          title = t('Linked Issue');
+        } else {
+          title = t('Created Issue');
+        }
```
Comment (scttcper) [inline static/app/views/issueDetails/streamline/sidebar/groupActivityItem.tsx:501]: nit - avoids the type of title being `any`
```suggestion
        let title = t('Created Issue');
        if (data.new === true) {
          title = t('Linked Issue');
        }
```

**Review by scttcper — APPROVED** [review]
