### PR TITLE
fix(ui): Use the correct docs link for user feedback docs

### LINKED ISSUE #23551: 404 when attempting to 'Read the Docs' in User Feedback
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

Trying to read documentation on [https://sentry.io/settings/{org-name}/projects/{project-name}/user-feedback/](https://sentry.io/settings/{org-name}/projects/{project-name}/user-feedback/) results in a 404 Page Not Found

## Steps to Reproduce

1. Go to User Feedback settings of a project
2. Attempt to click the 'Read the Docs' button
3. Error 404 resulting

Link to screen recording:
[https://user-images.githubusercontent.com/16801642/106670212-a6a7f880-65a4-11eb-9dfc-aa336ff66420.mp4](https://user-images.githubusercontent.com/16801642/106670212-a6a7f880-65a4-11eb-9dfc-aa336ff66420.mp4)

### What you expected to happen

URL should link to the correct page.

### PR DESCRIPTION
**Pull request by BYK**
Turns out there was an information architecture change over at getsentry/sentry-docs recently, requiring a platform name for the docs of user feedback. This patch tries to fix that. Fixes #23551.

### CODE REVIEW

File: src/sentry/static/sentry/app/views/userFeedback/userFeedbackEmpty.tsx [hunk 1]
```diff
@@ -108,7 +108,9 @@ class UserFeedbackEmpty extends React.Component<Props> {
                   eventName: 'User Feedback Docs Clicked',
                 })
               }
-              href="https://docs.sentry.io/enriching-error-data/user-feedback/"
+              href={`https://docs.sentry.io/platforms/${
+                this.props.projects[0].platform || 'javascript'
```
Comment (billyvg) [inline src/sentry/static/sentry/app/views/userFeedback/userFeedbackEmpty.tsx:112]: In case there are no projects

```suggestion
                this.props.projects?.[0].platform || 'javascript'
```

**Review by billyvg — APPROVED** [review]

File: src/sentry/static/sentry/app/views/userFeedback/userFeedbackEmpty.tsx (hunk 1 above)
Comment (BYK) [reply src/sentry/static/sentry/app/views/userFeedback/userFeedbackEmpty.tsx:112]: I don't think we can reach this line if `projects` is an empty array due to the check above. Am I missing something?

**Comment by BYK** [comment]
Verified the fix with the Vercel preview, it works. Added a small fix regarding selected projects on user feedback view.

Also /cc @PeloWriter & @dcramer to prevent similar things in the future. We may want to set up alerts on number of 404s on the docs.

**Comment by billyvg** [comment]
Doesn't seem like platforms always matches up to docs? e.g. https://docs.sentry.io/platforms/javascript-react/enriching-events/user-feedback/

**Comment by BYK** [comment]
>Doesn't seem like platforms always matches up to docs? e.g. docs.sentry.io/platforms/javascript-react/enriching-events/user-feedback

Ugh, good catch. I need the _parent_ platform id. I'll see if this is easy to get, otherwise I just need good ol' `platform.split('-', 1)[0]`.

**Comment by BYK** [comment]
@billyvg ugh, so not only my hacky `split()` solution wouldn't work due to things like `react-native` as a platform name, we don't have the docs for user feedback for all platforms.

Here's what I think:

1. This patch definitely makes things less broken so we should ship it mostly as it is, unless you have huge objections
2. We should figure out a way to detect on which platforms we support user-feedback and for the ones we don't, direct people to the raw API docs over at https://docs.sentry.io/api/projects/submit-user-feedback/

**Comment by PeloWriter** [comment]
Can we extrapolate support? We list the platforms that *don't* support User Feedback in the yaml frontmatter of 'src/platforms/common/enriching-events/user-feedback.mdx'

**Comment by PeloWriter** [comment]
It would be good to find a more automated fix. We've also got breakage for the link in Settings > Tags "add custom tags"
Screen Shot 2021-02-03 at 1 11 31 PM

**Comment by billyvg** [comment]
Going to remove myself from reviewers, feel free to re-tag me if there are updates

**Comment by BYK** [comment]
@EvanPurkhiser since you did #23720 recently, I need your eyes on this.

**Comment by EvanPurkhiser** [comment]
Should we just drop trying to incorporate the platform key?

**Comment by BYK** [comment]
>Should we just drop trying to incorporate the platform key?

I mean, wouldn't it be nice to take them directly where they should be going instead of introducing another hop? I think the missing link here is, if the platform does not support this, it should take you to the platform selection page instead of giving you a 404. Or we should fetch that information and not display this link/page at all (see getsentry/sentry-release-registry#39 for that part)

**Review by evanpurkhiser — APPROVED** [review]
