### PR TITLE
fix(merged): Always show a link for latests event of a merged group

### LINKED ISSUE #51294: Fix invisible links in Merged Issues tab of issue details page
For some issues, the link to each merged issue is 0x0 pixels, which makes it both invisible and unclickable.

Image

(That screenshot is from https://pollyex.sentry.io/issues/3781804953/merged/)

By contrast, here's one where it works:

Image

(This is from https://loonateam.sentry.io/issues/4005996746/events/7afec4898fe54cc8ba6bf74c5089d3b8/merged/)

We should find a way to make sure that the link is always attached to something which takes up space. (While we're there, let's also style the link like a link, so people know it's there.)

Related, perhaps exactly the same, or perhaps just a specific case of the larger problem described here: https://github.com/getsentry/sentry/issues/57383.

Customer issue which is likely a consequence of this problem: https://github.com/getsentry/sentry/issues/61027

### PR DESCRIPTION
**Pull request by leeandher**
Fixes https://github.com/getsentry/sentry/issues/51294 but only the UX issues.

It seems like the rendering is only a byproduct of a different issue. Either way, if we can generate a link, we'll do so here, though the subtitle/title showing up blank is better described by https://github.com/getsentry/sentry/issues/57383

Also converts the component to an FC, so the change looks bigger than it is.

image

### CODE REVIEW

File: static/app/views/issueDetails/groupMerged/mergedItem.tsx [hunk 1]
```diff
@@ -95,55 +83,76 @@ class MergedItem extends Component<Props, State> {
...
-            >
-              <Checkbox
-                value={id}
-                checked={checked}
-                disabled={checkboxDisabled}
-                onChange={this.handleCheckClick}
+  useEffect(
+    () => {
+      GroupingStore.listen(data => onGroupChange(data), undefined);
+    },
```
Comment (scttcper) [inline static/app/views/issueDetails/groupMerged/mergedItem.tsx:89]: you want to remove the listener on unmount by calling it

Comment (leeandher) [reply static/app/views/issueDetails/groupMerged/mergedItem.tsx:89]: good catch mb

**Review by scttcper — APPROVED** [review]
