### PR TITLE
fix(getting-started): Switch Vue 2 and Vue 3 configuration headings

### LINKED ISSUE #55155: Vue setup - minor issue with Configure SDK page
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/vue

### SDK Version

7.64.0

### Framework Version

Vue 3.2.37

### Link to Sentry event

_No response_

### SDK Setup

_No response_

### Steps to Reproduce

When creating a new Vue project in Sentry - the "Configure Vue SDK" page has a minor issue. The headings of the code blocks don't correspond to the actual Vue version. The V2 section shows vue 3 code and vice versa.

### Expected Result

The headings should be swapped.

### Actual Result

image

### PR DESCRIPTION
**Pull request by Lms24**
As reported in #55155, the the Vue getting started page installation instructions for Vue 2 showed the Vue 3 code snippet and - vice versa - the Vue 3 heading showed the Vue 2 snippet. This might have happened when migrating over the docs or it was mixed up even before that. 

This fixes this mixup by swapping out headings for Vue 2 and 3. We want to show Vue 3 first and Vue 2 further below. Given that Vue 2 is EOL, we might wanna consider removing it from the getting started page in the future but for now this will do.

Closes #55155

### CODE REVIEW

**Review by ArthurKnaus — APPROVED** [review]
👍

File: static/app/gettingStartedDocs/javascript/vue.tsx [hunk 1]
```diff
@@ -68,7 +68,7 @@ npm install --save @sentry/vue
     ),
     configurations: [
       {
-        description: <h5>V2</h5>,
+        description: <h5>Vue 3</h5>,
```
Comment (matejminar) [inline static/app/gettingStartedDocs/javascript/vue.tsx:71]: @Lms24 This will put `Vue 3` title first, but it will show `Vue 2` installation instructions. We should reorder the whole object in array, not just the title.

Comment (Lms24) [reply static/app/gettingStartedDocs/javascript/vue.tsx:71]: I believe this is correct as it currently is but I'm realizing that the PR description doesn't reflect the intent of my change. Sorry for that (I'll update it). 

We got a report that the headings were swapped _prior_ to this PR (in #55155), meaning we correctly showed the Vue 3 _code snippet_ first but gave it the wrong heading (v2). So since we actually want to show Vue 3 first, I only swapped the headings. 

image

Comment (matejminar) [reply static/app/gettingStartedDocs/javascript/vue.tsx:71]: gotcha! 👍
