### PR TITLE
fix(replay): Mobile replays look off when orientation changes

### LINKED ISSUE #83425: [Mobile Replay] Videos look buggy when flipping orientation
We use two `display:block` on video clips to hide gaps at the beginning of videos. However, you can change orientation on mobile devices, so we should only allow two `display:block` if the orientation stays the same. 
Example:
[https://sentry-sdks.sentry.io/replays/11eb3e2dc8bd4e028208791b116634a1/?project=5428562[…]s%2F%3AreplaySlug%2F&statsPeriod=14d&yAxis=count%28%29&t=2](https://sentry-sdks.sentry.io/replays/11eb3e2dc8bd4e028208791b116634a1/?project=5428562&query=&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=14d&yAxis=count%28%29&t=2)

### PR DESCRIPTION
**Pull request by c298lee**
We showed the previous video to fix the video flickering in Safari. However, if the orientation has changed, you can see both replay videos. We can't show the previous replay in this case. This also fixes an issue where video clips other than the one that's seeked to are firing off the `seeking` event, and if that clip has a different orientation, it causes the visible replay clip to have the wrong dimensions.

Before:

https://github.com/user-attachments/assets/51e434aa-7de2-4eaf-b991-cf5dad144974

After:

https://github.com/user-attachments/assets/bf1f41da-21a1-4865-90d2-f67ad0a679e8

Unfortunately on Safari, if the clips have gaps in them and the orientation has changed, these gaps will be visible. There is nothing feasible that we can do on the player side to fix this.
After on Safari:

https://github.com/user-attachments/assets/8dc124a0-f5cf-444d-b27f-6341ac010196

Fixes https://github.com/getsentry/sentry/issues/83425

### CODE REVIEW

File: static/app/components/replays/videoReplayer.tsx [hunk 1]
```diff
@@ -408,7 +411,11 @@ export class VideoReplayer {
 
     for (const [index, videoElem] of this._videos) {
       // On safari, some clips have a ~1 second gap in the beginning so we also need to show the previous video to hide this gap
-      if (index === (this._currentIndex || 0) - 1) {
+      // Edge case: Don't show previous video if the orientation is different
```
Comment (ryan953) [inline static/app/components/replays/videoReplayer.tsx:414]: Nit: we're not strictly checking orientation

File: static/app/components/replays/videoReplayer.tsx [hunk 2]
```diff
@@ -408,7 +411,11 @@ export class VideoReplayer {
...
+      if (
+        index === (this._currentIndex || 0) - 1 &&
+        videoElem.videoWidth === nextVideo.videoWidth
```
Comment (ryan953) [inline static/app/components/replays/videoReplayer.tsx:417]:
```suggestion
        (videoElem.videoHeight === nextVideo.videoHeight && videoElem.videoWidth === nextVideo.videoWidth)
```

File: static/app/components/replays/videoReplayer.tsx (hunk 1 above)
Comment (c298lee) [reply static/app/components/replays/videoReplayer.tsx:414]:
```suggestion
      // Edge case: Don't show previous video if size is different (eg. orientation changes)
```

**Review by ryan953 — APPROVED** [review]
