### PR TITLE
fix(replays): Set event.startTimestamp based on the earliest of span/breadcrumb/rrweb data

### LINKED ISSUE #34489: Timeline scale is incorrect, icons & network span ranges appear outside the timeline and in weird spots
Example https://sentry.io/organizations/sentry/replays/replay-test:843e1a6f3c9e4af293a0ce15172ae2cd/

### PR DESCRIPTION
**Pull request by ryan953**
Just like with the end-time, the start time depends on the earliest data that we've grabbed. During pageload we can grab span data before rrweb does an html snapshot. So we need to adjust `startTimestamp` as well the rrweb events to account for that earlier timestamp.

**Before**
before we had 2 seconds of span data that was rendered outside the Timeline component. Here you can see a sliver of data poking out, but actually more is hidden behind the Left Nav:
Screen Shot 2022-05-12 at 8 30 12 PM

**After**
The duration of the replay is actually 2seconds longer (from 30 to 32s) because of the pageload span data.
Those extra 2 seconds mean that the first click happens at about `t=9` instead of `t=7`

Screen Shot 2022-05-12 at 8 28 11 PM

Fixes https://github.com/getsentry/sentry/issues/34489

### CODE REVIEW

File: static/app/utils/replays/replayReader.tsx [hunk 1]
```diff
@@ -48,31 +49,48 @@ export default class ReplayReader {
    * The original `this._event.startTimestamp` and `this._event.endTimestamp`
    * are the same. It's because the root replay event is re-purposing the
    * `transaction` type, but it is not a real span occuring over time.
-   * So we need to figure out the real end time, in milliseconds.
+   * So we need to figure out the real start and end timestamps based on when
+   * first and last bits of data were collected. In milliseconds.
    */
-  private _getEndTimestampMS() {
+  private _getTimestampsMS = memoize(() => {
```
Comment (ryan953) [inline static/app/utils/replays/replayReader.tsx:55]: memoize because it's got that sorting business and is called twice: from `getEvent` as well as `getRRWebEvents`, both of which are also memoized.

Could be slightly premature

File: static/app/utils/replays/replayReader.tsx [hunk 2]
```diff
@@ -48,31 +49,48 @@ export default class ReplayReader {
...
+    const sortedRRwebEvents = Array.from(this._rrwebEvents).sort(
+      (a, b) => a.timestamp - b.timestamp
     );
-  }
+    const sortedCrumbs = Array.from(crumbs).sort(
+      (a, b) => +new Date(a?.timestamp || 0) - +new Date(b?.timestamp || 0)
+    );
+    const startSortedSpans = Array.from(spans).sort(
+      (a, b) => a.start_timestamp - b.start_timestamp
+    );
```
Comment (billyvg) [inline static/app/utils/replays/replayReader.tsx:68]: Should this be moved to the `getRaw*` methods? I would expect this data to always be sorted.

File: static/app/utils/replays/replayReader.tsx [hunk 3]
```diff
@@ -83,14 +101,27 @@ export default class ReplayReader {
...
     // root event.
-    // This allows the scrubber to view timestamps after the last captured
-    // rrweb event, like if a memory span was captured after the last mouse-move,
-    // but before page unload.
+    // This allows the scrubber to view timestamps before and after the last
+    // captured rrweb event, like if a memory span was captured after the last
+    // mouse-move, but before page unload.
+    const {startTimestsampMS, endTimestampMS} = this._getTimestampsMS();
+
+    const sortedRRwebEvents = this._rrwebEvents.sort((a, b) => a.timestamp - b.timestamp);
```
Comment (billyvg) [inline static/app/utils/replays/replayReader.tsx:111]: We call `mergeAndSort....` before returning, is the sorting there still needed?

File: static/app/utils/replays/replayReader.tsx (hunk 2 above)
Comment (ryan953) [reply static/app/utils/replays/replayReader.tsx:68]: Spans are the special case, I'm sorting here both by the start and also end timestamps. But yeah i guess sorting by start is a sane default to guarentee

File: static/app/utils/replays/replayReader.tsx (hunk 3 above)
Comment (ryan953) [reply static/app/utils/replays/replayReader.tsx:111]: I think the followup sort is needed too rightnow. That call is after we've inserted the highlights, which are going to be inserted into the middle of the list.

**Review by ryan953 — COMMENTED** [review]
Maybe a can re-arrange some things and make the data setup easier and less redundant. The dependencies between the different getters right now are not as clear as before.

**Comment by ryan953** [comment]
I managed to remove one `sort()` call!

**Review by billyvg — APPROVED** [review]
