### PR TITLE
fix: Protect against feedbacks ingested without project association

### LINKED ISSUE #67412: TypeError: Cannot read properties of undefined (reading 'id')
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Go to User Feedback page. But actually it happens only with my user.

### Expected Result

It loads

### Actual Result

image

### Product Area

User Feedback

### Link

_No response_

### DSN

_No response_

### Version

24.3.0

### LINKED ISSUE #70136: [self-hosted] User feedback: Something went horribly wrong rendering this page
I enabled User feedback on my self-hosted instance of Sentry.

When I try to view User Feedback in Sentry, I get the following error:
```Something went horribly wrong rendering this page.```
```TypeError: u.project is undefined```

This is caused by this line:

https://github.com/getsentry/sentry/blob/56d237c485abdbece0a0c9a4798f398c87d49f8c/static/app/components/feedback/useFetchFeedbackData.tsx#L40C29-L40C52

Version: 24.4.2 (latest at time of writing)
OS : Ubuntu 22.04.4 LTS
Nginx reverse proxy

I ran again install.sh to migrate database after enabling User feedback.

Here is the feature flags :
```SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            "organizations:discover",
            "organizations:events",
            "organizations:global-views",
            "organizations:incidents",
            "organizations:integrations-issue-basic",
            "organizations:integrations-issue-sync",
            "organizations:invite-members",
            "organizations:metric-alert-builder-aggregate",
            "organizations:sso-basic",
            "organizations:sso-rippling",
            "organizations:sso-saml2",
            "organizations:performance-view",
            "organizations:advanced-search",
            "organizations:session-replay",
            "organizations:issue-platform",
            "organizations:profiling",
            "organizations:monitors",
            "organizations:dashboards-mep",
            "organizations:mep-rollout-flag",
            "organizations:dashboards-rh-widget",
            "organizations:metrics-extraction",
            "organizations:transaction-metrics-extraction",
            "projects:custom-inbound-filters",
            "projects:data-forwarding",
            "projects:discard-groups",
            "projects:plugins",
            "projects:rate-limits",
            "projects:servicehooks",
        )
        + (
            "projects:span-metrics-extraction",
            "organizations:starfish-browser-resource-module-image-view",
            "organizations:starfish-browser-resource-module-ui",
            "organizations:starfish-browser-webvitals",
            "organizations:starfish-browser-webvitals-pageoverview-v2",
            "organizations:starfish-browser-webvitals-use-backend-scores",
            "organizations:performance-calculate-score-relay",
            "organizations:starfish-browser-webvitals-replace-fid-with-inp",
            "organizations:deprecate-fid-from-performance-score",
            "organizations:performance-database-view",
            "organizations:performance-screens-view",
            "organizations:mobile-ttid-ttfd-contribution",
            "organizations:starfish-mobile-appstart",
            "organizations:standalone-span-ingestion",
            "organizations:spans-first-ui",
        )  # starfish related flags
        + (
            "organizations:user-feedback-ui",
            "organizations:user-feedback-ingest",
            "organizations:feedback-ingest",
            "organizations:feedback-post-process-group",
            "organizations:feedback-visible",
        )  # user feedback
    }
)
```

Sometimes it will display another error "There was an error loading a component." then I can refresh with F5 and this time it loads without error.

### PR DESCRIPTION
**Pull request by ryan953**
Fixes some feedback types to make them align with reality a little more.

This comment is still true:
```
// Typescript is a lie. `project` might be missing if feedback didn't go
// through the new ingest pipeline. This can happen in new self-hosted upgrades.
```
So what I did is bake that into the feedback item type, and fix any downstream callsites, so that the feedback item page can render in this case. I also wrapped the FeedbackItem component in an ErrorBoundary, so if there are problems the rest of the page should appear.

Fixes https://github.com/getsentry/sentry/issues/67412
Fixes https://github.com/getsentry/sentry/issues/70136

### CODE REVIEW

File: static/app/components/feedback/useRedirectToFeedbackFromEvent.tsx
Comment (ryan953) [inline static/app/components/feedback/useRedirectToFeedbackFromEvent.tsx:1]: I pulled this out of [useCurrentFeedbackId.tsx](https://github.com/getsentry/sentry/pull/74218/files#diff-341e680feeb413f02cced685795e1d26a0cb6d871d856489e632dc7646603bd8) because i wanted to call that other hook more often, and didn't think the redirect stuff needed to be included each time.

File: static/app/components/feedback/list/feedbackListItem.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ import {t} from 'sentry/locale';
 import {space} from 'sentry/styles/space';
 import type {Group} from 'sentry/types/group';
 import {trackAnalytics} from 'sentry/utils/analytics';
-import type {FeedbackIssue} from 'sentry/utils/feedback/types';
+import type {FeedbackIssueListItem} from 'sentry/utils/feedback/types';
```
Comment (ryan953) [inline static/app/components/feedback/list/feedbackListItem.tsx:19]: This was the 'wrong' type before (ok, `FeedbackIssue` and `FeedbackIssueListItem` were the same, but using the right name matters)

File: static/app/components/feedback/feedbackItem/feedbackItemLoader.tsx [hunk 2]
```diff
@@ -37,9 +38,13 @@ export default function FeedbackItemLoader() {
...
-    <FeedbackEmptyDetails />
+  ) : issueData ? (
+    <ErrorBoundary
+      customComponent={<FeedbackErrorDetails error={t('Unable to load feedback')} />}
+    >
+      <FeedbackItem eventData={eventData} feedbackItem={issueData} tags={tags} />
+    </ErrorBoundary>
   ) : (
-    <FeedbackItem eventData={eventData} feedbackItem={issueData} tags={tags} />
+    <FeedbackEmptyDetails />
```
Comment (ryan953) [inline static/app/components/feedback/feedbackItem/feedbackItemLoader.tsx:48]: inverted the conditional here: `!issueData` becomes `issueData` and the result is flipped to match

File: static/app/views/feedback/feedbackListPage.tsx [hunk 3]
```diff
@@ -169,3 +171,6 @@ const SetupContainer = styled('div')`
   overflow: hidden;
   grid-column: 1 / -1;
 `;
+function useRedirectToFeedbackFromEvent() {
+  throw new Error('Function not implemented.');
+}
```
Comment (michellewzhang) [inline static/app/views/feedback/feedbackListPage.tsx:176]: what's this for?

Comment (ryan953) [reply static/app/views/feedback/feedbackListPage.tsx:176]: oh, that's not meant to be

File: static/app/components/feedback/useCurrentFeedbackId.tsx [hunk 4]
```diff
@@ -1,41 +1,12 @@
...
-  useEffect(() => {
-    if (projectSlug && event?.groupID) {
-      navigate(
-        `/organizations/${organization.slug}/feedback/?feedbackSlug=${projectSlug}:${event.groupID}`,
-        {replace: true}
-      );
-    }
-  }, [navigate, organization.slug, projectSlug, event]);
-
-  return feedbackSlug;
```
Comment (michellewzhang) [inline static/app/components/feedback/useCurrentFeedbackId.tsx:40]: why did this bit get deleted?

Comment (ryan953) [reply static/app/components/feedback/useCurrentFeedbackId.tsx:40]: that moved into it's own file, useRedirectToFeedbackFromEvent.tsx~

Comment (michellewzhang) [reply static/app/components/feedback/useCurrentFeedbackId.tsx:40]: oh i missed that! cool

**Review by michellewzhang — APPROVED** [review]
