### PR TITLE
nit(fe): update project name change warning

### LINKED ISSUE #67153: Changing Project Slugs should have clearer warnings
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Changing project name, changes the slug and that can break build scripts and API scripts. But the UX does not make this clear at all

image

### Expected Result

UX makes the consequences of changing project slug clear

### Actual Result

No info in the UX

### Product Area

Settings - Projects

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by ameliahsu**
closes https://github.com/getsentry/sentry/issues/67153

updated warning message when project name is changed

BEFORE:
image

AFTER:
image

### CODE REVIEW

**Review by schew2381 — APPROVED** [review]

**Review by iamrajjoshi — APPROVED** [review]
Yay!!!!  🚀

**Comment by cathteng** [comment]
can we get a screenshot of this new change?

File: static/app/data/forms/projectGeneralSettings.tsx [hunk 1]
```diff
@@ -64,8 +64,10 @@ export const fields: Record<string, Field> = {
     },
 
     saveOnBlur: false,
-    saveMessageAlertType: 'info',
-    saveMessage: t('You will be redirected to the new project slug after saving'),
+    saveMessageAlertType: 'warning',
+    saveMessage: t(
+      'Changing project name will change your project slug too and can break your build scripts. Are you sure you want to change name?'
```
Comment (cathteng) [inline static/app/data/forms/projectGeneralSettings.tsx:69]: this copy reads a little weird to me. how about something like

```suggestion
      'Changing a project's name will also change the project slug. This can break your build scripts! Please proceed carefully.'
```

**Review by cathteng — APPROVED** [review]
lgtm!

@iamrajjoshi this could also be a good opportunity to advertise our support for resource ids 🤔
