### PR TITLE
fix(feedback): Make sure to load in the AppComponentsData so all issue-trackers are available in Feedback

### LINKED ISSUE #61552: [User Feedback] - Linear ticket integration does not work
Not all issue trackers are appearing on the Feedback Details page

Sentry Issue: [JAVASCRIPT-2Q8E](https://sentry.sentry.io/feedback/?referrer=github_integration&feedbackSlug=javascript%3A4717471691&project=11276)
|  |  |
| ------------- | --------------- |
| **message** | I have enabled linear, but can't link it to an ... |

### PR DESCRIPTION
**Pull request by ryan953**
Turns out that we weren't loading AppComponentsData, so I extracted the two api calls into a new file calls `useSentryAppComponentsData`, rewrote the internals to leverage useApiQuery, and called it from inside Feedback

Now all the issue-trackers are visible, including Linear:
SCR-20231215-ntqg

Fixes https://github.com/getsentry/sentry/issues/61552

### CODE REVIEW

File: static/app/components/feedback/decodeFeedbackSlug.tsx
Comment (ryan953) [inline static/app/components/feedback/decodeFeedbackSlug.tsx:1]: This is basically a rename and tweak of [decodeFeedbackId.tsx](https://github.com/getsentry/sentry/pull/61968/files#diff-444aae94df808b9a0f062801475dcf4c134a9e158f0fcf3d896311f86da210a8)

File: static/app/components/feedback/useCurrentFeedbackProject.tsx
Comment (ryan953) [inline static/app/components/feedback/useCurrentFeedbackProject.tsx:1]: clone of `useCurrentFeedbackId`

If `useLocationQuery` were different then we wouldn't need it... the trouble is that `useLocationQuery` relies on the field key (in this case `feedbackSlug`) for input & output. If it only relied on that key for input OR output things would be different. 

I don't think this is the end of the world though. If someone wanted to bundle these two up it would work great with an extra useMemo, looks like this:

```
# useCurrentFeedback

function useCurrentFeedback() {
  const {feedbackSlug: feedbackId} = useLocationQuery({
    fields: {
      feedbackSlug: val => decodeFeedbackSlug(val).feedbackId ?? '',
    },
  });

  const {feedbackSlug: projectId} = useLocationQuery({
    fields: {
      feedbackSlug: val => decodeFeedbackSlug(val).projectId ?? '',
    },
  });

  return useMemo(() => ({feedbackId, projectId}), [feedbackId, projectId]);
}
```

...so i don't think we should mess with useLocationQuery

**Review by michellewzhang — APPROVED** [review]
👏🏻👏🏻👏🏻

**Review by billyvg — APPROVED** [review]
Any idea why the vertical whitespace here is inconsistent? 
image

**Comment by ryan953** [comment]
> Any idea why the vertical whitespace here is inconsistent?

@billyvg yeah the whitespace is all messed up, even for items on the same row. "Jira Issue" drops below "Linear" & "Github" in my screen shot :(. It's because the "+" icon provide some padding, but it's not consistently rendered (not sure why). On the Issue Details page these are all stacked vertically, so the spacing/height differences are harder to notice.

I think it's ok for now, not many orgs have 9 trackers like this one, and I do want to a) squeeze these down into just icons per the figma b) redo the whole details header area, add-in the date when feedback is received, but also make it better & space efficient on small screens.

File: static/app/stores/useSentryAppComponentsData.tsx [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    SentryAppComponentsStore.loadComponents(components);
+  }
+
+  useEffect(() => {
+    if (!projectId) {
+      Sentry.withScope(scope => {
+        scope.setExtra('orgSlug', organization.slug);
+        scope.setExtra('projectId', projectId);
+        Sentry.captureMessage('Project ID was not set');
+      });
```
[the remark this answers is not in the document]
Comment (ryan953) [reply static/app/stores/useSentryAppComponentsData.tsx:43]: I think i'll just remove it. If there's no projectId then some other assumptions in side groupEventDetails are already broken; and the query will not throw a 5xx or anything, instead it seems to return all data for the org.
