### PR TITLE
fix: exception not showing in console focus area

### LINKED ISSUE #36142: Errors should also show in the "Console" tab
Captured errors are not displayed as a console message.

Example replay: https://sentry.io/organizations/sentry-emerging-tech/replays/sourcemapsio-replays:f155f69e4dee4c999683ba8f69bae90a/

We currently filter breadcrumbs only for the `console` category, including `exception` may solve this.

### PR DESCRIPTION
**Pull request by jesus4497**
By including 'exceptions' type breadcrumbs for the console category, erros now show in the "console" tab. Closes #36142 

image

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: static/app/views/replays/detail/console/consoleMessage.tsx [hunk 1]
```diff
@@ -40,6 +40,15 @@ function renderString(arg: string | number | boolean | Object) {
 export function MessageFormatter({breadcrumb}: MessageFormatterProps) {
   let logMessage = '';
 
+  if (!breadcrumb.data?.arguments) {
+    // There is a possibility that we don't have arguments as we could be receiving an exception type breadcrumb.
+    // In these cases we just need the message prop.
+
+    // There are cases in which our prop message is an array, we want to force it to become a string
+    logMessage = breadcrumb.message?.toString() || '';
```
Comment (jesus4497) [inline static/app/views/replays/detail/console/consoleMessage.tsx:48]: NOTE: 
Exceptions breadcrumb types are returning Arrays in their message prop, which probably is an issue with the core SDK, to handle that I'm forcing it to become a string.

Comment (ryan953) [reply static/app/views/replays/detail/console/consoleMessage.tsx:48]: We will see the same output if the input is `{message: true}` or `{message: "true"}`, both will show `true` in the output.

Similarly, if message is a plain object we're going to see `[object Object]` in the output.

But we expect message to be a string, at least that's what the TS types say. And we know the value is coming from a JSON payload, so there's not going to be `Date` objects or custom class instances in there...

based on all the this seems fine to me.

**Review by ryan953 — APPROVED** [review]
