### PR TITLE
ref(replays): Call useReplaysCount for each list of issues in the app

### LINKED ISSUE #40730: Bug: Count of replays in the "Issue > Replay (N)" tab is incorrect
Depends on: https://github.com/getsentry/replay-backend/issues/190

1. Need to update the count on the Issues List page:
Screen Shot 2022-11-04 at 8 41 36 AM

2. Also the count on the "Issue>Replays" tab 
3. Also the count on the "Performance>Replays" tab

Related: https://github.com/getsentry/sentry/issues/40731

### PR DESCRIPTION
**Pull request by ryan953**
This fixes an N+1 problem where the UI was making a request for each row in the Issue table. Previously it was requesting the count of replays that belong to the specific issue.
Now we're doing one request (per issues table) to get the count of replays for a list of issue ids.

Test Plan:
Issue table still works,
There's 1 request in the network tab, so all the counts pop in at the same time, see the highlighted area in the screen shot:

Follows: https://github.com/getsentry/sentry/pull/41298

Fixes #40730

### CODE REVIEW

File: static/app/components/group/issueReplayCount.tsx [hunk 1]
```diff
@@ -27,18 +27,23 @@ function IssueReplayCount({groupId}: Props) {
...
         {countDisplay}
       </ReplayCountLink>
-    </Tooltip>
+    </StyledTooltip>
   );
 }
 
+const StyledTooltip = styled(Tooltip)`
+  display: flex;
+  align-items: center;
```
Comment (ryan953) [inline static/app/components/group/issueReplayCount.tsx:44]: tweak so the replay icon doesn't add extra height to rows.

Screen Shot 2022-11-17 at 8 00 26 PM

File: static/app/components/eventOrGroupExtraDetails.tsx [hunk 2]
```diff
@@ -57,76 +55,68 @@ function EventOrGroupExtraDetails({
   const showReplayCount =
     organization.features.includes('session-replay-ui') && projectSupportsReplay(project);
 
-  const counts = useReplaysCount({
-    groupIds: id,
-    organization,
-    project,
-  });
```
Comment (ryan953) [inline static/app/components/eventOrGroupExtraDetails.tsx:64]: This was doing basically an N+1 query, because this component lives inside each row of all the Issues tables. 

This PR updates all the callsites so we do one query for all the table-rows that are visible.

File: static/app/views/issueList/groupListBody.tsx [hunk 3]
```diff
@@ -74,18 +75,17 @@ function GroupListBody({
...
   return (
-    <GroupList
-      {...{
-        groupIds,
-        memberList,
-        query,
-        sort,
-        displayReprocessingLayout,
-        groupStatsPeriod,
-        source: 'group-list',
```
Comment (ryan953) [inline static/app/views/issueList/groupListBody.tsx:85]: This `source` prop was extra. why do folks like to avoid jsx syntax?

File: static/app/views/replays/detail/issueList.tsx [hunk 4]
```diff
@@ -68,28 +73,38 @@ function IssueList(props: Props) {
...
 
   useEffect(() => {
     fetchIssueData();
   }, [fetchIssueData]);
 
+  const counts = useReplaysCount({
+    groupIds: state.issues.map(issue => issue.id),
+    organization,
+    project,
+  });
```
Comment (ryan953) [inline static/app/views/replays/detail/issueList.tsx:86]: There is only one project in this context, so we can skip `<ReplayCountProvider>` that all the other instances use and call the hook directly. Also this and `GroupListBody` are the only functional components that could use a hook.

File: static/app/components/replays/replayCountContext.tsx [hunk 5]
```diff
@@ -18,4 +23,45 @@ import type useReplaysCount from 'sentry/components/replays/useReplaysCount';
  * const count = useContext(ReplayCountContext)[groupId];
  * ```
  */
-export default createContext<ReturnType<typeof useReplaysCount>>({});
+const ReplayCountContext = createContext<ReturnType<typeof useReplaysCount>>({});
+
+export default ReplayCountContext;
```
Comment (billyvg) [inline static/app/components/replays/replayCountContext.tsx:28]: nit: can we make this a named export so we're not mixing default + named?

(I'd be in favor of adding a lint rule for this too)

**Review by billyvg — APPROVED** [review]

File: static/app/components/replays/replayCountContext.tsx (hunk 5 above)
Comment (ryan953) [reply static/app/components/replays/replayCountContext.tsx:28]: I think i'll probably pull out the named export into it's own file tbh. 

I didn't start out with that extra thing, but it's got enough imports and utility that i can figure out a unique name for it

File: static/app/components/group/issueReplayCount.tsx [hunk 6]
```diff
@@ -27,18 +27,23 @@ function IssueReplayCount({groupId}: Props) {
   const countDisplay = count > 50 ? '50+' : count;
 
   return (
-    <Tooltip title={t('This issue has %s replays available to view', countDisplay)}>
+    <StyledTooltip title={t('This issue has %s replays available to view', countDisplay)}>
```
Comment (scttcper) [inline static/app/components/group/issueReplayCount.tsx:30]: you might use the `tn(` translate function to handle "1 replay" vs "2 replays"

File: static/app/components/group/issueReplayCount.tsx (hunk 1 above)
Comment (scttcper) [reply static/app/components/group/issueReplayCount.tsx:44]: if you use skipWrapper on the tooltip it stops rendering a span, not sure if this is a hack for that

File: static/app/components/group/issueReplayCount.tsx (hunk 6 above)
Comment (ryan953) [reply static/app/components/group/issueReplayCount.tsx:30]: damnit, just saw this as i was clicking.

i'll send in another pr with that

Comment (ryan953) [reply static/app/components/group/issueReplayCount.tsx:30]: Done! https://github.com/getsentry/sentry/pull/41568
