### PR TITLE
fix(billing): Use ff for prevent notification

### LINKED ISSUE #99475: [User Spend Notification] Prevent Users and Prevent Reviews settings is showing and can't be disabled
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Reported by a user in this ticket: https://sentry.zendesk.com/agent/tickets/162430

1. Go to your personal user notification settings for Spend Notifications: Settings > Notifications > Spend > Prevent Users or Prevent Reviews
2. Try toggling to OFF on either of them
3. get Invalid Type error in UI and 400 error in network

Image

### Expected Result

Option should work.  Should these options be hidden?

### Actual Result

Invalid Type error

### Product Area

Settings

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by brendanhsentry**
fixes https://github.com/getsentry/sentry/issues/99475

Moves Prevent Users toggle behind feature flag

### CODE REVIEW

File: static/app/constants/index.tsx [hunk 1]
```diff
@@ -577,7 +577,7 @@ export const DATA_CATEGORY_INFO = {
     titleName: t('Prevent Reviews'),
     productName: t('Prevent Reviews'),
     uid: 30,
-    isBilledCategory: true,
```
Comment (mrduncan) [inline static/app/constants/index.tsx:580]: Do we need this above for `PREVENT_USER` as well?

Comment (brendanhsentry) [reply static/app/constants/index.tsx:580]: No, we'll use the ff for prevent users

**Review by mrduncan — APPROVED** [review]
