### PR TITLE
ref(project_creation): Add project deletion to the go back button

### LINKED ISSUE #49531: Going back from project creation is broken
**Current behaviour**: When a user creates a new project from an existing org, selects a platform and clicks on "create project" and then clicks "back" only step 1 of the setup is displayed.

https://user-images.githubusercontent.com/26696515/238964799-0ea68190-3cb9-4c16-be15-7fe2f6e06497.mov

**Expected behaviour:** 
- When the user clicks "back", the same content and CTAs are displayed as the first time a customer clicks on "create project".
- Additionally, we should display the confirmation modal and update the CTAs as in the new org onboarding.

Image

### PR DESCRIPTION
**Pull request by priscilawebdev**
This PR introduces a crucial functionality to the `getting-started` UI by adding consistent behaviour to the "Go back" button, aligning it with the existing onboarding flow. The implemented behavior ensures that, when clicking on the "Back" button, an alert is displayed, informing the user that the project data will be deleted if he decides to go back. If he confirms, the project is deleted, but the form presented on the `create project` page will be filled with previous values from the deleted project, such as the name, the selected platform, etc.

**Preview:**

https://github.com/getsentry/sentry/assets/29228205/bdc15c2b-87d3-43b3-81f3-e45973ac6318

closes: https://github.com/getsentry/sentry/issues/49531

### CODE REVIEW

File: static/app/types/project.tsx [hunk 1]
```diff
@@ -38,12 +38,15 @@ export type Project = {
...
   isMember: boolean;
+  name: string;
   organization: Organization;
   plugins: Plugin[];
+
   processingIssues: number;
   relayPiiConfig: string;
 
   subjectTemplate: string;
+  team: Team;
```
Comment (priscilawebdev) [inline static/app/types/project.tsx:49]: these types were missing and it was needed for the context

File: static/app/utils/analytics/projectCreationAnalyticsEvents.tsx [hunk 2]
```diff
@@ -1,4 +1,16 @@
 export type ProjectCreationEventParameters = {
+  'project_creation.back_button_clicked': {};
```
Comment (priscilawebdev) [inline static/app/utils/analytics/projectCreationAnalyticsEvents.tsx:2]: already took the opportunity and add this analytics code so we can track how users are using the back button in the project creation flow. Please let me know if it is ok to have it here or if you prefer it in a separate PR

File: static/app/views/projectInstall/createProject.tsx [hunk 3]
```diff
@@ -36,6 +41,12 @@ type IssueAlertFragment = Parameters<
 function CreateProject() {
   const api = useApi();
   const organization = useOrganization();
+  const location = useLocation();
+  const gettingStartedWithProjectContext = useContext(GettingStartedWithProjectContext);
+
+  const autoFill =
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/createProject.tsx:47]: since the "getting started" docs and the "creating form" pages are on separate routes, depending on where the user is coming from and the project data saved in context... the default values could be wrong so a workaround is to look for these new URL parameters

File: static/app/views/projectInstall/createProject.tsx [hunk 4]
```diff
@@ -215,73 +234,37 @@ function CreateProject() {
     projectName !== '' &&
     (!shouldCreateCustomRule || conditions?.every?.(condition => condition.value));
 
-  const createProjectForm = (
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/createProject.tsx:218]: I moved this bew because it was just easier for me to debug and find myself in the code, but please let me know if you are ok with that, or of it makes things difficult to review.

File: static/app/views/projectInstall/createProject.tsx [hunk 5]
```diff
@@ -215,73 +234,37 @@ function CreateProject() {
...
-            priority="primary"
-            disabled={!canSubmitForm}
-          >
-            {t('Create Project')}
-          </Button>
-        </div>
-      </CreateProjectForm>
-    </Fragment>
-  );
+  const alertFrequencyDefaultValues = useMemo(() => {
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/createProject.tsx:237]: this new function checks for the alert saved in the context, converting it to default value formats used in the `IssueAlertOptions` component.

File: static/app/views/projectInstall/issueAlertOptions.tsx [hunk 6]
```diff
@@ -51,6 +52,10 @@ type StateUpdater = (updatedData: RequestDataFragment) => void;
 type Props = AsyncComponent['props'] & {
   onChange: StateUpdater;
   organization: Organization;
+  alertSetting?: string;
+  interval?: string;
+  metric?: MetricValues;
+  threshold?: string;
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/issueAlertOptions.tsx:58]: these new props are required for when the selected alert option is customized. If users have previously selected the customized option, all defined values will be populated by default

File: static/app/views/projectInstall/issueAlertOptions.tsx [hunk 7]
```diff
@@ -139,15 +144,15 @@ class IssueAlertOptions extends AsyncComponent<Props, State> {
     hasProperlyLoadedConditions: boolean
   ): [string, string | React.ReactElement][] {
     const customizedAlertOption: [string, React.ReactNode] = [
-      Actions.CUSTOMIZED_ALERTS.toString(),
+      RuleAction.CUSTOMIZED_ALERTS.toString(),
       <CustomizeAlertsGrid
-        key={Actions.CUSTOMIZED_ALERTS}
+        key={RuleAction.CUSTOMIZED_ALERTS}
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/issueAlertOptions.tsx:149]: updated the name just because I had to use it in another file, so it was easier to identify what this is about

File: static/app/views/projectInstall/platform.tsx [hunk 8]
```diff
@@ -120,10 +131,81 @@ export function ProjectInstallPlatform({location, params, route, router}: Props)
     ? projects.find(proj => proj.slug === params.projectId)
     : undefined;
 
+  const {
+    data: projectAlertRules,
+    isLoading: projectAlertRulesIsLoading,
+    isError: projectAlertRulesIsError,
+  } = useApiQuery<IssueAlertRule[]>(
+    [`/projects/${organization.slug}/${project?.slug}/rules/`],
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/platform.tsx:139]: when creating a project, an issue rule can be created in step 2, and the data is not saved in the project but in another location through this endpoint. That's why if we want to get those values again to fill out fields by default, we have to fire this request

File: static/app/views/projectInstall/platform.tsx [hunk 9]
```diff
@@ -120,10 +131,81 @@ export function ProjectInstallPlatform({location, params, route, router}: Props)
...
+        key: platforms[platformKey].id,
+      } as OnboardingSelectedSDK,
+    });
+  }, [
+    gettingStartedWithProjectContext,
+    project,
+    projectAlertRules,
+    projectAlertRulesIsLoading,
+    projectAlertRulesIsError,
+  ]);
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/platform.tsx:180]: this will make sure that always when the "getting-started" page is loaded, we populate the "gettingStartedWithProject" context

File: static/app/views/projectInstall/platform.tsx [hunk 10]
```diff
@@ -120,10 +131,81 @@ export function ProjectInstallPlatform({location, params, route, router}: Props)
...
+    // if the project has received a first error, we don't delete it
+    recentCreatedProject.firstError === false &&
+    // if the project has received a first transaction, we don't delete it
+    recentCreatedProject.firstTransaction === false &&
+    // if the project has replays, we don't delete it
+    recentCreatedProject.hasReplays === false &&
+    // if the project has sessions, we don't delete it
+    recentCreatedProject.hasSessions === false &&
+    // if the project is older than one hour, we don't delete it
+    recentCreatedProject.olderThanOneHour === false;
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/platform.tsx:207]: logic used to display or not the deletion modal

File: static/app/views/projectInstall/platform.tsx [hunk 11]
```diff
@@ -145,39 +252,96 @@ export function ProjectInstallPlatform({location, params, route, router}: Props)
...
+            onRender={() => {
+              if (!recentCreatedProject) {
+                return;
+              }
+              trackAnalytics('project_creation.data_removal_modal_rendered', {
+                organization,
+                platform: recentCreatedProject.slug,
+                project_id: recentCreatedProject.id,
+              });
+            }}
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/platform.tsx:339]: this is the component responsible for displaying the deletion modal.

File: static/app/views/projectInstall/platform.tsx [hunk 12]
```diff
@@ -145,39 +252,96 @@ export function ProjectInstallPlatform({location, params, route, router}: Props)
...
           >
-            {t('Back')}
-          </Button>
+            <Button icon={<IconChevron direction="left" size="sm" />} size="sm">
+              {t('Back to Platform Selection')}
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/platform.tsx:342]: since we don't display breadcrumbs in the header of the page, going back felt weird if users are landing on this page from other entry points, so I decided to rename it to "Back to Platform Selection"

File: static/app/views/projectInstall/platformOrIntegration.tsx [hunk 13]
```diff
@@ -20,7 +21,9 @@ function PlatformOrIntegration(props: Props) {
   }
   return (
     <OnboardingContextProvider>
-      <ProjectInstallPlatform {...props} />
+      <GettingStarted>
```
Comment (priscilawebdev) [inline static/app/views/projectInstall/platformOrIntegration.tsx:24]: since the overview is no longer being used - it is being deleted in this PR - we had to add this wrapper, adding spacing to the page.

File: static/app/views/projects/gettingStartedWithProjectContext.tsx [hunk 14]
```diff
@@ -0,0 +1,49 @@
+import {createContext} from 'react';
+
+import {OnboardingSelectedSDK, Project} from 'sentry/types';
```
Comment (priscilawebdev) [inline static/app/views/projects/gettingStartedWithProjectContext.tsx:3]: new context used to save project data. This data is later displayed as default values project creation form if users choose to go back in the flow

File: static/app/views/projects/index.tsx [hunk 15]
```diff
@@ -0,0 +1,13 @@
+import {GettingStartedWithProjectContextProvider} from './gettingStartedWithProjectContext';
+
+type Props = {
+  children: React.ReactNode;
+};
+
+export function Projects({children}: Props) {
+  return (
+    <GettingStartedWithProjectContextProvider>
```
Comment (priscilawebdev) [inline static/app/views/projects/index.tsx:9]: since the `project/new` endpoint is under `projects` it was needed to create this new page/component, wrapping the children with the "gettingStarted...." context

File: static/app/routes.tsx [hunk 16]
```diff
@@ -1048,22 +1027,38 @@ function buildRoutes() {
         path=":projectId/events/:eventId/"
         component={errorHandler(ProjectEventRedirect)}
       />
+      <Route
+        path=":projectId/getting-started/"
+        component={make(
+          () => import('sentry/views/projectInstall/platformOrIntegration')
+        )}
+      />
```
Comment (priscilawebdev) [inline static/app/routes.tsx:1035]: since we are now using the context "gettingStartedWithProject", both "new" and "getting-started" routes have to contain the same parent

File: static/app/routes.tsx [hunk 17]
```diff
@@ -1995,48 +1990,28 @@ function buildRoutes() {
...
+        <Fragment>
+          <Redirect
+            from="/getting-started/:projectId/"
+            to="/projects/:projectId/getting-started/"
+          />
+          <Redirect
+            from="/getting-started/:projectId/:platform/"
+            to="/projects/:projectId/getting-started/"
+          />
+        </Fragment>
```
Comment (priscilawebdev) [inline static/app/routes.tsx:2005]: redirects so that old links still present in the app or saved by the user are not broken

**Review by matejminar — APPROVED** [review]
