### PR TITLE
fix(alerts): Disallow wildcard in session dataset queries

### LINKED ISSUE #55672: Frontend implementation

### PR DESCRIPTION
**Pull request by ArthurKnaus**
* Alert editor: Disallow wildcard in session dataset queries
* `SmartSearchBar`: Re-parse query on wildcard option change

Closes https://github.com/getsentry/sentry/issues/55672

### CODE REVIEW

File: static/app/components/smartSearchBar/index.tsx [hunk 1]
```diff
@@ -408,6 +410,9 @@ class SmartSearchBar extends Component<DefaultProps & Props, State> {
     ) {
       // eslint-disable-next-line react/no-did-update-set-state
       this.setState(this.makeQueryState(addSpace(query ?? undefined)));
+    } else if (disallowWildcard !== lastDisallowWildcard) {
+      // Re-parse query to apply new options (without resetting it to the query prop value)
+      this.setState(this.makeQueryState(this.state.query));
```
Comment (matejminar) [inline static/app/components/smartSearchBar/index.tsx:415]: I see that there's `// eslint-disable-next-line react/no-did-update-set-state` above the previous setState. Do we also need it here or can we remove it from there?

**Review by matejminar — APPROVED** [review]

File: static/app/components/smartSearchBar/index.tsx (hunk 1 above)
Comment (ArthurKnaus) [reply static/app/components/smartSearchBar/index.tsx:415]: right, that is not needed anymore 👍
