### PR TITLE
fix(replays): Dont query for errors events when there are no ids in the condition list

### LINKED ISSUE #38243: Errors query is wrong and adding unrelated errors to all replays
This is a regression due to https://github.com/getsentry/sentry/pull/38074 - refactoring from using the deprecated `/eventsv2/` endpoint. The query is now returning errors unrelated to the current replay. It's also using the `projects` field which does not seem to be supported by the API.

Image

### PR DESCRIPTION
**Pull request by ryan953**
Previously we were always doing a query for errors, even if there were no errors to search for. This was returning lots of items because there was nothing to limit the response.

Now we do a search for `errorIds`, if there are items in the list. If the list is empty, do not search.

Fixes #38243

Depends on #38272

### CODE REVIEW

**Review by billyvg — APPROVED** [review]

File: static/app/utils/replays/hooks/useReplayData.tsx [hunk 1]
```diff
@@ -190,40 +189,40 @@ function useReplayData({replaySlug, orgSlug}: Options): Result {
...
       const response = await api.requestPromise(`/organizations/${orgSlug}/events/`, {
         query: {
           field: ['id', 'error.value', 'timestamp', 'error.type', 'issue.id'],
-          projects: [projectSlug],
-          query: conditions.formatString(),
+          projects: [-1],
+          start: replayRecord.startedAt.toISOString(),
+          end: replayRecord.finishedAt.toISOString(),
+          query: `id:[${String(replayRecord.errorIds)}]`,
+          referrer: 'api.replay.details-page',
```
Comment (ryan953) [inline static/app/utils/replays/hooks/useReplayData.tsx:204]: This gets put together to be something like:
Screen Shot 2022-08-30 at 1 34 38 PM

```
Request URL: https://dev.getsentry.net:7999/api/0/organizations/sentry/events/?end=2022-08-30T19%3A37%3A11.000Z&field=id&field=error.value&field=timestamp&field=error.type&field=issue.id&projects=-1&query=id%3A%5B8976b9b3376e4e4f9c4c278495c32c22%2C9e4d685eb3c04ad092cf97701141c86d%2C375f5bd24261499bae24ccd5e7f8e50c%2Cd7af866f58454802b5aa8bbd4c9f1eba%5D&referrer=api.replay.details-page&start=2022-08-30T18%3A22%3A47.000Z
```

Comment (billyvg) [inline static/app/utils/replays/hooks/useReplayData.tsx:204]: Where is this used?

File: static/app/utils/replays/hooks/useReplayData.tsx [hunk 2]
```diff
@@ -190,40 +189,40 @@ function useReplayData({replaySlug, orgSlug}: Options): Result {
...
 
       const response = await api.requestPromise(`/organizations/${orgSlug}/events/`, {
         query: {
           field: ['id', 'error.value', 'timestamp', 'error.type', 'issue.id'],
-          projects: [projectSlug],
-          query: conditions.formatString(),
+          projects: [-1],
+          start: replayRecord.startedAt.toISOString(),
+          end: replayRecord.finishedAt.toISOString(),
+          query: `id:[${String(replayRecord.errorIds)}]`,
```
Comment (billyvg) [inline static/app/utils/replays/hooks/useReplayData.tsx:203]: This is valid query syntax? 👀

Comment (ryan953) [reply static/app/utils/replays/hooks/useReplayData.tsx:203]: yes!
it evaluates to be: `id:[abc, zyx]` which is an OR case.

I tested it against this replay which has 4 errors: https://dev.getsentry.net:7999/organizations/sentry/replays/javascript:22585d5caca7435a860f48b6cd079f0b/

File: static/app/utils/replays/hooks/useReplayData.tsx (hunk 1 above)
Comment (wmak) [reply static/app/utils/replays/hooks/useReplayData.tsx:204]: Its tagged on the backend & snuba creates transactions based on this referrer value
