### PR TITLE
fix(insights): cache page doesn't load with long transactions

### LINKED ISSUE #74554: Cannot load Caches page
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. the customer tries to open the Caches page in production
2. the endpoint gives the following error: 

```
{
"detail": "Invalid quote at '[\"BackOfficeClient': quotes must enclose text or be escaped."
}
```
3. the page does not load properly

### Expected Result

the customer should be able to load the page

### Actual Result

the page is not loading

### Product Area

Insights

### Link

_No response_

### DSN

_No response_

### Version

_No response_

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2227) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by DominikB2014**
Fixes https://github.com/getsentry/sentry/issues/74554 (the first issue mentioned is fixed already, this fixes the second page)

In cache landing page we fetch the transaction durations for the 20 transactions that appear. The query looks something like `query=transaction:[transaction1, transaction2, ....]`. If the transaction names are really long a 502 will occur on the request originating from ngnix. This occurs because the response headers contains the next page url for pagination, and with large transaction names, the header was too large for the nginx request buffer.

We actually don't need pagination at all for this request, as we always return 20 results, therefore we can add `noPagination` to the query parms and not worry about the nginx buffer at all!

### CODE REVIEW

File: static/app/views/insights/common/queries/useDiscover.ts [hunk 1]
```diff
@@ -19,8 +19,10 @@ interface UseMetricsOptions<Fields> {
   enabled?: boolean;
   fields?: Fields;
   limit?: number;
+  noPagination?: boolean;
   pageFilters?: PageFilters;
-  search?: MutableSearch | string; // TODO - ideally this probably would be only `Mutable Search`, but it doesn't handle some situations well
+  search?: MutableSearch | string;
+  // TODO - ideally this probably would be only `Mutable Search`, but it doesn't handle some situations well
```
Comment (gggritso) [inline static/app/views/insights/common/queries/useDiscover.ts:25]: Stray whitespace change?

**Review by gggritso — APPROVED** [review]
Right on!

File: static/app/views/insights/common/queries/useDiscover.ts (hunk 1 above)
Comment (DominikB2014) [reply static/app/views/insights/common/queries/useDiscover.ts:25]: oops, fixed!
