### PR TITLE
fix: Suppress unexpected Type Error in capturing RouteError

### LINKED ISSUE #16314: Capturing RouteError fails unexpectedly
Sometimes when capturing a RouteError, writing to the `message` property of JavaScript's `Error` object causes a `Type Error: setting getter-only property "message"`.

The new Type Error exception thrown is then logged into Sentry, causing the previous RouteError to be discarded.

While instances are captured in Sentry, these errors are not reproducible. The `message` property should be writable, it is unclear why these errors are being thrown in this scenario. @billyvg suspects browser or browser extension incompatibility.

### PR DESCRIPTION
**Pull request by jeffkwoh**
Wraps unreproducible Type Error (missing setter) in Error.message property in a try-catch. Type
Error is unreproducible, and when thrown causes intital error to be ignored and the newer and less
informative Type Error to be captured by Sentry instead. Currently, a minority of users are
affected and certain browser and/or browser extension incompatibility is suspected.

Suppression should help in the discovery of the actual errors causing the RouteError and perhaps
uncover the root cause of the Type Error.

Fixes GH-16314
Fixes Sentry-JAVASCRIPT-129Q

### CODE REVIEW

File: src/sentry/static/sentry/app/views/routeError.jsx [hunk 1]
```diff
@@ -36,7 +36,19 @@ class RouteError extends React.Component {
...
+       * Unexpectedly, error.message would sometimes not have a setter property, causing another exception to be thrown,
+       * and losing the original error in the process. Wrapping the mutation in a try-catch in an attempt to preserve
+       * the original error for logging.
+       * See https://github.com/getsentry/sentry/issues/16314 for more details.
+       */
+      try {
+        error.message = `${error.message}: ${route}`;
+      } catch (e) {
+        if (!(e instanceof TypeError)) {
+          throw e;
```
Comment (billyvg) [inline src/sentry/static/sentry/app/views/routeError.jsx]: Let's capture in Sentry instead of re-throwing, otherwise we'll have a similar issue.

Comment (jeffkwoh) [reply src/sentry/static/sentry/app/views/routeError.jsx]: Done.

File: src/sentry/static/sentry/app/views/routeError.jsx [hunk 2]
```diff
@@ -35,17 +35,36 @@ class RouteError extends React.Component {
...
+       * Unexpectedly, error.message would sometimes not have a setter property, causing another exception to be thrown,
+       * and losing the original error in the process. Wrapping the mutation in a try-catch in an attempt to preserve
+       * the original error for logging.
+       * See https://github.com/getsentry/sentry/issues/16314 for more details.
+       */
+      try {
+        error.message = `${error.message}: ${route}`;
+      } catch (e) {
+        Sentry.withScope(scope => {
+          scope.setFingerprint(['route-error', 'error-message-mutation-error']);
```
Comment (billyvg) [inline src/sentry/static/sentry/app/views/routeError.jsx]: Let's remove the fingerprint

**Review by billyvg — APPROVED** [review]

File: src/sentry/static/sentry/app/views/routeError.jsx (hunk 2 above)
Comment (jeffkwoh) [reply src/sentry/static/sentry/app/views/routeError.jsx]: Done

**Review by billyvg — APPROVED** [review]
