### PR TITLE
fix(replay): Fix video flickering on Safari

### LINKED ISSUE #82771: [Mobile Replay]: Player flickering on Safari
When watching replays on Safari, the video seems to flicker between clips. This is happening because the video clips itself have around a second in the beginning where it's empty. On Chrome, this is not an issue because the empty part of the video is never played, so if it's a 6 second clip and the first second is empty, the first second is skipped and only 5 seconds of that clip is played. However on Safari, the entire 6 second clip will be played, so it results in the video itself looking like it's flickering.

I've noticed this issue on all replays in the brustolin org but not the sentry-sdks org.
Example replay: https://brustolin.sentry.io/replays/c817d3d7daac4440a2788fd0cbf521b0 
The third video clip in this replay and onwards contains around a second where the clip is just empty: 

https://github.com/user-attachments/assets/a072d64f-1057-4450-8485-0b2ad71e826f

Note how Github doesn't let you play the empty first second of the clip. You'll be able to see the empty part if you download and play with Quicktime Player

We should fix this by ensuring that we don't have any empty parts in the video clips. However, this might take a while to fix so in the meantime, we will try to fix this in the player.

### PR DESCRIPTION
**Pull request by c298lee**
To prevent flickering in Safari, we set the z-index of the clip depending on its index. We hide all videos except the next video and the video before that. This "fixes" the gap in the video by showing the previous video when the gap is happening.

Example replay: https://brustolin.sentry.io/replays/c817d3d7daac4440a2788fd0cbf521b0

Before:
Playthough with gaps

https://github.com/user-attachments/assets/49e19a85-8e38-4f03-900b-e57202db88d5

Clicking to gap
image

After:
Playthrough is smooth

https://github.com/user-attachments/assets/83db4493-fcc9-4fbc-87c3-cdccad3df823

No empty video at same timestamp
image

Fixes https://github.com/getsentry/sentry/issues/82771

### CODE REVIEW

File: static/app/components/replays/player/styles.tsx [hunk 1]
```diff
@@ -3,6 +3,7 @@ import {css, type Theme} from '@emotion/react';
 // Base styles, to make the Replayer instance work
 export const baseReplayerCss = css`
   .replayer-wrapper {
+    z-index: 1000000;
```
Comment (c298lee) [inline static/app/components/replays/player/styles.tsx:6]: Replays should be max 60 minutes and each clip is ~5 seconds so the z-index of the clips should never reach this

File: static/app/components/replays/videoReplayer.tsx [hunk 2]
```diff
@@ -397,29 +398,35 @@ export class VideoReplayer {
...
       return;
     }
 
-    // This is the soon-to-be previous video that needs to be hidden
-    if (this._currentVideo) {
-      this._currentVideo.style.display = 'none';
-      // resets the soon-to-be previous video to the beginning if it's ended so it starts from the beginning on restart
-      if (this._currentVideo.ended) {
-        this.setVideoTime(this._currentVideo, 0);
+    for (const video of this._videos) {
```
Comment (ryan953) [inline static/app/components/replays/videoReplayer.tsx:409]: how about destructuring to get named vars:
```suggestion
    for (const [index, videoElem] of this._videos) {
```
and then `video[0]` would be `index` and `video[1]` would be `videoElem` now

**Review by ryan953 — APPROVED** [review]

**Review by billyvg — COMMENTED** [review]
Does this work as expected if we are in say segment 1 and we seek to near the end of the replay (e.g. segment 20), will it show end of video 0 or 19?

**Comment by c298lee** [comment]
> Does this work as expected if we are in say segment 1 and we seek to near the end of the replay (e.g. segment 20), will it show end of video 0 or 19?

It works as expected! It shows the end of video 19 in that scenario
