### PR TITLE
fix(breadcrumbs) : Add transaction title and remove deadlink 

### LINKED ISSUE #49599: Add Transaction name in breadcrumbs
### Problem Statement

As a developer
when scrolling through breadcrumbs I want to know which transaction(s) was created
so that I can see it clearly in the breadcrumb list
and click and link to go into the transaction details should I want to see more
given that a txn was create and it does still exist in Sentry

Today this is in place however the usier is presented with a generic UUID and not the transaction name
The link also potentially takes you to a dead page https://github.com/getsentry/sentry/issues/49600

### Solution Brainstorm

UUID should be replaced with transaction name instead

image

### Product Area

Issues

### PR DESCRIPTION
**Pull request by roggenkemper**
this pr makes 2 changes. first, it removes the link from transaction that don't exist in Sentry. This can be caused by a number of things, but the current experience is a not found page if the transaction doesn't exist. second, if the transaction does exist, we will now show the transaction title instead of the id in the breadcrumbs. clicking this link will still bring you to the transaction page, but will now show more useful information about the transaction while just looking at the breadcrumbs. 

Screenshot 2023-06-06 at 10 31 27 AM

Closes https://github.com/getsentry/sentry/issues/49599 and https://github.com/getsentry/sentry/issues/49600

### CODE REVIEW

File: static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/default.tsx [hunk 1]
```diff
@@ -48,50 +49,80 @@ function isEventId(maybeEventId: string): boolean {
...
-  loadingProjects: boolean;
   message: string;
   orgSlug: Organization['slug'];
-  projects: Project[];
   searchTerm: string;
   event?: Event;
 }) {
+  const {projects, fetching: loadingProjects} = useProjects();
+
   const content = <Highlight text={searchTerm}>{message}</Highlight>;
```
Comment (scttcper) [inline static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/default.tsx:73]: not your change, but its weird to put this up here

File: static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/default.tsx [hunk 2]
```diff
@@ -48,50 +49,80 @@ function isEventId(maybeEventId: string): boolean {
...
+  const isSentryTransaction =
+    breadcrumb.category === 'sentry.transaction' && isEventId(message);
+
+  const maybeProject = !loadingProjects
+    ? projects.find(project => {
+        return event && project.id === event.projectID;
+      })
+    : null;
+
+  const {data: queryData} = useApiQuery<{data: DataItem[]; meta: any}>(
```
Comment (malwilley) [inline static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/default.tsx:84]: One thing I'm worried about here is if there are events with a large number of unique transaction IDs. If someone were to scroll down the list quickly, it will cause a large number of requests to go off at once. If the number of unique transactions is <5 it doesn't really matter, but if you could have 10+ it might be an issue.

The _best_ way to do this would be to implement batching (make a request for all visible transaction IDs with some sort of debouncing), but that would complicate the logic quite a bit. And I'm not sure how we would want to do that with React Query (as an aside, this could be a good feature addition).

The other option would be to lift this query up to the `Breadcrumbs` component and do a single request for all transaction IDs at once. There's a chance that a query like that would not be that much slower than each individual query so it could be worth a shot.

File: static/app/components/events/interfaces/breadcrumbs/breadcrumbs.tsx [hunk 3]
```diff
@@ -51,10 +58,47 @@ function Breadcrumbs({
...
+      {
+        query: {
+          query: `id:[${sentryTransactionIds}]`,
+          field: ['title'],
+          project: [maybeProject?.id],
+        },
+      },
+    ],
+    {
+      staleTime: Infinity,
```
Comment (malwilley) [inline static/app/components/events/interfaces/breadcrumbs/breadcrumbs.tsx:98]: We want to disable this query when there's no project or transaction Ids, right?

Comment (roggenkemper) [reply static/app/components/events/interfaces/breadcrumbs/breadcrumbs.tsx:98]: yup, that got lost in moving it to the diff file. thanks for catching!

**Review by malwilley — COMMENTED** [review]
Sorry one last thing @roggenkemper - can you add a test case to `breadcrumbs.spec`?

File: static/app/components/events/interfaces/breadcrumbs/breadcrumbs.spec.tsx [hunk 4]
```diff
@@ -223,6 +234,39 @@ describe('Breadcrumbs', () => {
...
+      expect(
+        await screen.findByText('12345678123456781234567812345678')
+      ).toBeInTheDocument();
+
+      expect(screen.getByText('12345678123456781234567812345678')).not.toHaveAttribute(
+        'href'
+      );
+
+      // Transaction in response should show as clickable title
+      expect(await screen.findByText('/settings/')).toBeInTheDocument();
```
Comment (malwilley) [inline static/app/components/events/interfaces/breadcrumbs/breadcrumbs.spec.tsx:266]: Could also do `screen.findByRole('link', { name: '/settings/' })`

**Review by malwilley — APPROVED** [review]
