### PR TITLE
fix(sidebar): Fix page selection reset when clicking sidebar links

### LINKED ISSUE #78207: UI resets project selection causing "You do not have the multi project stream feature enabled" error
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open issues page
2. Select a project
3. Click on the issues page again

### Expected Result

no error

### Actual Result

The project selector resets and selects multiple projects, this feature is not available on a team plan causing the error message
More details (affected org and recordings) are in the shadow ticket due to PII

### Product Area

Issues

### Link

_No response_

### DSN

_No response_

### Version

_No response_

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2303) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by malwilley**
Fixes https://github.com/getsentry/sentry/issues/78207

When you click the sidebar links, the URL no longer contains any page selection query params, so the selection store will reset. For free orgs, this also results in an error due to multi-project selection not being enabled. This was originally solved with [this PR](https://github.com/getsentry/sentry/pull/59205), but the react router upgrade changed the way that `state` was passed. Now it is no longer included in the LocationDescriptor object, but passed in as a `Link` prop ([described in this section of the docs](https://reactrouter.com/en/v6.3.0/upgrading/v5#use-usenavigate-instead-of-usehistory))

### CODE REVIEW

**Review by armenzg — APPROVED** [review]
🎉 yay!

**Review by MichaelSun48 — APPROVED** [review]

**Comment by scttcper** [comment]
oh i thought someone removed those on purpose

File: static/app/components/nav/utils.tsx [hunk 1]
```diff
@@ -98,12 +98,17 @@ export function isSubmenuItemActive(
 }
 
 /** Creates a `LocationDescriptor` from a URL string that may contain search params */
-export function makeLocationDescriptorFromTo(to: string): LocationDescriptor {
+export function makeLinkPropsFromTo(to: string): {
+  state: object;
```
Comment (scttcper) [inline static/app/components/nav/utils.tsx:102]: boo object type

**Review by scttcper — APPROVED** [review]
