### PR TITLE
fix(ui) Don't overflow on IPv6 data.

### LINKED ISSUE #10316: Audit log overflow with IPv6 IPs
## Important Details

How are you running Sentry?

* [X] On-Premise docker [Version 9.1.0.dev0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When opening the Audit Log for an organization and changes are made with an IPv6 IP, the IP overflows out of the table.

## Steps to Reproduce

1. Make auditable changes with an IPv6 IP
2. Open the Audit Log

image

### What you expected to happen

It should not be overflowing :O

### PR DESCRIPTION
**Pull request by markstory**
If we get a value longer than ipv4 data truncate and display a tooltip. This prevents an unsightly overflow in the audit logs.

screen shot 2018-10-30 at 4 43 16 pm

Fixes #10316

### CODE REVIEW

File: src/sentry/static/sentry/app/views/settings/organizationAuditLog/auditLogList.jsx [hunk 1]
```diff
@@ -110,7 +115,15 @@ class AuditLogList extends React.Component {
                       </NameContainer>
                     </UserInfo>
                     <Box w={150}>{entry.event}</Box>
-                    <Box w={130}>{entry.ipAddress}</Box>
+                    <Box w={130}>
+                      {entry.ipAddress && entry.ipAddress.length > ipv4Length ? (
+                        <Tooltip title={entry.ipAddress}>
```
Comment (billyvg) [inline src/sentry/static/sentry/app/views/settings/organizationAuditLog/auditLogList.jsx]: You could simplify this a bit and always render with `<Tooltip>` and `<OverflowBox>`, but disable `<Tooltip>` if ipv4.

**Review by billyvg — APPROVED** [review]

File: src/sentry/static/sentry/app/views/settings/organizationAuditLog/auditLogList.jsx (hunk 1 above)
Comment (markstory) [reply src/sentry/static/sentry/app/views/settings/organizationAuditLog/auditLogList.jsx]: I like that approach better.

Comment (markstory) [reply src/sentry/static/sentry/app/views/settings/organizationAuditLog/auditLogList.jsx]: I like that approach better.
